### ISSUE TITLE
Migrate www.butterfly-monitoring.net to Drupal 8

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#1]
Migrate to drupal 8, hosted on Pantheon, using the Bootstrap theme

**Comment by Gary-van-Breda** [comment]
@BirenRathod : what is the best way to get pantheon setup for this new EBMS setup?

**Comment by BirenRathod** [comment]
@Gary-van-Breda , @DavidRoy 

I need to create first site in BRC repository of Pantheon.

**Comment by johnvanbreda** [comment]
@BirenRathod Is the Pantheon template we will used based on Bootstrap 3? I ask because Indicia now has a cleaner output for HTML/CSS if it is Bootstrap and you get a nicer, more modern, end result.

**Comment by BirenRathod** [comment]
Yes, it is based on Bootstrap 3.16 version which is the one supported by Drupal.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Please start migrating this site to Drupal 8 on your machine, I will send you URL of the test Pantheon site soon.  Also, I'm inspecting the relevant module require by this site. So if you have any suggestions do let me.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

I have created the test site of butterfly-monitoring. Here is the URL http://test-butterfly-monitoring.pantheonsite.io/. Also, I added your user for this website, you should be able to see from your Pantheon dashboard.

**Comment by Gary-van-Breda** [comment]
Thanks.
I tried pulling a backup using backup/migrate of the existing system: I think it takes too long to generate. I have got the MYSQL database: @BirenRathod could you zip up the file system and send it to me?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

The first option "Entire site (code, files & DB)" is not ideal to take backup. Instead you can take backup using default database. I have done done it for you.

1. Back up from website.
[EuropeanButterflyMonitoring-2019-01-23T20-23-51_Live.mysql.gz](https://github.com/BiologicalRecordsCentre/ABLE/files/2789040/EuropeanButterflyMonitoring-2019-01-23T20-23-51_Live.mysql.gz)
2. Backup from Mysql
[butterfly-monitoring_live_23012019.zip](https://github.com/BiologicalRecordsCentre/ABLE/files/2789042/butterfly-monitoring_live_23012019.zip)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
3. Backup of files folder
[Uploading files.zip…]()

**Comment by BirenRathod** [comment]
4. Backup of theme
[at_ebms.zip](https://github.com/BiologicalRecordsCentre/ABLE/files/2789129/at_ebms.zip)

**Comment by Gary-van-Breda** [comment]
Hi @BirenRathod : I don't think the "3. Backup of files" folder worked. Can you try again?
Thanks
Gary

**Comment by Gary-van-Breda** [comment]
@BirenRathod : I have a couple of questions about the process from here on in:

- I have got an upgraded system on my local development environment. Is it best to rerun the upgrade from within the development / test pantheon environments (which is problematic - I can't see how to create a copy of the live ebms database within their environment so I can run the upgrade - I would hope that the database is not accessible directly, nor is there any obvious place to put the files), or should I just import the database from my enviornment and upload the files directory?
- How do we switch over the URL from pointing at the current EBMS site to the new site (after it is moved to live)?

I've attached the upgrade document that has a list of those modules that are active on the current libe system, indicating those being carried across and the versions used.
[Upgrade Instructions.docx](https://github.com/BiologicalRecordsCentre/ABLE/files/2825700/Upgrade.Instructions.docx)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
1. if you already got upgraded version of EBMS site in Drupal 8 on your local machine, you can simply restore your backup on test pantheon. I'm guessing the files directory hasn't been much changes, so I can upload same files directory from current live version of website. If it has changed then upload it here and I will upload onto Pantheon. I'm happy to help you on this if you want me to restore the backup of your local site.
You are right we don't have MySQL database access at our end. So the only option is to migrate the Drupal site via "Backup and restore" module, which you find in the current version of Pantheon test site.  
2. Switching URL require is a job for our hosting provider. Once we are happy with test version of EBMS site then I will ask them to upgrade the domain and point to Pantheon.

I checked list of modules mentioned in 3rd, So I'm making sure all Drupal 8 module is available prior to restore your local copy of Drupal 8 version of EBMS site. I will let you know soon about it.

Also, Can I ask , which theme have you used? I insist if possible to use sub theme based on Bootstrap.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I also checked that you have already uploaded require modules which is good. About uploading files in the files folder,  Check the SFTP section in this link https://pantheon.io/docs/rsync-and-sftp/.

Things to consider : before uploading files, establish the connection via one of SFTP GUI and put dev pantheon site into SFTP mode. Do let me if you stuck or need any help.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : Do we have google Map API keys enabled for the pantheon URL, or should I leave it at Open Street Map?
Re the theme, I'm just going to switch on the basic Bootstrap generic theme that comes with Drupal for the time being.
I've done a clean migrate on my local environment, but I need to complete a bug fix (see UKBMS issue 75) which is also present on EBMS.
I'm going to remove the document I uploaded above for security issues, and will reload a new version.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
We don't need separate Google Map API key for Pantheon. Also, we don't need for its test and dev site too.

Yes, for time being it is fine to use Bootstrap theme, which is already on Pantheon, so you don't need to upload separately only for this site.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : I've attempted to load up my "export" from the backup/migrate on my server, but I can't log in : what are the login details I should use? (email me separately?)
After the install I believe the user accounts (and their passwords) will be the same as the ones on butterfly-monitoring.
I did try to import the database directly using tthe pantheon tools, but it didn't work, and there is no feedback to give any idea what went wrong.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
The user account and password will be the same as the butterfly-monitoring.  Try not to import via database directly using Pantheon, it won't work at first place. it will only work if database imported via Pantheon.  
I sent you text for login detail.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Due to different data structure of Pantheon, import doesn't work via Pantheon import utility. As I mention before, You could import data via "Backup and Restore" feature. If you struggle doing it, let me know and I will help you to do it.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : I am happy with the Backup/Migrate process. I just don't have the admin password for butterfly-monitoring, so I can't log into the pantheon sites: can you get it to me?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
You didn't see my previous message.

I already sent you text message.

**Comment by Gary-van-Breda** [comment]
Only other thing is that this migration ends up with the Pantheon site pointing at the Live EBMS warehouse2. Is there a dev/test warehouse we can point to for testing? Pointing at Live is potentially dangerous, if only for asking for accidents to happen, and it doesn't really allow for proper testing.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

Fine to point any of this warehouse. Just to keep in mind that warehouse2 doesn't have separate test/dev warehouse. so you can use the existing one which are devwarehouse.indicia.org.uk or testwarehouse.indicia.org.uk to test your survey. you can create survey on any of this warehouse.

**Comment by Gary-van-Breda** [comment]
I've put my migration onto the Dev Pantheon environment: not Test yet.
There was an existing test website/survey for EBMS on testwarehouse.indicia.org.uk, so I've swapped the Indicia settings and all the webpage configurations to point to the testwarehouse.
This is throwing up some issues now, so I'll look at them: this includes reports not returning data, and messages from the pages themselves.

I have concerns about Mapping : configuration on Live is dubious, as it looks like it references ID values from warehouse 1 not 2.
This test system does not include Linear Habitat or the Luxembourg Reliability.

**Comment by DavidRoy** [comment]
Remaining issues are solved or raised through other issues.  Am closing this issue and will open any specific issues as required
