### ISSUE TITLE
Possible to add burnet moths to checklist

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#100]
Our scheme has always included burnet moths and it would be great to have them in the app.  I realise that there can be several other Lepidoptera groups that people might want to add so adding burnets is a bit of opening Pandora's Box, but I feel that they would be a very useful, valuable and straightforward addition.

**Comment by DavidRoy** [comment]
Agreed.  Identifying 'day-flying' moths for anywhere in Europe is not clear-cut.  The current plan is therefore to add a complete list of moth (macro/larger) species to the App.  Do you agree?

**Comment by larspett** [comment]
I would go for just burnets for the time being since they are a well-defined and straightforward group plus that  they are covered already by at least some schemes. Adding all macros risk adding too much complexity and negatively affect the UX/user experience

**Comment by larspett** [comment]
Alternatively , Sweden would need a work-around or a tweaked national version of the app

**Comment by DavidRoy** [comment]
I think we'll add in the full moth list, but only include a subset for recording within the app.  Burnets plus others typically recorded via transects - based on those schemes that record them.  Can you add a column to the species list to indicate the Burnets plus any additions - I saw quite a few Siona lineata in Sweden in June during the day for example

**Comment by larspett** [comment]
Ok I can pull out the ones we have received as extra species plus the burnet moths, will probably cover most relevant day active moth species for Sweden

**Comment by larspett** [comment]
Here are the Swedish Burnet Moths, some aggregates that we use, and some day-active moths that we receive reports of.

[moth_species_and_additional_aggregates.txt](https://github.com/BiologicalRecordsCentre/ABLE/files/3396670/moth_species_and_additional_aggregates.txt)

**Comment by kazlauskis** [comment]
@DavidRoy have the new species been added to the warehouse?

@johnvanbreda once this is added could you re-export the species list like you did here below?
https://github.com/BiologicalRecordsCentre/ABLE/issues/13#issuecomment-495299115

or better, create a report so I could do this myself next time. Cheers

**Comment by DavidRoy** [comment]
Taxon list = 260

Still needs some aggregates adding which I will do today

**Comment by DavidRoy** [comment]
@johnvanbreda can you add the following to the ABLE moth lists (id = 260)

- Unidentified Geometrid (within Geometridae family)
- Hemaris fuciformis/tityus | Narrow-bordered Bee Hawk-moth/Broad-bordered Bee Hawk-moth
(within Sphingidae family)
- Zygaena viciae/lonicerae | New Forest Burnet/Narrow-bordered Five-spot Burnet (within Zygaenidae)

**Comment by johnvanbreda** [comment]
New taxa added. Will there be any other taxonomic amendments or shall I proceed and update the Elasticsearch taxonomic lookup tables @DavidRoy?

@kazlauskis there is a new report referenced in the above commit for you.

**Comment by DavidRoy** [comment]
There is a dragonfly list to load plus some butterfly aggregates to add.  In June milestone

**Comment by DavidRoy** [comment]
@johnvanbreda extra species dictionary tasks are:
#246 
#193

**Comment by kazlauskis** [comment]
Hi @johnvanbreda, could you also add in the `language_iso` to the taxa results? I would like to filter out non latin names on my end.

**Comment by johnvanbreda** [comment]
@kazlauskis The report now includes a language_iso column.

**Comment by kazlauskis** [comment]
The new list is now in the app and will go through beta testing next week. I think the 15min web form needs updating with the new species list ID.

**Comment by kazlauskis** [comment]
@johnvanbreda There were some strange entries coming out from the species report, we have just filtered these out on the app-end, but mentioning this here in case this indicates some bigger problem.

when using species list 260, we got some `[Unterfamilie nicht zugeordne...]` as latin entries
```
{
            "id": "446489",
            "taxon_group": "insect - moth",
            "taxon": "[Unterfamilie nicht zugeordnet: ehem. \"Meesiinae\"]",
            "language_iso": "lat",
            "preferred": "t",
            "parent_id": "446330",
            "external_key": "EBMSM0000000000257",
            "preferred_taxa_taxon_list_id": "446489",
            "preferred_taxon": "[Unterfamilie nicht zugeordnet: ehem. \"Meesiinae\"]"
        },
```
when using species list 251, we got some zero-width space characters `\u200b` which were gave us fun time trying to understand why two strings don't match 😄 

```
{"id":"466901","taxon_group":"insect - butterfly","taxon":"\u200bMuschampia proteides","language_iso":"lat","preferred":"t","parent_id":"432027","external_key":"eBMS682","preferred_taxa_taxon_list_id":"466901","preferred_taxon":"\u200bMuschampia proteides"}
```
