### ISSUE TITLE
Setup Transifex to handle translations for www.butterfly-monitoring.net

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#101]
It is more efficient to handle translations for www.butterfly-monitoring.net via Transifex (which is being used for the mobile app translations)

This requires some setup, but guide is available at
https://docs.transifex.com/drupal/drupal-8

Suggest we test this via the test site, firstly using the privacy policy page as test content to push from Drupal to Transifex, translate in Transifex and pull back translation to Drupal

Here is project link on Transifex: https://www.transifex.com/ceh/ebms-website-wwwbutterfly-monitoringnet/dashboard/

@johnvanbreda can you take on this issue?

**Comment by johnvanbreda** [comment]
Presumably this should be added to the dev site first - as I don't have Pantheon access can you send me a URL please?

**Comment by DavidRoy** [comment]
yes, dev first
https://dev-butterfly-monitoring.pantheonsite.io/

**Comment by larspett** [comment]
I had a look at the Swedish version of the website now and saw that there are plenty of strings to translate but assume these will appear in Transifex once it has been linked to the dev version of butterfly-monitoring.net?

**Comment by larspett** [comment]
Btw Swedish is not activated on the dev site

**Comment by DavidRoy** [comment]
Swedish now implemented on dev and test.

Transifex will become the preferred way of translating the website.  But in the meantime, if you have a more urgent requirement for translation, please provide Swedish translations for the key text in this word document.
[eBMS Translations required.docx](https://github.com/BiologicalRecordsCentre/ABLE/files/3397605/eBMS.Translations.required.docx)

**Comment by larspett** [comment]
Hi David, Many thanks for this. Have now passed the file to my most active translator. Is there a way in which I could see and try the data warehouse/backend part of the the workflow? I am thinking I’d better know as much as possible if I am to advocate this to my bird colleagues. So much better to build upon your Indicia solutions than to build our own warehouse. Best wishes Lars

16 juli 2019 kl. 16:35 skrev David Roy (CEH) <notifications@github.com<mailto:notifications@github.com>>:


Swedish now implemented on dev and test.

Transifex will become the preferred way of translating the website. But in the meantime, if you have a more urgent requirement for translation, please provide Swedish translations for the key text in this word document.
eBMS Translations required.docx<https://github.com/BiologicalRecordsCentre/ABLE/files/3397605/eBMS.Translations.required.docx>

**Comment by johnvanbreda** [comment]
@DavidRoy In order to connect Drupal to Transifex I need the API token - can you email it to me please when you get a chance as I can't access it.

**Comment by DavidRoy** [comment]
@johnvanbreda are we able to progress this again now we've made progress on this with iMammalia

**Comment by johnvanbreda** [comment]
@DavidRoy can you send me the Transifex API token for ABLE please?

**Comment by johnvanbreda** [comment]
@DavidRoy I've added Transifex to the Dev site for you to test. For the Indicia pages, note that the parameters of the page are not submitted for translation (as that would be too prone to error). Instead, the individual strings which Indicia outputs are added to the translation sources (under the Locale section).

**Comment by DavidRoy** [comment]
@johnvanbreda thanks.  I think we agreed you would produce some simple guidance on the setup so that we start off on the right basis.

**Comment by johnvanbreda** [comment]
Ok, so you can (on the dev site):
1. Pages (including Indicia pages) should be created with their language set to English.
2. Go to Translation -> Sources, set Choose Source = Content, select page(s) and click Request Translation. Submit to Provider, then repeat for each language.
3. For Indicia pages, the page configuration is not translated in this way as it is too prone to errors in translation. You can translate the title and any body text only. So, you need to also do the following:

  * Visit the page, then change the language to any language other than English. This causes Drupal to request the translated version of each string so they get logged into the system, even though the translations don't exist yet.
  * Go to Translation -> Sources, set Choose Source = Locale. The strings on the page should now appear in this list and are available for submission as before.

@DavidRoy Please can you do this for a couple of pages and strings then translate them in Transifex, so I can correctly update this documentation with the steps required to pull the translations back into Drupal.
  2.

**Comment by DavidRoy** [comment]
@johnvanbreda I've done the first two steps, and need to check a few things. 

firstly, on [2] the page gave some warnings. See attached below. The page is shown in Transifex but there are some additional characters formatting that doesn't look right.
![err](https://user-images.githubusercontent.com/2699478/78242917-c4b35100-74da-11ea-8296-8d12c2bc4e44.png)

[error.docx](https://github.com/BiologicalRecordsCentre/ABLE/files/4420572/error.docx)

I'll also test [3] on the list now

**Comment by DavidRoy** [comment]
@johnvanbreda I tried the steps for translation for Indicia pages
1. viewed https://dev-butterfly-monitoring.pantheonsite.io/my-sites and switched language to Spanish
2. i searched for 'site name' but the Indicia column heading text was not there to translate

Maybe this page has already been tested with translation?

Tried the same with this page and it worked as expected.  I've translated in Transifex so would be good to test the return journey back to the Drupal page
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-2

**Comment by DavidRoy** [comment]
p.s. it is better if the translations in Transifex get put under:
https://www.transifex.com/ceh/ebms-website-wwwbutterfly-monitoringnet/dashboard/

rather than
https://www.transifex.com/ceh/ebms/dashboard/

which can focus on the app translations

**Comment by johnvanbreda** [comment]
The My Sites page has a lot of rubbish <span> elements in the HTML - click on View Source at https://dev-butterfly-monitoring.pantheonsite.io/node/32/edit and you will see what I mean. I think Transifex is showing these as the numbered tags. I'll look into the error messages - I think I mentioned before that the Drupal -> Transifex module has some bugs.

**Comment by DavidRoy** [comment]
oh yes.  We'll clear this up before the main translations in that case.

I think the next steps are:
- move to using https://www.transifex.com/ceh/ebms-website-wwwbutterfly-monitoringnet/dashboard/
- complete a round-journey test of the translations, including Indicia elements

**Comment by johnvanbreda** [comment]
I've fixed the PHP notices and also changed the Transifex project, so ready for a round-journey test.

**Comment by DavidRoy** [comment]
Thanks.  I went through the steps again on the 'my walks' page. https://dev-butterfly-monitoring.pantheonsite.io/my-walks

For step 1, I got this warning.  Can it be ignored?
"You have enforced the job source language which most likely resulted in having a translation of your original content as the job source text. You should review the job translation received from the translator carefully to prevent the content quality loss."

The resource appeared as expected on Transifex, under https://www.transifex.com/ceh/ebms-website-wwwbutterfly-monitoringnet/content/.  Tick

I translated one sentence to French, clicked as Reviewed (i.e. ready to go back to Drupal)

It shows up as a job 'in progress' in Drupal: https://dev-butterfly-monitoring.pantheonsite.io/admin/tmgmt/jobs

----------------
For Indicia strings, i requested translation of 'Week number' to French
This appeared as expected in Transifex
I translated and reviewed.  Again, the job shows up in Drupal as in progress.

@johnvanbreda is the remaining task to complete the jobs in Drupal

**Comment by johnvanbreda** [comment]
@DavidRoy please can you add me to the Transifex team so I can check the language codes in use. At the moment the pull of translation back into Drupal is not working but I've managed to work out that this is because the language code configured in Drupal (fr_FR) is expected to be just fr in the API requests.

**Comment by DavidRoy** [comment]
@johnvanbreda invites sent

**Comment by johnvanbreda** [comment]
Hi @DavidRoy the problem I had was because French and Italian are listed on Transifex with the 2 character main language code (fr or it) rather than the code including the sub-dialect (e.g. fr_FR). The settings on the Transifex provider configuration in Drupal have to exactly match or when you try to pull translations down you get an error. I've changed the settings in Drupal to match. So, here are the remaining steps after you've reviewed a string in Transifex:
1. Go to Translations > Jobs. 
2. Click Manage for the string you want to pull.
3. Click Check for Updates.
Note that I've now set the option on the provider settings to automatically accept translations, rather than requiring them to be reviewed in Drupal. I've been unable to test this as I set the option after pulling the translation example, so I had to go to Translation > Job Items > then click Save as Completed to accept it.

This all seems a bit long winded, so I've followed the instructions at https://docs.transifex.com/drupal-integrations/drupal-8#setting-up-an-auto-update-webhook-with-transifex to setup a webhook. I hope that this means when you review an item in Transifex, it should appear in Drupal without you needing to check for updates.

**Comment by DavidRoy** [comment]
hi  @johnvanbreda I've got round to testing.  I tested translating the column heading 'Site Name' on https://dev-butterfly-monitoring.pantheonsite.io/my-sites to Swedish

Pushing to Transifex and translating worked ok.  But when getting to the Drupal step (https://dev-butterfly-monitoring.pantheonsite.io/admin/tmgmt/jobs) of:
Go to Translations > Jobs. Click Manage for the string you want to pull.  Click Check for Updates.

I get the following error.
![pic t](https://user-images.githubusercontent.com/2699478/81695628-cb7a9f80-945a-11ea-9167-7f2a18d249e1.png)

**Comment by johnvanbreda** [comment]
This was exactly the same issue as before. The language codes used by Drupal need to be mapped correctly to those used in Transifex. The mapping is on the Provider settings page (https://dev-butterfly-monitoring.pantheonsite.io/admin/tmgmt/translators/manage/transifex?destination=/admin/tmgmt/translators) and the language codes used in Transifex are at https://www.transifex.com/ceh/ebms-website-wwwbutterfly-monitoringnet/languages/. Unfortunately I think the default behaviour in Drupal is 5 letters (en_EN) whereas in most cases in Transifex we are using 2 characters (en).
I've fixed this for the cases where the language is in both Drupal and Transifex.

**Comment by DavidRoy** [comment]
Thanks @johnvanbreda.  The end-to-end test works in translating 'Site Name' on https://dev-butterfly-monitoring.pantheonsite.io/es/node/32 into Spanish.

Can you new setup on the live site so we can push through text for translation

**Comment by johnvanbreda** [comment]
Installed and configured on the live site ready for you to try @DavidRoy.

**Comment by DavidRoy** [comment]
Thanks @johnvanbreda 
We will test.

One question, how do hyperlinks get sent for translations.
e.g. "Full Sites data download (CSV)" returns no results with source = 'Locale' 
![pic13](https://user-images.githubusercontent.com/2699478/82895197-b9fdc100-9f4b-11ea-9404-4d981230be6c.png)

**Comment by DavidRoy** [comment]
The return journey Drupal-Transifex seems to work.  See completed jobs:
https://butterfly-monitoring.net/admin/tmgmt/jobs?state=5&source_language=All&target_language=All&translator=All
![pic14](https://user-images.githubusercontent.com/2699478/83001033-12dc6080-a003-11ea-8451-8e5ab91b812c.png)

But the translation does not appear on the page as expected.  Site Name should be translated when switching to Spanish, e.g.
![pic15](https://user-images.githubusercontent.com/2699478/83001042-17087e00-a003-11ea-8bb3-b83b18247a07.png)

**Comment by johnvanbreda** [comment]
After some investigation I discovered that clearing the Drupal cache is required to update the translations.

**Comment by DavidRoy** [comment]
That works, hurray.  It's been a challenge to say the least, but now seems to work ok.  Closing this issue as the job is now pushing through content for translation.  Will raise anything specific as separate issues.

**Comment by johnvanbreda** [comment]
> One question, how do hyperlinks get sent for translations.

The hyperlinks in this page are generated by the "report footer" option which doesn't send it's content for translation. Although we can enable translation of the entire Indicia parameters setting, I think this will be prone to error. A better solution would be to add a feature to the report footer option (as well as other dynamic content added to reporting pages) to allow content to be exposed to translation. E.g. we could wrap the labels in the HTML as so: 
`<a href="...">{t:Label for translation}</a>`

Shall I implement that?

**Comment by DavidRoy** [comment]
Yes please.  I've re-opened this issue to cover this

**Comment by johnvanbreda** [comment]
Done and implemented for the my-sites page. 

@Gary-van-Breda tagging you just so you are aware of what I've done. Up to now, any custom HTML added to pages was untranslatable (e.g. by embedding directly in the form structure of a dynamic page, or using the footer of a report grid as in this case). I've changed it so that you can specify a phrase for translation in the format `{t:phrase here}`. Have a look at the footer on my-sites to see how it works. As a side effect, the same token replacements that worked on the report footer now work on any custom content added to a dynamic form's user interface.
