### ISSUE TITLE
Data entry UX suggestion, numbers

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#102]
Adding count numbers for each species would be easier if the current Area Count screen allowed clicking on the species name to add +1, would be necessary with a count indicator next to each name then, though. The present count sub-screen could be kept as an editable detailed view. Also, am not sure if this has been discussed, but I would expect the + sign to be to the right of the number and the - sign to the left.

**Comment by DavidRoy** [comment]
If you click on the number it increments +1

**Comment by larspett** [comment]
Excellent solution! I thought it was some other list number, the button function there didn't spring to mind. Maybe it could be emphasised somehow, or just shown in introductory walkthrough of the app. Anyway, once you know the function is there, you'll remember it. What do you think of the sub-screen + & - positioning?

**Comment by DavidRoy** [comment]
Yes, I agree that the + - are the wrong way around.
@kazlauskis to change

**Comment by kazlauskis** [comment]
Can this be closed?

**Comment by larspett** [comment]
yes fine with me, the recent version has the the signs the other way round as suggested
