### ISSUE TITLE
Data entry UX suggestion, transect segment data entries

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#103]
Adding data from individual segments is something I have been thinking a bit about since results in a two dimensional list that can be tricky to visualise and navigate. My suggestion is that transect segments are accessed as left-right swipes between screens with a per-segment species list on each screen. This could be either looping with screens moving x(1) ... x(n) -> x(1) or having ends at x(1) and x(n). This design would see the Area Count list as a special case of the Transect Segment list.

**Comment by DavidRoy** [comment]
@kazlauskis to consider for eBMS app v2.0

**Comment by kazlauskis** [comment]
@larspett great, thanks for the suggestion, let me know if you have any more ideas. When developing the v2 of the app I will update the app's wireframe and circulate it around for feedback. 

Cheers, I will close this now.
