### ISSUE TITLE
App data to website missing for Swedish entires

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#104]
Is butterfly-monitoring.net where my app data should appear? The user id and pw are the same but I suppose data might go to a mirrored dev site instead of the live site. Anyway, I have some test data that I expected to see within my web account but there is nothing there. Am just creating this issue in case Sweden is outside the defined coordinate bounding box.

**Comment by DavidRoy** [comment]
Yes, the data can be viewed/edited via the website.  The reports are still being configured.  In the interim, your records can be viewed at: https://butterfly-monitoring.net/mydata/my-records when you are logged in.  This is a draft report at this stage - it doesn't currently allow training records to be viewed.  There will also be more functionality within the app for view/editing your records in due course.

The back-end dashboard shows the following activity to date, including your records from S. Sweden.
![e test](https://user-images.githubusercontent.com/2699478/61456756-c940d500-a95e-11e9-9a9d-f1bff228aa09.png)

**Comment by larspett** [comment]
OK, so have I entered my observations as training records? Because I couldn’t find any at my-records. May have missed sth but think I looked at the proper places. Obviously the data is in as I see in (the very nice) overview above.

**Comment by larspett** [comment]
Btw are the sites I define in the app just temporary? Because they seem to disappear from the app?

**Comment by larspett** [comment]
Also, just let me know if you would like to have our point site network as geojson, wgs84 or so. I can export them easily. They are currently just points but the plan is to have proper polygons for them in due time.

**Comment by DavidRoy** [comment]
The current version of the app does not allow for saving/marking routes as favourites.  This will come in the next iterations.  Also, the link to existing transects for recording is for v2.

To enable recording of existing transects via the app, it will make the work simpler if the sites are loaded into Indicia - with an agreed update frequency.  Are the sites 'open' as the aim is to have a data flow to GBIF.

**Comment by larspett** [comment]
All point sites are open but some of the transects are not right now. Our present dataflow to GBIF from SEBMS will aggregate to a 1 km grid and then be displayed in the ALA Spatial Portal. We have that running in a Docker container with GBIF IPT

**Comment by larspett** [comment]
My records have been in training mode and now I can’t access them. They do not appear at my-data (probably because they were in training mode) but are also away from the app (the record seems to be there but the only available action is to delete the record. I would have expected I could expand the record using the right arrow? Would really like to check those records.

**Comment by DavidRoy** [comment]
Yes, see my first reply to this thread

**Comment by larspett** [comment]
Ok so the data is there just not viewable /yet/. Should submitted reports still be viewable from within the app?

**Comment by DavidRoy** [comment]
will be resolved with #85 and #95
