### ISSUE TITLE
report of samples, sites, occurrences, species by scheme/country

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#106]
new reports required to show overall progress for survey = 562:

Columns required: 
country, year, number of samples, number of sites (with data), number of occurrences, number of species

**Comment by Gary-van-Breda** [comment]
Is this for download, or to be displayed as a grid on a new reporting page?

**Comment by johnvanbreda** [comment]
Hi @Gary-van-Breda - it's assigned to me so I'm assuming its an Elasticsearch output page.

**Comment by johnvanbreda** [comment]
@DavidRoy - is this OK: https://butterfly-monitoring.net/elastic/summary-by-country-year?

**Comment by DavidRoy** [comment]
@johnvanbreda looks great.  Can you also add in a column for number of samples

**Comment by johnvanbreda** [comment]
@DavidRoy why was this re-opened?

**Comment by DavidRoy** [comment]
@johnvanbreda can you summarise the report filters.  There are some discrepancies in the numbers on the report.

Austria= 5 (2020); correct number 12 transects
Italy= 23 (2020); correct number 53 transects
Portugal= 27 (2020); correct number 37 transects

**Comment by johnvanbreda** [comment]
The data look correct as far as I can tell. For Austria I used the following workings to check:
```sql
select * from locations where name='Austria' -- id is 215970 

-- Grab all Austrian 2020 data.
select * into temporary austriandata
from cache_occurrences_functional 
where 215970 = ANY(location_ids) and survey_id=562 and extract(year from date_start)=2020

-- Find the distinct list of location parents
select distinct l.parent_id 
from austriandata a
join locations l on l.id=a.location_id
```

The above queries give 5 as a result. @DavidRoy how are you calculating the value 12?

**Comment by CrisSevilleja** [comment]
@johnvanbreda you are right, Austrian transects are 5 for 2020, I may miss up with transects in 2019 maybe. 

Did you check for Italy and Portugal? I think there had been more transects registered this year. I checked the numbers with the Scheme site page of the coordinator https://butterfly-monitoring.net/de/node/33 but there, the total number appears. I will rise a new issue to help me in check properly those numbers. Thanks

**Comment by johnvanbreda** [comment]
@CrisSevilleja yes, I've rechecked all the data. I get the same result for queries directly on the raw PostgreSQL data and the Elasticsearch reporting data - 23 and 27 for Italy and Portugal respectively. Note that this result excludes any data flagged as "training".

**Comment by johnvanbreda** [comment]
@DavidRoy @CrisSevilleja can this be closed?

**Comment by CrisSevilleja** [comment]
Could it be possible to see which transects are flagged as "training"? Thanks

**Comment by johnvanbreda** [comment]
Training data filters are automatic according to the flag on your edit profile page. So if you tick this option and save your profile, the report will show just training data. If you untick the option, the report will show just live data.
