### ISSUE TITLE
My walks page doens't work in any language. Urgent

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#107]
https://butterfly-monitoring.net/my-walks is not working and it returns to the home page. It is not working for any language. 

The link that appears https://butterfly-monitoring.net/mis-visitas

@DavidRoy @johnvanbreda

**Comment by johnvanbreda** [comment]
I'll look into this now...

**Comment by johnvanbreda** [comment]
Fixed. I've done 2 things:
1) Correct the link embedded into the My Walks page to /my-walks. 
2) Applied a small patch which gets rid of an error message on the My Walks page.
