### ISSUE TITLE
Unable to create account on test website

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#109]
Unable to create an account on https://test-butterfly-monitoring.pantheonsite.io/user/register

Message says 'The email xx@xx is reserved, and cannot be used.' even when email address is new

Needed to test #2

**Comment by johnvanbreda** [comment]
I'm not sure but last time this cropped up I think @BirenRathod knew what caused it?

**Comment by Gary-van-Breda** [comment]
There is a contrib module called user_restrictions, the page Admin toolbar->Configuration->People->User REstrictions. (https://test-butterfly-monitoring.pantheonsite.io/admin/config/people/user-restrictions)
The regex on this page is wrong (at the moment it will ban any email which ends in .com): I'll update it to match live, which was fixed the last time/

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
You have implemented on when site was on Wallingford server and backup taken on Pantheon before that implementation.

**Comment by Gary-van-Breda** [comment]
See #81 
Regex now sorted on Test site to match values on Live

**Comment by DavidRoy** [comment]
Thanks.  Now ok. Closing
