### ISSUE TITLE
Implement ElasticSearch to support reporting

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#11]
To support reporting via online website and to support mobile application reports

**Comment by kazlauskis** [comment]
@johnvanbreda nope, I don't see anything in particular that would benefit mobile apps at the moment. There might be some specific reporting required when releasing the European Butterflies app but I have no clear requirements for that yet. Thanks.

**Comment by DavidRoy** [comment]
Initially, a single Elasticsearch index with everything from warehouse1 and warehouse2, with the ability to distinguish between the two warehouses.  This is then a better test of the scalability of reporting this way.

**Comment by johnvanbreda** [comment]
@DavidRoy Ok. I suspect that scalability will not be an issue as Elasticsearch is well documented as coping with billions of documents (e.g. see https://thoughts.t37.net/how-we-reindexed-36-billions-documents-in-5-days-within-the-same-elasticsearch-cluster-cd9c054d1db8), but realistically it will need multiple machines in a cluster and SSD to get the best out of it. At some point we may therefore need to consider either outsourcing the Elasticsearch hosting to a specialist, or getting some in-house training on Elasticsearch sysadmin as there is a difference between understanding how to set up, populate and report on a data store and how to optimally configure the hardware setup for that data store. Having said that I think we will get reasonable performance for at least a few tens of millions of occurrences so the need to explore this further is not immediate. The Elasticsearch documentation is very good so I've been able to pick up at least the basics.

Elasticsearch has a concept of an index being a group of related documents, normally with a similar structure. A single instance of Elasticsearch can support multiple indexes. I think when we discussed there woud "index" above, we actually meant there being a single instance of Elasticsearch (i.e. a single cluster on a single machine for now), not necessarily that there should be a single index. Now I've read all the documentation on this I am of the opinion that each warehouse should have it's own index within the cluster - note that it is easy to search both within and across multiple indexes so this doesn't really limit us.

One aspect of having multiple warehouses represented on the single cluster is that each warehouse will add documents to the indexes with IDs that won't match up. For example, in the proposed document structure you could do a query for indexed location_ids matching the location ID for England, but the location ID for England would be different on each of the 2 warehouses so you'd need to either limit this search to 1 index (i.e. 1 warehouse), or you'd need to search for the text England instead. The latter is of course not ideal and has internationalisation implications. I suspect though that this will be workable for our needs - you will get best querying possibilities when searching within 1 warehouse's index, but you also have a possibility to run queries that span all the warehouses even though they will have some limitations. If this becomes a serious issue in future then we can augment the data using Logstash to add global identifiers for some of the things we need to query across warehouses for.

**Comment by DavidRoy** [comment]
@johnvanbreda is the ES Index open by default?  My understanding is that we'd plug into via APIs and the data controls would happen at that point.  The Index would therefore need appropriate fields included to allow the necessary filtering for sensitive locations and confidential records.  Ideally, the Index includes ALL records from the warehouses.

I understand the distinction between ES server and Indexes and your description above seems sensible - a separate Index for Warehouse1 and Warehouse2 and potentially other data stores.

**Comment by johnvanbreda** [comment]
An implementation is now ready to try (should be fully populated by late tomorrow). Briefly, we will access the Elasticsearch index via a proxy URL on the warehouse which will allow clients to use the Elasticsearch Search API. The document structure is described at https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/document-structure.md. 

Some notes:
1. The ES index will contain 2 copies of any sensitive record, one blurred and one full precision.
2. We won't therefore grant direct access to the ES index, instead the warehouse will provide proxies within the REST API. Each proxy will provide access to the ES index via an "alias", an Elasticsearch construct which allows you to apply a filter to the data retrieved via the alias. Therefore we can provide aliases and proxy URLs that expose data from certain websites or projects. We can also use the aliases  to filter out full precision versions of records, unreleased and confidential stuff.
3. The REST API proxy end-points can be configured to only allow access to certain Elasticsearch APIs, e.g. the search API, so you can't "damage" the index.
4. REST API authentication can be applied to the proxy end-points, so you can authenticate using http header authorisation for example.
5. Currently the index is populated with public versions of sensitive records only, only records that are available on iRecord for public reporting and doesn't handle deletions. I can set this up when we've proven the concept for reporting though.

If anyone wants be to set up access for them to try please let me know.

**Comment by johnvanbreda** [comment]
Elasticsearch now configured on new server.

**Comment by DavidRoy** [comment]
Thanks John - now closing and will raise separate issues for switching to ES for ABLE reports
