### ISSUE TITLE
Changes to admin emails for user accounts

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#111]
Currently, admin emails on the live site (www.butterfly-monitoring.net) come from 

European butterfly Dev Site <bire@ceh.ac.uk>

This should be changed to:
European Butterfly Monitoring Scheme (eBMS) <ebms@ceh.ac.uk>

**Comment by BirenRathod** [comment]
@DavidRoy 
I changed the settings in SMTP module. it should be from ebms@ceh.ac.uk email address.

**Comment by DavidRoy** [comment]
Thanks.  Tested and now closing.
