### ISSUE TITLE
Menu stylying issue - for activated users without permission = data recorder

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#112]
The menu is incorrect for activated users that do not have any permissions set.

![ebms menu](https://user-images.githubusercontent.com/2699478/61933920-f6087400-af7e-11e9-903e-d71eecf260e1.png)

The menu items in black text should not be available

**Comment by Gary-van-Breda** [comment]
Sorted on Live.

**Comment by DavidRoy** [comment]
Thanks
