### ISSUE TITLE
User registration validation

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#114]
After registering with a new account this validation message appeared. So not sure if this means that my username is invalid or that just the message could be removed (improved).

<img width="642" alt="Screenshot 2019-07-30 at 14 52 22" src="https://user-images.githubusercontent.com/7383162/62135550-529ac480-b2da-11e9-9cc2-1d29bc202dba.png">

**Comment by johnvanbreda** [comment]
@kazlauskis do you know what the username was in this instance and whether the user account was actually created and linked to the warehouse?

Has this happened again since?

**Comment by kazlauskis** [comment]
@johnvanbreda I have tried it again and this hasn't repeated. Maybe it was a one-off then. Feel free to close it for now.

**Comment by johnvanbreda** [comment]
Thanks!
