### ISSUE TITLE
Integrate Scheme module with IForms

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/ABLE#115]
The new Scheme module allows us to review the way the Country (branch) assignment is carried out.

- My Sites Page: no change
- Site data entry: remove the "Branch CMS User ID" attribute, and all the functionality used to assign this Branch users. (This should be done last)
- National Sites: Add a hook call into the report grid to replace a placeholder in the report preset parameters with the location_id for the country associated with the current user. Write this hook in the scheme module. Alter the underlying report to query using the region location id rather than the "Branch CMS User ID" attribute.
- All Sites: No change
- Transect Allocation: Reconfigure the form to remove the Branch allocation (this will now be done automatically). Change the Country filter field to uses Schemes instead.
- My Walks: no change
- National Walks: Alter the report calendar grid to use the hook (see National Sites above). Reconfigure form to use the country attribute rather than the "Branch CMS User ID" attribute. (In this case the underlying Report should be OK).
- Reporting: Site/Visit Summary: (report grid assumed updated as for National Sites above): Alter report to allow a parameter to restrict the returned data for users Scheme (see also #79)
- Reporting: Annual Summary: Change "My Country" to lookup the country on the location via their scheme (same hook as above), rather than "Branch CMS User ID" attribute. Allow normal data recorders to see overall Scheme data, though ensure they do not have access to the data entry page for Walks that are not their own.
- Reporting: Mapping: No change(?)
- Reporting: Year index Plot: Add filter to restrict the available location list if user has a scheme (no filter currently exists - all users can see all sites): use same hook.
- Reporting: Section Plot: Add filter to restrict the available location list if user has a scheme (no filter currently exists - all users can see all sites): use same hook.
- File Upload: No change.

**Comment by DavidRoy** [comment]
include requirement #106

**Comment by Gary-van-Breda** [comment]
National Sites: Done (no report change required)
National Walks: Done (no report change required)

These have been pushed to Live.

**Comment by Gary-van-Breda** [comment]
New report ebms_visits_and_sites_summary.xml created, awaiting deployment onto warehouse.
This will go into a new version of the Reporting: Site/Visit Summary page, which will display either a users data, or their scheme's data (see #79)
The original report/page will be kept for supermanagers only.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I have pulled that report on to live warehouse.

**Comment by Gary-van-Breda** [comment]
Section Plot: Done & Pushed to Live

**Comment by Gary-van-Breda** [comment]
Reporting: Site/Visit Summary page : Done

**Comment by Gary-van-Breda** [comment]
Year Plot: Done & Pushed to Live

Still to Do:
- Site data entry
- Transect Allocation
- Reporting: Annual Summary

Then we remove the Branch CMS attribute.

**Comment by Gary-van-Breda** [comment]
Have removed the Country Manager allocation from the Transect Allocation form. this still needs some code changes to sort the filters.

**Comment by Gary-van-Breda** [comment]
New version of report ebms_region_locations.xml created, awaiting deployment onto warehouse.

This is required to make the region to site linked list in the Transect Allocation form work - a bugfix that is independant of this particular issue.

@johnvanbreda or @BirenRathod : can we have the current master branch of the brc reports deployed onto warehouse1? Thanks.

**Comment by johnvanbreda** [comment]
I've pulled the brc_reports folder @Gary-van-Breda.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : Thx. There is a commit which has not been pushed to live - comment 'Column title can be empty' : is this OK to go on Live? I have several commits waiting behind it. (These are the code changes for the Transect Allocation page)

**Comment by Gary-van-Breda** [comment]
Schemes now integrated into Site Data Entry page: scheme co-ordinators can edit a site if the country on the site matches the country associated with their scheme.
I have also tidied up the menu permission code, and created a dummy Italian page visible to Italian scheme members on the TEST system, under the ABLE main menu item.
Both of these code changes are on DEV and TEST, and queued up to go on Live subject to John's reponse to question above.
Only remaining page to do is the annual summary.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda fine about the commit going live.

**Comment by Gary-van-Breda** [comment]
All existing changes pushed to Live: Site Data Entry and Transect Allocation

**Comment by Gary-van-Breda** [comment]
@DavidRoy : I've completed the Annual Summary changes. I have pushed them through as far as TEST only, as there have been some fairly major changes to the filtering and I thought you should perhaps check them out to ensure you are happy with them before they go to Live. The fundamental changes are that the selection of branch/scheme data has moved from user filter to location filter, and there a more branch options for supermanagers.

**Normal Users:**
User filter : Can choose to see

- all their data, or
- Everyones combined data

Location filter: They can select to

- combine the data for all locations they have entered (independant of scheme, not available if selecting "everyone's data")
- combine the data for all their current scheme's locations, 
- pick an individual location to which they are currently assigned.

**Scheme coordinators:**
User filter : Can choose to see

- all their own data,
- Everyones combined data, or 
- the data for a particular person on their scheme

Location Filter: Can choose to 

- combine the data for all locations they are assigned to as a data recorder, 
- combine the data for all locations the selected user is assigned to as a data recorder (available only if a particular user is selected and is different from the scheme coordinator themselves), 
- combine the data for all sites on their scheme,
- pick an individual location on their scheme.

**Supermanager:**
User filter : Can choose to see

- all their own data,
- Everyones combined data, or 
- the data for any particular user (scheme independant)

Location Filter: Can choose to 

- combine the data for all locations they are assigned to as a data recorder,
- combine the data for all locations the selected user is assigned to as a data recorder (available only if a particular user is selected and is different from the supermanager themselves),
- combine all the data for all sites,
- combine all the data for all sites on any particular scheme, or
- pick any individual location (scheme independant).

**Comment by DavidRoy** [comment]
Thanks.  That works well and makes sense.  Please deploy to live

**Comment by Gary-van-Breda** [comment]
Code deployed to Live, and configured.
@johnvanbreda : the last stage is going to be removing the Branch CMS (Drupal) User Id attribute. Can I just remove the attribute from the survey? Will this remove the attribute values in the database?

**Comment by johnvanbreda** [comment]
Removing the attribute from the survey will leave the values "dead" in the database - if you let me know the survey ID and attribute ID I can clean them out properly.

**Comment by Gary-van-Breda** [comment]
Survey ID = 562 (EBMS Live)
Location attribute ID = 235 (Branch CMS User ID)
Shall I remove the attribute first?

**Comment by johnvanbreda** [comment]
Done - I removed the attribute from the survey as well as the values. Here's the script for reference:
```sql
update location_attributes_websites 
set deleted=true
where location_attribute_id=235 and restrict_to_survey_id=562;

update location_attribute_values
set deleted=true, updated_on=now(), updated_by_id=3
where location_attribute_id = 235 and location_id in (select location_id from locations_websites where website_id=118);
```

**Comment by Gary-van-Breda** [comment]
@DavidRoy : this issue is now completed - would you like to close it?

**Comment by DavidRoy** [comment]
Now working, thanks
