### ISSUE TITLE
Integrate scheme module with registration via the eBMS mobile app

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#116]
When implemented, the scheme module will require users to be assigned to a scheme.  

Need to establish how this will this work with the eBMS mobile app that does not require users to select a scheme on registration.

**Comment by Gary-van-Breda** [comment]
Scheme module no longer mandates a user has a scheme.
I think this can now be closed, as no longer an issue.

**Comment by DavidRoy** [comment]
Thanks
