### ISSUE TITLE
Incorrect explore link from 'Record details' page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#118]
From a record details page, e.g. 
https://butterfly-monitoring.net/mydata/details/record?occurrence_id=11037115

The 'Explore records of xxx' should link to a filtered version of the explore all records report, e.g. https://butterfly-monitoring.net/elastic/all-records?filter-taxon_meaning_list=187115

Current link is: https://butterfly-monitoring.net/mydata/my-records?filter-taxon_meaning_list=187115

**Comment by johnvanbreda** [comment]
Done
