### ISSUE TITLE
My records download file - updates

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#120]
Download file from my-record report to be simplified.  Remove the following columns as not relevant to eBMS:
Date start
Date end
Determiner
Vice County
Vice County number
Identified by
Coordinate uncertainty (m)

Missing values: quantity field is not populated

**Comment by johnvanbreda** [comment]
I've removed those columns. I tried downloading the records for dbr.ebms.test@gmail.com and the quantity field was populated OK. Please re-open if there is still a problem.
