### ISSUE TITLE
Deleting occurrences does not remove from ES report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#122]
As user: https://butterfly-monitoring.net/user/1301

Records are shown via:
https://butterfly-monitoring.net/elastic/my-records

But going to edit and delete list, the records are not removed from the ES report. 

Records are no longer accessible via the record-details page:
https://butterfly-monitoring.net/mydata/details/record?occurrence_id=11268322

**Comment by johnvanbreda** [comment]
Changes to records (including deletions) will only be replicated into Elasticsearch when the next Logstash run occurs. This means a typical delay of up to 15 mins if everything is up to date.

**Comment by DavidRoy** [comment]
Understood.  I'll raise a separate issue for an information message when deleting
