### ISSUE TITLE
New users automatically assigned 'data recorder' recorder

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#125]
I think we do not need an approval step for the 'data recorder' role for registrations via the website.  It adds a delay to new users getting involved and requires an extra admin step to setup users.

New users registering via the website to automatically setup as role = 'data recorder'

@Gary-van-Breda is this straightforward to implement.  The alternative is to remove the role completely.

**Comment by Gary-van-Breda** [comment]
This functionality has now been included in the EBMS Scheme module: a config option has been added which allows the specification of a role to be added automatically on user creation.

**Comment by Gary-van-Breda** [comment]
This has now been configured on Live

**Comment by Gary-van-Breda** [comment]
Note, the role is filled in after the save button is pressed on creation of the account.

**Comment by DavidRoy** [comment]
Thanks.  Closing
