### ISSUE TITLE
Problems with My sites and My walks

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#126]
@DavidRoy   @Gary-van-Breda 

The link to My sites https://butterfly-monitoring.net/my-sites and My Walks https://butterfly-monitoring.net/my-walks is not working and bring you to the home page (any section of the sites or walks). It is not working for any language.

**Comment by Gary-van-Breda** [comment]
I have flushed the caches: it looks OK now. Can you try again?

**Comment by CrisSevilleja** [comment]
Yes, now it is working. Thank you!
