### ISSUE TITLE
Message to users if trying to password reset after account locked

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#128]
relates to #127 

Need better handling of the scenario that a user locks their account due to multiple failed login attempts and then attempts a password reset

**Comment by Gary-van-Breda** [comment]
When this happens, an AccessDeniedHttpException is raised in the code. This is then configured on the page /admin/config/system/site-information to redirect to the front page (see under "Default 403 (access denied) page" field).
@BirenRathod Is there a reason we do this? Security?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
The redirection is the by default setup by Drupal. So we can change as per requirement.

**Comment by Gary-van-Breda** [comment]
OK, I switched off the 403 redirect on Live, so it will now give a more appropriate message when access is denied: this should include a message about why  access is blocked when a "flood" (blocked due to multiple failed login attempts) occurs.
