### ISSUE TITLE
enable viewing of samples within app

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#129]
Add option for app users to view samples in the app, including those submitted

**Comment by kazlauskis** [comment]
Is this for viewing samples submitted through the website?

**Comment by DavidRoy** [comment]
No, for within the app.  Maybe this can be closed?

**Comment by kazlauskis** [comment]
Thanks. Users can view submitted samples but only at a shallow level - not everything is shown. Let's leave keep it open for now.

**Comment by DavidRoy** [comment]
Requirement is to see the full sample/occurrence details in the app even after submission

**Comment by kazlauskis** [comment]
I agree this is important and we should have it before the first big public release.
