### ISSUE TITLE
Uploaded photos should be associated with occurrences not samples

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#130]
Currently photos are associated to the whole 15 minute sample.  They should be associated with the species occurrence instead to enable use within verification

**Comment by kazlauskis** [comment]
@DavidRoy sorry, I couldn't reproduce this, do you have an ID of a sample that has the photos?

**Comment by DavidRoy** [comment]
Athough you can't see the images, this is an example where two photos were added against two different species but both assigned to: http://warehouse1.indicia.org.uk/index.php/occurrence/edit/12176567

whereas one should have been assigned to: http://warehouse1.indicia.org.uk/index.php/occurrence/edit/12176568

**Comment by kazlauskis** [comment]
Ah, got it now! All photos are attached to the first occurrence of a sample rather than to multiple occurrences. I will fix it for the next update.

**Comment by DavidRoy** [comment]
Great.  I have a screen recording if you want me to demonstrate this.  But you are right, that the photos accumulate.
