### ISSUE TITLE
Upgrade warehouse2 to latest Indicia code

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/ABLE#14]
Will be required before integration with Elasticsearch.

**Comment by DavidRoy** [comment]
@johnvanbreda this could do with a bit of discussion before we decide this is needed.  I'm not now sure of the logic of 2 warehouses for species surveys.  We initially took this approach because European and UK projects were distinct.  That is no longer the case. For example, the European Ladybird App is on warehouse1 as users with an iRecord will be directed to this for ladybird recording in the UK.  The same is true of the butterfly App for this project - it will be used by UK recorders.

The need for a separate warehouse (warehouse3) for non-species surveys (i.e. soils) remains as this is a different user community.

Should we concentrate all species based Indicia projects in a single warehouse?  If so, how would we migrate users and data from warehouse1 to warehouse2

**Comment by johnvanbreda** [comment]
Elasticsearch does give us the possibility to merge data from multiple sources so could mitigate some of the problems with cross warehouse reporting, however I think this situation still going to be quite messy if we keep separate warehouses. Therefore I agree we should at least explore the idea of just using warehouse1. Do you have a feeling for the number of records the European Butterfly/ABLE project will generate? It may be that we will eventually need a server with more RAM and an SSD to cope but having the Elasticsearch reporting option will help a lot.

I think we will need a script written specially to do a merge of the 2 warehouses, including some level of intelligence so users aren't duplicated. Although it will be a bit of work to write this script, it should be possible to write it in such a way as to make it reusable in other instances.

**Comment by johnvanbreda** [comment]
Just the data move - 2.5 days which should give us a re-usable approach for extracting data from one warehouse into another.
There are some other considerations:
1. Currently, warehouse 1 is built around UKSI providing the taxonomic backbone around which other lists are linked. For example, a query filtered to a family can be based around the hierarchy in UKSI even if the list used is not UKSI, since we can map across using taxon version keys. Although not essential, we will be losing this functionality unless we work out a way of allowing the European butterflies list to sit nicely alongside UKSI. For example we don't have the following subfamilies in UKSI: Aphnaeinae, Charaxinae,Libytheinae, Nemeobiinae.
2. We should probably consider again whether a move to a server that can support more RAM and an SSD would be wise if the data volume grows substantially. Not all queries will be serviced via Elasticsearch so continuing work on performance is to be expected.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda there is now a collection of scripts plus documentation on how to move the data from warehouse2 to warehouse1 for EBMS at https://github.com/Indicia-Team/support_files/tree/master/SQL%20scripts/migrate%20data%20between%20warehouses.
**Please note the scripts are complex so it would be worth testing onto the dev server first**. Do you have a test environment that could be pointed to the dev server if I try the migration?

**Comment by DavidRoy** [comment]
@johnvanbreda 
The Fauna Europe hierarchy is helpfully made available via a data paper:
https://bdj.pensoft.net/article/4034/list/5/

See supplementary material 11.  Direct link to file
http://bdj.pensoft.net//lib/ajax_srv/article_elements_srv.php?action=download_suppl_file&instance_id=759228

But less helpful is that it starts at sub-family.  If you can advise on the format, I could link the EU Butterfly Genera to Fauna Europeae sub-families so we have the complete tree

**Comment by johnvanbreda** [comment]
Are there other projects which are likely to use taxa from outside UKSI? Or is ABLE likely to involve non-Lepidoptera taxa? If not, then actually I think we should just keep it simple. I'll load up the provided list into warehouse 1 complete with higher taxa up to Kingdom, then use a query to auto-generate the matching TVKs where available. Where they are not available, I'll create a "pseudo-TVK" in a format that won't clash with any existing TVKS.
This approach does mean that it may be require additional fiddling with IDs to get a single query across UKBMS & ABLE data that pulls in a single higher taxon (e.g. a family) within the warehouse to work, However it should at least work as a text based Elasticsearch query, so I suggest we cross that bridge when we come to it. 
Does that sound OK?

**Comment by DavidRoy** [comment]
- Other projects using the warehouse will go beyond the UK.  
- ABLE is just Lepidoptera.
- What you suggest sounds ok, but there is no particular priority/urgency to integrate UKBMS with the ABLE online capture system (www.butterfly-monitoring.net/mydata).   Although they use the same system, they are somewhat separate.
- Similarly, there is no specific need to use/align to TVKs unless it's a convenient external key to build upon (but maybe Fauna Europa keys are better for the higher taxa)

**Comment by johnvanbreda** [comment]
I can align the higher taxa to Fauna Europea, though I note that Nemeobiinae is not present which seems to be an omission.
Is it worth the effort of aligning the lower taxa? Given the low priority at the moment of integrating reports from multiple systems, I think it may be easiest to just generate a unique ID in a format that is recognisably different, so we can report within ABLE for now and resolve the issue of aligning taxa later if and when it becomes important.

**Comment by DavidRoy** [comment]
Yes, Nemeobiinae is an omission and may reflect recent taxonomy changes that Fauna Europea hasn't tracked.
Agreed, that alignment is not currently a priority.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : can we have testwarehouse brought up to latest version as well?
Thx

**Comment by johnvanbreda** [comment]
Species list covered by #13 

@BirenRathod is doing the test warehouse upgrade as it's also going on the new server

**Comment by johnvanbreda** [comment]
@Gary-van-Breda any thoughts on running a migration of the warehouse2 records to the dev server and being able to test that it worked OK?

**Comment by BirenRathod** [comment]
Hello @Gary-van-Breda

I have upgraded warehouse to version 2 code. I haven't found major problem apart from below index creation failed.

CREATE INDEX ix_cache_occurrences_functional_verify_taxa
  ON cache_occurrences_functional
  USING GIN(website_id, taxon_path)
WHERE record_status='C' and record_substatus IS NULL;

ERROR: data type integer has no default operator class for access method "gin"

**Comment by johnvanbreda** [comment]
@BirenRathod the v2 upgrade notes mention you need to run:
```
CREATE EXTENSION btree_gin;
```
Then it should be OK to create this index. It only helps a bit with verification performance.

**Comment by BirenRathod** [comment]
@johnvanbreda 
I did, still gives same error.

**Comment by BirenRathod** [comment]
@johnvanbreda 
It works after I used set search_path. Many thanks.

**Comment by DavidRoy** [comment]
@Gary-van-Breda can we close this issue.  And raise a separate issue about migrating to Warehouse 1 for later in the year?

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : you may be a better person to respond to this question. Looks like warehouse 1 is at 2.21.0, warehouse2 at 2.18.2 -- is this close enough?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Yes, it is , I will upgrade today.

**Comment by johnvanbreda** [comment]
As long as we are on 2.x, then updating to the current minor release is straightforward, so I am happy with 2,18. Further upgrades can be applied as code is developed.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
It has been upgraded to 2.21.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : then I think we can close this now.

**Comment by DavidRoy** [comment]
Thanks
