### ISSUE TITLE
Enable option to submit single sightings

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#140]
Add option to add ad-hoc/individual occurrences

**Comment by kazlauskis** [comment]
Is there an existing survey for this?

**Comment by DavidRoy** [comment]
No.  Are you ok setting up?

Sharing relevant attributes with times count or transect surveys

**Comment by kazlauskis** [comment]
Sure, which of the attributes would you like us to use?
* Temperature
* Sun
* Wind direction, speed
* Recorder

**Comment by DavidRoy** [comment]
Just recorder name and a quantity measure

No need for the weather details on this 'causal records' mode

**Comment by DavidRoy** [comment]
view from martin warren -  will need a very clear introduction which I suggest has to be read and ticked before you move on to use the app for the first time.

Also consider using the milestone functionality within Indicia to email recorders who generally use casual recording mode, i.e. advocate the value of timed counts

**Comment by DavidRoy** [comment]
closing this as unlikely to ever do this
