### ISSUE TITLE
Add current location symbol to map

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#141]
Testing feedback:
For the map, would it be possible to have a dot marker to show the position of the latest fix as well as the blue line? When doing the timed count in the back garden (standing still) it didn't look as if the map had picked up my location - until I walked up and down the garden and a blue line then appeared.

**Comment by DavidRoy** [comment]
@kazlauskis can we close this issue?

**Comment by kazlauskis** [comment]
This isn't done yet. I'll add this to the next milestone.

**Comment by kazlauskis** [comment]
I suggest showing the start of the trail, the current last point and also the end of the trail when the survey was finished. Something similar to how the Strava app does:

 
![Screenshot 2022-12-22 at 10 48 40](https://user-images.githubusercontent.com/7383162/209095459-2d64682f-488a-4b6d-8882-70ffd3c02fae.png)
