### ISSUE TITLE
Need to confirm initial GPS fix before tracking route?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#142]
user feedback:
For the tracking, I noticed that the initial jumping-around as the satellite fix is refined is actually tracked as part of the route - see attached screen grab. I walked the whole transect in a south-westerly direction, and the initial northwards jump was just my phone figuring out my GPS location. Not sure how this could be fixed - perhaps the first couple of fixes should be ignored or something?

![app](https://user-images.githubusercontent.com/2699478/66259308-5e59aa00-e7a7-11e9-953d-205871b79c52.png)

**Comment by DavidRoy** [comment]
@kazlauskis can we close this?

**Comment by kazlauskis** [comment]
Let's close it. I haven't heard of this one happening again and we did improve how we capture the area since.
