### ISSUE TITLE
Add sample attributes to samples tab of explore report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#145]
To add to:
https://butterfly-monitoring.net/elastic/my-records

Samples tab, add the following attributes:
1. Start time
2. End time
3. Area sampled

**Comment by johnvanbreda** [comment]
Done

**Comment by DavidRoy** [comment]
Re-opening as the area sampled field is not being populated.
![samples](https://user-images.githubusercontent.com/2699478/68933448-5a08af80-079d-11ea-9e8f-19711efb313c.png)

**Comment by johnvanbreda** [comment]
This is a data issue, the area sampled attribute is not being stored for sample ID 7045628 for example. This sample is in survey 562 but the area sampled (m2) attribute (ID 723) is only linked to survey 565.

**Comment by DavidRoy** [comment]
@johnvanbreda yes, please restrict the report page to survey = 565.  The Area sampled (id 723) is linked to this survey and should therefore display for the other samples?

**Comment by johnvanbreda** [comment]
Fixed. The survey ID now applied as a filter, plus an extraneous space removed from the config that broke it for the other samples. Please close if OK.

**Comment by DavidRoy** [comment]
Thanks, closing
