### ISSUE TITLE
Enable sample list download

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#146]
For https://butterfly-monitoring.net/elastic/my-records, samples tab.  Enable spreadsheet download of data grid.

Requires this issue to be completed first
#145

**Comment by johnvanbreda** [comment]
Code in develop branch (warehouse, client_helpers and media) can support download of ES composite aggregations. This would need to be set up on the page after the next full release.

**Comment by DavidRoy** [comment]
@johnvanbreda are we able to finish this issue?

**Comment by johnvanbreda** [comment]
@Gary-van-Breda is it OK for me to update the client helpers and media folders fully, or would you prefer for me to restrict the update to just the Elasticsearch reporting code?

**Comment by Gary-van-Breda** [comment]
@johnvanbreda  Can I review the state over the next couple of days, and get back to you?

**Comment by DavidRoy** [comment]
@Gary-van-Breda is waiting on you?

**Comment by Gary-van-Breda** [comment]
OK: There are no changes to the Iform and media on ABLE which are not in the main repository.  
I have created a branch on client_helpers which has the single outstanding change in ABLE (#191), and I have assigned the merge request to you, @johnvanbreda.  
As a note, I have also (erroneously?) done a change to helper_base.php to switch on the language delegation: I know this should be done in helper_config.php, but none of these files are in Git, and I do not have access into the environment. When you drop the new client_helper in, this will be overwritten - I suppose the proper way would be to edit the helper_config.php on each environment to switch it on in there.

**Comment by johnvanbreda** [comment]
Thanks @Gary-van-Breda, I'll update iform when I get a chance then. 

I think you can just add a helper_config.php file to the respository, containing the single `$delegate_translation_to_hostsite` variable setting?

**Comment by Gary-van-Breda** [comment]
Do you know if there are any helper_config files on the systems as they are, which would be overwritten by such a file?

**Comment by johnvanbreda** [comment]
As there is nothing under Git, I am reasonably sure that there is no helper_config.php file. Not sure if you spotted this change but about a year ago I changed things so the helper_config.php file can be omitted if just using Drupal settings (it used to make things fall over if you accidentally removed it during an upgrade for example).

**Comment by Gary-van-Breda** [comment]
OK - I've done that now, pushed onto master: you should now be able to copy the current develop branches of media and client_helpers over to ABLE.

**Comment by DavidRoy** [comment]
@johnvanbreda can we complete this issue now?

**Comment by johnvanbreda** [comment]
This is now configured on the live site, as well as a species list download.
