### ISSUE TITLE
Discrepancies in field content of .shp and .csv reports of sites and sections

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/ABLE#148]
From the page "National sites", the fields of the "Full Site Sections data download (CSV)" and the SHP have discrepancies have discrepancies in their content:
Section code (.csv) = e.g. S1, S2, S3... => duplicates 
Section_code (.shp) = e.g. EBMS:Luxembourg:10.1, EBMS:Luxembourg:10.2, ... => unique

So there are currently no possibilities to make a join between these fiels based on section IDs.  
In the .csv, fields "Site ID" and "Section ID" are not in the .shp. 
Would be great to add these IDs in the .shp, or at least to change the content of the "Section code" (of the .csv) to be unique and joinable with the "Section_code" of the .shp.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda or @birenrathod : can we replace the section_gis_download_view in the ukbms shema on warehouse 1 with the following view?
```
-- View: ukbms.section_gis_download_view

-- DROP VIEW ukbms.section_gis_download_view;

CREATE OR REPLACE VIEW ukbms.section_gis_download_view AS 
 SELECT section.id AS section_id,
    (COALESCE(l.code, l.name)::text || '.'::text) || "substring"(section.code::text, 2) AS section_code,
    section.code AS section_number,
    section.centroid_sref AS grid_ref,
    l.id AS site_id,
    l.code AS site_code,
    l.name AS site_name,
    lw.website_id,
    l.location_type_id,
    lav.location_attribute_id,
    ('|'::text || string_agg(lav.int_value::text, '|'::text)) || '|'::text AS attr_value,
    section.boundary_geom AS geom,
    round(st_length(st_transform(section.boundary_geom, 27700))) AS section_length
   FROM indicia.locations_websites lw
     JOIN indicia.locations l ON l.id = lw.location_id AND l.deleted = false
     JOIN indicia.locations section ON section.parent_id = l.id AND section.deleted = false
     LEFT JOIN indicia.location_attribute_values lav ON lav.location_id = l.id
  WHERE lw.deleted = false AND geometrytype(section.boundary_geom) = 'LINESTRING'::text
  GROUP BY section.id, ((COALESCE(l.code, l.name)::text || '.'::text) || "substring"(section.code::text, 2)), section.code,
	section.centroid_sref, l.id, l.code, l.name, lw.website_id, l.location_type_id, lav.location_attribute_id,
	section.boundary_geom, (round(st_length(st_transform(section.boundary_geom, 27700))))
  ORDER BY l.name;

ALTER TABLE ukbms.section_gis_download_view
  OWNER TO postgres;
```

**Comment by Gary-van-Breda** [comment]
@johnvanbreda or @birenrathod : can I have the new version of the ebms_site_sections_download.xml file deployed from the brc-reports into warehouse1? Thx

This adds the unique section code to the "Full Site Sections data download (CSV)".

After this it should be quite easy to join the data.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

The view in ukbms database has been implemented now and report has been pulled down now.

**Comment by Gary-van-Breda** [comment]
Thx @BirenRathod 
I have updated the layer in geoserver, so now the shp file includes the new columns added to the view.
@xaviermestdagh : can you confirm that you can now join the data, and if you are happy, close this issue?

**Comment by xaviermestdagh** [comment]
That's great, many thanks!
