### ISSUE TITLE
Enable transect count mode for app

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#149]
add in functionality to enter data against routes/transects already.  
The requirement here is for a user having the option to select a transect (location where website = ABLE and Type = Transect) already setup (via the website) and assigned to the user logged into the app.  Then a simple user interface to allow entry of the sample attributes (linked to surveyID = 562), list of occurrences (species with count) for each transect section (sub-site location in indica where website = ABLE and Type = Transect Section.  

This functionality does not require access to phone location information (i.e. GPS) as the location is already known in advance

**Comment by kazlauskis** [comment]
* Is the `Recorder` attribute necessary to show the user for editing or could it be pre-populated with the user account details on submit?
* Does `Sun` attribute have to be per-section or a global one is enough?

**Comment by larspett** [comment]
As for SeBMS, pre-populated would be fine. sun would be fine as a global attribute for us but others may have other preferences. We started in 2010 with per-section sun information but later I heard quite a few BMSs do not use it at the per-section level.

**Comment by DavidRoy** [comment]
Yes, recorder can be pre-populated from account but ideally editable

Sun is per-section but can be set globally

**Comment by DavidRoy** [comment]
Also, further sample attribute is ‘completeness’.  Should be available in warehouse

**Comment by DavidRoy** [comment]
Sample Attribute to add into 'eBMS Transect mode' = 
Reliability (ID 1393, restricted to Transect Section)

For 'Sun', we intend to switch to the inverse (% cloud) as this is used by most scheme #68

**Comment by kazlauskis** [comment]
@DavidRoy for the timed count we have created a mobile-specific survey, I assume in this case here for the transects the app should post the existing eBMS survey (surveyID = 562) is that correct? If that is the case, would you like me to enhance the survey to capture mobile-specific attributes like device operating system, app version etc?

**Comment by DavidRoy** [comment]
@kazlauskis yes and yes

Link to surveyID = 562 and add in mobile-specific attributes

**Comment by kazlauskis** [comment]
@johnvanbreda When submitting a transect record from the app, does sending the `zero_abundance: t/f` attribute matter or can the app skip it? I have tried it both and the website forms showed up the same. Cheers.

**Comment by johnvanbreda** [comment]
@kazlauskis if you set the zero abundance=t flag for any record which is actually a zero count, then it will still be a record but will be shown with a strike-through style on any Explore pages. It can also then be filtered out of any reports as appropriate. It needs to be set by the client (i.e. the app) rather than automatically on the server, since only the client knows the exact behaviour of all the abundance attributes it uses.

**Comment by DavidRoy** [comment]
@kazlauskis I don't think zero_abundance is relevant for the app and can be skipped.  The transect and timed area count protocols are both expecting positive counts for species recorded

**Comment by kazlauskis** [comment]
@DavidRoy do you say the app shouldn't allow empty lists submission, right? If so then I will skip the flag indeed.

**Comment by DavidRoy** [comment]
Empty lists are fine.  This is a sample without any occurrences?

This is different from occurrences with zero_abundance.

Zero abundance/absence is a difficult concept in the context of the eBMS samples.

**Comment by kazlauskis** [comment]
Got it, thanks 👍
