### ISSUE TITLE
New report for www.butterfly-monitoring.net/mydata: users

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#15]
Report of user allocation to transects.  Required fields in report:
userID
userName
userEmail
LocationType
LocationsID
LocationName

Report only available to country manager role, for transects within their country boundary

**Comment by Gary-van-Breda** [comment]
See UKBMS issue # 80

**Comment by Gary-van-Breda** [comment]
@BirenRathod : Can you put the most recent version of https://github.com/BiologicalRecordsCentre/indicia-reports onto both warehouse2 and the testwarehouse? (I don't think it is on the testwarehouse at all, so the module will need to be switched on, not sure about warehouse2)

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Reports have been pulled down on all three warehouses. Also latest code have been pulled down on testwarehouse & warehouse2.

**Comment by DavidRoy** [comment]
@Gary-van-Breda can this report now be implemented

**Comment by Gary-van-Breda** [comment]
@BirenRathod : Can you (again) put the most recent version of https://github.com/BiologicalRecordsCentre/indicia-reports onto both warehouse2 and the testwarehouse? (There should be a new report in the ebms directory)

**Comment by Gary-van-Breda** [comment]
@DavidRoy : this page is only displayed for the "super manager" role and the "scheme co-ordinator' role.
The "super manager" can see every country, and every user.
The "scheme co-ordinators" need to be associated with a scheme in their user account (as defined in #25), and can only see transects whose centroid is within the boundary of the scheme/country, or whose country attribute is set to the scheme/country. Do I restrict the users that "scheme co-ordinators" can see (and hence can allocate to a transect) to those users who are associated with that the same scheme? (e.g. If X is a scheme coordinator for scheme A, and Y is a user on scheme B, should X be able to see Y?)

**Comment by DavidRoy** [comment]
@Gary-van-Breda thanks.  What is the url.  Is this on the live/test/dev drupal 8 sites?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I have pulled the reports on all warehouses yesterday.

**Comment by Gary-van-Breda** [comment]
@BirenRathod : is there any caching going on? I can't see the new report or warehouse2 (John's new versions of the UKBMS reports are also not there), and there is no "projects" directory at all on the test warehouse. I've checked via the report selector widget on the Iform page and through the warehouse Reports page. 

@DavidRoy : the report can be downloaded from the "Download Allocations Report" button near the bottom of the "Transects Allocation" page: this is currently only configured on dev (http://dev-butterfly-monitoring.pantheonsite.io/transects-allocation) and test (http://test-butterfly-monitoring.pantheonsite.io/transects-allocation), but this will be of limited use until the issue with the report (see above) is bottomed out. I haven't touched Live yet.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

Ahh, no caching, I just upgraded warehouse2 code and reports folder too.

**Comment by DavidRoy** [comment]
On test.  When logged in as admin, the report produced a file as expected.  Although with following features:
Column Location type had all rows with value 'Column report:location_type_term not found'
Column Location code had all rows with value 'Column report:code not found'
Column Country had all rows with value: 'Column report:attr_country_name not found'

When masquerading as http://test-butterfly-monitoring.pantheonsite.io/user/447 which has role = 'scheme co-ordinator' and country = Italy

The report does not download and returns to the home page, trying to find the url:
http://test-butterfly-monitoring.pantheonsite.io/iform/ajax/ebms_transects_allocation/downloadSiteAllocations/35?location_type_ids=107&attribute_id=20&region_location_type_id=213

**Comment by Gary-van-Breda** [comment]
I've cleared the Caches, and swapped the report over to use the newer ABLE/EBMS version (not UKBMS). Downloads OK for me now.
Bit concerned that the Italy search is not working - it may be that the country boundary geometry is too complex.

**Comment by DavidRoy** [comment]
Both issues are now resolved.  Italy download is fine.
@Gary-van-Breda shall we close this issue?

**Comment by Gary-van-Breda** [comment]
Yes, I think so: as you opened it @DavidRoy , I'll let you do the honours...

**Comment by DavidRoy** [comment]
Gladly, thanks!
