### ISSUE TITLE
Create a report to pull user transects

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#150]
This links to BiologicalRecordsCentre/ABLE#149 where the app should allow a user to submit surveys based on selected transects. The specification here is work in progress, so feel free to update.

Example request:
```js
{
  "userID": 1234,
  "websiteID": 456
}
```

Example response:
```js
[
  {
    "id": 123,
    "name": "River meadows",
    "entered_sref_system": 4326,
    "entered_sref": "55.49359, 22.18693",
    "sections": [
      {
        "id": 224311,
        "entered_sref_system": 4326,
        "entered_sref": "55.4, 22.13",
      },
      {
        "id": 224324,
        "entered_sref_system": 4326,
        "entered_sref": "55.459, 22.693",
      }
    ]
  },
  {
    "id": 456,
    "name": "Wittenham clumps",
    "sections": [
      {
        // ...
      }
    ]
  },
  // ...
]

```

**Comment by DavidRoy** [comment]
Thanks.  @Gary-van-Breda i suggested you pick this up but it might be better suited to @johnvanbreda?

**Comment by Gary-van-Breda** [comment]
Sorry - I don't have more visibility of the workings of mobile app - is the userId the Drupal CMS ID, or the Indicia Warehouse User ID?

**Comment by kazlauskis** [comment]
Here in this example I was thinking of Drupal user ID. The spec above is mostly speculative as I don't know the current structure of the transects, how they are stored and what properties have. If you have any info to share then that would be great. Thanks.

**Comment by Gary-van-Breda** [comment]
The surveyID for the transects is 562
The transects are stored as locations with the following data:

- Parent_id is null
- Name
- Sref /System/Gemoetry - usually the centre point of the sections.
- Code : unique text value.
- Location Type : Transect
- Attribute : CMS User ID (ID 234, multi value integer, holding the Drupal CMS User ID of users this Transect is allocated to, optional)
- Attribute : Country (ID 233, integer pointing to ID of location it belongs to, used for scheme allocation, mandatory) 
- Attribute : No. of sections (ID 216, integer, mandatory) 
- Attribute : Overall Length (m) (ID 217, integer, automatically generated from the lengths of the Transect sections, optional)
- Attribute : Transect Width (m) (ID 218, lookup list, optional)
- Attribute : Sensitive (ID 219, boolean, optional)
- Attribute : Principal Habitat (ID 221, lookup list, optional) 
- Attribute : Principal Land Management (ID 225, lookup list, optional)
- Attribute : 2nd Habitat (ID 222, lookup list, optional)
- Attribute : 2nd Land Management (ID 226, lookup list, optional)
- Attribute : Principal Land Tenure (ID 223, lookup list, optional)
- Attribute : 2nd Land Tenure (ID 224, lookup list, optional)
- Attribute : Notes on habitat, land management and tenure (ID 227, optional)

The Transect sections are also stored as locations:

- Parent_id is the location ID of the Transect.
- Code : Section number prefixed with 'S', e.g. 'S4'
- Name : Constructed name from Transect name and Code
- Sref /System/Geometry - should be a line geometry describing the section, though it is initialised to a point before it is drawn in. System will match the system on the Transect.
- Location Type : Transect Section
- Attribute : Section Length (m) (ID 220, integer, automatically calculated from the drawn geometry) 
- Attribute : Primary Habitat Present (ID 228, lookup list, optional)
- Attribute : Primary Land Management Present (ID 230, lookup list, optional)
- Attribute : 2nd Habitat Present (ID 229, lookup list, optional)
- Attribute : 2nd Land Management Present (ID 231, lookup list, optional)
- Attribute : Linear habitat (ID 236, lookup list, optional)
- Attribute : Notes on Land use and management (ID 232, text, optional)

Which of all these do you want?

When it comes to the samples, there is a similar structure, with a supersample pointing at the Transect, and subsamples for each Transect section pointing at the supersample as their parent sample and at the Transect Section location. The occurrences are attached to the subsamples.

**Comment by DavidRoy** [comment]
Thanks.  For the initial requirement, the following are needed I think.

1.  To provide the user with a list of transects they are assigned to, together with the name and code of the transect and the number of sections for the transect.
Requires a request to identify the transects assigned to a user (defined by their DrupalID), transect name, code and the number of sections

2. The user to select a transect from the list above and enter a new transect walk, with the sample information: recorder, date, start time, end time, temperature, %cloud/sun, wind speed, wind direction, notes
Requires a supersample post, with location = Transect

3. The user to enter occurrence list for each transect section.
Requires a list of Transect Section location IDs to post against?  Uses same supersample ID from step 2 above, but separate subsample IDs?.  Species list has occurrence attribute=780 for species' abundance counts.  %cloud/sun (sample_occurrence ID = 1387) can be given for each subsample (transect sections).

**Comment by johnvanbreda** [comment]
@Gary-van-Breda I'll assume you've picked this one up then unless you tell me otherwise.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : can you deploy the new reports/projects/ebms/ebms_app_sites_list.xml in the brc-report repository into warehouse1? Thx

**Comment by johnvanbreda** [comment]
@Gary-van-Breda done

**Comment by Gary-van-Breda** [comment]
@kazlauskis : the report is there now. It uses "website_id", but otherwise is as requested.

reports/projects/ebms/ebms_app_sites_list.xml

**Comment by kazlauskis** [comment]
Thanks @Gary-van-Breda, what can I use for `location_type_id` and `locattrs`? Also, is the `website_id` here the same for all users, that is `118`?

**Comment by Gary-van-Breda** [comment]
You should be able to leave those empty
Yes - everyone is website_id = 188

**Comment by kazlauskis** [comment]
@DavidRoy does this cover United Kingdom?

**Comment by kazlauskis** [comment]
@Gary-van-Breda would it be possible to retrieve the path of a transect in the future? This is not an immediate requirement.

**Comment by DavidRoy** [comment]
Yes, UKBMS website.id = 27

**Comment by kazlauskis** [comment]
I have tried to create a new transect on the eBMS website and it didn't allow me to select UK, I assume this should be done on the UKBMS site instead right?

**Comment by DavidRoy** [comment]
Correct.  Actually, thinking about this - it won't work easily as the users will be registered with eBMS.  Forget about the UKBMS for now, and I'll give it some more thought

**Comment by Gary-van-Breda** [comment]
@kazlauskis : There are already KML, GPX and SHP file format downloads of the section paths available on the main Drupal site (the paths are held on the section location records, not the transects themselves), so yes it should be relatively easy to get. What format would you want?

**Comment by kazlauskis** [comment]
Can you do GeoJSON or WKT?

**Comment by Gary-van-Breda** [comment]
We could probably do WKT out of the box: GeoJSON would take a little bit more work but would be doable - may a day or two to add a new report format type.

**Comment by kazlauskis** [comment]
WKT is fine, if that doesn't require much of your time then please add this in to the response of the report. Cheers

**Comment by johnvanbreda** [comment]
@Gary-van-Breda FYI there is this function which I've successfully used elsewhere: http://www.postgis.org/docs/ST_AsGeoJSON.html

**Comment by kazlauskis** [comment]
@Gary-van-Breda any thoughts on when the section paths could be added to the report?

**Comment by kazlauskis** [comment]
@Gary-van-Breda could you also add `location_id`, `entered_sref_system` and `entered_sref` to responses? I have updated the example.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : when I use the report engine to attempt to generate the JSON structure above, I get the sections data as JSON encoded strings, rather than an array of objects, and similar for the ST_AsGeoJSON. Has what @kazlauskis is asking been done before, and if so where?
This looks like an API type thing, rather than something that can be handled by the report engine. I could conceivably add something into the report engine to process the column into a structure before it is re-JSONed, but I want to make sure this hasn't already been done somewhere else, and make sure I don't break anything that already relies on the data coming out as a JSON encoded string.

**Comment by kazlauskis** [comment]
@Gary-van-Breda does the system have any transects without any sections? or should I exclude such possibility? Cheers

**Comment by Gary-van-Breda** [comment]
It is possible for a transect to not have the sections defined for it, and/or have a number of sections = 0. I do not know if there are any just now.

**Comment by DavidRoy** [comment]
@Gary-van-Breda we should restrict the transect number to be 1 at least where setup.  

@kazlauskis - for the app you can assume there is at least 1 section for a transect site.  As Gary says, for some transects we'll know the number of sections but have no route (GIS) data for them

**Comment by kazlauskis** [comment]
@Gary-van-Breda I am planning to release the app functionality that uses the report by the end of next week. Do you think it is possible for the updated report to be ready sometime early next week? Don't worry about the transect paths for now.

**Comment by Gary-van-Breda** [comment]
@kazlauskis : can we separate the two reports, one for the transects, and one for the sections for a transect? I think this is the easiest way to get the current report engine giving the data you require.

**Comment by kazlauskis** [comment]
@Gary-van-Breda we can do that but only if there are not better ways. If a user has 8 different transects then the app will have to make 1+8 requests on a slow mobile network to gather all the relevant information. Knowing how slow some of our reports can be the user experience will be poor here.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : can you deploy the new reports/projects/ebms/ebms_app_sections_list.xml in the brc-report repository into warehouse1? Thx

**Comment by Gary-van-Breda** [comment]
@kazlauskis : this new report takes the request format:
```
{
  "websiteID": 118,
  "location_list": "1974,1975,1976"
}
```
Note the location list is a comma separated string of the transect location ids, and will return all the sections for those transects. This means you should need just 2 requests.
It should return a list of the parent_id, id, name, code, centroid_sref, sref_system and geom (as a stringified GeoJSON object) for each section whose parent is in the location_list provided.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda just to confirm - I've pulled the BRC reports module on warehouse1 but it was already up to date.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda if you are still needing help with the question above about JSON encoding of the sections and GeoJSON data can you let me know exactly what you are doing in order to see the problem please?

**Comment by kazlauskis** [comment]
@Gary-van-Breda looks good to me, thanks. Can you also add the `centroid_sref` and `sref_system` to the transect?

**Comment by kazlauskis** [comment]
@Gary-van-Breda could you also put this report to `devwarehouse`? I am using the dev site for testing the functionality.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : I think I'm happy about where we are with these 2 reports.
I've updated the reports/projects/ebms/ebms_app_sites_list.xml report to include the 2 new columns: can you deploy it to both warehouse1 and the devwarehouse ?
Thx

**Comment by johnvanbreda** [comment]
I've done warehouse1. @BirenRathod do you mind pulling the brc_reports module on the devwarehouse please, either that or reset my password as I can't log in. Thanks!

**Comment by BirenRathod** [comment]
@johnvanbreda 
I have pull the reports now. Also I have reset the password too. please change the password after you logged in.

**Comment by kazlauskis** [comment]
Thanks all for helping to build the report ✌️ The app is now using this and I am closing the task.

**Comment by kazlauskis** [comment]
@Gary-van-Breda some users aren't getting the transects. This account that should have some transects: `dbr.ebms.test@gmail.com`, drupal ID `1301`. Would you be able to look into this?

**Comment by DavidRoy** [comment]
@Gary-van-Breda it is my account under email dbr@ceh.ac.uk where I am not seeing my sites listed via the app.
user = https://butterfly-monitoring.net/users/david-roy

I should be seeing this site listed on the app, when calling the report created for this issue:
https://butterfly-monitoring.net/ebms-site-details?id=222517

**Comment by DavidRoy** [comment]
Closing as sites now appear after log out/in to the app

**Comment by kazlauskis** [comment]
@Gary-van-Breda please ignore the last few comments from myself and David. The transects are returned correctly. 

For one user the sections report is not returning any sections though.

Transects report:
```js
website_id:118
userID:1281

{
    "data": [
        {
            "id": "220098",
            "name": "Trans1",
            "centroid_sref": "56.03327N 8.11836E",
            "sref_system": "4326",
            "sections": "10"
        },
        {
            "id": "220097",
            "name": "Trans1",
            "centroid_sref": "56.03327N 8.11836E",
            "sref_system": "4326",
            "sections": "10"
        }
    ]
}

```

Sections report:
```js
website_id:118
userID:1281
location_list:220098,220097

{
    "data": []
}

```

**Comment by DavidRoy** [comment]
@Gary-van-Breda in this case, the transect site is setup but not its component sections.  This is why no data is returned.  

One suggestion for dealing with this scenario is that sections (child locations) are automatically setup on site (parent location) setup.  On initial setup, the sections (child locations) can have the same spatial information (i.e. point) as the transect (parent) location.

I believe this approach is used on the setup of the UKBMS WCBS sites?

**Comment by Gary-van-Breda** [comment]
That approach is used on WCBS, but only for the sites that I upload (from a CSV file). I then create another CSV file with the sections in and then upload that. If a site is created manually from the data-entry form, then the sections are not created - there is currently no functionality to create the sections automatically in the site data entry form on either UKBMS or ABLE/EBMS.   
Do you want this altered? We can create the sections when the sites are created, and when the number of sections is altered. We will also have to do a data fix to retrospectively create the sections for site where this has not already happened.

**Comment by DavidRoy** [comment]
Yes, i think we need this to prevent frustration with app users.  How work do you estimate to complete this?

**Comment by Gary-van-Breda** [comment]
About a day...

**Comment by DavidRoy** [comment]
Please schedule this in.  i will close this issue and start a new one.
