### ISSUE TITLE
Verification filter setup by Countries (of Europe) and NUTS region

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#152]
For the where element of the filter setup for verification - https://butterfly-monitoring.net/admin/filter-edit

the options should be countries of Europe and NUTS regions (first sub-country level)

remove UK-specific layers currently offered:
ViceCounty
Butterfly Conservation Branch
National Trust Site
RSPB Reserves
National Nature Reserve
Country (as currently only UK countries plus Isle of Man)

**Comment by johnvanbreda** [comment]
Done
