### ISSUE TITLE
Mobile photo upload doesn't work

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#153]
Uploading a photo shows an error in Drupal logs. Sample is still created but the photo in the occurrence is missing, showing an empty image thumbnail. To replicate this open the eBMS app and create a test record.

**Comment by BirenRathod** [comment]
@kazlauskis & @DavidRoy 
I have upgraded the path in sample.php for photo upload. Can any of you test and let me know. if it is working.

**Comment by DavidRoy** [comment]
@BirenRathod still not working.  See: http://warehouse1.indicia.org.uk/index.php/occurrence/edit/12176567

**Comment by BirenRathod** [comment]
@DavidRoy 
is it the same problem on the website too? there is a fair chance that it might not work on the website too. which form do you use for photo upload? can you send me the URL please?

**Comment by DavidRoy** [comment]
@BirenRathod adding photo by the website works fine.  I've just added one:
http://warehouse1.indicia.org.uk/index.php/occurrence/edit/12176568

Form used = https://butterfly-monitoring.net/enter-app-record?occurrence_id=12176568&sample_id=

**Comment by BirenRathod** [comment]
@DavidRoy & @kazlauskis 

Photo upload problem has now resolved. please check it from your mobile. 
here is the record -> http://warehouse1.indicia.org.uk/index.php/sample/edit/7050517

Please me know if it works , so I will delete this record as this is just for testing.

**Comment by DavidRoy** [comment]
Thanks - closing this issue.  Confirmed this now works ok.  Please delete the test record.

**Comment by BirenRathod** [comment]
@DavidRoy 

Thanks for confirming. I deleted that record now.
