### ISSUE TITLE
Fix app transect record duplication

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#154]
In case of a network failure or a timed out submission a duplicate record can occur and to prevent this the Drupal `mobile-indicia-api` module should be improved. 

In the module there is already a mechanism that would prevent the duplicates, but only for records with 1-5 occurrences attached. The limit of 5 occurrences is for optimisation purposes only as it can be slow to make multiple requests to the warehouse to check for an existing duplicate.

For a proper fix, it would be much better if there was a way to check the sample rather than occurrence duplication as there is only one sample at the top (and that can also have no occurrences occasionally). At the very least, batching the requests to the warehouse to check for the duplicates would be a big improvement.

This issue affects NPMS app as BiologicalRecordsCentre/NPMS#165

**Comment by DavidRoy** [comment]
I suggest a quick fix of increasing the occurrence limit to 50

Then schedule time for the sample-id duplication check for sometime in the new year?
