### ISSUE TITLE
Download page for role = scheme co-ordinator

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#155]
Require a new page to enable verifiers to download occurrences - transect records and mobile app records.

i.e. to download records shown on https://butterfly-monitoring.net/elastic/all-records, restricted to spatial context as defined by verification filter

**Comment by johnvanbreda** [comment]
@DavidRoy Is this best done as a new page, or should we put the verification data table on a tab and have a 2nd tab for downloading?

**Comment by DavidRoy** [comment]
@johnvanbreda both ideally, but maybe start with the easiest.

The plan is to have a separate downloads page for the various file formats, e.g. transect routes, occurrences, summary tables etc.  The verifier download would fit into that idea?

**Comment by DavidRoy** [comment]
@johnvanbreda bumping this issue, and other able for Nov milestone

**Comment by johnvanbreda** [comment]
I've created a separate page at https://butterfly-monitoring.net/verification/download, for 2 reasons: 1) We could add multiple downloads to the page and 2) adding download to the existing tool means the UI being a little more cramped. But, I can see that it would be useful to download straight from the verification tool as well so let me know if that's needed, or close if this is OK.

**Comment by DavidRoy** [comment]
I can't get this to work.
I masqueraded as a user with role = verifier and verification filter setup.
https://butterfly-monitoring.net/user/1198

Goto:  https://butterfly-monitoring.net/verification/download

Click on download but nothing happens (the pie does not move off 'Downloading')

**Comment by DavidRoy** [comment]
Also, the download file format should match the version for 'my data' at https://butterfly-monitoring.net/elastic/my-records 

i.e. removes UK-centric fields such as VC

**Comment by johnvanbreda** [comment]
Both issues fixed.

**Comment by DavidRoy** [comment]
The file was produced, thanks.  One issue I noticed is that the 'Date interpreted' column has 'Unknown' for all occurrences.  As the only date column it is essential that this is populated correctly.

**Comment by johnvanbreda** [comment]
Bug fixed, relating to removing the date start and end fields from the download which meant that the calculated date interpreted field could not get its underlying data.

**Comment by DavidRoy** [comment]
@johnvanbreda re-opening this issue as the requirement is clarifying in my mind.  What we need is a download page that covers all the options for a scheme co-ordinator to have.  I've drafted a rough page to show the requirement to group together all the download types in one place.  Either delivered via a single page or as a set of links to specific download pages
https://butterfly-monitoring.net/downloads

**Comment by johnvanbreda** [comment]
Ok - I think this would be a set of links as we'd deliver some via Elasticsearch and some via PostgreSQL. Is this on the current list of priorities?

**Comment by johnvanbreda** [comment]
@DavidRoy will a scheme coordinator have there permissions set up using a verification filter, or is there a different mechanism in place to define which records fall inside their scheme's remit?

**Comment by DavidRoy** [comment]
We need three separate roles.
1. scheme co-ordinator (gives access to list of sites, transect walks etc).  
Defined by Drupal setting?
2. verifier (gives access to the verification page)
Defined by verification filter and stored in warehouse
3. data downloads
Defined by filter and stored in warehouse

thanks
david

**Comment by johnvanbreda** [comment]
Thanks, are the downloads available for each role going to be identical?

**Comment by DavidRoy** [comment]
In terms of file formats yes.   Ideally, the filter setup will define the set of records

**Comment by johnvanbreda** [comment]
Sorry, another question - are the downloads of transect occurrence data a simple list of occurrences (like the iRecord download tool) or a summary table (like the download on the Annual Summary)?

**Comment by DavidRoy** [comment]
Simple occurrences (e.g. iRecord like)

The Annual report will remain separate for more bespoke downloads

**Comment by johnvanbreda** [comment]
@DavidRoy do you need pages added to the website to allow you to set up the filters for different users?

**Comment by DavidRoy** [comment]
@johnvanbreda 
I think we have these?
https://butterfly-monitoring.net/admin/filters-list
https://butterfly-monitoring.net/filters/admin-edit

**Comment by johnvanbreda** [comment]
@DavidRoy ready for you to try out - see https://butterfly-monitoring.net/downloads

**Comment by DavidRoy** [comment]
@johnvanbreda I've tested and it works well.  The only thing to finalise is the 'roles'.

The two relevant ones are:
scheme co-ordinator
verifier

Both are defined by NUTS regions.  In theory they could be different but we can assume/ensure they are the defined by the same geographic area.  Therefore can we remove the need for the drop-down [Dataset:] list to switch between them.
![download_dataset](https://user-images.githubusercontent.com/2699478/86399049-8296d880-bc9e-11ea-840a-0aee21e627bf.png)

Also, we need a more flexible Download role for people who are not verifiers or scheme co-ordinators

Should we therefore just have this page lined to a role = 'Data Download' and setup filters accordingly

**Comment by johnvanbreda** [comment]
At the moment, we have a custom permissions control which does the following:
1. Picks up any verification filters for the user and extracts the associated location ID (i.e. country). Creates options to download the data for each it finds.
2. Picks up any download filters for the user and extracts the associated location ID (i.e. country). Creates options to download the data for each it finds.
3. Looks in the user profile, if the user has "country manager" permission and a value in the field_associated_scheme, provides an option to download the data for that.

I think if you give someone a download filter with no linked country they could then download everything. 

I've changed it so that there is a permission called downloads which scheme coordinators and verifiers have, giving access to the page. You can add this to other roles as required.

Apart from that I wonder if the only change actually required is to replace the list of datasets given with a list of distinct countries you have access to, so a scheme coordinator who also verifies for a country would only have one choice. That would be clearer I think?

**Comment by DavidRoy** [comment]
That all sounds good.  Related to this is the filter admin setup #272

**Comment by johnvanbreda** [comment]
Now done. If you only have 1 country option, then you just see a message. Please close if OK.

**Comment by DavidRoy** [comment]
@johnvanbreda this page is getting there, but when masquerading as user = 'muguira' who has role 'scheme co-ordinator' for Spain I get an error message when trying to download the Transect occurrence and sample files.
![spain error](https://user-images.githubusercontent.com/2699478/86528517-afb2d900-bea0-11ea-9e71-acf87fbde777.png)

**Comment by johnvanbreda** [comment]
Fixed - a minor permissions configuration mistake.

**Comment by DavidRoy** [comment]
thanks, works well
