### ISSUE TITLE
Empty "Samples" report (annual report)

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/ABLE#156]
In Annual report, tab Download, the report "Samples" is empty (.csv file of 0kb).

**Comment by Gary-van-Breda** [comment]
Coding donw, awaiting deployment to live: see https://github.com/Indicia-Team/warehouse/pull/340

**Comment by johnvanbreda** [comment]
Merged to develop ready for the next full release.

**Comment by Gary-van-Breda** [comment]
@xaviermestdagh : this has now been deployed, and it looks like it is working.
Can you review, and hopefully close? Thank you.

**Comment by xaviermestdagh** [comment]
@Gary-van-Breda : I made several trials on Firefox and Edge and it is often very slow to load on this part (I had this message 2-3 times "The application did not respond in time."). When working, the "samples" report is however still empty.

**Comment by Gary-van-Breda** [comment]
What are the filter options you are using?

**Comment by xaviermestdagh** [comment]
"Combine data for all recorders".
Indeed, when using the filter "My data" the "Samples" csv report is not empty.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda or @BirenRathod : could either of you deploy a new ebms_sample_download.xml report in the brc-reports into warehouse1 please?

**Comment by johnvanbreda** [comment]
Done

**Comment by xaviermestdagh** [comment]
Sorry, I don't know if this deployment was supposed to fix the problem, but I still have empty "samples" reports

**Comment by Gary-van-Breda** [comment]
I have just now reconfigured the Annual summary page to use the new report. I've done a couple of trial sample downloads, and it looks OK to me - @xaviermestdagh can you check now?

**Comment by xaviermestdagh** [comment]
great, thanks
