### ISSUE TITLE
Restrict menu item 'Scheme admin' to role = scheme co-ordinator

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#158]
Currently, all users can see the Scheme Admin menu.  
https://butterfly-monitoring.net/scheme-admin

This should be changed so it is restricted to users with role = Scheme co-ordinator or Super-manager

**Comment by Gary-van-Breda** [comment]
Done: I've set it for roles Scheme co-ordinator, Super-manager and Administrator

**Comment by Gary-van-Breda** [comment]
When you edit a menu link there is now a section which allows you to specify which roles this link applies to.

**Comment by DavidRoy** [comment]
Thanks.  Now closing
