### ISSUE TITLE
Verification page only visible to users with role = verifier

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#159]
https://butterfly-monitoring.net/verification should only be visible to users with role = verifier

Currently this page is accessible by all users

**Comment by Gary-van-Breda** [comment]
Done: I've set it for roles verifier and Administrator
See comments on #158  
Note that as the verification is under the "Scheme admin" menu, which is restricted (as in #158), the verifier must also be a Scheme coordinator, supermanager or administrator in order to see the menu item.

**Comment by DavidRoy** [comment]
Thanks, that's now correct
