### ISSUE TITLE
New report for www.butterfly-monitoring.net/mydata: site details

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#16]
New report with following fields:
LocationType
LocationID
LocationName
LocationCode
LocationCentroidLatitude
LocationCentroidLongitude
NumberOfSections
OverallLength
TransectWidth
Sensitive
PrincipleHabitat
2ndHabitat
PrincipleLandTenure
2ndLandTenure
PrincipleLandManagement
2ndLandManagement
LocationNotes (e.g. notes on habitat,land, management and tenure)

**Comment by DavidRoy** [comment]
@Gary-van-Breda this report already exists as 
http://warehouse2.indicia.org.uk/index.php/services/report/requestReport?report=projects/ebms/ebms_sites_download.xml&reportSource=local&mode=csv&nonce=c27098d3a7cc63aeb617a28729e76ce55d2bdce3&auth_token=be874739a92aabb7ed3417eb06e20afc42986581&cms_user_id=1&cms_attribute_id=19&location_type_id=107&locattrs=18,1,2,3,4,6,7,8,9,10,11,12

If so, please close this issue

**Comment by Gary-van-Breda** [comment]
Yes: this report is already available as a download on the footer of the all-sites page (http://www.butterfly-monitoring.net/it/all-sites). Unfortunately this has been co-opted into an Italian only page somewhere along the lines - there is no English equivalent of this page.
This should all be sorted when the multi-lingual Drupal 8 site appears.
The report will be be part of the migration.
