### ISSUE TITLE
Create sections when transect site created or number of sections changes

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#162]
follows on from #150 

Requirement is:
1. Create the sections when the sites are created, and when the number of sections is altered. 
2. Data fix to retrospectively create the sections for site where this has not already happened.

Estimated as ~1 day of work

**Comment by Gary-van-Breda** [comment]
Data fix for Part 2: 
[Issue 162.zip](https://github.com/BiologicalRecordsCentre/ABLE/files/3941969/Issue.162.zip)

**Comment by Gary-van-Breda** [comment]
Code changes to the site form now deployed.
@johnvanbreda : can you run the script above against warehouse1?

**Comment by johnvanbreda** [comment]
@Gary-van-Breda - sorry I missed the notification. Do you still want me to run the script in the zip?

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : yes please.

**Comment by DavidRoy** [comment]
@Gary-van-Breda where are we with this one?

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : did we ever run this script?

**Comment by johnvanbreda** [comment]
It has now been run - 83 locations created.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : I think this is now done.

**Comment by DavidRoy** [comment]
Thanks, closing as not so easy to test
