### ISSUE TITLE
Empty .csv reports from the page "National sites"

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/ABLE#165]
Perhaps related to issue #156 
The two reports listed below are empty:
Full Sites data download (CSV)
Full Site Sections data download (CSV)

**Comment by Gary-van-Breda** [comment]
The footer had not been converted properly to the new EBMS Scheme, so was referencing the old "Branch" based way of doing things.
I've corrected the form configuration and the footer code.
There seems to be some data duplication, which I will look at

**Comment by Gary-van-Breda** [comment]
There is some attribute duplication on the sections: I will do a data fix, but this seems to have happened a while back and the site form has been re-written since.

**Comment by Gary-van-Breda** [comment]
Data fix done.  
Xavier - please check, and hopefully close?

**Comment by xaviermestdagh** [comment]
Working from the "My Data", but cannot test from the "Scheme admin": the scheme transect allocation, scheme sites and scheme walks are redirecting to the home page.

**Comment by Gary-van-Breda** [comment]
Which language are you using?

**Comment by xaviermestdagh** [comment]
English and French are both redirecting to English home page

**Comment by CrisSevilleja** [comment]
For all the language these links are not working. The links are okay if you write them directly https://butterfly-monitoring.net/scheme-sites  but they are not well linked to the menu.

**Comment by Gary-van-Breda** [comment]
The 3 scheme links have now been sorted.
The titles on the pages have been changed, and the automatic URL generation is ticked. This means that the URLs on the pages have have changed, but the menu items had not. I've sorted this now.
