### ISSUE TITLE
Alternative walk input form 

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#168]
Requested by Hungary scheme.  

To have two entries per species per section:
1. standard count for species within transect strip 5m width
2. count/count-range for species outside main transect width

One option is a wide table with 2 columns per section

@Gary-van-Breda to provide estimate for when this can be implemented

**Comment by Gary-van-Breda** [comment]
I have deployed the new form version at https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-2. It is currently set up to be identical to the normal walk data entry form.  
  
I will (on the Dev site):

- Switch over the My Walks, Branch Walks and Annual summary to point to the new form.  
- Add a Moths Grid: As a EBMS/ABLE moth list is not in the Dev site, I will attach this to the "UK Master List" restricted as for UKBMS, for testing purposes.

I will do the following for Hungary only:

- Add an additional select box occurrence attribute for "Outside Transect Count" - values "one (1)", "few (2-5)", "Many (16--)" - @DavidRoy Can you confirm what the wording should be for the 6-15 value(s)?  
- Switch on the main sample images
- Switch on the occurrence images
- Add a checkbox attribute on the main sample "Any butterflies?", which will be displayed with the butterflies grid. If unchecked, the butterflies grid will not be displayed.
- Add a checkbox attribute on the main sample "Any Moths?", which will be displayed with the moths grid. If unchecked, the moths grid will not be displayed.

**Comment by DavidRoy** [comment]
I confirm the number scale:
one (1)
few (2-5)
several (6-16)
many (>16)

thanks

**Comment by DavidRoy** [comment]
@Gary-van-Breda  
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-2 
does not allow a temperature value to be entered, so the rest of the functionality can't be tested

**Comment by Gary-van-Breda** [comment]
I think there was a config mismatch on the DEV site for the termlists: I've set them to be owned generically (as they are common between EBMS and UKBMS), run the scheduled tasks and cleared the caches. It now looks OK.
This is not a problem on Live, so its config is OK.

**Comment by DavidRoy** [comment]
@Gary-van-Breda the page works well.  I don't think the main sample image functionality is implemented?  I suggest this should be available by default

**Comment by DavidRoy** [comment]
@Gary-van-Breda Does this need to be implemented within 
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new

Specifically:
I will do the following for Hungary only:

Add an additional select box occurrence attribute for "Outside Transect Count" - values "one (1)", "few (2-5)", "Many (16--)" - @DavidRoy Can you confirm what the wording should be for the 6-15 value(s)?
Switch on the main sample images
Switch on the occurrence images
Add a checkbox attribute on the main sample "Any butterflies?", which will be displayed with the butterflies grid. If unchecked, the butterflies grid will not be displayed.
Add a checkbox attribute on the main sample "Any Moths?", which will be displayed with the moths grid. If unchecked, the moths grid will not be displayed.

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site as part of the new walk page, for review:

- Added extra "Outside Transect Count" occurrence attribute for this testing case: Hungarian Branch transects walks only, have made up a name for the 6-15 value case.
- Transect Images enabled across the board.
- Occurrence Images enabled on Hungarian Branch transects walks only.
- "Any Butterflies?" attribute enabled across the board : although on the main sample itself, it appears under the "Butterflies" heading on the second page (both original simple version and new version), and hides the "Butterflies" grid if unchecked and there are no existing occurrences. Note that in the original simple version, the subsample attributes ("% Sun", "% cloud", and for Luxembourg only - "Reliability") are left on the grid.
- Ditto for "Any Moths?", relative to the Moths heading/grid.

https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new

**Comment by Gary-van-Breda** [comment]
@DavidRoy Walk Data Entry page (2) deployed to Live.
