### ISSUE TITLE
Map of sample locations

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#170]
A map to view all sample locations, with different symbols for timed counts and transects

**Comment by kazlauskis** [comment]
I am thinking of having the functionality as a third tab in the Surveys page. Let me know if anyone thinks of a better place.

<img width="319" alt="Screenshot 2020-03-23 at 09 53 22" src="https://user-images.githubusercontent.com/7383162/77304343-370e7f00-6cec-11ea-8dbe-4d27775078df.png">

**Comment by DavidRoy** [comment]
Agreed!  Good solution

**Comment by CrisSevilleja** [comment]
Yes! I like this idea, good solution to see the map :D

**Comment by kazlauskis** [comment]
I have added the map now. It shows all the user surveys on the device. Circle for 15min counts and a square symbol for transects. Clicking on any of the markers it opens a popup with few record details. This is essentially only a placeholder for some more fancy stuff and should be worked on more in the future. Unless you want me to add something specific here I am going to pick up another issue.

<img width="318" alt="Screenshot 2020-03-23 at 16 37 26" src="https://user-images.githubusercontent.com/7383162/77347094-3a772a00-6d2f-11ea-9efe-9748e658d0ee.png">

**Comment by CrisSevilleja** [comment]
I really like it. Thanks!

**Comment by DavidRoy** [comment]
me too!
