### ISSUE TITLE
Show a GPS permissions warning

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#173]
If the user denies to give the app enough permissions to use the GPS, then some warning message should be shown to notify this next time the app is in use.

**Comment by CrisSevilleja** [comment]
@kazlauskis Is this already applied? if yes close the issue, if not see how much priority deserves

**Comment by kazlauskis** [comment]
This isn't yet implemented. We could pick this up with the next release.
