### ISSUE TITLE
Add extra countries

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#178]
Add Turkey (outside europe0)

**Comment by kazlauskis** [comment]
To add these countries I would need an updated warehouse species list export with the new country statuses, just like in #13 (@johnvanbreda)

After adding these countries to the warehouse, I suggest wrapping the SQL query into a report, so I could pull it programmatically next time.

**Comment by kazlauskis** [comment]
We'll be working on adding extra species to the app next (#100) which overlaps with this task so we could do both. Have the new countries been added to the warehouse now?

**Comment by DavidRoy** [comment]
Still waiting on me. I'll try and do this today

**Comment by DavidRoy** [comment]
@johnvanbreda can you extend the ABLE Butterflies list to incorporate Armenia then make availalbe to Karolis.  The steps are:
1. Add [AM] as a taxon attribute for this list
2. Add in additional taxa that are present in Armenia but absent from the existing list.  See eBMS Species + Armenia New Taxa.xlsx in attached .zip file
3. Set [AM} = P for species already on the list and present in Armenia.  See eBMS Species + Armenia New Attribute.xlsx in attached .zip file

[eBMS Armenia.zip](https://github.com/BiologicalRecordsCentre/ABLE/files/4730205/eBMS.Armenia.zip)

**Comment by johnvanbreda** [comment]
Now done.

**Comment by DavidRoy** [comment]
@johnvanbreda can you extend the ABLE Butterflies list to incorporate Turkey (Asian part) then make availalbe to Karolis. The steps are:

1. Add [TRA] as a taxon attribute for this list

2. Add in additional taxa that are present in Turkey (Asia) but absent from the existing list. 
[eBMS Species + TRA New Taxa.txt](https://github.com/BiologicalRecordsCentre/ABLE/files/4826887/eBMS.Species.%2B.TRA.New.Taxa.txt)

3. Set [AM} = P for species already on the list and present in Turkey (Asia). 
[eBMS Species + TRA New Attribute.txt](https://github.com/BiologicalRecordsCentre/ABLE/files/4826890/eBMS.Species.%2B.TRA.New.Attribute.txt)

**Comment by DavidRoy** [comment]
@johnvanbreda this is higher priority than other ABLE issues so we can update the species list in the app in one go

**Comment by johnvanbreda** [comment]
This is done, with a couple of caveats:
* Point 3 - I set [TRA] (not AM) to the code provided in the list (not always P).
* Some of the taxa listed for point 3 are actually on the moths list (e.g. https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/455867, see #259).

**Comment by DavidRoy** [comment]
@kazlauskis can you add Armenia as a country option on setup.  The butterfly species list for this is taxon_attribute [AM]

**Comment by kazlauskis** [comment]
I am creating smaller tickets for any subsequent countries. Helps me manage the workflow.
