### ISSUE TITLE
Define www.butterfly-monitoring.net roles

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#18]
We currently have the following roles:

@Gary-van-Breda please give an explanation of each role, and confirm which are needed for the Drupal 8 version #1 

 authenticated user
 administrator
 project editors
 regional collator
 site editor
 country manager
 data recorder
 super manager

**Comment by DavidRoy** [comment]
@Gary-van-Breda  Please remove some roles which are duplicates
1. remove 'Site editor' as duplicates 'Project editor'
2. merge 'regional collator' with 'country manager' and rename the role as 'scheme co-ordinator' (e.g. this would be the roles for Xavier for Luxembourg)

Also, we want to setup a regional verification role.  Should we do this via Drupal permissions or via Indicia database settings.  For other verification systems (e.g. iRecord), we use database settings. 
@johnvanbreda do you have a view on this?  We will want a verification system setup for ABLE, similar to iRecord

**Comment by johnvanbreda** [comment]
@DavidRoy presumably the regional verification role is going to need whichever Drupal role you are using to enable access to the verification page, plus a filter in the Indicia database which limits the records to a region.
That also implies that we should load a SHP file of the regions (= countries?) into the Indicia locations table and ensure that it is indexed. This could perhaps be an extension of the existing indexed "Country" layer we already have, which currently only covers the British Isles plus Channel Islands. Or, if not by country then we may need a specific ABLE region layer much like we have BC branches. I have been writing notes for Martin on adding to the indexed sites in relation to the NT site data, which will be applicable here.

**Comment by DavidRoy** [comment]
Yes, regional verification will need Drupal 'Verifier' role as with iRecord

We will need sub-country polygons so I recommend using the NUTS level 2 dataset.
@johnvanbreda any view on the version to use (i.e. what Scale).  Also how this relates to the existing Country layer

I'll add new issues to cover these requirements

**Comment by johnvanbreda** [comment]
I think the decision as to the NUTS level is best determined by organisational requirements rather than technical ones. I agree that NUTS 2 looks to provide a reasonable subdivisioning - NUTS 3 may be too detailed making it harder to manage the verification requirements (see https://en.wikipedia.org/wiki/Nomenclature_of_Territorial_Units_for_Statistics#/media/File:NUTS_3_regions_EU-27.svg).

**Comment by DavidRoy** [comment]
@johnvanbreda sorry, I should have been clearer.  From the list of NUTS 2 versions listed here:
https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/nuts

what is the recommended scale, range between 1:1million to 1:60 million

**Comment by johnvanbreda** [comment]
I recommend: 
NUTS 2016 SHP file, 1:1m, NUTS_RG_01M_2016_4326_LEVL_2.shp.zip file, which is the EPSG:4326 layer (GPS lat long), RG seems to be the region boundaries. For reference I've attached a comparison of the 1m vs 3m layers around Poole harbour - you can see the red 3m layer is simplified enough that some data on Studland would be missed as an example.

![image](https://user-images.githubusercontent.com/2392594/52490945-d7bfdf00-2bbd-11e9-85fd-cc91af9b1ddd.png)

**Comment by DavidRoy** [comment]
Agreed.  
@johnvanbreda Please load this into warehouse1 for ABLE use.  Presumably needs to be indexed?

@Gary-van-Breda Please remove some roles which are duplicates
1. remove 'Site editor' as duplicates 'Project editor'
2. merge 'regional collator' with 'country manager' and rename the role as 'scheme co-ordinator' (e.g. this would be the roles for Xavier for Luxembourg)
3. add new role 'verifier'

**Comment by johnvanbreda** [comment]
NUTS level 2 loaded onto warehouse and indexed. Also now loaded into Elasticsearch index.

**Comment by Gary-van-Breda** [comment]
"Site Editor" role removed.
"Regional collator" role merged into "Country manager". 'regional collator' role removed. "Country manager" role renamed to "scheme co-ordinator"
"verifier' role created: I have not given it any permissions beyond those for an authorised user.

**Comment by Gary-van-Breda** [comment]
I think this is currently all set up as required.

**Comment by DavidRoy** [comment]
Closing this main issue.  I will raise additional specific things through new issue(s)
