### ISSUE TITLE
Add ability to copy species list from previous 15min count

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#180]
* This would copy species list from previous survey
   * In the future it would allow to select the survey to copy from
*  All the species counts would be reset to 0
* Species with 0 counts would not be submitted to the database

**Comment by kazlauskis** [comment]
We can allow to clone the survey with species counts reset to 0s and location/date/other cleared. It could look something like this - record swipe left to delete and swipe right to clone and other options in the future. Would this be OK?

<img width="361" alt="Screenshot 2020-05-29 at 11 50 25" src="https://user-images.githubusercontent.com/7383162/83252261-da738880-a1a2-11ea-8034-e1d2f5b3611d.png">
<img width="362" alt="Screenshot 2020-05-29 at 11 50 32" src="https://user-images.githubusercontent.com/7383162/83252264-dba4b580-a1a2-11ea-9843-8f3fbbf46bec.png">

**Comment by DavidRoy** [comment]
Yes, that looks good.  And only species with count >0 would get submitted for the list

**Comment by DavidRoy** [comment]
This requirement is also needed for the 15m counts.  Maybe the best first option is "previous species list'

**Comment by kazlauskis** [comment]
My comments were regarding the 15min survey only. But having defined the transect species list copy in another ticket I started to think that being consistent and adding same long-press dialog to the 'Add species' button here would be also better.

Instead of the swipe-right option to clone I will add a long-press to the add species button, OK?

**Comment by Vilius-Stankaitis** [comment]
@Cristina Sevilleja Hi, Are you using the latest app version 1.17.0(186)?

**Comment by CrisSevilleja** [comment]
Hi @Vilius-Stankaitis I am using the 1.17.0(185), now I am downloading the 186 I can try if this function is working. Should it work on the 186 version?

**Comment by chrisvanswaay** [comment]
I am not sure which version I used when I was on holiday in Italy, but there I tried several times and usually it didn't work and only two or three species were copied from the previous count. And with the big numbers there this meant I had to re-enter all species again and again.



--

De Vlinderstichting is een organisatie zonder winstoogmerk. Voor een deel van ons werk zijn wij afhankelijk van de steun van donateurs. Wilt u bijdragen aan bescherming van vlinders en libellen? Neem dan een kijkje op onze website<https://www.vlinderstichting.nl/help-mee/donateur-worden> en help ons!


Chris van Swaay
De Vlinderstichting
Mennonietenweg 10
Postbus 506
6700 AM  Wageningen

[t] algemeen (+31) 0317 467346 / direct (+31) 0317 467342

[e] ***@***.******@***.***>
[i] www.vlinderstichting.nl<http://www.vlinderstichting.nl/>
[twitter] www.twitter.com/vlinderNL<http://www.twitter.com/vlinderNL>
[facebook] www.facebook.com/Vlinderstichting<http://www.facebook.com/Vlinderstichting>
[instagram] www.instagram.com/vlinderstichting<http://www.instagram.com/vlinderstichting>
[linkedin] www.linkedin.com/company/vlinderstichting<http://www.linkedin.com/company/vlinderstichting>

------------------------------
Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------
No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.

________________________________
Van: Vilius Stankaitis ***@***.***>
Verzonden: woensdag 22 juni 2022 19:34
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Chris van Swaay ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [BiologicalRecordsCentre/ABLE] Add ability to copy species list from previous 15min count (#180)


@CrisSevilleja<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCrisSevilleja&data=05%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C8bcd4e33876c430f439c08da5475837f%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637915160951928548%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OEC4435d2QllByv8cQnTB4SA79FUeD3XbpS3EvCqET0%3D&reserved=0> It's working for me (android & ios). So it should work. If it doesn't work for you, could you provide more details, about your phone (version, model)? Does "Copy species" alert appear or it's just not copying species from the previous list?

Thank you

**Comment by Vilius-Stankaitis** [comment]
@Chris van Swaay thanks, it helped a lot. Fixed
