### ISSUE TITLE
Add option for adding transect occurrence photos and comments

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#183]

**Comment by CrisSevilleja** [comment]
Add option for adding sample photos and comments per individual on transects

similar to the available option for 15-min counts (without the location) showing species name, stage, comment and picture.

<img width="231" alt="2022-05-11_15h41_15" src="https://user-images.githubusercontent.com/25052478/167864137-a68fe7ee-a63d-4a1d-a0c4-762bb363dcbe.png">

**Comment by kazlauskis** [comment]
@CrisSevilleja OK, we can add a page like in your screenshot with options to add a photo and a comment. You could access it from the section species list. Is that OK?

![butterflies app flumens io_(iPhone SE) (1)](https://user-images.githubusercontent.com/7383162/168756701-4c20a71b-ffc0-4543-9e97-248b954a9971.png)

**Comment by CrisSevilleja** [comment]
Yes @kazlauskis , like that is good
