### ISSUE TITLE
Contact email to coordinators with formatting error

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#184]
The information email to country coordinators sent when someone points their scheme to a particular BMS appears to  be html but sent as plain text or something like that.

![IMG_2651](https://user-images.githubusercontent.com/19598308/71159594-34f8d800-2246-11ea-967d-48641872b281.jpg)

**Comment by Gary-van-Breda** [comment]
@larspett : is this still a problem for you?
A change was put in a while back, so this may have been fixed. If so, could you close the issue?
Thanks.
