### ISSUE TITLE
import European bumblebee checklist

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#186]
Import European Bumblebee checklist for use within ABLE tools

[BumblBee Checklist.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/3998007/BumblBee.Checklist.xlsx)

**Comment by johnvanbreda** [comment]
[BumblBee.Checklist.zip](https://github.com/BiologicalRecordsCentre/ABLE/files/4224618/BumblBee.Checklist.zip)

Attached file uploaded. The same script as in #185 was used to allocate TVKs (using EBMSB as a prefix).
