### ISSUE TITLE
Implement approach to handle sensitive species

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#189]
Requirement to handle sensitive species appropriately within workflow mechanism.  Applied to eBMS surveys.

SPECIES | Action   (blurring etc)
-- | --
Pieris   wollastoni | Hidden
Coenonympha   phryne | 10 km square
Pseudochazara   cingovskii | 10 km square
Gonepteryx   maderensis | 1 km square
Colias   myrmidone | Hidden
Pieris   cheiranthi | 1 km square
Lycaena   helle | 1 km square
Phengaris   arion | 1 km square
Turanana   taygetica | Hidden
Agriades   zullichi | 1 km square
Polyommatus   humedasae | 1 km square
Boloria   improba | 1 km square
Coenonympha   oedippus | Hidden
Pararge   xiphia | 1 km square
Pseudochazara   euxina | 1 km square
Pyrgus   cirsii | 1 km square
Gonepteryx   cleobule | 1 km square
Colias   chrysotheme | 1 km square
Euchloe   bazae | Hidden
Tomares   nogelii | 1 km square
Phengaris   teleius | 1 km square
Polyommatus   golgus | 1 km square
Polyommatus   violetae | 1 km square
Polyommatus   orphicus | 1 km square
Boloria   polaris | 1 km square
Euphydryas   maturna | Hidden
Coenonympha   tullia | 1 km square
Coenonympha   hero | Hidden
Coenonympha   orientalis | 1 km square
Lopinga   achine | Hidden
Hipparchia   tilosi | No data
Hipparchia   bacchus | 1 km square
Pseudochazara   amymone | Hidden
Pseudochazara   orestes | 1 km square
Erebia   sudetica | 1 km square
Erebia   christi | 1 km square
Parnassius   mnemosyne | 10 km square
Parnassius   apollo | 10 km square
Leptidea   morsei | Hidden
Phengaris   nausithous | 1 km square
Polyommatus   eros eroides | 1 km square
Papilio   alexanor | 1 km square
Papilio   hospiton | 1 km square
Zerynthia   polyxena | 1 km square
Lycaena   dispar | 1 km square
Pseudophilotes   bavius | 1 km square
Agriades   aquilo | 1 km square
Fabriciana   elisa | 1 km square
Apatura   metis | 1 km square
Nymphalis   vaualbum | 1 km square
Euphydryas   aurinia | 1 km square
Melanargia   arge | 1 km square
Erebia   calcarius | 1 km square
Erebia polaris | 1 km square
Muschampia   cribrellum | 1 km square
Muschampia   tessellum | 1 km square
Lycaena   thetis | Hidden
Polyommatus   iphigenia | Hidden
Pseudochazara   tisiphone | 1 km square

**Comment by johnvanbreda** [comment]
@DavidRoy would you prefer the hidden taxa to be set as unlreleased, or confidential? I think the latter is perhaps more logical?

**Comment by johnvanbreda** [comment]
Note to self: I've added the workflow events for blurring but still need to do the "hidden" ones, plus write a script to update existing data.

**Comment by DavidRoy** [comment]
@johnvanbreda - confidential preferred to unreleased.  But is sensitive not the way we handled this requirement previously?

**Comment by johnvanbreda** [comment]
Sensitive means a record remains visible but is blurred. If you want the ones flagged as hidden to be completely invisible for normal users then they have to be confidential.

**Comment by DavidRoy** [comment]
sorry, i didn't read your message carefully enough.  yes to making the hidden ones confidential.
thanks

**Comment by johnvanbreda** [comment]
I've done the confidential records and updated past data. 

For future reference, here's the script:
```sql
-- 1km
update occurrences set sensitivity_precision=1000, updated_on=now(), updated_by_id=3 where id in (
select id from cache_occurrences_functional where website_id=118 and taxa_taxon_list_external_key in (
select external_key
from cache_taxa_taxon_lists where taxon in (
	'Gonepteryx maderensis',
	'Pieris cheiranthi', 'Lycaena helle', 'Phengaris arion', 'Agriades zullichi', 'Polyommatus humedasae',
	'Boloria improba', 'Pararge xiphia', 'Pseudochazara euxina', 'Pyrgus cirsii', 'Gonepteryx cleobule', 
	'Colias chrysotheme', 'Tomares nogelii', 'Phengaris teleius', 'Polyommatus golgus', 'Polyommatus violetae',
	'Polyommatus orphicus', 'Boloria polaris', 'Coenonympha tullia', 'Coenonympha orientalis',
	'Hipparchia bacchus', 'Pseudochazara orestes', 'Erebia sudetica',
	'Erebia christi', 'Phengaris nausithous', 'Polyommatus eros eroides',
	'Papilio alexanor', 'Papilio hospiton', 'Zerynthia polyxena', 'Lycaena dispar', 'Pseudophilotes bavius', 'Agriades aquilo',
	'Fabriciana elisa', 'Apatura metis', 'Nymphalis vaualbum', 'Euphydryas aurinia', 'Melanargia arge', 'Erebia calcarius',
	'Erebia polaris', 'Muschampia cribrellum', 'Muschampia tessellum', 'Pseudochazara tisiphone') 
and taxon_list_id=251
	));
	
	
-- 10km
update occurrences set sensitivity_precision=10000, updated_on=now(), updated_by_id=3 where id in (
select id from cache_occurrences_functional where website_id=118 and taxa_taxon_list_external_key in (
select external_key
from cache_taxa_taxon_lists where taxon in (
	'Coenonympha phryne', 'Pseudochazara cingovskii', 'Parnassius mnemosyne', 'Parnassius apollo') 
and taxon_list_id=251
	));

-- Hidden
update occurrences set confidential='t', updated_on=now(), updated_by_id=3 where id in (
select id from cache_occurrences_functional where website_id=118 and taxa_taxon_list_external_key in (
select external_key
from cache_taxa_taxon_lists where taxon in (
	'Pieris wollastoni', 'Colias myrmidone', 'Turanana taygetica', 'Coenonympha oedippus', 'Euchloe bazae', 'Euphydryas maturna', 
	'Coenonympha hero', 'Lopinga achine', 'Pseudochazara amymone', 'Leptidea morsei', 'Lycaena thetis', 'Polyommatus iphigenia') 
and taxon_list_id=251
	));
	
-- Add to work_queue
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, 100, 2, now()
from cache_occurrences_functional where website_id=118 and taxa_taxon_list_external_key in (
select external_key
from cache_taxa_taxon_lists where taxon in (
	'Pieris wollastoni', 'Coenonympha phryne', 'Pseudochazara cingovskii', 'Gonepteryx maderensis', 'Colias myrmidone',
	'Pieris cheiranthi', 'Lycaena helle', 'Phengaris arion', 'Turanana taygetica', 'Agriades zullichi', 'Polyommatus humedasae',
	'Boloria improba', 'Coenonympha oedippus', 'Pararge xiphia', 'Pseudochazara euxina', 'Pyrgus cirsii', 'Gonepteryx cleobule', 
	'Colias chrysotheme', 'Euchloe bazae', 'Tomares nogelii', 'Phengaris teleius', 'Polyommatus golgus', 'Polyommatus violetae',
	'Polyommatus orphicus', 'Boloria polaris', 'Euphydryas maturna', 'Coenonympha tullia', 'Coenonympha hero', 'Coenonympha orientalis',
	'Lopinga achine', 'Hipparchia tilosi', 'Hipparchia bacchus', 'Pseudochazara amymone', 'Pseudochazara orestes', 'Erebia sudetica',
	'Erebia christi', 'Parnassius mnemosyne', 'Parnassius apollo', 'Leptidea morsei', 'Phengaris nausithous', 'Polyommatus eros eroides',
	'Papilio alexanor', 'Papilio hospiton', 'Zerynthia polyxena', 'Lycaena dispar', 'Pseudophilotes bavius', 'Agriades aquilo',
	'Fabriciana elisa', 'Apatura metis', 'Nymphalis vaualbum', 'Euphydryas aurinia', 'Melanargia arge', 'Erebia calcarius',
	'Erebia polaris', 'Muschampia cribrellum', 'Muschampia tessellum', 'Lycaena thetis', 'Polyommatus iphigenia', 'Pseudochazara tisiphone') 
and taxon_list_id=251
	);
```

**Comment by johnvanbreda** [comment]
@DavidRoy This is all done now apart from Hipparchia tilosi which is marked as no data so I wasn't sure what to do with it.

**Comment by DavidRoy** [comment]
@johnvanbreda please treat this as 'confidential' for the time being

**Comment by CrisSevilleja** [comment]
@DavidRoy a user has a question regarding some records that were not visible on his account; later he realised it could be possible those records were sensitive for being protected species. The user understands we don't show the coordinates but asked if we could make public this information, which species are considered sensitive for eBMS and place the list somewhere on the website. 

Do you agree @DavidRoy and @chrisvanswaay ? and if yes, where should I place that information? Also, I would need an updated list of eBMS sensitive species in case the one below has been updated. 

> Requirement to handle sensitive species appropriately within workflow mechanism. Applied to eBMS surveys.
> 
> SPECIES	Action (blurring etc)
> Pieris wollastoni	Hidden
> Coenonympha phryne	10 km square
> Pseudochazara cingovskii	10 km square
> Gonepteryx maderensis	1 km square
> Colias myrmidone	Hidden
> Pieris cheiranthi	1 km square
> Lycaena helle	1 km square
> Phengaris arion	1 km square
> Turanana taygetica	Hidden
> Agriades zullichi	1 km square
> Polyommatus humedasae	1 km square
> Boloria improba	1 km square
> Coenonympha oedippus	Hidden
> Pararge xiphia	1 km square
> Pseudochazara euxina	1 km square
> Pyrgus cirsii	1 km square
> Gonepteryx cleobule	1 km square
> Colias chrysotheme	1 km square
> Euchloe bazae	Hidden
> Tomares nogelii	1 km square
> Phengaris teleius	1 km square
> Polyommatus golgus	1 km square
> Polyommatus violetae	1 km square
> Polyommatus orphicus	1 km square
> Boloria polaris	1 km square
> Euphydryas maturna	Hidden
> Coenonympha tullia	1 km square
> Coenonympha hero	Hidden
> Coenonympha orientalis	1 km square
> Lopinga achine	Hidden
> Hipparchia tilosi	No data
> Hipparchia bacchus	1 km square
> Pseudochazara amymone	Hidden
> Pseudochazara orestes	1 km square
> Erebia sudetica	1 km square
> Erebia christi	1 km square
> Parnassius mnemosyne	10 km square
> Parnassius apollo	10 km square
> Leptidea morsei	Hidden
> Phengaris nausithous	1 km square
> Polyommatus eros eroides	1 km square
> Papilio alexanor	1 km square
> Papilio hospiton	1 km square
> Zerynthia polyxena	1 km square
> Lycaena dispar	1 km square
> Pseudophilotes bavius	1 km square
> Agriades aquilo	1 km square
> Fabriciana elisa	1 km square
> Apatura metis	1 km square
> Nymphalis vaualbum	1 km square
> Euphydryas aurinia	1 km square
> Melanargia arge	1 km square
> Erebia calcarius	1 km square
> Erebia polaris	1 km square
> Muschampia cribrellum	1 km square
> Muschampia tessellum	1 km square
> Lycaena thetis	Hidden
> Polyommatus iphigenia	Hidden
> Pseudochazara tisiphone	1 km square

**Comment by CrisSevilleja** [comment]
I just realised this issue is closed sorry.

**Comment by DavidRoy** [comment]
@CrisSevilleja I'm closing this issue as the original requirement is met.  Please add new specific issues if required
