### ISSUE TITLE
Import NUTS2 regions to allow regional filtering

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#19]
Import NUTS 2 region SHP into Warehouse 1 to enable regional filtering within www.butterfly-monitoring.net

Source = https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/nuts

**Comment by johnvanbreda** [comment]
This is now done on the warehouse. Need to enable layer in Elasticsearch data.

**Comment by johnvanbreda** [comment]
Elasticsearch Logstash config now includes NUTS level 2 layer data so records have their region as an attribute.
