### ISSUE TITLE
Use 'long press' to access 'Transect mode' and 'Casual record'

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#190]
As discussed, the primary mode for the app should be timed counts.  This should be the survey with a standard press of the '+' button.

Transect counts and casual records should be alternative survey modes when user has a long-press of the '+' button

**Comment by CrisSevilleja** [comment]
Could it be possible to add a pop-up mentioning this function? I can imagine many people are not going to try a long-press by default and they are not going to find the transects and casual records
@kazlauskis

**Comment by DavidRoy** [comment]
The casual records option is not there yet, only the transect recording.  So I think we don't need to make this too obvious as we can contact transect recorders directly?

When the casual mode is available, then I agree we should add a pop-up

**Comment by kazlauskis** [comment]
I'm thinking of adding some text label when using long-press to somehow explain why other surveys require long-press. Does 'Advanced recording options' make sense? here is to illustrate it:

<img width="324" alt="Screenshot 2020-03-24 at 08 53 54" src="https://user-images.githubusercontent.com/7383162/77406915-44d80900-6dad-11ea-99cc-a72fb513b415.png">

**Comment by DavidRoy** [comment]
I suggest 'Other recording options' as casual/opportunistic is less advanced than the 15-minute count
