### ISSUE TITLE
An user cannot add a new transect 

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#191]
@GPowney @DavidRoy 
The user nachoarce77 https://butterfly-monitoring.net/es/user/1395 cannot add a new transect on eBMS website. He got on the Site details: https://butterfly-monitoring.net/ebms-site-details  the following message without any option to continue further adding a new site: 

> This form is designed to be used with an attribute setup to assign the location to a country. This attribute should be shared with all location types. 

He is registered under the BMS Spain.

**Comment by DavidRoy** [comment]
wrong gary :-)

Now tagging the right one @Gary-van-Breda 

Also marking as urgent as affects new transects being setup.  I have checked other users and confirm there is a general issue with the new site page

**Comment by CrisSevilleja** [comment]
hahaha sorry. Thanks!

**Comment by Gary-van-Breda** [comment]
Caused by looking up the country attribute using the translated caption, rather than untranslated - worked OK in English, not in Spanish etc.  
Fixed and deployed to Live.

**Comment by DavidRoy** [comment]
Thanks
@CrisSevilleja can you check and close if resolved

**Comment by CrisSevilleja** [comment]
thank you, it is already working
