### ISSUE TITLE
Include dragonflies within ABLE app and website

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#193]
@CrisSevilleja to provide list of species

**Comment by CrisSevilleja** [comment]
Here is the list of European Dragonflies:
[European Odonata.zip](https://github.com/BiologicalRecordsCentre/ABLE/files/4249686/European.Odonata.zip)

Should we add a new issue @DavidRoy to include the filter of the different taxa in the Entry Data of the app?

**Comment by kazlauskis** [comment]
This is to add 134 species to both recording and species guide, right?

**Comment by DavidRoy** [comment]
Just the recording pages.  Needs the list loading into Indicia Warehouse first?

**Comment by kazlauskis** [comment]
Yes, if the list is not in the warehouse yet.

**Comment by DavidRoy** [comment]
@johnvanbreda can you import this list into the warehouse please, thanks

**Comment by johnvanbreda** [comment]
Done - list 265

**Comment by DavidRoy** [comment]
Re-opening as the list is required in the ButterflyCount app

**Comment by kazlauskis** [comment]
@johnvanbreda this contains only the dragonflies, would you like me to combine the 265 (dragonflies) and 260 (butterflies+burnet moths) to a single species list within the app or is the plan here to create another species list with all the species groups for the web forms and the app to use?

**Comment by DavidRoy** [comment]
@johnvanbreda bump

**Comment by johnvanbreda** [comment]
@DavidRoy I'm not sure if I'm the right person to decide strategy on combinations of lists for the app? I had wondered whether we should combine everything into a "European Insects" list at some point (even if incomplete initially) so they all share the same hierarchy.

**Comment by DavidRoy** [comment]
We've decided to keep them separate for the time being.  We can consider merging them at a later date.  Closing this issue and will raise anything more specific as separate issues
