### ISSUE TITLE
Improved names displayed on species guide

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#194]
two requirements.
1. Users to choose language displayed for species names, e.g. Latin, Common name
2. Common name to match language setting, defaulting to latin where common name missing

@kazlauskis to label if small, medium, large task

**Comment by kazlauskis** [comment]
I understand this is for the species guide list, right? We are showing both names in the species profile.
![Screenshot 2020-02-19 at 09 48 42](https://user-images.githubusercontent.com/7383162/74822471-158d3280-52fd-11ea-9166-34cb0d10e014.png)

**Comment by DavidRoy** [comment]
yes, that's correct.  It's only on the multi-species display

**Comment by CrisSevilleja** [comment]
Right now it is correct, showing Latin names when the language is not English. At the moment other languages are loaded that use Common names in their languages, that one should be the default (e.g. Dutch, Croatian, Czech)

**Comment by CrisSevilleja** [comment]
Common names in Dutch, Czech and Croatian
@kazlauskis @DavidRoy 

[Croatian_butterfly_names.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/4275485/Croatian_butterfly_names.xlsx)

[Czech_butterfly_names.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/4275462/Czech_butterfly_names.xlsx)
[SpeciesList_NL.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/4275471/SpeciesList_NL.xlsx)

**Comment by kazlauskis** [comment]
Hi @CrisSevilleja, would it be OK to ask the translators to add the names directly to Transifex instead? We have this `app_species_names` resource there:
https://www.transifex.com/ceh/ebms/app_species_names/

**Comment by CrisSevilleja** [comment]
@kazlauskis Yes I know, but people directly sent me the files. I think It is time-consuming for them, adding one by one the names when they have it on a file. Also, the names are in English, that not everyone knows the corresponding one in their language. It would be better to have the scientific name, but anyways they need to add one by one on Transifex and it is annoying. I don't think they will do it.

If we can include directly files to Transifex, I could do it

**Comment by kazlauskis** [comment]
OK, I see you point, I can certainly add the lists myself.

**Comment by DavidRoy** [comment]
@CrisSevilleja is this issue fixed?

**Comment by CrisSevilleja** [comment]
yes, it is fixed. Thanks! @DavidRoy

**Comment by DavidRoy** [comment]
Thanks, closing
