### ISSUE TITLE
App home page report for user's own data

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#196]
Currently the home page report gives overall totals for all users

@kazlauskis to label size of task

**Comment by kazlauskis** [comment]
A comment from Martin Warren: 

>Not sure this is in hand but the default screen when you open the app is a list of top recorded butterflies, but there is no caption saying the name of the app.
Can I suggest something like 
ButterflyCount, part of the European Butterfly Monitoring Scheme (eBMS). (or brought to you by EBMS) 
Plus add the logo? And say "top recorded butterflies"

**Comment by kazlauskis** [comment]
This is the same as #56, no?

**Comment by CrisSevilleja** [comment]
Following this issue back, currently, the home page of ButterflyCount is a bit boring and we discussed possibilities to improve it. Now you see a list of the top recorded butterflies in all 15-min counts that don't say much to recorders and almost never change being meadow brown on the top always. @DavidRoy @kazlauskis 

I would suggest including the top recorded butterflies from the user's own data, in total and if possible, in last month. If close to the name can be added a tiny picture of the butterfly it would give more colour to the home page (you cannot see almost butterflies on the app now).

Also, it would be interesting to see the total length walked with the 15-min counts and scrolling down the page to see international numbers: like the number of records per country, butterfly species, or something like that. 

Thanks

**Comment by kazlauskis** [comment]
Done the top user species now. Please create another report for walked distance report.
![localhost_8000_home_report(Pixel 5)](https://user-images.githubusercontent.com/7383162/171843962-7a7f7fc3-56cc-4fd9-a985-3f3944ff21cd.png)
