### ISSUE TITLE
Transect allocation to filter users by scheme

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#198]
When using transect allocation as a scheme co-ordinator, the list of users should be filtered by the same scheme

e.g. https://butterfly-monitoring.net/scheme-transects-allocation

If being used by Spanish co-ordinator, then list of users should be those linked to Spain BMS

**Comment by larspett** [comment]
This is very high on my wishlist, Since volunteers register with all sorts of names, it is difficult to administer a list which includes everyone from all schemes

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site to be tested. Users drop down list now depends on scheme/country (this is fixed for scheme co-ordinators, but selectable for the super-managers).

**Comment by Gary-van-Breda** [comment]
Currently deployed to Live.

**Comment by CrisSevilleja** [comment]
This is working for a while on the website.
