### ISSUE TITLE
Extend the drupal website to enable 'micro-sites' for separate countries

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#2]
This could just be a standard multi-lingual site with an option to choose country on the profile edit page, with that choice being fed through to reports. Or, we could do something a bit more fancy with https://www.drupal.org/project/domain.

**Comment by DavidRoy** [comment]
@Gary-van-Breda the requirements for this are not yet well defined.  Can this be left open without affecting the Drupal 8 update which is more urgent

**Comment by DavidRoy** [comment]
Some initial requirements for this.
1. Users can set the country/scheme they are part on within user settings #25 
2. Menus available are dependent on this setting #24 
3. Country manager has editing role for their country page #18

**Comment by Gary-van-Breda** [comment]
Deployed/Configured to Test Environment.

Basic functionality points are:

- New content type for schemes, which are attached to a country
- New field on user profiles and menu items, which references the scheme content type.
- All users except Supermanagers/Admins have to provide their scheme filled in when editing their profile.
- At the moment the sideeffect of this is that when creating a new account, the scheme must be provided.
- A person can edit their own scheme
- Supermanagers/Admins can view/edit anybody's data, including their scheme
- Supermanagers/Admins and Scheme coordinators can view the full list of people, but Scheme coordinators can only view/edit the details of users who share the same scheme.
- A Scheme coordinator can assign the role of Data recorder or Scheme coordinator to users who share the same scheme.
- A Scheme coordinator can set a user’s status to Active or Blocked for users who share the same scheme.
- When a scheme is changed an email is sent to all the scheme coordinators of the new scheme notifying them.
- Supermanagers/Admins can see all menu items
- Anyone can see menu items which do not have a scheme set
- Anyone with a scheme set can see menu links which have the same scheme.
- Supermanagers/Admins can create menu links with or without a scheme
- Scheme coordinators have to specify a scheme for any menu item links they create.
- Additional user and content editing capability means that the Scheme coordinators will now be shown a cutdown version of the admin toolbar at the top of their page.

**Comment by Gary-van-Breda** [comment]
@DavidRoy 
This has not been deployed to Live yet, and somewhere along the line the Live environment database has been copied back to test (probably when we where sorting out which enviorment should point to which warehouse), so the Test environment no longer has this installed either.
Shall I go ahead and configure both Test and Live for this, or would you prefer me just to do Test so you can have another look at it first, before it goes Live?

**Comment by DavidRoy** [comment]
It can go straight to live and we'll do the final tests there.  The site should be reasonably quite now the season is over.  Please let me know when you'll do this update

**Comment by Gary-van-Breda** [comment]
It shouldn't affect anyone during deployment - I'll do it tonight.

**Comment by Gary-van-Breda** [comment]
I've created a whole list of Scheme records to match the countries that the users were previously flagged against, apart from 2:

- User aoqmarlon is logged against "Australia" - is this correct? Their timezone is Belize.
- User denimcgowan is logged aginst Jersey - is this part of the UKBMS scheme?

Everything else is done.

**Comment by DavidRoy** [comment]
Please create an 'Other BMS' option and tag aoqmarlon to that

Also create a 'Jersey BMS' and tag denimcgowan to that

**Comment by Gary-van-Breda** [comment]
At the moment every BMS scheme has to have an associated country: for the other BMS which country should I use, or should I change this so that the country is not mandatory?

**Comment by Gary-van-Breda** [comment]
@DavidRoy : can you now review this (in the light of completion of #115) - can this now be closed?
