### ISSUE TITLE
Add verification page to www.butterfly-monitoring.net

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#20]
To support verification of butterfly transect data collected

**Comment by Gary-van-Breda** [comment]
Can I confirm that the verification will take place primarily at a scheme/country level? (By this I mean the verifiers will specify a country/scheme in their user account which will be used to restrict the records they can verify).

**Comment by DavidRoy** [comment]
Either country level of Nuts level 1 to restrict record view

**Comment by johnvanbreda** [comment]
Done
