### ISSUE TITLE
Add moth-survey mode to eBMS app

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#201]
Add new survey mode to app, for moth trapping (follow approach used for iRecord app)

Will need moth-trap form on website for record editing/viewing - will raise this as a separate issue

links to #200 and #185

**Comment by kazlauskis** [comment]
Thanks, should I use the same survey and it's attributes?

**Comment by DavidRoy** [comment]
Yes, but cloned across to the ABLE website (id = 118)
