### ISSUE TITLE
Walk Data Entry Page changes language to English

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#203]
Trying to introduce data for a transect walk, the page changes from Italian to English 

https://butterfly-monitoring.net/ebms-input-data?location_type_id=777&date=11/03/2020

@Gary-van-Breda  @DavidRoy 
(I cannot establish labels for the issue, I don't know why)

**Comment by johnvanbreda** [comment]
@Gary-van-Breda does the reload of the page need to respect the language prefix in the URL?

**Comment by Gary-van-Breda** [comment]
Its the generation of the link within the calendar grid that needed to be language aware. I've changed the form to allow the definition of the node via the node ID, which is then translated into the language specific route, for both new and existing walks.
Code deployed to Live. Looks OK to me.
@CrisSevilleja : please review (and hopefully close?)

**Comment by CrisSevilleja** [comment]
It looks okay, thanks
