### ISSUE TITLE
Wrong Spanish translation in ButterflyCount app

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#204]
In the eBMS app, Menu section, there is one part called "Help" in Spanish is "Ayuda" and in that page, it is well translated. If you enter in the help page, the title of the page should be "Ayuda" but it appears as "Creditos". I checked the translation in Transifex and it is well done. 

@kazlauskis could you change this mistake on the app? There is not a hurry on that but it would be great to change it. I uploaded a picture to show the mistake. 

![Help-wrong translation](https://user-images.githubusercontent.com/25052478/76848240-a6472780-6843-11ea-90da-4fb765d565e1.jpg)

**Comment by kazlauskis** [comment]
Thanks, well spotted, I will fix it asap.

**Comment by CrisSevilleja** [comment]
thanks @kazlauskis! Also, I saw it happens the same for English, I imagine it is in every language.
