### ISSUE TITLE
Problems loading google map while drawing a transect

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#206]
@Gary-van-Breda @DavidRoy 
Some users reported me they had some issues drawing a new transect on the eBMS website (Site details, https://butterfly-monitoring.net/ebms-site-details) because the google hybrid map didn't load the complete area, only the square in the center (like in the picture). Maybe it is a problem with the browser. 

Drawing one transect I realised that if you move the image around with the mouse, the consecutive squares of the map load. However, some users can't realise that. If the problem cannot be resolved, I would suggest adding some help message mention how to load the whole area to draw well the transect. Thank you

![problems loading google map drawing a transect](https://user-images.githubusercontent.com/25052478/77307795-35e44e80-6cfa-11ea-9624-6f17673f4dac.png)

**Comment by DavidRoy** [comment]
@CrisSevilleja we can't replicate this.  Is this still happening or maybe it was a temporary connection issue?

**Comment by CrisSevilleja** [comment]
@DavidRoy it doesn't happen exactly that, only one square loaded but if you want to create a new transect you don't see the whole map and you need to move around the image to load the surrounding squares. It happened to me last Tuesday drawing a new transect, even for drawing one section was tricky to get the whole area loaded.

**Comment by DavidRoy** [comment]
Closing as not reported again
