### ISSUE TITLE
Missing section number in the Transect window on the app

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#208]
@kazlauskis  @DavidRoy 

In the transect window on ButterflyCount app, it is missing the section number when you are inside of a section adding butterfly species.
See the picture. 

![missing section number](https://user-images.githubusercontent.com/25052478/77628716-b4cec680-6f48-11ea-8df3-8ca271a51c35.png)

**Comment by DavidRoy** [comment]
I agree.  I think it would be helpful to also have an option to move back-forward through sections, e.g. a back and next option.  It could look like this

Section:   <<--- 3 ---->>

with the arrows being buttons

Maybe tricky as the species list would need to change with the section chosen

**Comment by kazlauskis** [comment]
I will add the section number to the header and will also add a link to the next section. I have to keep the back button as a link to the all-sections page for now.

**Comment by CrisSevilleja** [comment]
Thank you @kazlauskis I like your propose. It will be enough with these changes
