### ISSUE TITLE
Add ability to copy species list from previous transect section

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#209]
@kazlauskis @DavidRoy 

Using the app for 15-minute counts and transects, I thought it would be more comfortable to have a fixed list of species seen by the recorder on the data entry window. Especially if you are doing a transect with 4-5 sections, in every section you need to type every time the common species for example. Maybe it can be fixed to 5-7 species more commonly seen in that specific transect or recorder and starting always at 0.

I don't know how feasible is this function, but it would be useful although not a high priority for now.

**Comment by larspett** [comment]
It might be even better to preload (as an option, possibly also the number of species optional) the same feature as in the website entries with "species seen by me - species seen at this site - common species - all species - etc"  That would align with the website entry method and has actually been asked for by one of the Danes who I was in contact with (a guy who wouldn't translate for free, though)

**Comment by kazlauskis** [comment]
Yeah, Martin Warren also wanted to see something like this in the app. We can make this progressive, first, allow to copy user's previous lists, then suggest common species in the country and then, also, suggest species based on location.

**Comment by DavidRoy** [comment]
links to #180

**Comment by kazlauskis** [comment]
We are thinking of adding this functionality under the species 'Add' button as a long press dropdown list. Would something like this be OK?

<img width="357" alt="Screenshot 2020-05-29 at 11 55 41" src="https://user-images.githubusercontent.com/7383162/83252852-de53da80-a1a3-11ea-8ad0-fb058e292aa7.png">

**Comment by DavidRoy** [comment]
yes, although how would 'from my past record' work?
'recommended species' not currently available?

This functionality does give the potential for the options to align with the warehouse species list later on (separate work to extend the warehouse list to include other flags)

**Comment by kazlauskis** [comment]
Great, for this ticket we would pick up the section-copy only and then we could create another tickets for other options.

**Comment by DavidRoy** [comment]
Agreed, that would be a good start

**Comment by CrisSevilleja** [comment]
@kazlauskis This option is not working on the app now, you are able to copy the list but the app only copies a maximum of one species, and I think it is the last one added. 
Please if possible solve this issue although right now after counting a lot on an island with a low number of species, I see more convenience to set the fixed species list on the app. I would place it on app settings, hidden a bit.

**Comment by kazlauskis** [comment]
For the transects, I think, the copying isn't added at all. For the 15min surveys it should copy the full list of the previous survey, does this not work?

For the transect surveys, would you prefer setting up a single static list of species? or would copying from the previous section be OK?

**Comment by CrisSevilleja** [comment]
No, currently, this option is not working for 15-min counts, it only copies one species as maximum, although you have 10 species. 

Maybe for transects is more convenient to enable this option too, copying the species from the section before it is useful

**Comment by kazlauskis** [comment]
I've just tried it with the 15min survey 
and it has correctly copied over my previous survey list. All of the copied entries have 0s as a count set. Doesn't this work the same way for you?

![IMG_CC93B3147316-1](https://user-images.githubusercontent.com/7383162/134913011-d6922dfb-14fc-4729-ab17-c68f29774ef9.jpeg)

**Comment by CrisSevilleja** [comment]
So strange it is working for you and not for me... I just tried again and the app only copied one species when I have it three on the previous record. I did it with an Android but Irma did it with her Apple and it didn't work either. 

Can it be something related to using common names? We use normally Latin names and I see yours are only common English names. If it is not that, I don't get why it is not working for me, although I know from other users it doesn't work well

**Comment by kazlauskis** [comment]
Yes, I've tried it with latin names as well as other languages and it works fine for me. Which app version do you have? Could you send me a few screenshots to illustrate the issue?

**Comment by CrisSevilleja** [comment]
Here are some screenshots: I did three 15-min countsone after the other, in the first one (1st pic) you see 5 species with different abundances where Aglais io is the most abundant. In the second one, I tried to copy the species list and it was only copied Aglais io. I finish that count with 4 species changing abundances, now Pieris rapae has the most abundance. I start the third 15-min count and try to copy the species list and only Pieris rapae is copied. I have the eBMS version v1.14.0 (46) as you see it in the picture, using an Android version 10, Mi A2 Lite Xiaomi. 

I hope this helps! Thank you Karolis

![1- first](https://user-images.githubusercontent.com/25052478/135081224-84692c71-7313-49e7-9b3b-a83971a57afe.png)
![2- copy from the first](https://user-images.githubusercontent.com/25052478/135081228-7c40e972-7e9d-4653-991d-569f3247d25f.png)
![2- second](https://user-images.githubusercontent.com/25052478/135081231-c2f62124-8de7-4aef-ba95-1da9b60250f1.png)
![3- copy from the second](https://user-images.githubusercontent.com/25052478/135081233-0aa05b10-4569-404c-a6de-c9df87018fe5.png)

![version](https://user-images.githubusercontent.com/25052478/135080959-33d13b77-56fb-4488-b303-feb3139184c1.png)
