### ISSUE TITLE
No transects available in v 1.5

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#210]
I am trying out the newest version of the app on iOS (v 1.5.0 (1) ) and can't access the transect entry form. Why is that? Is it permanently disabled until I have allocated a transect to myself, is it a deliberate omission in this version, or is it a bug? I used to have a couple of transects allocated to myself.

**Comment by DavidRoy** [comment]
via your gmail account which is set as Sweden BMS co-ordinator
You were only allocated to a one site: Billebjer

I have allocated you to all the ones in Sweden:
Billebjer
Fjällmossen slinga
Fjällmossen transekt
Rökepipan
Simängsvägen

Can you test this, thanks

**Comment by CrisSevilleja** [comment]
Dear Lars,

I think I understood your question. We included the option to do a
long-press on the + button to enter to transect form and other options. If
you click the + button as normal you will enter directly to 15-min counts.

I hope I resolved your doubt.

Cheers,
Cristina

**Comment by larspett** [comment]
Yes, it did work, it was the press long-option that effectively hid the transect option to me.  I suspect that I might not be the only one getting stuck on that. Personally I preferred seing both options and chosing. Possibly being offered to have a default option of my own. But being forced into 15-min counts is slightly annoying (to me)

**Comment by larspett** [comment]
I would vote against this UX as a user

**Comment by DavidRoy** [comment]
We had a long discussion about this.  We think the transect option is confusing to the general user, so is a deliberate option to make the transects less obvious.  To use the transect option requires the route to be setup and the user allocated to the site - both need engagement with the national co-ordinator who can then explain how the app works.

For more general users of the app, we want to keep this as simple as possible and therefore go straight to the 15 minute count that can be done anywhere at any time and requires no prior setup.

Does that help explain this thinking?

**Comment by larspett** [comment]
I understand the rationale and don't want to jump in with old arguments in a discussion that has already been closed but the UX favours 15-min counts over transects (which is fine for the general users) while I would prefer to encourage the standardised observations. If anything, I'd be happy with the long press alternating between default entry form (15-min until transects are selected, then transects until 15-min is selected).

**Comment by DavidRoy** [comment]
Agreed, this was a compromise.  We also discussed two separate apps but that is more work.

We'll raise a feature request to have a user-setting - to have a preferred method for standard vs long-press.  We also intend to add in opportunistic recording as a third method

**Comment by larspett** [comment]
Just to be clear - I meant that the long press could be used to set the current default method, i.e. that users can toggle between althernative methods using long press. Then again, the + wasn't intuitive to me as a new user as a means to change entry mode. I am not entirely confortable promoting 15-min counts as a preferred/default method in the app text either but will do my best to phrase it in a way that works for Swedish settings
