### ISSUE TITLE
Enable automatic record re-upload when back online

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#212]
At the moment, the user has to manually manage the upload of each record.

**Comment by CrisSevilleja** [comment]
@kazlauskis with re-upload you mean when the first you wanted to upload the record and it failed?

I see it important to choose when to upload the records to give the recorders the option of checking the record before submitting it.

**Comment by kazlauskis** [comment]
@CrisSevilleja yes, once the user flags the record for upload it will try to send it but if failed it should try to resend it once the user is back online.

**Comment by CrisSevilleja** [comment]
@kazlauskis ah great useful to add it, thanks for the clarification.

**Comment by Vilius-Stankaitis** [comment]
- [x] Move the Upload all button to the user-records page

**Comment by Vilius-Stankaitis** [comment]
Hi, I did not implement automatic upload. I moved the 'Upload all' button to the "surveys" page, a simpler solution with a similar UX effect.

![Screenshot 2023-05-19 at 11.19.39.png](https://zube.io/files/biologicalrecordscentre/856a73f51eb12d497715b81133a38a3c-screenshot-2023-05-19-at-11-19-39.png)
