### ISSUE TITLE
Common species screen is not translated

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#216]
The common species screen pulls the most common species from Indicia which means that they are currently shown in English, no matter what the default app language is. The best option would be to have this in the selected language. It should be noted that if these five remain the top 5, then there should be names available in all app languages, however there could be a situation where a given language would lack one of the five so we might need to cover for that possibility.  @DavidRoy has a possible solution: "Maybe a holding position is to have some text to say ‘This screen is not yet available in other languages’."

![Skärmavbild 2020-03-31 kl  11 19 44](https://user-images.githubusercontent.com/19598308/78010657-eaa5ed80-7342-11ea-97c8-66dfe09bd584.png)

**Comment by DavidRoy** [comment]
Another holding position is to just show the latin name?

**Comment by larspett** [comment]
That would be even easier option than adding an explanation about the current vs planned translation of the page

**Comment by DavidRoy** [comment]
@kazlauskis as discussed, could you quickly remove english common names from the home page report for the time being

**Comment by kazlauskis** [comment]
OK, the app is undergoing the iOS app store review right now and if all goes well it should be finished by tomorrow morning which will give us another day to fix this.

**Comment by DavidRoy** [comment]
@larspett please close if now fixed for you in Swedish

**Comment by larspett** [comment]
In what version? The TestFlight one is still the same so should I check somewhere else? The webpage version of the app?  Best, Lars

2 apr. 2020 kl. 09:37 skrev David Roy (CEH) <notifications@github.com>:

﻿

@larspett<https://github.com/larspett> please close if now fixed for you in Swedish

**Comment by DavidRoy** [comment]
The app is now live, v1.5.1 (1), so best to update from the app store.

**Comment by larspett** [comment]
Yes- in Swedish now. Well done! /Lars

2 apr. 2020 kl. 09:53 skrev David Roy (CEH) <notifications@github.com>:

﻿

The app is now live, v1.5.1 (1), so best to update from the app store.

**Comment by larspett** [comment]
closing now
