### ISSUE TITLE
Incorrect name in species list

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#217]
The entry "Oliver Grizzled Skipper" in the English part of the Transifex species list should be "Olive/Oberthür's Grizzled Skipper"

**Comment by DavidRoy** [comment]
@larspett can you point me to the where this needs fixing in Transifex please

**Comment by DavidRoy** [comment]
@larspett is this still an open issue?

**Comment by larspett** [comment]
@DavidRoy I can't locate the species list in Transifex now that I referred to, I did submit an issue through Transifex back in 2020 as this entry was referring to the species complex Olive Grizzled Skipper/Oberthür's Grizzled Skipper (if I remember correctly) but was called Oliver Grizzled Skipper. But maybe this is pulled from the Indicia data warehouse now? Anyway, I had a look and Oliver is still there :)
![oliver](https://github.com/BiologicalRecordsCentre/ABLE/assets/19598308/71055a7c-cb53-4493-81d0-645ac989dc4e)

**Comment by larspett** [comment]
Plus a better overvi
![oliver2](https://github.com/BiologicalRecordsCentre/ABLE/assets/19598308/33a8972b-e005-4539-82dc-689627767a40)
ew here

**Comment by DavidRoy** [comment]
Thanks.  I've removed the offending name.  It will get picked up next time the app is updated
