### ISSUE TITLE
Typo on Transect page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#218]
On the transect mode, the 'Cloud' label is repeated on the screen.  The first 'Cloud' label should be [Wind Direction]

This is a bug
![Screenshot 2020-04-02 at 08 41 51](https://user-images.githubusercontent.com/2699478/78222883-e6520f80-74bd-11ea-8886-5a1434691da1.png)

**Comment by kazlauskis** [comment]
Thanks, I have found how this has crept into and have it fixed now. The update should reach our users shortly.

**Comment by DavidRoy** [comment]
Fixed, thanks
