### ISSUE TITLE
Website logout button is missing on small screens

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#219]
From Carin:
> I checked the website once more on the computer, and the button “My Account” at the right of the navigation bar shows the alternative “Log out” when in full width, ie. large screen, but as I reduce window size,  and the menu bar turns into a button, there is an “My account” alternative, but no “Log out” option. Maybe an actual logout button on the page would be a good idea, apart from adding it to the menu?

Here is a screenshot. 

<img width="325" alt="Screenshot 2020-04-02 at 11 49 30" src="https://user-images.githubusercontent.com/7383162/78241351-21f9d300-74d8-11ea-9a69-13215d256913.png">

**Comment by DavidRoy** [comment]
@BirenRathod can you pick this one up?

**Comment by BirenRathod** [comment]
@DavidRoy 
I will take a look.

**Comment by BirenRathod** [comment]
@kazlauskis & @DavidRoy 
It hidden under that "My account" dropdown menu but it provides scroll bar at right side, so it needs to scroll down by mouse.

**Comment by BirenRathod** [comment]
The same trick you need to do to see a list of submenu of "My transect reports"

**Comment by BirenRathod** [comment]
Here is a screenshot
![image](https://user-images.githubusercontent.com/5941255/78245732-e105bc80-74df-11ea-88d0-a1d715eed6e0.png)

**Comment by kazlauskis** [comment]
I have only tried this on iOS myself, but the scrolling didn't work well.

**Comment by BirenRathod** [comment]
@kazlauskis 
I just checked on iOS, it works same way as on Windows or Android phone.

**Comment by BirenRathod** [comment]
Here it is from iOS
![image](https://user-images.githubusercontent.com/5941255/78248350-67240200-74e4-11ea-9016-9d8183ad5ac1.png)

**Comment by DavidRoy** [comment]
Very clunky but not an immediate priority.  At some point we'll work on the theming/design a bit more.

**Comment by BirenRathod** [comment]
That's right. There is a solution for that. I'm not suggesting do now but we can certainly implement. 
The solution is here -> https://dev-brc-site.pantheonsite.io/, I still need to do bit of work on it but menu is almost there.

**Comment by DavidRoy** [comment]
Closing, as the layout on iOS is ok
