### ISSUE TITLE
Add admin page for setup of verification filters

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#22]
To enable filters to be setup for users to define the geographic region for their verification role

**Comment by DavidRoy** [comment]
Also needs a drupal role to assign users as verifiers

**Comment by Gary-van-Breda** [comment]
Drupal 'verifier' role already exists.

**Comment by johnvanbreda** [comment]
Done - see https://butterfly-monitoring.net/admin/filters-list.

**Comment by DavidRoy** [comment]
When i go to create a new filter, i return to the site home page instead of the filter setup page:
https://butterfly-monitoring.net/filters/admin-edit

When logged in as admin

**Comment by johnvanbreda** [comment]
Fixed
