### ISSUE TITLE
Problem transect Cruzinha I (Portugal), two sections 2

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#222]
The transect Cruzinha I is recorded by Paula Banza and Filipa Bragança. When they enter the data, in the "Entry data site" https://butterfly-monitoring.net/ebms-input-data?, section 2 (S2) appears duplicated (see the picture attached). This transect has data from last year, so I cannot remove it and draw it again easily.

@Gary-van-Breda could you check this issue?
@DavidRoy 
![error transect Cruzinha I](https://user-images.githubusercontent.com/25052478/78901917-4fff8a00-7a79-11ea-9215-69ae621e98a6.PNG)

**Comment by Gary-van-Breda** [comment]
The transect data entry page is currently  undergoing a rewrite.  It had created two S2s.
The walks have been merged onto a single section, and the duplicate section removed.
@CrisSevilleja : This instance should now be fixed.

**Comment by CrisSevilleja** [comment]
Thanks @Gary-van-Breda for resolving this issue
