### ISSUE TITLE
Records with one GPS coord are rejected by warehouse

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#223]
Needs better validation on the app to indicate this to the user. Linked to [#237 (BiologicalRecordsCentre/ABLE#214)](https://zube.io/biologicalrecordscentre/ebms/c/237)

**Comment by DavidRoy** [comment]
@kazlauskis was this fixed in last update?

**Comment by kazlauskis** [comment]
No this wasn't, let's keep it open for now.

**Comment by Vilius-Stankaitis** [comment]
@kazlauskis I think this one is no longer an issue.
