### ISSUE TITLE
add common names to warehouse for several countries

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#226]
@johnvanbreda further to #225, we would like to add common names for:
Croatian
Czech
Finish
German
Hungarian

Is the best option for us to supply a file for each language with two columns:
taxa_taxon_list_id, common name

**Comment by kazlauskis** [comment]
No Lithuanian? 😢

At the moment, only 3 more languages have this translated which I have attached here. The data sheets have a bit more info for validation in case my matching of taxon_ids to common names had any mistakes.

@DavidRoy Are we planning on using Transifex for further species name translations or would you expect people to send us the excel sheets? 

[ru_RU.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/4550865/ru_RU.xlsx)
[lt_LT.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/4550863/lt_LT.xlsx)
[hu_HU.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/4550861/hu_HU.xlsx)

**Comment by DavidRoy** [comment]
Thanks.
@CrisSevilleja what do you think.  We use spreadsheets for the common names?

**Comment by johnvanbreda** [comment]
@DavidRoy if we are just using the standard importer as before, then we need a spreadsheet with the taxa_taxon_list_id of the accepted name, plus a single field formatted with ALL the common names (including the ones already uploaded), in the format:
name | langcode
name | langcode

This approach might be quite fiddly though. Another approach would be to have a spreadsheet with just the names plus the external_key we allocated for each species. I'd then upload them as standalone names and use a post-processing query to make them into common names linked to the accepted name.

**Comment by CrisSevilleja** [comment]
@DavidRoy I think coordinators will prefer to send spreadsheets directly than typing one by one common names on Transifex. Common names are relatively static strings that are not going to change.

Sorry @kazlauskis I didn't have the common names from Lithuania, good you included them!

**Comment by kazlauskis** [comment]
@johnvanbreda @DavidRoy I could set up a shared excel doc with the current names we have if this helps. It would look like this




taxa_taxon_list_id | external_key | taxon | nl_NL | ru_RU | …
-- | -- | -- | -- | -- | --
432425 | eBMS442 | Aglais io | Dagpauwoog | Многоцветница павлиний глаз | …
… | … | … | … | … | …

**Comment by DavidRoy** [comment]
@kazlauskis yes please. Here are the extra names that Cristina has collated:
[CommonNames_Hu_Cro_Ger_Fin_Cz.zip](https://github.com/BiologicalRecordsCentre/ABLE/files/4552031/CommonNames_Hu_Cro_Ger_Fin_Cz.zip)

**Comment by CrisSevilleja** [comment]
@kazlauskis thanks for including the common names. Please for German language use this updated version (in the last minute an error found). Thank you

[eBMS_list_plus_Eng&German(Austria).xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/4552226/eBMS_list_plus_Eng.German.Austria.xlsx)

**Comment by kazlauskis** [comment]
I have pulled in all the names to an online document. I had to do some manual corrections to the English names (formatting issues) and also mapping of the limited Russian species list to the full list here. Please have a look and let me know if you needed anything else. I will send you the password to access the doc separately over email.

[Species Names Sheet](https://flumensio-my.sharepoint.com/:x:/g/personal/karolis_flumens_io/EVAl-UYRLwBOtl0b5_lZJ60BndTEKqLL3yPzNFp68luUvA?e=2amLCs
)

**Comment by DavidRoy** [comment]
Thanks
@johnvanbreda can you work with this to update the common names in the warehouse.  Via the back-end database sounds the best option

**Comment by johnvanbreda** [comment]
Here are the steps:
1. Download the spreadsheet and save as CSV (UTF-8).
2. I created a new list on the warehouse to act as a temporary staging ground - list 262.
3. On the warehouse, check the Languages list contains all required languages and add any that are missing.
4. Use the warehouse imported on list 262's Taxa tab, upload the CSV file. Set the language to the match the first column of names you are going to import (English in this case). Set the taxon group to insect - butterfly.  On the next tab, External Key should auto-match to Taxon > External key. Unmap the Taxon column and instead set the first column (en_GB in this case) to map to Taxon > Taxon. You DON'T want to map the taxa_taxon_list_id field as we are going to import a list of standalone names then use a script to map them back to the correct accepted names using the external key. Run the import - note that the blank rows will report as errors, that is fine.
5. Repeat step 4 for each of the language columns.
6. I spotted a few dodgy versions of unicode characters in the source data so fixed these where I could with the following SQL:
```sql
update taxa set taxon=replace(taxon, E'\u0081', 'ü'), updated_on=now()
where id in (select taxon_id from taxa_taxon_lists where taxon_list_id=262) and taxon like  E'%\u0081%';
update taxa set taxon=replace(taxon, '‡', 'ç'), updated_on=now()
where id in (select taxon_id from taxa_taxon_lists where taxon_list_id=262) and taxon like  '%‡%';
update taxa set taxon=replace(taxon, '„', 'ä'), updated_on=now()
where id in (select taxon_id from taxa_taxon_lists where taxon_list_id=262) and taxon like  '%„%';
```
6. I ran the following SQL to get a temporary table summarising the new names so I could double check it looks right, in particular we don't want to duplicate existing common names:
```sql

select ttl.id, t.taxon, l.language, ttl2.id as accepted_ttl_id, t2.taxon as accepted_name, 
  t3.id is not null as existing,
  (select string_agg(taxon, '; ') from cache_taxa_taxon_lists where taxon_list_id=251 and external_key=t.external_key and preferred=false) as existing_names,
  ttl.taxon_meaning_id as old_taxon_meaning_id, ttl2.taxon_meaning_id as new_taxon_meaning_id  
into temporary names_summary
from taxa_taxon_lists ttl
join taxa t on t.id=ttl.taxon_id and t.deleted=false
join languages l on l.id=t.language_id
left join (taxa t2 -- accepted name on list 251 
  join taxa_taxon_lists ttl2 on ttl2.taxon_id=t2.id and ttl2.taxon_list_id=251 and ttl2.deleted=false and ttl2.preferred=true
) on t2.external_key=t.external_key and t2.deleted=false
left join (taxa t3 -- does this name exist on list 251?
  join taxa_taxon_lists ttl3 on ttl3.taxon_id=t3.id and ttl3.taxon_list_id=251 and ttl3.deleted=false 
) on t3.external_key=t.external_key and t3.deleted=false
  and t3.language_id=t.language_id and t3.taxon=t.taxon
where ttl.taxon_list_id=262 and ttl.deleted=false;

select * from names_summary;
```
7. I then used the following query to copy the new names over into list 251, with the correct link to the taxon concept:
```sql
update taxa_taxon_lists ttl
set taxon_meaning_id=ns.new_taxon_meaning_id, preferred=false, taxon_list_id=251, updated_on=now()
from names_summary ns
where ns.id=ttl.id
and ns.existing=false;
```

That should be done - I also need to update the lookup tables in Elasticsearch which I'll do now.

**Comment by DavidRoy** [comment]
Thanks John
@kazlauskis can you incorporate in the app now?  And push out an update?

**Comment by johnvanbreda** [comment]
@kazlauskis @DavidRoy please can you pause on that till tomorrow morning? There were a few copies of names with dodgy characters in which I've had to clean up in the database, but because they then didn't match up with the existing names in my matching query above we've ended up with duplicates and other issues. I've tidied quite a bit but need an hour or so tomorrow to finish off I think.

**Comment by johnvanbreda** [comment]
@kazlauskis @DavidRoy I'm happy with the names as they are now.

**Comment by kazlauskis** [comment]
I have pulled in the species names and will add all into the app today.

**Comment by DavidRoy** [comment]
Thanks all.  Closing this for now.
