### ISSUE TITLE
For UK app users, message about links to other surveys

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#227]
Requirement is for UK but possibly needed for other countries too

For those using the app where they choose United Kingdom as country on startup or via app settings:
add popup text to say:
_This app is not for the Big Butterfly Count.  If you want to take part in that survey please visit https://www.bigbutterflycount.org/_

@kazlauskis to comment on the feasibility/complexity of implementing

**Comment by kazlauskis** [comment]
Do we want this to be translated to other languages? e.g. selecting Spanish + UK as a country would show this translated.

**Comment by DavidRoy** [comment]
no, just English is fine
