### ISSUE TITLE
change to App 'about' text

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#228]
Edit to ‘About This App’ statement to reduce potential for confusion with participants in Big Butterfly Count.

Currently it says ‘_This app enables you to contribute to butterfly conservation_’. 

change to:
‘_This app enables you to contribute to the recording and conservation of Europe’s butterflies.  The app is not part of the Big Butterfly Count that is run in the UK by Butterfly Conservation each summer.  Please visit their project website for information on how to get involved in that survey https://www.bigbutterflycount.org/.  Data collected through this ButterflyCount app is shared with UK Butterfly Conservation (and other Butterfly Conservation Europe partners) to support their monitoring and conservation work_.’

**Comment by kazlauskis** [comment]
Sorry, I couldn't find this specific term anywhere in the app 😐 Should I just add this to the top of the About page text?

**Comment by DavidRoy** [comment]
yes please, I think that was what is intended

**Comment by kazlauskis** [comment]
Great, would you like this to be shown to all other languages as well or is it just English?

**Comment by DavidRoy** [comment]
Just english is fine, in fact preferred as it won't make much sense to other countries

**Comment by kazlauskis** [comment]
Cool, that's what I thought too.
