### ISSUE TITLE
emails from butterfly-monitoring.net getting blocked by spam filters

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#230]
We've had some reports of emails from butterfly-monitoring.net not getting through.
@BirenRathod do you have any suggestions on how we can minimize this?

**Comment by BirenRathod** [comment]
@DavidRoy 
There was a due of upgrading major version of SMTP module. I just did so should be fine by now. Please check and let me know if you find any porblem.

**Comment by BirenRathod** [comment]
@DavidRoy 
After upgrading a module, I checked and it is a problem of spam filter. I have asked CCS.

**Comment by johnvanbreda** [comment]
@DavidRoy I recently had a similar problem on another site. One thing I found that was handy is that in Outlook if you can get hold of a message which did pass through the filters, you can look at the message properties (using a small arrow pointing to bottom right in the message's toolbar), This contains an Internet Headers field which has a section called X-Spam-Filters (though I think it may differ on other filtering systems). This section contains lots of data about checks which passed or failed, how the total spam score was calculated and what threshold was set for treating the message as spam. I found via this method that errors in my HTML output were raising the spam score.

**Comment by BirenRathod** [comment]
This has been blocked by spam filter used in CEH if it hasn't been allowed before. It may end up in junk folder.

**Comment by DavidRoy** [comment]
Closing for now.  Raise more specific issues as needed
