### ISSUE TITLE
Transect visit summary page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#231]
Require a summary page to show the visit and count information on a single page.  Currently they are on separate pages of the input-data form. https://butterfly-monitoring.net/ebms-input-data

Example information to include on a single page = 
[Guembres_4.05.2020_exampleSumVisit.pdf](https://github.com/BiologicalRecordsCentre/ABLE/files/4644436/Guembres_4.05.2020_exampleSumVisit.pdf)

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Is this a separate page, or built into the walk data entry page?

**Comment by DavidRoy** [comment]
I think this can be closed as requirement not clear
