### ISSUE TITLE
Allow recorders to see/edit all walks for transect sites assigned to

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#234]
https://butterfly-monitoring.net/my-walks is currently restricted to a users own transect walks.

This should be extended to include any transect walks to sites that a user is assigned to.

**Comment by CrisSevilleja** [comment]
Thanks @DavidRoy for posting this issue. I received this same suggestion from several coordinators recently. Could it be possible to give a bit of a priority?

**Comment by Gary-van-Breda** [comment]
I've just uploaded a new report into the indicia-reports BRC repository.
https://github.com/BiologicalRecordsCentre/indicia-reports/commit/286ef87fb97f69c321620ee9a9f60faf05e27103
@johnvanbreda or @BirenRathod : could I have it deployed into warehouse1?

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I have just the pulled the report.

**Comment by Gary-van-Breda** [comment]
Thanks @BirenRathod.  
  
I have configured the "My walks" page to use the new report. It shoudl now display all walks created by the user or on sites allocated to the user.  
@CrisSevilleja Can you please check?

**Comment by CrisSevilleja** [comment]
Yes, I checked it and it is working well. Thank you so much

@DavidRoy you can close this issue

**Comment by DavidRoy** [comment]
Thanks
