### ISSUE TITLE
ButterflyCount app - Add in sample attribute for 'type of count'

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#236]
There are three main modes of using the 15 minute count within the app and it would be good to capture the 'type':
1. Count while walking a track
2. Count while surveying an area of habitat
3. Count while stationary, e.g. in a garden

Interpreting the area is different for each.  Suggest adding an attribute to the 15-minute count screen below 'Area' of ''Type of count" with options being 
- 'Walking a track'
- 'Surveying an area'
- 'Stationary (e.g. not moving)'

If possible, the 'area' element then becomes different depending on the survey type.  For a 'stationary count' the area would be an estimate for example and would require the user to enter an area category?

**Comment by kazlauskis** [comment]
Adding a new attribute is a small task, to make changes to the area count will make it medium-large.

**Comment by DavidRoy** [comment]
closing as repeated by #267
