### ISSUE TITLE
ButterflyCount app: + button to remember last choice

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#238]
Currently, the plus button starts a 15 minute count and a long-press enable transect recording.

Could the + press remember the last option chosen.  So if mainly using for transects then a long-press is not needed?

**Comment by kazlauskis** [comment]
Yes, we could do this. This would probably confuse some people without enough clarification. Another option would be to add a settings option to allow the user to choose the preferred default plus-button action.

**Comment by DavidRoy** [comment]
yes, that would be a good option
