### ISSUE TITLE
Menus for www.butterfly-monitoring.net

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#24]
Changes to Menus required.  New menu setup (submenus indicated by numbers):
- Home
- MyData
1. Sites
2. Walks
3. Timed Counts
4. Reports
- National Scheme [menu dependent on user account setting for Country/scheme, e.g. Italy BMS if selected].  Absent if no scheme selected in user account
- Partners (eBMS)
- Projects
1. ABLE
2. BGEMS

**Comment by Gary-van-Breda** [comment]
Basic framework of the above is already in place.
Home : present
My Data & is submenus : present
National Scheme : missing until the country setup is finalised
Partners (eBMS) : Present
Projects : Present, although there is currently no ABLE page so that menu item is missing until it is created.

**Comment by DavidRoy** [comment]
blank able page created:
http://dev-butterfly-monitoring.pantheonsite.io/able

@Gary-van-Breda please add as a submenu item under 'Projects' and advise on the steps to do this

**Comment by Gary-van-Breda** [comment]
Menu Item added.

For future reference:
From Admin toolbar -> Structure -> Menus.
Pick the "Add Link" in the drop down beside the required Menu.
Fill in the Menu Link title.
Fill in the relative url as the link : in this case it is "/able"
Set the language to "not specified"
Save this.
From Admin toolbar -> Structure -> Menus.
Pick the "Edit Menu" in the drop down beside the required Menu.
Drag the new item to the required position within the menu.
Save.

**Comment by DavidRoy** [comment]
Thanks

**Comment by DavidRoy** [comment]
Reopening as the country-specific menu to be completed.  This is of less immediate importance

**Comment by Gary-van-Breda** [comment]
With the Scheme module now enabled, what are the requirements for the country-specific menu?

**Comment by DavidRoy** [comment]
Closing, will raise more specific issues as needed
