### ISSUE TITLE
ButterflyCount: Add 'weather' as attributes for 15 minute counts

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#240]
* [x] Create a new page labeled 'Additional details'
* [x] Move Comment page link to the new details page
* [x] Add in weather criteria for 15 minute counts
  * Weather options same as used on Transects:
Temperature
Cloud
Wind Direction
Wind Speed
  * Label: Weather conditions
  * (optional)  auto-populating the weather values using a Meterological API?
https://openweathermap.org/current

**Comment by kazlauskis** [comment]
The survey main page is becoming tight for the species list. I think we should wrap any new attributes like weather, survey type etc under a new 'Other' page, would that be OK?

**Comment by DavidRoy** [comment]
How about changing 'Comment' to be 'Additional details' and include weather + comments?

**Comment by kazlauskis** [comment]
👍
<img width="448" alt="Screenshot 2020-05-19 at 09 48 46" src="https://user-images.githubusercontent.com/7383162/82305721-f06c9680-99b5-11ea-832a-bb6d3bccdba2.png">

**Comment by kazlauskis** [comment]
@DavidRoy it will look like this for the 15min survey now, is it OK?

<img width="367" alt="screenshot" src="https://user-images.githubusercontent.com/7383162/83329971-41b53980-a284-11ea-923b-9b09c5d473cb.png">

**Comment by DavidRoy** [comment]
yes, thanks.  Looks good

**Comment by CrisSevilleja** [comment]
Really good idea to include it inside of the comment tab. Just one question, is it going to be compulsory to fill these weather conditions to save the 15-min counts? I don't imagine but just in case, to be sure. Thanks!

**Comment by kazlauskis** [comment]
Yeah, we probably want to keep it optional.

**Comment by DavidRoy** [comment]
Yes, optional and hopefully with values already filled in from online met data

**Comment by CrisSevilleja** [comment]
great! thanks for answering

**Comment by kazlauskis** [comment]
@DavidRoy do we want to capture `not-recorded/no data` weather option or can we omit it when the user hasn't selected anything?  i.e. do we want it to be more intentional and allow the user to specify that it wasn't recorded as an option.

Temperature values:
```
'Not recorded/no data': 16556,
10: 16530,
11: 16531,
12: 16532,
13: 16533,
....
```

**Comment by DavidRoy** [comment]
If we use the API then we'll have the values for the weather?

If we don't have the API values, we'll want the 'not recorded/no data' as the default

**Comment by kazlauskis** [comment]
Yes, the API should provide the values if the user has a network connection. Otherwise, we will then default it to `not recorded/no data` and if the user clicks on a specific temperature and then decides to not record it by selecting `not recorded/no data` we will not send any value to the database and it will look like the user didn't record anything rather than intentionally selected 'no data'. This is how our other apps work, but seeing that the default value here has an assigned attribute value, I though to double check if you wanted to capture that information.

By the way, do you have an API account we should use for this or would you like us to create a new free one for CEH? https://openweathermap.org/price

**Comment by DavidRoy** [comment]
have set up an account and will email you the API key

**Comment by DavidRoy** [comment]
here are the wind speed terms linked to mph. https://en.wikipedia.org/wiki/Beaufort_scale

<1 mph = Smoke rises vertically
1-3mph = Slight smoke drift
4-7 mph = Wind felt on face, leaves rustle
8-12 mph = Leaves and twigs in slight motion
13-18mph = Dust raised and small branches move
19-24 mph = Small trees in leaf begin to sway
25+ = Large branches move and trees sway

**Comment by kazlauskis** [comment]
We think this is good to go live, the translations haven't been done yet but the weather values are correctly captured and the weather API works well. 

The next step would be to change the website edit form to allow to edit the new weather values.

**Comment by DavidRoy** [comment]
Closing.  Works well and data captured.  Have raised separate issue for the occurrence editing
