### ISSUE TITLE
eBMS website: add language Bulgarian

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#243]
In the eBMS website, include in the language list, the Bulgarian and in the list of BMS (when someone registers), the Bulgarian BMS 

@DavidRoy @Gary-van-Breda

**Comment by DavidRoy** [comment]
That's now setup - can you check and close the issue if needed?
Are there any other schemes to add?

**Comment by CrisSevilleja** [comment]
Thanks! I think we are missing the Czech Republic and Slovenian BMS, just in case someone wants to use the app.

**Comment by DavidRoy** [comment]
https://butterfly-monitoring.net/czechia-bms
https://butterfly-monitoring.net/slovenia-bms

also created
