### ISSUE TITLE
Problems entering data for one Transect: eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#244]
One recorder has problems entering data to his transect.  The transect name is LLANES (one of the transects migrated from the Spanish platform). 

He enters on the page My visits, and then the Walk Data Entry. He fills all the environmental variables and time and when he clicks on the Next button, it appears a warning message "The data could not be saved" (picture attached). He never continued to the next pages to fill the species and the website stays blocked. 

He tried several times, different browsers and it gives the same error. I tried to do it with him together online watching his screen and there is nothing strange how he did it. His transect looks like right.

More information about the user: 
User name: Javier (1282)
First name: javier
Last name: Gil Vaquero
Indicia Warehouse User ID: 784512

@DavidRoy  @Gary-van-Breda 

![Error_Javier](https://user-images.githubusercontent.com/25052478/83156836-2e2e9500-a103-11ea-9c39-f43ce54a950f.jpg)

**Comment by DavidRoy** [comment]
@Gary-van-Breda could you look at this one as a priority please

**Comment by CrisSevilleja** [comment]
@Gary-van-Breda any news about this issue?

**Comment by Gary-van-Breda** [comment]
The problem was that Javier's Indicia Warehouse User ID=784512 was wrong. I do not know how it was changed, but I have reset the value (clearing it then saving the user) - it is now 272766.
Could Javier try again?

**Comment by CrisSevilleja** [comment]
Solved! thanks
