### ISSUE TITLE
Additional butterfly recording aggregates

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#246]
To add to ABLE Butterflies, id = 251

Addition of recording aggregates of:
Unidentified Blue (within Lycaenidae)
Unidentified Copper (within Lycaenidae)
Unidentified Hairstreak (within Lycaenidae)
Unidentified Heliconians and Fritillaries (within Nymphalidae)
Unidentified Browns, Graylings and Ringlets (within Nymphalidae)
Unidentified Fritillary (within Nymphalidae)
Boloria selene/euphrosyne | Small Pearl-bordered Fritillary/Pearl-bordered Fritillary (within Nymphalidae)
Lasiommata petropolitana/maera | Northern Wall Brown/Large Wall Brown (within Nymphalidae)
Boloria napaea/aquilonaris | Mountain Fritillary/Cranberry Fritillary (within Nymphalidae)

**Comment by johnvanbreda** [comment]
Done
