### ISSUE TITLE
eBMS website: Change Species Search bar position

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#247]
The Species search bar appears at the bottom of the page makes it not easy to find for new users. Could it be possible to place the Searching bar on the top for better visibility?

Issue related to #232 

![Input species data](https://user-images.githubusercontent.com/25052478/83762733-237e7d80-a678-11ea-9021-97e53e1cc3bc.PNG)

**Comment by DavidRoy** [comment]
consider as part of work on walk-input-form2

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site for review.
The urls have been redone on Dev, so use:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new
My Walks and Scheme Walks have been reconfigured to point to this URL

**Comment by Gary-van-Breda** [comment]
@DavidRoy @CrisSevilleja New form deployed to Live, configured so "Add Species" auto is at top of page.
