### ISSUE TITLE
Species list: add the Aggregate species Polyommatus icarus/celina

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#248]
Polyommatus icarus/celina is required for the Iberian Peninsula.

@DavidRoy sorry, I cannot add labels or assign the issue.

**Comment by johnvanbreda** [comment]
@DavidRoy shall I add this?

**Comment by DavidRoy** [comment]
yes please

**Comment by johnvanbreda** [comment]
Done  - it's 466950. I set the country codes to P for Portugal and Spain.

**Comment by kazlauskis** [comment]
I will pull this in with the next app update.

**Comment by CrisSevilleja** [comment]
thank you. I close this issue
