### ISSUE TITLE
Change location_id for loaded samples

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#249]
@Gary-van-Breda 18 samples were imported in error to the wrong location_id.  To correct this is it as simple as below, which would then trigger the necessary work_queue items:

update indicia.samples sa set location_id = 223870, updated_on = now0, updated_by_id = 1
where sa.survey_id = 562
and survey_id = 562
and external_key is not null
and location_id = 228053

**Comment by johnvanbreda** [comment]
Assuming the update is OK for Gary, note that the work_queue items won't be auto-created. You'll want something like:
```sql
insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select distinct 'task_cache_builder_update', 'occurrence', id, 100, 2, now()
from occurrences
where sample_id in (select id from samples where …);

insert into work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select distinct 'task_cache_builder_update', 'sample', id, 100, 2, now()
from samples
where …;
```

**Comment by Gary-van-Breda** [comment]
Are these pure top level samples, or do they have subsamples/occurrences associated with them? (If so we'll need to realign the sub samples to the section location records).
We'll also need to work queue entries for the summary builder...

**Comment by DavidRoy** [comment]
Just pure samples. No sub-samples or occurrences attached

**Comment by DavidRoy** [comment]
@Gary-van-Breda is the logic of this update ok?

**Comment by Gary-van-Breda** [comment]
Yes-ish, but don't need the occurrences cache task as there are none. So in total, do the following...

update indicia.samples set location_id = 223870, updated_on = now0, updated_by_id = 1
where survey_id = 562
and external_key is not null
and location_id = 228053;

delete from indicia.summary_occurrences where location_id = 228053;

insert into indicia.work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select distinct 'task_cache_builder_update', 'sample', id, 100, 2, now()
from indicia.samples
where survey_id = 562
and external_key is not null
and location_id = 223870;

insert into indicia.work_queue(task, entity, record_id, cost_estimate, priority, created_on)
select distinct 'task_summary_builder_sample', 'sample', id, 50, 2, now()
from indicia.samples
where survey_id = 562
and location_id in (223870, 228053);

**Comment by DavidRoy** [comment]
Thanks.  Now done
