### ISSUE TITLE
User account settings

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#25]
Changes needed to user account settings, e.g. ..../user/1/edit

1. Remove 'Recording location' section
2. Remove 'Locality of your expertise' section
3. Remove 'Species groups you have expertise in'
4. Remove 'Surveys you are an expert for'
5. Remove 'Date of birth'
6. Rename 'Default species view' as 'Preferred species list view for transect recording'
7. Add section labelled 'Country/scheme you are part of'.  With a drop-down list of European Countries

**Comment by Gary-van-Breda** [comment]
The Data of Birth field was part of the easy login in previous versions. No longer part of easy login, and not required by anything else, so field deleted.
Do we still want the Under 16 flag? This was also a previous Easy Login field.

**Comment by Gary-van-Breda** [comment]
Actually should really have just disabled the DOB field: I've disabled the other 5, in both the Manage form display and the Manage display

**Comment by DavidRoy** [comment]
Agree.  Neither of DOB nor U16 needed

**Comment by Gary-van-Breda** [comment]
First 5 no longer displayed.
'Default species view' renamed to 'Preferred species list view for transect recording'
New ebms_country_field module added and enabled on the dev site: this creates a "Country/Scheme" field for the user. Field "field_country_scheme" has been enabled for entry and display.
Currently this looks to the warehouse and fetches a list of location ids/names which the user can choose from. Current configuration restricts this location list to the "Country" location type id.

**Comment by Gary-van-Breda** [comment]
U16 also disabled.

**Comment by Gary-van-Breda** [comment]
I have rather assumed that the country/schemes are going to be defined by a location within the warehouse, if only because this is going to make the reporting easier. Is this assumption correct?

**Comment by DavidRoy** [comment]
Yes, to start with we need a layer of all countries of Europe.  Ideally part of the NUTS hierarchy
@johnvanbreda how does this relate to the NUTS layers you've already imported

**Comment by DavidRoy** [comment]
User account settings, not showing countries in drop-down list

**Comment by Gary-van-Breda** [comment]
@DavidRoy : I've set the location type in the module config on the Test system (Admin->Configuration->Indicia integration->EBMS Country Field configuration), and cleared the caches: looks OK to me now.

**Comment by Gary-van-Breda** [comment]
Also done on Live

**Comment by DavidRoy** [comment]
Thanks.  Works well.  Now closing issue
