### ISSUE TITLE
One problem loading transects on ButterflyCount

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#250]
Saba González Lorenzo, (https://butterfly-monitoring.net/user/1392) Indicia Warehouse User ID: 246336 cannot see her transects on the app. 

I asked for screenshots and she has a warning error in the transect window. I asked her to log out and log in again and she got the same error message when she tries to refresh the transects (picture 4).

She is recording the transect called CALDAS DE REIS, one of the Spanish transects migrated directly to the website. She did several 15-min counts, sent to the website and they don't appear on the website. There is a bug in her account not doing well the connection between the website and the app. 

It looks like similar to the error before with Xavi and Fernando, but the error was fixed. 
Thanks
@kazlauskis @DavidRoy 

![pic2](https://user-images.githubusercontent.com/25052478/83949664-76e1fe80-a825-11ea-87a8-e65f0b1b0a4b.png)
![pic3](https://user-images.githubusercontent.com/25052478/83949668-7ba6b280-a825-11ea-82eb-c9dac96d5549.png)
![pic1](https://user-images.githubusercontent.com/25052478/83949659-6a5da600-a825-11ea-82e2-734551399c92.png)

**Comment by DavidRoy** [comment]
@CrisSevilleja do you know whether there has been a password change for this user?  The two need to be kept in synch.

@kazlauskis any other ideas about this problem?

**Comment by kazlauskis** [comment]
I have tried to pull in her transects in to the app and it works fine. I think she has to re-login and try  it again.

**Comment by CrisSevilleja** [comment]
I asked her to try to re-login and try again. Thanks

**Comment by CrisSevilleja** [comment]
She continues with the same error message "Could not find/authenticate user" in the transect window. She re-logined and nothing changed, although she discarded local data, so I am not sure if the 15-min counts were really sent to the website. At least there is one she recently did (picture)
 She has the version 1.6.1

![15-min count Saba](https://user-images.githubusercontent.com/25052478/84127796-fd722800-aa3f-11ea-817b-29d9ce8442a4.png)

**Comment by kazlauskis** [comment]
Fixed it now, she should try to re-login again using her email. This links to #221 where special characters in username/password are not allowed. Reopen this if she still has any problems.
