### ISSUE TITLE
Additional sample attributes to 'my records' report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#251]
https://butterfly-monitoring.net/elastic/my-records

The app now collects weather information for 15 minute count samples.  These need to be available via the explore report, under the samples tab.  Also included within sample downloads

All attributes: http://warehouse1.indicia.org.uk/index.php/attribute_by_survey/565?type=sample

**Comment by johnvanbreda** [comment]
Done

**Comment by DavidRoy** [comment]
Looks good but the edit link on the samples is blank

**Comment by johnvanbreda** [comment]
This is now fixed.
