### ISSUE TITLE
Record edit form should include all attributes for editing

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#252]
https://butterfly-monitoring.net/enter-app-record?occurrence_id=14188823&sample_id=

Link for my-records report-occurrence tab to edit a record should goto a form to allow editing of all information.  This should include sample attributes for weather conditions.
http://warehouse1.indicia.org.uk/index.php/attribute_by_survey/565?type=sample

Currently it does not include the weather conditions

**Comment by johnvanbreda** [comment]
Done
