### ISSUE TITLE
ButterflyCount: Improve the app understanding

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#256]
App users asked me similar doubts about the app functions. It would be good to improve the app's understanding with simple actions. 

We talked to include pop-ups when opening the app the first times. I would add them for:

- [x]  _How to remove a record_ 
   show a popup after more than 2 pending records have been added to the surveys page list. Show it once only when the user navigates to the pending survey page. OR show a message under surveys list `To delete a survey swipe it to the left.`
    
- [x] _When finishing a 15-min count, remember to check if the recording area is correct before sending the record_ (the route could have some "jumps") 
   after the user has finished the 'draft' and opened the record to upload, show a warning message above the Area button.

- [x] _Highlight to read the "Guide" and "help"_ 
  after the user has installed the app and finished the onboarding screens, show a popup with a tip to see the usage guide and help pages in the app menu

- [x] _Include the link to the app Guidelines with screenshots_ https://butterfly-monitoring.net/ebms-app 
(somewhere in the Guide page)

- [x] Add a note to use the plus-button in the empty surveys page. Like this
![Screenshot 2020-07-01 at 11.29.13.png](https://zube.io/files/biologicalrecordscentre/47d5f9116054af511d9115ec36cdc0fe-screenshot-2020-07-01-at-11-29-13.png)

- [x] Show an info alert saying 'Tip: adding species' 'You can bulk copy your previous species lists by long-pressing the Add Species button.'
  show it only once when previous survey exists and there are new species to copy.

- [x] Inform the user to upload a finished survey. Show a message below any unfinished surveys.

**Comment by kazlauskis** [comment]
I agree that we could make it more informative. The help page on the app has some information, if you'd like to expand it then I would be happy to incorporate your texts with the next app release. It would be best if the guidelines that are currently on the website would also be somehow added to the app itself but for now adding a link would be easy to do.
