### ISSUE TITLE
ButterflyCount: allow extra information (e.g. stage, photo) for butterfly records in eBMS transect option

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#257]
@kazlauskis @DavidRoy 
I wonder if it would be possible to add the option of Edit Occurrence of the butterfly records (adding pictures, comments, stage...) to the eBMS transect on the app like it is possible to do for the 15-min counts. 

Some transect recorders asked me if it could be possible to add that option. If the action to apply it is not complicated, I would include it. What do you think?

**Comment by DavidRoy** [comment]
This would be a useful addition.  It would also require some changes to the website to enable the records to be viewed/edited once submitted.
I'll discuss the requirement with @Gary-van-Breda

**Comment by DavidRoy** [comment]
@CrisSevilleja just to confirm that we'd only expect one life stage per species transect walk so will build this in with a species only appearing once on the list

**Comment by CrisSevilleja** [comment]
@DavidRoy okay. Thanks for informing me

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site for review: configured on Hungary branch only: you will need to create/edit a walk on a Hungarian location to see.
Added extra stage attribute for this testing case; photos and comments also enabled.

The urls have been redone on Dev, so use:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new
My Walks and Scheme Walks have been reconfigured to point to this URL

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you switch the stage term to ID = 293 (Butterfly life stage), e.g Adults, Larvae, Pupae, Eggs
This can be used for both butterflies and moths

**Comment by Gary-van-Breda** [comment]
Done.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : the Walk data entry page (2) has been deployed to live, using the Butterfly life stage, initially configured for Hungary only.

**Comment by kazlauskis** [comment]
The app transect occurrences have stage, comment and photo options now. Can this be closed then or does the website still need some work?
