### ISSUE TITLE
Moth list data fix

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#259]
@johnvanbreda can you do an urgent data fix for ABLE so that the ButterflyCount mobile app uses the correct species lists.

For the attached list of taxa_taxon_list_ids the following actions are needed:
- update taxon_group_id = 104 (they are all currently id = 114)
- update allow_data_entry to false

These are all taxa on list 260 which are butterflies.  We use list id 251 for the butterfly list.  260 should be restricted to moths
[ABLE Moths Data fix.txt](https://github.com/BiologicalRecordsCentre/ABLE/files/4826717/ABLE.Moths.Data.fix.txt)

**Comment by johnvanbreda** [comment]
I've changed the IDs as above, but have discovered another issue with this list. We use the external_key as a unique identifier for the taxonomic concept (i.e. all name variants for a taxon share the external key) and the search_code as a unique identifier for the name itself. In the taxa which were added last week, the search code of all the names is set to the same as the external key, so we have no unique ID for each name that Elasticsearch indexing can use. I'll need to generate new search codes for all the synonyms and common names added, then force all data recorded against this list to update in Elasticsearch.

**Comment by DavidRoy** [comment]
Thanks John
@kazlauskis I don't think this remaining issue stops you from updating the app

**Comment by johnvanbreda** [comment]
@DavidRoy there seem to be > 300 other butterflies on the moths list that were not on the above list. The following query illustrates this:
```sql
-- This query grabs the taxon meaning ID for Papilionidae in the moths list.
select taxon_meaning_id from cache_Taxa_Taxon_lists 
where taxon in ('Papilionoidea') -- butterflies
and taxon_list_id=260 -- moths list
-- Taxon_meaning_id=208572

-- Use this to query the paths table to find all butterflies that are still in the moths list which were not set to allow_data_entry=false.
select cttl.id, cttl.taxon, cts.path, cttl.taxon_group
from cache_taxa_taxon_lists cttl
join cache_taxon_paths cts on cts.taxon_meaning_id=cttl.taxon_meaning_id and cts.path && ARRAY[208572] 
where cttl.taxon_list_id=260
and cttl.allow_data_entry=true
```

This query demonstrates that there are quite a few butterflies on list 260 which are not represented on list 251:
```sql
select cttl.id, cttl.cache_created_on, cttl.taxon, cts.path, cttl.taxon_group
from cache_taxa_taxon_lists cttl
join cache_taxon_paths cts on cts.taxon_meaning_id=cttl.taxon_meaning_id and cts.path && ARRAY[208572] 
where cttl.taxon_list_id=260
and cttl.allow_data_entry=true
```

Questions:
1) Should the butterflies on list 260 that are not on list 251 be moved across (or duplicated) into list 251? This may include those that were already set to allow_data_entry=false.
2) Should any remaining butterflies on list 260 which are already on list 251 be moved into taxon group 104 and allow data entry set to false?

**Comment by DavidRoy** [comment]
Thanks.  Two actions needed.
- All butterflies on list 260 should have taxon_group set to id=104 and set to allow_data_entry=false

The 251 list is well-curated and the definite list for Europe.  Butterfly additions on 260 are either additional common names or synonyms.  I will review them to see whether it is worth incorporating.

**Comment by johnvanbreda** [comment]
Ok, thanks. That's done.

**Comment by johnvanbreda** [comment]
RE-opening as this part of the issue is not yet resolved and the Elastic search species lookups will need to be updated to reflect changes: "We use the external_key as a unique identifier for the taxonomic concept (i.e. all name variants for a taxon share the external key) and the search_code as a unique identifier for the name itself. In the taxa which were added last week, the search code of all the names is set to the same as the external key, so we have no unique ID for each name that Elasticsearch indexing can use. I'll need to generate new search codes for all the synonyms and common names added, then force all data recorded against this list to update in Elasticsearch."

**Comment by johnvanbreda** [comment]
I've repaired the search codes by generating new ones using the following script, but still need to update the ES lookup files:

```sql
drop table if exists to_fix;

select ttl.id, ttl.taxon_id, 
  'EBMSM00000000' || (row_number() OVER () + 15016)::text as new_search_code
into temporary to_fix
from taxa_taxon_lists ttl
join taxa t on t.id=ttl.taxon_id
where ttl.taxon_list_id=260
and t.search_code=t.external_key and ttl.preferred=false
order by new_search_code;

update taxa t set search_code=new_search_code, updated_by_id=3, updated_on=now()
from to_fix tf
where tf.taxon_id=t.id;
```

**Comment by johnvanbreda** [comment]
ES lookups now updated.
