### ISSUE TITLE
ButterflyCount - improve filtering of species list by country

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#260]
Now the app has a long species list, to avoid users being swamped by names.

Enable option for the full list or a list restricted by country

@kazlauskis to indicate scale or task

**Comment by DavidRoy** [comment]
to clarify, this issue is for the species list in the recording functionality (transects and 15 minute counts)

**Comment by DavidRoy** [comment]
@JimBacon are you able to pick this up?

**Comment by DavidRoy** [comment]
agreed!

**Comment by JimBacon** [comment]
@kazlauskis I have updated `ebms_app_species_list` to include the additional information you requested.

I did what you asked for but `taxa_list_for_app` has changed since you raised the issue so maybe this needs additional work.

**Comment by kazlauskis** [comment]
@JimBacon This is great! The app only requires one report now, so the `taxa_list_for_app` can be deprecated. I have done the work on the app now. 

There is one thing you might want to check. When fetching moths, I also get some butterflies, like this:
```
 {
            "taxa_taxon_list_id": "455840",
            "preferred_taxa_taxon_list_id": "455839",
            "taxon_meaning_id": "217417",
            "taxon_id": "408507",
            "external_key": "EBMSM0000000009607",
            "taxon": "Tagpfauenauge",
            "preferred_taxon": "Aglais io",
            "attributes": null,
            "language_iso": "deu"
        }
```

2.

**Comment by JimBacon** [comment]
There are about a thousand butterfly names in the moth list. 
It relates to issue https://github.com/BiologicalRecordsCentre/ABLE/issues/259
I don't know why they weren't deleted.
Would you like me to add a filter on `allow_data_entry = true` which will exclude them from the report results?
Such a filter is present in the `taxa_list_for_app` report.

I thought you might not be able to determine the day-flying moths from the updated report. Is that not an issue?

**Comment by kazlauskis** [comment]
> Would you like me to add a filter on allow_data_entry = true which will exclude them from the report results?

Yes, please. If some taxa entries shouldn't be used for recording in the app then we should exclude these from the report.

>I thought you might not be able to determine the day-flying moths from the updated report. Is that not an issue?

The current report returns all the attributes for the taxa, including the country codes and the day-flying status. This and other of your improvements now make this report to be the only one we currently require 🎉

**Comment by JimBacon** [comment]
Okay, there should be no more butterflies appearing in the moth list for you now.

Day-active is a boolean but the report assumes all attributes are of the termlist type, which is why I expected a problem. It is returning `Day-active=Dominant` as true is stored as an integer value of 1 and 'Dominant' is the term with id=1. It's the wrong value but you get the right meaning. I don't want to 'fix' it and break things for you.

**Comment by kazlauskis** [comment]
Thanks, all done then!
