### ISSUE TITLE
Website: section 2 duplicated in transect EBMS:Portugal:38

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#262]
The transect Parque Ambiental de Santa Margarida in Portugal has the Section 2 duplicated (EBMS:Portugal:38)

@DavidRoy @johnvanbreda could you remove one of Sections 2? Thanks

![section duplication-  PT 15 May](https://user-images.githubusercontent.com/25052478/85985267-c9f53e80-b9ea-11ea-8dd0-c47d75d165ef.PNG)

**Comment by DavidRoy** [comment]
One for @Gary-van-Breda

**Comment by CrisSevilleja** [comment]
This issue is still unresolved. Please, could be possible to do it? @Gary-van-Breda 

Thank you

**Comment by CrisSevilleja** [comment]
@Gary-van-Breda @DavidRoy the transect **Parque Ambiental de Santa Margarida** (Portugal) continues with Section 2 duplicated. 

Another transect, **Puertos de la Bachota** (Spain) has a duplication in Section 2. I don't know how to resolve that and volunteers get confused when they see the duplication and don't know where to add the data. 

Can you resolve this issue, please?

**Comment by Gary-van-Breda** [comment]
I have addressed Parque Ambiental de Santa Margarida.

**Comment by Gary-van-Breda** [comment]
**Puertos de la Bachota** also resolved.
@CrisSevilleja : can you check you are happy?

**Comment by CrisSevilleja** [comment]
Yes, now everything is correct. Thanks
