### ISSUE TITLE
Keep the app awake

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#263]
It would be nice if the app could keep the phone awake >> the app is really great but one of the biggest hindrance when working with lots of species and count numbers (i.e. you should often catch and identify confusion species esp. when day-flying geometrids are also around) that the phone keeps getting locked >> of course, i can change it in the setting but the bulk of the volunteer users wouldn't and sometimes cannot do this.

Implementation: maybe use `https://ionicframework.com/docs/native/insomnia`

**Comment by CrisSevilleja** [comment]
@kazlauskis issue done, you can close it
