### ISSUE TITLE
Incorrect values stored for timed counts data

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/ABLE#270]
Whilst working on downloads, I noted that sample_attribute_values stored for sample_attribute_id=1393 (Reliability) often have the int_value set to 222. This attribute is a lookup list linked to termlist 837 which supports the following:
16592	(3)
16591	(2)
16590	(1)
I'm not sure why the value 222 is being stored - is this an incorrect value in the app?

**Comment by kazlauskis** [comment]
I have looked this up and couldn't see why the 222 was sent. The app uses the correct values but there might be a bug somewhere. Do you have some sample Ids I could look up that has this issue?

**Comment by johnvanbreda** [comment]
The sample ID I spotted was 8906521 but looking in the sample_attribute_values table it seems widespread. The most recent is 9044926.

**Comment by Gary-van-Breda** [comment]
If I remember correctly, this is an issue with the main site and/od data migration, not the App

**Comment by kazlauskis** [comment]
Would you still like me to investigate this or can I leave it to you guys?

**Comment by DavidRoy** [comment]
@Gary-van-Breda the samples.external_key and occurrences.external_key fields are empty for the sample IDs given by john as examples.  Also, the location name is not one that is part of the data migration.  Therefore, I conclude this bug is on the walk_input form on the website?

**Comment by Gary-van-Breda** [comment]
Not necessarily. I can't see the attribute being included in the Post from the form on any of the non-Luxembourg walks.

When this site was hosted on warehouse2, the default value for Reliability was set to "1", and the term id was 222. I believe the default value being stored in warehouse1 is also 222, and that this was not translated properly on migration into warehouse1 (this is the migration of the attribute definition, not the attribute values).

@johnvanbreda : could you look at the default value for the reliability (sample attribute_id 1393) held in the database, for survey_id=562? As 222 is not a valid value in the current termlist, it is not showing in the warehouse front end.

If this is the case, I suggest:

- we resave the survey level defaults for the reliability, setting the default value to blank. If we don't do this, the other countries who don't use the reliability will have theirs set.
- We can then delete all the 222 reliability attribute values: these will have been set by the warehouse when no reliability value was provided.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : can you confirm you mean timed counts (in the Issue title)? I think the Reliability is only used on the EBMS Transects survey.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda you are correct on 2 fronts - I got the survey name wrong (which stemmed from a muddle elsewhere with survey IDs) and the default value was set to 222. I've run the following script which I believe closes this issue including updating the cache and ES data:
```sql

update sample_attributes_websites set default_int_value=null where sample_attribute_id=1393 and restrict_to_survey_id=562;

select sample_id into temporary to_fix from sample_attribute_values where sample_attribute_id=1393 and int_value=222;

delete from sample_attribute_values where sample_attribute_id=1393 and int_value=222;

insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_attrs_sample', 'sample', sample_id, null, 30, 2, now()
from to_fix;
```
