### ISSUE TITLE
ButterflyCount - Ringlet missing from species list?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#273]
I can't work out why the taxon name 'Ringlet' is missing from the 15 minute list.  See
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/432558
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/434490

**Comment by kazlauskis** [comment]
Fixed it now. The issue was that there were many Ringlets all sorted alphabetically and results caped to 20 species (for performance), placing the African Ringlet and others above. We'll release this fix with the next update this week.

**Comment by DavidRoy** [comment]
Thanks.  Is this fixed for other name searches as there will likely be similar cases with returns >20?

**Comment by kazlauskis** [comment]
Yes, this should work for other names now too. We have increased the limit to 200 and placing single-word names above others too.
