### ISSUE TITLE
Import Swedish fixed point sites 

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#274]
Actions required:
1. New location_type  = 'Fixed point site'
2. New survey 'Fixed points' for website = ABLE
3. Import existing locations (file sent by email)
4.	Sample attributes (mirrored from ‘Transects’ and ‘Mobile App Timed Counts’
•	Start Time [id=1385]
•	End Time [id=1386] 
•	% Sun [id=1387]
•	% Cloud [id=1457]
•	Temperature [id=1388]
•	Wind Direction [id=1389]
•	Wind Speed [id=1390]

5.	Occurrence attributes
•	Abundance count [id=780]
•	Life stage [id=293]

**Comment by johnvanbreda** [comment]
@DavidRoy will all the data entry be done via the app?

**Comment by DavidRoy** [comment]
yes

**Comment by johnvanbreda** [comment]
I've imported the locations (location type ID=17785, name=ABLE fixed point site).
I've set up the survey (ID 589).
I've added the attributes pending review from Lars.

**Comment by DavidRoy** [comment]
Thanks.  Lars agreed with the attributes.  We may need to extend reports, editing forms and downloads to accommodate data for these sites but will raise those as separate issues as needed.
