### ISSUE TITLE
walk-data-entry-2: prevent end time being before start time

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#277]
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-2

It should not be possible to enter an end time that is before a start time.  
See example
![problem_start-time_end-time](https://user-images.githubusercontent.com/2699478/86781744-26dd9e00-c056-11ea-9353-c4fee9310ee7.jpg)

**Comment by Gary-van-Breda** [comment]
Due to the nature of how the Start and End time checks are coded, we can't add this check to the new walk form until we have the node number on Live. However, I have added the check to the old form, and deployed it to Dev for review: see https://dev-butterfly-monitoring.pantheonsite.io/node/36/

**Comment by Gary-van-Breda** [comment]
I've revisited this, and pulled the existing format checks (which were in a node.js file) and the new check into the form JS.
Deployed to Dev as part of the new walk data entry form:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new

**Comment by DavidRoy** [comment]
I'm still able to enter a start time later than end time?
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new?location_type_id=777&date=13/11/2020&sample_id=9303326

**Comment by Gary-van-Breda** [comment]
Caches cleared: it is working now...

**Comment by DavidRoy** [comment]
Thanks
