### ISSUE TITLE
walk-data-entry-2: any options to speed up page?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#278]
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-2

Possible problem with being on dev and maybe on temporary but the page was slow when tested.  Is there room for improvement?
![problem_slow_script](https://user-images.githubusercontent.com/2699478/86781866-59879680-c056-11ea-9df5-ca983041521b.jpg)

**Comment by Gary-van-Breda** [comment]
I have done some tweaks on this page to speed it up a bit.
I've disabled the Full species list as this is I think too big to be practical.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Walk Data Entry page (2) deployed to Live.
