### ISSUE TITLE
walk-data-entry-2: photo upload size limit

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#279]
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-2

The sample photo upload functionality is currently missing from the form.  When re-instated, it needs to provide information on permitted file size.

![problem_pic_too_large](https://user-images.githubusercontent.com/2699478/86783568-64432b00-c058-11ea-8e9f-01bd0a7d140f.jpg)
![problem_pic_too_large_2](https://user-images.githubusercontent.com/2699478/86783573-66a58500-c058-11ea-8414-8f580c5e0765.jpg)

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site for review.
The urls have been redone on Dev, so use:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new

**Comment by DavidRoy** [comment]
We still have this issue with large image files?
![problem_pic_upload](https://user-images.githubusercontent.com/2699478/113301549-0a297a80-92f7-11eb-98ac-b0a413e2cb97.jpg)
