### ISSUE TITLE
Page footer required for www.butterfly-monitoring.net

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#28]
Website footer should include a logo banner (similar to https://www.dipterists.org.uk/) with BCE and CEH logos.
Text below should read:
Copyright © 2019 Butterfly Conservation Europe and the Centre for Ecology & Hydrology. 

Below copyright text should be a hyperlink to the privacy notice (..\privacy-notice. Privacy Notice.

**Comment by BirenRathod** [comment]
@DavidRoy 

This is done.
