### ISSUE TITLE
walk-data-entry-2: Dropdown should show reliability score descriptions

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#280]
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-2

Drop-down list currently not populated
![problem_cloud_reliability](https://user-images.githubusercontent.com/2699478/86783737-9e143180-c058-11ea-8ce1-414a27fdbe5c.jpg)

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site for review.
The urls have been redone on Dev, so use:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new

**Comment by DavidRoy** [comment]
Reliability drop-down not showing? e.g. 
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new?sample_id=9303254
![wde new](https://user-images.githubusercontent.com/2699478/98265615-31b32b80-1f81-11eb-92d8-7daef7cfbca9.png)

**Comment by Gary-van-Breda** [comment]
Sorry: Reliability is currently enabled for Luxembourg transects only on this page: @DavidRoy do you want to enable across the board?

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Walk Data Entry page (2) deployed to Live. (Reliability is enabled for all schemes.)
