### ISSUE TITLE
walk-data-entry-2: improve name search

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#281]
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-2

The search does not allow using the species part of the name epiphet, e.g. typing 'rhamni' to find 'Gonepteryx rhamni'
Also, the option to search 3+2 in names, e.g 'Gon rh'

![problem_spp_entry_1](https://user-images.githubusercontent.com/2699478/86785066-20e9bc00-c05a-11ea-85d3-2482596c8dc9.jpg)

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site for review. 
The urls have been redone on Dev, so use:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry

**Comment by DavidRoy** [comment]
Thanks
