### ISSUE TITLE
walk-data-entry-2: species name should be filtered by language

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#282]
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-2

Currently the species name list includes the latin name plus Latin+common names in multiple languages.  The search should be specific to country/language
![problem_spp_entry_2](https://user-images.githubusercontent.com/2699478/86785373-76be6400-c05a-11ea-8dba-fa9aa5294548.jpg)

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site for review.
The urls have been redone on Dev, so use:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new

**Comment by DavidRoy** [comment]
Thanks
