### ISSUE TITLE
walk-data-entry-2: tidy up visit information page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#283]
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-2

1. Time entry should be in 24HR clock format as used in most of Europe.  The entry field heading and help text/error messages should make this clear
2. % Sun currently has a value 'NaN' in field when form first loaded. Should be blank.
3. Form to be tidied up to follow approach for UKBMS
![ukbms walks](https://user-images.githubusercontent.com/2699478/86786522-057fb080-c05c-11ea-865c-5306f62977d3.png)

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site for review.
The urls have been redone on Dev, so use:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new

**Comment by DavidRoy** [comment]
Looks good, thanks

**Comment by Gary-van-Breda** [comment]
I've revisited this, and modified the form to allow override of the sample attribute labels.
Deployed to Dev as part of the new walk data entry form, and configured to add "(HH:MM)" to the end of the start and end time labels:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new
