### ISSUE TITLE
walk-data-entry-2: add option for comments attached to occurrences

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#284]
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-2

Required for the extended (long) version of the form.

**Comment by DavidRoy** [comment]
Linked to #257 requirement for additional occurrence information

**Comment by Gary-van-Breda** [comment]
@johnvanbreda or @BirenRathod : there is a new report in indicia-reports : "projects/ukbms/ukbms_occurrences_list_for_parent_sample.xml"
Could I have this deployed to the devwarehouse?

**Comment by johnvanbreda** [comment]
@Gary-van-Breda I've pulled brc_reports on the dev warehouse.

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site for review: configured on Hungary branch only: you will need to create/edit a walk on a Hungarian location to see.

The urls have been redone on Dev, so use:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new
My Walks and Scheme Walks have been reconfigured to point to this URL

**Comment by DavidRoy** [comment]
Am unable to enter comments on the form as the 'comments' button is not clickable.  It shows a red warning symbol when hovering over...
![wde new](https://user-images.githubusercontent.com/2699478/98265057-81ddbe00-1f80-11eb-8274-d3406c1fb744.png)

**Comment by Gary-van-Breda** [comment]
Bug fix applied to Dev: note can only add images/comments when an attribute value has been added - i.e. the occurrence has already been created.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Walk Data Entry page (2) deployed to Live. Occurrence comments initially configured for Hungary only.
