### ISSUE TITLE
Downloads - transect visit report improvements

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#288]
https://butterfly-monitoring.net/downloads
![visit download](https://user-images.githubusercontent.com/2699478/87061215-60074100-c203-11ea-8f30-a106b6a5e768.png)

To help joining with count (occurrence downloads) and site details, add [Location.id] labelled as Transect ID

For consistency, rename 'Site name' as 'Transect Name'
rename 'Transect sample ID' as 'Transect Sample ID'

**Comment by johnvanbreda** [comment]
Done
