### ISSUE TITLE
menu changes

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#29]
Changes required:
1. When not logged in, there should be a 'Log in' menu link on the right side of the menu
2. When logged in, there should be a 'My Account' menu link on the right side of the menu.  This should have two sub-menus of 'Edit' and 'Log out'

3. Remove 'Home' top menu item. This is not needed as the logo will link to the home page
4. Move 'ABLE' to top-level menu item. Menu items should be 'My data', 'Partners', 'ABLE', 'Projects'

**Comment by BirenRathod** [comment]
@DavidRoy 
Above changes have been done.

**Comment by DavidRoy** [comment]
thanks
