### ISSUE TITLE
Downloads - Site Details report improvements

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#290]
https://butterfly-monitoring.net/downloads
![visit download](https://user-images.githubusercontent.com/2699478/87064453-abbbe980-c207-11ea-8d45-e4438ff62119.png)

rename 'Site ID' as 'Transect ID'
rename 'Site Name' as 'Transect Name'
rename 'Site Code' as 'Transect Code'
rename 'SRef' as 'Spatial Reference'
rename 'System' as 'Spatial Reference System'
rename 'No. of sections' as 'No. of Sections'

Delete field 'Country'
Delete field 'Site Type'

**Comment by johnvanbreda** [comment]
Done
