### ISSUE TITLE
Downloads - Section Details report improvements

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#291]
https://butterfly-monitoring.net/downloads
![count download](https://user-images.githubusercontent.com/2699478/87065124-8a0f3200-c208-11ea-9f98-f9b490f08469.png)

rename 'Site ID' as 'Transect ID'
rename 'Site Name' as 'Transect Name'
rename 'Site Code' as 'Transect Code'
rename 'SiteRef' as 'Transect Spatial Reference'
rename 'System' as 'Spatial Reference System'
rename 'Section ID' as 'Transect Section ID'
rename 'Section Name' as 'Transect Section Name'
rename 'Section Code' as 'Transect Section Code Number'
rename 'SectionRef' as 'Transect Section Spatial Reference'
rename 'Unique Section Code' as 'Transect Section Code'

Delete these fields which repeat fields in Site download:
Country
No. of sections
Overall Length (m)
Transect Width (m) term ID
Transect Width (m) term
Sensitive
Principal Habitat term ID
Principal Habitat term
2nd Habitat term ID
2nd Habitat term
Principal Land Tenure term ID
Principal Land Tenure term
2nd Land Tenure term ID
2nd Land Tenure term
Principal Land Management term ID
Principal Land Management term
2nd Land Management term ID
2nd Land Management term
Notes on habitat, land management and   tenure
Section Length (m)
Linear habitat term ID
Linear habitat term
Primary Habitat Present term ID
Primary Habitat Present term
2nd Habitat Present term ID
2nd Habitat Present term
Primary Land Management Present term ID
Primary Land Management Present term
2nd Land Management Present term ID
2nd Land Management Present term
Notes on Land use and management

**Comment by johnvanbreda** [comment]
Done, but I've not deleted the following columns pending confirmation, as I believe these are specific to the transect sections and therefore are not on the sites report:
Section Length (m)
Linear habitat term ID
Linear habitat term
Primary Habitat Present term ID
Primary Habitat Present term
2nd Habitat Present term ID
2nd Habitat Present term
Primary Land Management Present term ID
Primary Land Management Present term
2nd Land Management Present term ID
2nd Land Management Present term
Notes on Land use and management

@DavidRoy can you confirm please?

**Comment by DavidRoy** [comment]
You are right to keep these columns!  My mistake in haste.
