### ISSUE TITLE
Fix duplication issue when importing data

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#296]
There is a duplication issue of counts, caused by imports of data for Spain.  There are either 2 or 3 duplicates.   The simplest way to resolve this is to delete the duplicates and retain the first occurrence (and associated occurrence attributes).

The sql to identify the duplicates is:
```
select location_id, sample_id, o.external_key, count(*) n
from occurrences o, samples s
where o.sample_id = s.id 
and website_id = 118
and o.external_key is not null
group by location_id, sample_id, o.external_key
having count(*) > 1
order by n desc
```

returns 10683 rows 

@Gary-van-Breda can you make this the top priority task for ABLE

**Comment by Gary-van-Breda** [comment]
@DavidRoy : I've run an update against the database for the Spanish data : can you rerun the query to see if there are still outstanding issues - if possible attach the output, thanks.
