### ISSUE TITLE
ButterflyCount: back button not working

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#297]
A report of the back button not working on Android device - Xiaomi Mi A1 phone with Lineage OS 17.1 (Android 10).

**Comment by kazlauskis** [comment]
Android native back button or the app back button on the header?

**Comment by DavidRoy** [comment]
native android button is not working, while the one in the app is fine.

**Comment by kazlauskis** [comment]
Yes, that's disabled on purpose. None of the other apps we have done has it enabled either. The reason is that this keeps things much more simple. We have it as a feature request in another ticket so I am closing this one now. #211
