### ISSUE TITLE
Extend Indicia butterfly-monitoring scheme input system to include photo capture/display

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#3]
One potentially quick solution and one possibly expensive solution.

The quick solution would just be to allow uploading of photos for each walk (either via the Walk data entry screen, or by adding another tab after butterflies, moths, odonata, others, images). This would be quick, and it would also allow recorders to to add photos of temporal habitat condition etc, but it wouldn't allow photos to be attached to individual records/species.

Another solution would be to provide recorders with a list of their records (in similar format to iRecord, but without the map) which they could then filter, review and edit (add photos) individually. Effectively providing a partial iRecord interface within the UKBMS website (new tab - My Records).

**Comment by Gary-van-Breda** [comment]
Deployed to Dev site for review: 
Walk level images included at bottom of first page in walk data entry, configured all branches.
See #257 for details on Occurrence level images.

The urls have been redone on Dev, so use:
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new
My Walks and Scheme Walks have been reconfigured to point to this URL

**Comment by DavidRoy** [comment]
Unable to add photo as 'Images' button is not clickable.  Shows red warning symbol.  Using Chrome
![wde new](https://user-images.githubusercontent.com/2699478/98265169-adf93f00-1f80-11eb-8573-a54a59a6a391.png)

**Comment by Gary-van-Breda** [comment]
Bug fix applied to Dev: note can only add images/comments when an attribute value has been added - i.e. the occurrence has already been created.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Walk data entry page (2) deployed to Live.
