### ISSUE TITLE
Update butterfly list to include Pieris napi/rapae aggregate

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#301]
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/473307

**Comment by DavidRoy** [comment]
Could you update the species list when you are next updating the app

**Comment by kazlauskis** [comment]
I should add this only to the species recording functionality - not to the species guide, is that correct?

**Comment by DavidRoy** [comment]
yes, aggregates are just for the recording lists
