### ISSUE TITLE
ButterflyCount: Update Slovenian language into the app

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#304]
@kazlauskis  
Slovenian language has been 100% translated on Transifex and the translator would like to see the translation in the app in order to edit it if there are some mistakes. 

Thank you

**Comment by kazlauskis** [comment]
Thanks, with the next app version we could add the language and let the translator check it before the public release.

**Comment by CrisSevilleja** [comment]
Thanks @kazlauskis when are you planning to do the next app version?

**Comment by kazlauskis** [comment]
It depends on when I can finish my current projects but if nothing urgent comes up then I should be able to produce the web app for the translator within the next 2 weeks if that's OK?

**Comment by CrisSevilleja** [comment]
Yes, 2 weeks is okay for me. I only wanted to have an approximation date to say to the translator. 
Thanks!

**Comment by kazlauskis** [comment]
Heya, I have added the Slovenian to the app now. It is available now in the web demo: https://butterflies.app.flumens.io/demo.html

**Comment by DavidRoy** [comment]
@kazlauskis do you know when the app update will go live with Slovenian?

**Comment by kazlauskis** [comment]
Early next week I will spend 2 days working on the app and will push a Beta release for another week of testing. So if all is good then the Slovenian language should appear within 1-2 weeks time.
