### ISSUE TITLE
Urgent- one volunteer cannot create new transects on the website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#305]
@DavidRoy  A Spanish volunteer (regional coordinator) nachoarce77 Indicia Warehouse User ID246551 cannot create new transects since Friday and has a warning message (picture). I had the same problem last Friday with another user, but today everything works well for me but not with Nacho's account.

Could you resolve this issue soon? 
![image](https://user-images.githubusercontent.com/25052478/93740789-7b230380-fbeb-11ea-9e7b-0e0ca8c15607.png)

**Comment by DavidRoy** [comment]
@Gary-van-Breda @johnvanbreda 
Any clues in the error message to resolve this?

**Comment by Gary-van-Breda** [comment]
This error occurs when the number of sections is zero: can they try to re-enter the new transect, but add a positive number for the number of sections.

**Comment by Gary-van-Breda** [comment]
I have bumped the minimum value for the number of sections up from zero to 1, and cleared the caches.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda the line of code with the error has the following:
```php
 } else throw(1);
```

Why does this throw a number, rather than an exception object?

**Comment by Gary-van-Breda** [comment]
This is a reminent of the development, when I absolutely wanted it to drop out in this scenario, and not be caught. I'll review the code.

**Comment by CrisSevilleja** [comment]
https://butterfly-monitoring.net/user/1395 
This user continues not able to add new transects.

**Comment by Gary-van-Breda** [comment]
An issue was found in code where it was using a translated value for the attribute caption when looking up the attribute for the number of sections. This has now been corrected, and deployed to Live. As a test, I created a site whilst masqueraded in as Mr de Acre, whilst the language was set to Spanish, and it worked OK. I have deleted the test site.

I think this is now resolved: can you confirm with the user?

**Comment by CrisSevilleja** [comment]
Yes, I can confirm the user can create and edit his transects. Thanks
