### ISSUE TITLE
Transect sample download - missing information

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#306]
https://butterfly-monitoring.net/downloads

Reported by https://butterfly-monitoring.net/users/xavier-mestdagh

These may be legacy issues as Luxembourg was an early adopter of the eBMS online but problems reported = 

Downloading sample(visit) information for transects (zipped csv) lacks information.
1. "Transect ID" is missing for all records
2. "Transect Name" is missing for some records
3. For weather-related fields, null values should be set to 'not recorded'
4. In the same export, some values of the field "Output sref." are preceding by a "~"  ex: "~ 50.135N 5.979E". Why are these values approximate?

![xav](https://user-images.githubusercontent.com/2699478/94652416-e35f9c80-02f1-11eb-8f25-fdce56c53c69.gif)

**Comment by johnvanbreda** [comment]
There is definitely a legacy issue for the first 20 records in this download so I'll only report on issues that I could find in the later data.
1. I've fixed this - a configuration mistake.
2. I think this is only an issue in the first 20 rows where the data are wrong.
3. The output is the data as it is stored. The app doesn't seem to be storing not recorded for these, so nothing will appear in the report.
4. The output is a summary of visit data created from Elasticsearch by extracting info from the records they contain. The output sref field is using a feature called "top hits" to get the output sref of 1 example record to include in the output. The tilda prefix indicates that the lat/long is reduced precision due to the example record being sensitive.

**Comment by DavidRoy** [comment]
Thanks.
2. @Gary-van-Breda can you look into this
3. @kazlauskis - I'll raise a separate issue for this
4. @johnvanbreda - for this report for co-ordinators, the full sref can be downloaded

**Comment by Gary-van-Breda** [comment]
RE Number 2: It looks to me like an issue around Elasticsearch: those initial 20 shouldn't be in the download. Cross referencing the Transect Sample IDs - these are all created years before ABLE was moved over to warehouse1. The first 8 have IDs that have been deleted, and the other 12 are on other surveys.  
In addition there is some duplication of Transect Sample IDs e.g. 6010870 where there are 3 different rows.  
Am I miss-understanding the report?

**Comment by johnvanbreda** [comment]
The issue wasn't Elasticsearch, but the initial migration of data from warehouse2 to warehouse1 which didn't recreate parent samples correctly in these cases. I've recreated the parent samples required using the following script: 

```sql
select distinct s.parent_id as parent_sample_id_to_replace, 
  null::integer as new_sample_id,
  562 as survey_id, 
  l.parent_id as location_id,
  s.date_start, 
  s.date_end, 
  s.date_type,
  coalesce(lp.centroid_sref, max(s.entered_sref)) as entered_sref,
  coalesce(lp.centroid_sref_system, max(s.entered_sref_system)) as entered_sref_system,
  lp.name as location_name, 
  min(s.created_on) as created_on,
  min(s.created_by_id) as created_by_id,
  min(s.updated_on) as updated_on,
  min(s.updated_by_id) as updated_by_id,
  22 as sample_method_id,
  coalesce(lp.centroid_geom, st_union(s.geom)) as geom
into temporary new_samples
from samples s
left join samples sp on sp.id=s.parent_id
left join locations l on l.id=s.location_id
left join locations lp on lp.id=l.parent_id
where s.parent_id is not null 
and s.survey_id=562
and (sp.id is null or sp.survey_id<>562)
and s.deleted=false
group by s.parent_id,
  l.parent_id,
  s.date_start, 
  s.date_end, 
  s.date_type,
  lp.centroid_sref,
  lp.centroid_sref_system,
  lp.name,
  lp.centroid_geom;
  
update new_samples set new_sample_id=nextval('samples_id_seq'::regclass);

insert into samples (id, survey_id, location_id, date_start, date_end, date_type, entered_sref, entered_sref_system, location_name, created_on, created_by_id, updated_on, updated_by_id, sample_method_id, geom)
select new_sample_id, survey_id, location_id, date_start, date_end, date_type, entered_sref, entered_sref_system, location_name, created_on, created_by_id, updated_on, updated_by_id, sample_method_id, geom
from new_samples;

update samples s 
set parent_id=ns.new_sample_id, updated_on=now()
from new_samples ns
where ns.parent_sample_id_to_replace=s.parent_id;

insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'sample', id, null, 100, 2, now()
from samples where parent_id in (select new_sample_id from new_samples);

insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, null, 100, 2, now()
from occurrences where sample_id in (select id from samples where parent_id in (select new_sample_id from new_samples));
```

**Comment by johnvanbreda** [comment]
NB - point 4 still to do.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : Also need
```
insert into work_queue (task, entity, record_id, cost_estimate, priority, created_on)
select 'task_summary_builder_sample', 'sample', id, 50, 2, now()
from samples where id in (select new_sample_id from new_samples);
```

**Comment by johnvanbreda** [comment]
Point #4 will be done once changes on Pantheon Dev are pulled through to live (awaiting testing on other issues for @Gary-van-Breda). I've also done the work queue.

@Gary-van-Breda please can you close this the next time you update the code on live.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda All my work is on a form which is not currently being used on Live: feel free to push it all through to Live.
