### ISSUE TITLE
ButterflyCount app - weather data should be submitted as 'Not recorded' when null for both Transects and 15 minute counts

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#307]
Following on from #306 

When weather information is missing from Transect/15-minute counts, the value submitted should be 'Not recorded' rather than null.

Is the simplest approach to make 'Not recorded' the default value in the app?

**Comment by kazlauskis** [comment]
Yes, that's the simplest way. Either make it mandatory or set it to 'not recorded' by default.
