### ISSUE TITLE
Error in butterfly species list of eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#308]
Checking the data from Portugal, I realised about one error in the butterfly species, Coenonympha pamphilus
As you can see in the picture, it appears Coenonympha pamphius, missing the L in pamphilus. 

Now on the species lists of countries appear both options. 
Can it be possible to repair this issue? @DavidRoy I am not sure, who can do it

<img width="445" alt="Coenonympha pamphilus error" src="https://user-images.githubusercontent.com/25052478/95854929-ed54b700-0d57-11eb-817d-cacab7ce9797.PNG">

**Comment by johnvanbreda** [comment]
I've corrected the data in the warehouse using the following script:
```sql
-- Query to fetch the taxa_taxon_list IDs.
select id, taxon from cache_taxa_taxon_lists where taxon in ('Coenonympha pamphilus', 'Coenonympha pamphius')
and taxon_list_id=251
--432465	"Coenonympha pamphilus"
--466948	"Coenonympha pamphius"

-- Disable mispelling for data entry.
update taxa_taxon_lists set allow_data_entry=false, updated_on=now() where id=466948;

-- Ensure all records updated in cache when we map to the correct name.
insert into work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
select 'task_cache_builder_update', 'occurrence', id, null, 100, 2, now()
from occurrences where taxa_taxon_list_id=466948;

-- Map to the correct name.
update occurrences set taxa_taxon_list_id=432465 where taxa_taxon_list_id=466948;
```

@kazlauskis can you confirm that the app submits ID 432465 not 466948 please?

**Comment by Gary-van-Breda** [comment]
There is also a child taxon of 466948 - "Coenonympha pamphilus ssp. lyllus", 466949 (which looks like it is spelt correctly). Should we move it across to be under 432465 ?

I think we also have to run the following:
```
insert into indicia.work_queue (task, entity, record_id, cost_estimate, priority, created_on)
select distinct 'task_summary_builder_occurrence_update', 'occurrence', id, 50, 2, now()
from indicia.occurrences
where website_id = 118
AND deleted = false
AND  taxa_taxon_list_id = 432465
;
```
This should recalculate the Annual Summary data for the changed occurrences, including removing the summary data for the old taxon.

**Comment by kazlauskis** [comment]
@johnvanbreda the app allows to submit 3 options right now:

```
      [432465, "pamphilus"],
      [466949, "pamphilus ssp. lyllus"],
      [466948, "pamphius"]
```
This comes from `projects/ebms/taxa_list_for_app.xml` report.

**Comment by johnvanbreda** [comment]
@kazlauskis I've updated the report so taxa where allow_data_entry=false are excluded. Therefore [466948, "pamphius"] can be removed from the app.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda agreed, I've re-parented 466949 and inserted the work_queue tasks as suggested.

**Comment by kazlauskis** [comment]
Thanks, I will update the species list in the app then.
