### ISSUE TITLE
Translate option needs to be added for transect input pages

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#31]
No translate tab on transect input pages, e.g. 
http://dev-butterfly-monitoring.pantheonsite.io/my-walks
http://dev-butterfly-monitoring.pantheonsite.io/sites-list

**Comment by BirenRathod** [comment]
@DavidRoy 
Translate tab is now available for any indicia pages.

**Comment by DavidRoy** [comment]
Excellent, thanks!
