### ISSUE TITLE
Downloads for 15minute count survey - GIS data

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#310]
The downloads page:
https://butterfly-monitoring.net/downloads

The 15 minute timed-count downloads (survey id = 565) are not downloading.  The file currently includes transect data.  Is this because of the form structure restricted to location_type_id = 777 (transect sections?)

Needs resolving urgently.

[misc_extensions.report_helper_control]
@control=report_download_link
@caption=Download tracks and areas (KML)
@dataSource=projects/ebms/ebms_section_gis_download
@extraParams=
@class=btn btn-primary

**Comment by johnvanbreda** [comment]
Done
