### ISSUE TITLE
Warning messages on Walk data entry page

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#311]
Several users reported three warning messages appeared on the second page of Walk data entry (entering species) https://butterfly-monitoring.net/ebms-input-data?sample_id=12134857

The visit data is saved perfectly but the warning messages shouldn't be there, it si confusing for the users.

Could you @Gary-van-Breda or @johnvanbreda check it?
@DavidRoy 

<img width="661" alt="3" src="https://user-images.githubusercontent.com/25052478/98248164-daa75980-1f74-11eb-9e79-526c8d5281ed.PNG">
<img width="655" alt="1" src="https://user-images.githubusercontent.com/25052478/98248166-db3ff000-1f74-11eb-955c-18ce84e079da.PNG">
<img width="664" alt="2" src="https://user-images.githubusercontent.com/25052478/98248167-dbd88680-1f74-11eb-9064-89bc2ba7a60f.PNG">

**Comment by Gary-van-Breda** [comment]
@johnvanbreda 
We're getting an "Unsupported array field sub-type" from warehouse1 when querying the cache view of occurrences: see 

https://warehouse1.indicia.org.uk/index.php/services/data/occurremce?auth_token=76c84a448f5686eea49ae538d8ce9e33e69eed89&nonce=d939f476aee2dbbe84587790838d839a38034193&mode=json&survey_id=562&view=cache

Obviously you'll have to change the auth_token/nonce.

Is this related to the array type changes you were doing a couple of days ago?

**Comment by johnvanbreda** [comment]
Yes, I think so, I'll take a look.

**Comment by johnvanbreda** [comment]
@Gary-van-Breda Can you check now please - note the link above has a typo and doesn't select a particular record so will probably timeout.

**Comment by Gary-van-Breda** [comment]
Thanks: looks good now.
Bouncing to Cris and David to check and close.

**Comment by CrisSevilleja** [comment]
Thank you, the warning messages are gone!
