### ISSUE TITLE
Improve Scheme sites page for summarising transects

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#312]
The current Scheme sites page for coordinators gives the total number of samples for all the sites in their countries, 
https://butterfly-monitoring.net/scheme-sites  I was wondering if it can be added a second column showing the samples per transect done in the calendar year apart from the current column. It would help the coordinators and me to control the samples done per transect.

@johnvanbreda could it be possible to add it?
Thanks

**Comment by johnvanbreda** [comment]
@CrisSevilleja I'm sure we could add something - can you specify the exact calculation for what you want to see please? Is it just for the current calendar year or do we need multiple columns?

**Comment by CrisSevilleja** [comment]
@johnvanbreda  sorry for not replying before. 

I will try to explain it in the best way. For the Scheme site page, I would like to have four columns: 

1. Samples done in the calendar year (2020 in this case) per transect 
2. Samples done in total per transect = sum of all the samples done for that transects including former years of monitoring
3. Number of species registered per transect.
4. Actions (like it is now) to allow the edit of that transect

I hope now it is clearer. This organisation will help and give good information to the coordinators. 
Thank you so much.

**Comment by CrisSevilleja** [comment]
One thing more sorry, if possible to include a searching bar above the columns like in the All site page https://butterfly-monitoring.net/all-sites to be able to search any transect. 

Now transects are organised by samples and you cannot search by alphabetic order or typing directly. 

Thank you

**Comment by johnvanbreda** [comment]
All done now @CrisSevilleja
