### ISSUE TITLE
Choosing species group for full lists

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#313]
- [x] Add app settings page for choosing favourite species groups
- [x] Filter species search results based on fav groups
- [ ] Add a summary page with "I have recorded full list" toogle for each fav group.

From Chris:

> One important thing is still missing in the app (though I reported that earlier), at least, as far as I can see.
It is now possible to enter records from multiple species groups. However we have to be sure that ALL species of a group are entered. Lets assume I do a transect counting butterflies, and I also recognize (among many other dragonflyspecies flying around as well) the only species of dragonfly I can identify, and enter that as well. But not all the other dragonflies (which I can't identify). Then this might end up as a dragonfly count with only 1 species. So we have to find a way to be sure that all species are recognized and entered. Two possible ways this could be done:  
> *   Before starting: you have to choose the species groups you want to count. If you choose butterflies and dragonflies, you won't be able to enter another group. And if you choose only butterlfies, you only get butterflies when you search for a species, so you can't enter a dragonfly anymore (or alternatively: they will be marked as single opportunistic records)
 > *   At the end: for which species groups have you entered ALL you have seen?

>  I would prefer the first, and make other species opportunistic records.

**Comment by kazlauskis** [comment]
@DavidRoy Should moths be a seperate group in the app. At the moment, we have added 4 groups: **butterflies, moths, bumblebees, dragonflies**. Also, do you want to have all of the groups selected automatically the first time user installs the app? Alternatively, I could autoselect only the butterflies to keep the app more butterfly focused.

**Comment by DavidRoy** [comment]
@kazlauskis yes, moths separate

I like the idea of just having butterflies to start with but would be interested in @chrisvanswaay 's view on this

**Comment by DavidRoy** [comment]
@kazlauskis Chris agrees with these points.
1. Groups are: butterflies, moths, bumblebees, dragonflies
2. By default, the group selected is butterflies
3. It is possible to restrict the app to any group, e.g. dragonflies only

**Comment by kazlauskis** [comment]
Thanks, will do. After finishing a 15min count survey do you want the user to actively select/deselect "Full species list recorded for GROUPNAME" checkboxes? Or can these be auto-checked by default and hidden under the 'Aditional details' menu?

**Comment by DavidRoy** [comment]
These can be auto-selected as will be the default case
- are we having an extra survey for 'single-species'?

**Comment by chrisvanswaay** [comment]
Hi Karolis and David,
I think it is essential the recorder decides at the beginning (with a default) what species groups he is going to count. Only those species should occur in the possibilities to add. You can't decide halfway to start counting a new group.
For single species: certainly a very valuable addition (will make it easier to count one rare species on a remote place, as you are not required to be able to id all species there, as long as you can do the one), but of course also something you have to decide before starting. Then of course this single species is already in the list and none of the others.

Best wishes,
Chris



--

De Vlinderstichting is een organisatie zonder winstoogmerk. Voor een deel van ons werk zijn wij afhankelijk van de steun van donateurs. Wilt u bijdragen aan bescherming van vlinders en libellen? Neem dan een kijkje op onze website<https://www.vlinderstichting.nl/help-mee/donateur-worden> en help ons!


Chris van Swaay
De Vlinderstichting
Mennonietenweg 10
Postbus 506
6700 AM  Wageningen

[t] algemeen (+31) 0317 467346 / direct (+31) 0317 467342

[e] ***@***.******@***.***>
[i] www.vlinderstichting.nl<http://www.vlinderstichting.nl/>
[twitter] www.twitter.com/vlinderNL<http://www.twitter.com/vlinderNL>
[facebook] www.facebook.com/Vlinderstichting<http://www.facebook.com/Vlinderstichting>
[instagram] www.instagram.com/vlinderstichting<http://www.instagram.com/vlinderstichting>
[linkedin] www.linkedin.com/company/vlinderstichting<http://www.linkedin.com/company/vlinderstichting>

------------------------------
Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------
No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.

________________________________
Van: Karolis Kazlauskis ***@***.***>
Verzonden: donderdag 29 april 2021 15:42
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Chris van Swaay ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [BiologicalRecordsCentre/ABLE] Choosing species group for full lists (#313)


Thanks, will do. After finishing a 15min count survey do you want the user to actively select/deselect "Full species list recorded for GROUPNAME" checkboxes? Or can these be auto-checked by default and hidden under the 'Aditional details' menu?

**Comment by kazlauskis** [comment]
> are we having an extra survey for 'single-species'?

Yes, I'll add this in.

Regards, the favourite species groups, at the moment, I have added this under the Settings menu so this applies app-wide when searching for species. From our last discussion over the phone I thought that the per-survey "full-list" checkbox is merely to understand if the intent was to record all the species, not so much to limit the search results for particular groups - is that not right?

**Comment by chrisvanswaay** [comment]
Hi Karolis,
You have to decide upfront anyway which groups you are going to count (in my case: only butterflies, but others might want to do dragonflies or can do both). It seems convenient that you can then only enter those groups anyway, makes your search quicker (now sometimes loads of moths pop up, orginally there were only butterflies, which worked much easier).

Best wishes,
Chris


--

De Vlinderstichting is een organisatie zonder winstoogmerk. Voor een deel van ons werk zijn wij afhankelijk van de steun van donateurs. Wilt u bijdragen aan bescherming van vlinders en libellen? Neem dan een kijkje op onze website<https://www.vlinderstichting.nl/help-mee/donateur-worden> en help ons!


Chris van Swaay
De Vlinderstichting
Mennonietenweg 10
Postbus 506
6700 AM  Wageningen

[t] algemeen (+31) 0317 467346 / direct (+31) 0317 467342

[e] ***@***.******@***.***>
[i] www.vlinderstichting.nl<http://www.vlinderstichting.nl/>
[twitter] www.twitter.com/vlinderNL<http://www.twitter.com/vlinderNL>
[facebook] www.facebook.com/Vlinderstichting<http://www.facebook.com/Vlinderstichting>
[instagram] www.instagram.com/vlinderstichting<http://www.instagram.com/vlinderstichting>
[linkedin] www.linkedin.com/company/vlinderstichting<http://www.linkedin.com/company/vlinderstichting>

------------------------------
Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------
No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.

________________________________
Van: Karolis Kazlauskis ***@***.***>
Verzonden: donderdag 29 april 2021 16:40
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Chris van Swaay ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [BiologicalRecordsCentre/ABLE] Choosing species group for full lists (#313)


are we having an extra survey for 'single-species'?

Yes, I'll add this in.

Regards, the favourite species groups, at the moment, I have added this under the Settings menu so this applies app-wide when searching for species. From our last discussion over the phone I thought that the per-survey "full-list" checkbox is merely to understand if the intent was to record all the species, not so much to limit the search results for particular groups - is that not right?

**Comment by DavidRoy** [comment]
@chrisvanswaay are you ok this being an app setting rather than having to confirm each time?  We want to make the app as simple as possible

**Comment by chrisvanswaay** [comment]
Yep


*****************
Chris van Swaay
De Vlinderstichting - Dutch Butterfly Conservation
Postbus 506, 6700 AM Wageningen, Netherlands
T: +31 317 467346
***@***.***
*****************

________________________________

**Comment by kazlauskis** [comment]
Great! In that case, are most people recording full lists? Do we need to show the "Full species list recorded for GROUPNAME" checkboxes at all? Or can we assume that our users will always submit full species lists of their favourite groups in the Settings?

**Comment by DavidRoy** [comment]
I think so, yes
@chrisvanswaay - do you agree?

**Comment by chrisvanswaay** [comment]
Yes. For me it is clear that all species have to be recorded and counted. If that is not clear for others, than we should work on ways to make that more clear.
Best wishes,
Chris


--

De Vlinderstichting is een organisatie zonder winstoogmerk. Voor een deel van ons werk zijn wij afhankelijk van de steun van donateurs. Wilt u bijdragen aan bescherming van vlinders en libellen? Neem dan een kijkje op onze website<https://www.vlinderstichting.nl/help-mee/donateur-worden> en help ons!


Chris van Swaay
De Vlinderstichting
Mennonietenweg 10
Postbus 506
6700 AM  Wageningen

[t] algemeen (+31) 0317 467346 / direct (+31) 0317 467342

[e] ***@***.******@***.***>
[i] www.vlinderstichting.nl<http://www.vlinderstichting.nl/>
[twitter] www.twitter.com/vlinderNL<http://www.twitter.com/vlinderNL>
[facebook] www.facebook.com/Vlinderstichting<http://www.facebook.com/Vlinderstichting>
[instagram] www.instagram.com/vlinderstichting<http://www.instagram.com/vlinderstichting>
[linkedin] www.linkedin.com/company/vlinderstichting<http://www.linkedin.com/company/vlinderstichting>

------------------------------
Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------
No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.

________________________________
Van: David Roy (CEH) ***@***.***>
Verzonden: donderdag 29 april 2021 18:47
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Chris van Swaay ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [BiologicalRecordsCentre/ABLE] Choosing species group for full lists (#313)


I think so, yes
@chrisvanswaay<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchrisvanswaay&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C76ff331f4b444684e41f08d90b2e74a1%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637553116436599958%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YPfvTgCcqdUdey%2FzOwI0ewLGQr26k4Gc5r42rvUH97o%3D&reserved=0> - do you agree?

**Comment by kazlauskis** [comment]
Thanks, in that case, this work is now mostly complete. With the next app update, you should be able to select your favourite groups from the app settings.

@DavidRoy I wonder how it is best to upload this new survey information. Shall I create a "Complete list" `boolean` attribute for each species group in the warehouse? Alternatively, I can submit the names/IDs of the groups under a single sample attribute as an array.

**Comment by DavidRoy** [comment]
Thanks! The group settings are mainly for reducing the species list when searching names to add.  I don't think we need to capture anything on 'complete list'.  At least for the 15 minute counts.

We may need to consider what we do for transects for the situation where one recorder includes moths but another does not for the same transect.  The lack of moths recorded either indicates a zero count or 'not recorded'. To capture information on whether the count includes moths, dragonflies, bees we should have a boolean attribute for each?

**Comment by kazlauskis** [comment]
Yes, we could have the checkboxes for each separate group somewhere in the Transect edit page or I could automatically attach user's favourite groups to the record.
