### ISSUE TITLE
Walk data entry new - unable to add new species to list for recording

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#314]
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new?location_type_id=777&date=11/11/2020

e.g. trying to add 'Aglais urticae' based on 'Species I have recorded' as the list chosen.  Unable to add new species.  When name selected the page scrolls to the top but the name is not added to the list.

Masquaring as user = szabadfalvi and entering data for Hungary site

![and](https://user-images.githubusercontent.com/2699478/99075897-292aa880-25b2-11eb-8018-65573e5e7579.png)

**Comment by DavidRoy** [comment]
Add extra species works when 'Region species list' is active

**Comment by Gary-van-Breda** [comment]
As a result of the performance tweaks for #278, unseen taxa are left on the page if they have been on it previously, but hidden: I forgot to re-display the species in this case.
Fix applied to Dev site.

**Comment by DavidRoy** [comment]
Tried to test this and got the follow page

{"success":"multiple records","outer_table":"sample","outer_id":9312387,"struct":{"model":"sample","id":9312387,"created_on":"2021-02-17 10:45:53","updated_on":"20210217 10:46:09","children":[{"model":"sample_attribute_value","id":35498323,"created_on":"2021-02-17 10:45:53","updated_on":"2021-02-17 10:45:53"},{"model":"sample_attribute_value","id":35498324,"created_on":"2021-02-17 10:45:53","updated_on":"2021-02-17 10:45:53"},{"model":"sample_attribute_value","id":35498325,"created_on":"2021-02-17 10:45:54","updated_on":"2021-02-17 10:45:54"},{"model":"sample_attribute_value","id":35498326,"created_on":"2021-02-17 10:45:54","updated_on":"2021-02-17 10:45:54"},{"model":"sample_attribute_value","id":35498327,"created_on":"2021-02-17 10:45:54","updated_on":"2021-02-17 10:45:54"},{"model":"sample_attribute_value","id":35498328,"created_on":"2021-02-17 10:45:54","updated_on":"2021-02-17 10:45:54"},{"model":"sample_attribute_value","id":35498329,"created_on":"2021-02-17 10:45:54","updated_on":"2021-02-17 10:45:54"},{"model":"sample_attribute_value","id":35498330,"created_on":"2021-02-17 10:45:54","updated_on":"2021-02-17 10:45:54"},{"model":"sample_attribute_value","id":"35498331","created_on":"20210217 10:46:09","updated_on":"20210217 10:46:09"}]},"transaction_id":"superSampleAttr-1501"}

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you get this page up and running so we can test please
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new

**Comment by Gary-van-Breda** [comment]
@DavidRoy : fix deployed to dev site.

**Comment by DavidRoy** [comment]
Thanks
