### ISSUE TITLE
Error log in for several user

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#315]
Several users reported errors to log in in the eBMS website https://butterfly-monitoring.net/user/login, the password is unrecognized. Also, this problem happened to me I reset the password and change the account and I managed to log in. 
If I log out and try to enter again it doesn't recognize the new password. 

I can only log in if I reset the password.... 
@DavidRoy @Gary-van-Breda @johnvanbreda any clue what is happening?

![image](https://user-images.githubusercontent.com/25052478/99439387-65913800-2915-11eb-9d41-d3cfe082d1a3.png)

**Comment by BirenRathod** [comment]
@DavidRoy 
This could be affected due to using his email address if email is not his username.

**Comment by johnvanbreda** [comment]
@DavidRoy I think Biren is correct - the username here is CristinaSevilleja and the site is not setup to allow login via email address.

**Comment by DavidRoy** [comment]
@BirenRathod @Gary-van-Breda  is that a change as I thought login via email was possible previously?

@BirenRathod can you allow login via email again

**Comment by BirenRathod** [comment]
@DavidRoy 
It has been re-enabled now. 
It was enabled before but due to language translation module it was not implemented through out the site.

**Comment by CrisSevilleja** [comment]
thanks @BirenRathod it works with the username. It was confusing because login with email was possible before. 
Now I can log in with both, username and email. Thank you for the prompt solution.
