### ISSUE TITLE
Error loading the map of the page "Explore online record" - eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#316]
The map on the page https://butterfly-monitoring.net/elastic/all-records gives an error and it doesn't load 
@DavidRoy  @Gary-van-Breda 

<img width="935" alt="online data error" src="https://user-images.githubusercontent.com/25052478/99440039-49da6180-2916-11eb-8639-b253f03f34ae.PNG">

**Comment by johnvanbreda** [comment]
Now fixed
