### ISSUE TITLE
walk-data-entry-2: add option Not recorded/no data for Temperature value

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#319]
Temperature is a compulsory value to add when registering a visit. 
Please add the option "Not recorded/no data" in the drop-down options, to allow visits without registering Temperature

thanks

@DavidRoy

**Comment by DavidRoy** [comment]
We've now worked on this page as 
https://dev-butterfly-monitoring.pantheonsite.io/walk-data-entry-new

can you test that one please

**Comment by CrisSevilleja** [comment]
I test it and it is working, the page allows to save No recorded data/no data in different variables (Temp and wind). 

From my side, it is ready for the live site. Thank you for all the improvements
