### ISSUE TITLE
Add eBMS logo and colour scheme to website

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#32]
Here is draft of logo (awaiting final .png)
![image](https://user-images.githubusercontent.com/2699478/54906893-33c79400-4edc-11e9-91ca-ff204682af18.png)

Add to website as temporary option.  
http://dev-butterfly-monitoring.pantheonsite.io/

Change the website theme to match the eBMS colour:
![image](https://user-images.githubusercontent.com/2699478/54907032-84d78800-4edc-11e9-8180-75e8affaba49.png)

**Comment by BirenRathod** [comment]
@DavidRoy 
Logo uploaded and color have been changed thorough out the site.

**Comment by DavidRoy** [comment]
Thanks!
