### ISSUE TITLE
Error Scheme transect Allocation page not working

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#320]
The user filter in the Scheme Transect Allocation page https://butterfly-monitoring.net/scheme-transects-allocation is not working. The drop-down of the user filter doesn't show the filter and any user. 

@DavidRoy 

<img width="665" alt="scheme transect allocation - not working" src="https://user-images.githubusercontent.com/25052478/100858064-c5e3b600-348d-11eb-84d9-764e3e24f4c1.png">

**Comment by DavidRoy** [comment]
Were you logged in when doing this?  The page worked ok for me.  Can you try again?

**Comment by CrisSevilleja** [comment]
Now it works! It was needed to log out. After logging in the page works.
a good tip to remind for next time
