### ISSUE TITLE
Unable user to sign in eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#321]
A user from the Spanish BMS, Tomás Sanz, is not able to enter the website, after resetting his password. I tried to enter his account from several browsers and it is not working, message ×_Error message Unrecognized username or password._

The user Indicia Warehouse User ID 248898
username: Tomás
email: donguillos@xxx
new password: xxx

I don't know what is the problem, no other user had problems signing in and he apparently did everything right to reset the password.
Could you help me @Gary-van-Breda or @johnvanbreda ? Thank you so much

@DavidRoy

**Comment by DavidRoy** [comment]
I logged in using these details.  Can you try again. 

Also, best not to put personal information and passwords in this github repository as it is open to all.

**Comment by CrisSevilleja** [comment]
Now I logged in, it looks like you need to see it before... sorry for this silly issue. 

Yes, sorry I won't place more personal details and say to Tomas to change his password.

**Comment by DavidRoy** [comment]
Thanks, glad it is ok :-)
