### ISSUE TITLE
Samples missing from download files

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#323]
https://butterfly-monitoring.net/downloads.
"Download sample (visits) information from transects (zipped CSV)"
user = https://butterfly-monitoring.net/user/1379
who has role = Scheme co-ordinator for Spain

1046 (out of 1495) samples are missing for 2020. 
- mostly since May 2020 so possibly an issue with the ElasticSearch index populating?

Example sample data missing is:

location_id | transect_code | transect_name | Transect_sample_id | date_start | created_on
-- | -- | -- | -- | -- | --
223604 | EBMS:Spain:36 | TAJA | 12282491 | 2020-09-16 | 2020-12-05 16:10:11
223604 | EBMS:Spain:36 | TAJA | 12282479 | 2020-09-01 | 2020-12-05 15:56:14
223604 | EBMS:Spain:36 | TAJA | 12282427 | 2020-08-25 | 2020-12-05 15:38:03
223604 | EBMS:Spain:36 | TAJA | 12282392 | 2020-08-16 | 2020-12-05 15:24:34
223604 | EBMS:Spain:36 | TAJA | 12282361 | 2020-08-07 | 2020-12-05 15:11:38
223604 | EBMS:Spain:36 | TAJA | 12279094 | 2020-07-27 | 2020-12-04 22:03:17
223604 | EBMS:Spain:36 | TAJA | 12279085 | 2020-07-14 | 2020-12-04 21:45:51
223604 | EBMS:Spain:36 | TAJA | 12279004 | 2020-07-05 | 2020-12-04 19:51:29
223604 | EBMS:Spain:36 | TAJA | 12278985 | 2020-06-28 | 2020-12-04 19:37:48
223604 | EBMS:Spain:36 | TAJA | 12278972 | 2020-06-21 | 2020-12-04 19:25:53
223604 | EBMS:Spain:36 | TAJA | 12278966 | 2020-05-23 | 2020-12-04 19:21:31
223604 | EBMS:Spain:36 | TAJA | 12278943 | 2020-05-30 | 2020-12-04 19:03:59
223604 | EBMS:Spain:36 | TAJA | 8423673 | 2018-09-17 | 2020-05-29 14:53:34
223604 | EBMS:Spain:36 | TAJA | 8423667 | 2018-08-06 | 2020-05-29 14:53:33
223604 | EBMS:Spain:36 | TAJA | 8423666 | 2018-07-30 | 2020-05-29 14:53:33
223604 | EBMS:Spain:36 | TAJA | 8423665 | 2018-07-23 | 2020-05-29 14:53:33
223604 | EBMS:Spain:36 | TAJA | 8423656 | 2018-09-09 | 2020-05-29 14:53:33
223604 | EBMS:Spain:36 | TAJA | 8423655 | 2018-08-15 | 2020-05-29 14:53:33
223604 | EBMS:Spain:36 | TAJA | 8423654 | 2018-09-22 | 2020-05-29 14:53:32
223604 | EBMS:Spain:36 | TAJA | 8423653 | 2018-09-29 | 2020-05-29 14:53:32

**Comment by johnvanbreda** [comment]
At least some of these examples are training data - does that explain it?
