### ISSUE TITLE
walk-data-entry-2 license text update

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#324]
reword license information at bottom of page to:
By submitting these records you confirm that they contain data that you have collected, give permission for the records to be used for research, education and public information, and to be made generally available for re-use for any other legal purpose under the terms of the creative commons license '[no rights [reserved]',](https://creativecommons.org/share-your-work/public-domain/cc0) and agree that your name will be associated with the record.  National co-ordinator are responsible for sharing data for their region.

**Comment by Gary-van-Breda** [comment]
Fix deployed to Dev to be checked.

**Comment by DavidRoy** [comment]
thanks
