### ISSUE TITLE
Data not appearing on ebms-input form

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#325]
This data was imported.  It shows on the annual-summary [view](https://butterfly-monitoring.net/annual-report?userID=all&locationID=223875&year=2019) with data for 13 species and 41 individuals, but data is missing from the ebms-input [page.](https://butterfly-monitoring.net/ebms-input-data?sample_id=8421755).  Both when masquerading as user with scheme-ordinator role for [Spain](https://butterfly-monitoring.net/user/1379)

Screenshots to illustrate
![ebms2](https://user-images.githubusercontent.com/2699478/108192810-a105f300-710c-11eb-9a30-e027f5b57470.jpg)
![ebms1](https://user-images.githubusercontent.com/2699478/108192812-a2372000-710c-11eb-9640-f05bd248bb56.png)

**Comment by Gary-van-Breda** [comment]
The annual summary is correct. The import has created multiple child samples for each section - this requires a datafix.
The import keeps a track of the previous row's walk section sample when attaching occurrences, to prevent this duplication, but it does rely on the occurrences being grouped (sorted) by section number, especially if the previous data lookup is not used. It looks like this was not the case here.
This needs a data fix, not a code one.

**Comment by JimBacon** [comment]
Following work to fix the data, the input page now correctly shows 13 species and 41 individuals for the given example.

![image](https://user-images.githubusercontent.com/2545390/189845557-327f086a-c438-4895-9dcf-914a03b91898.png)
