### ISSUE TITLE
Add drop-down list for the years on My walks page

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#327]
It would be helpful to add a drop-down list for the year on My walks page https://butterfly-monitoring.net/my-walks to move between years and not only clicking on the arrows. Now you can move to consecutive years and not jump between years

See the example from another page https://butterfly-monitoring.net/annual-report
<img width="669" alt="drop-down years- annual report" src="https://user-images.githubusercontent.com/25052478/108870372-5a2a6880-75f8-11eb-8df0-f4247148c04e.png">

@DavidRoy @johnvanbreda

**Comment by johnvanbreda** [comment]
Need to double check with @Gary-van-Breda if changing report parameters will affect UKBMS.

**Comment by DavidRoy** [comment]
yes, one for Gary to consider

**Comment by Gary-van-Breda** [comment]
This change has been implemented with the recent Region coordinator changes; also on the region and scheme walk pages.
Bouncing to @CrisSevilleja for review/closure.

Report parameters don't change, this only affects the year control on the form itself. Minimum year set to 2007.

**Comment by CrisSevilleja** [comment]
perfect, the drop-down list is working in the different pages. Thank you for including it. 
We can close this issue
