### ISSUE TITLE
Unable to unblock user account

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#328]
https://butterfly-monitoring.net/user/2252/edit?destination=/admin/people

Clicking 'active' on user account and saving returns a page asking to confirm other accounts.
![ebms error](https://user-images.githubusercontent.com/2699478/109412753-bea34a00-79a1-11eb-81c0-6966944a4567.png)

either clicking none or all of these tick boxes returns an error and failure to save.  Account remains blocked.

The website encountered an unexpected error. Please try again later.
ArgumentCountError: Too few arguments to function easy_login_handle_get_user_id_response(), 2 passed in /code/modules/custom/indicia_features/easy_login/src/Form/ResolveMultipleUsersForm.php on line 71 and exactly 3 expected in easy_login_handle_get_user_id_response() (line 77 of modules/custom/indicia_features/easy_login/easy_login.module).
easy_login_handle_get_user_id_response(Object, '{"userId":"41199","attrs":[]}') (Line: 71)
Drupal\easy_login\Form\ResolveMultipleUsersForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('easy_login_resolve_multiple_users_form', Array, Object) (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 91)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 49)
Asm89\Stack\Cors->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by johnvanbreda** [comment]
This problem relates to an old version of the easy_login module running on EBMS and it is fixed in the newest code. I've applied the latest code and activated this account. The new code no longer displayed the request to check which sites the account was linked to.
