### ISSUE TITLE
ButterflyCount app: searching species wrong

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#329]
One user told me he was not able to find "Pontia daplidice" on the ButterflyCount app. The species is not found when you search "Pont" but it is possible when you type "dapl". Check the pictures

Please correct this error on species searching @DavidRoy @kazlauskis 

![Screenshot_20210316-Pontia2](https://user-images.githubusercontent.com/25052478/111291977-01268100-8648-11eb-8190-80110c7d7651.png)
![Screenshot_20210316-Pontia](https://user-images.githubusercontent.com/25052478/111291980-01bf1780-8648-11eb-86a0-5d1cd97c1ba0.png)

**Comment by kazlauskis** [comment]
Thanks for raising this here, looks like there is a bug somewhere.
