### ISSUE TITLE
Drawing the transect route

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#33]
Doing some test, some errors appeared when I was drawing the transect and entering new visits:

- The new transects don't appear in the "My Sites", only in the "National Sites"and "All sites"
- In Site details -> Your route, when I draw a section is highlight, I try to save the section gives an error and if I continue without saving then the route is saved. The message said:

"There are unsaved changes to the route and/or the section details for this currently selected section. Select 'Continue' to discard these changes, and load the new section; choose 'Cancel' to prevent the data load, and allow you to save the data first."

So you should saved before change the section, but if you save the section is placed wrong. The message should be modified. The process now works drawing all the section and when you finish, save the whole route. If you save is constantly giving errors:

{"success":"multiple records","outer_table":"occurrence","outer_id":"1297723","struct":{"model":"occurrence","id":"1297723","created_on":"20190325 13:49:18","updated_on":"20190325 13:49:18","children":[{"model":"occurrence_attribute_value","id":"3982359","created_on":"20190325 13:49:19","updated_on":"20190325 13:49:19"}]},"transaction_id":"value:535085:S4"}

- About entering a visit to a route, it gives an error entering the number of individual species:

The website encountered an unexpected error. Please try again later.
Error: Call to a member function format() on boolean in iform_ukbms_sectioned_transects_input_sample::get_occurrences_form() (line 1367 of modules/custom/iform/client_helpers/prebuilt_forms/ukbms_sectioned_transects_input_sample.php).
iform_ukbms_sectioned_transects_input_sample::get_occurrences_form(Array, '36', NULL) (Line: 951)
iform_ukbms_sectioned_transects_input_sample::get_form(Array, '36', NULL) (Line: 546)
iform_node_view(Array, Object, Object, 'full')
call_user_func_array('iform_node_view', Array) (Line: 403)
Drupal\Core\Extension\ModuleHandler->invokeAll('node_view', Array) (Line: 269)
Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) (Line: 220)
Drupal\Core\Entity\EntityViewBuilder->build(Array)
call_user_func(Array, Array) (Line: 378)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by DavidRoy** [comment]
@Gary-van-Breda I've replicated this error, even after clearing my browser cache and trying on a different browser

**Comment by Gary-van-Breda** [comment]
> The new transects don't appear in the "My Sites", only in the "National Sites"and "All sites"
Cristina has been given virtually every single role: this means she has sufficient permissions to be able to allocate not only normal users, but branch level users. Sites are only allocated automatically to the creating user if that user is a normal user (without user allocation powers). If she wishes to see the site in her own "My Sites" page, she needs to allocate the site to herself, using the "Allocate recorders to the site" control at the bottom of the main site tab.

**Comment by Gary-van-Breda** [comment]
> About entering a visit to a route, it gives an error entering the number of individual species:

Bugfix applied: Drupal 8 conversion of iform module was losing the response from the warehouse, so it could not load in the newly created sample (it did not know the new sample's id), which led to an invlid date. This error occurred on the initial save, an not when going back into the walk.

**Comment by DavidRoy** [comment]
Site is created ok, and appears in My Sites list.  When then selected 'edit' and going to 'Your route' tab, the section does not save.  It gets stuck with the 'Saving route' popup
![err](https://user-images.githubusercontent.com/2699478/55396735-83d9d280-553c-11e9-97ce-275f00154fd8.png)

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can we have the "log_browser" module switched on warehouse2? Thanks

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Re the section drawing issues - I've put some changes to this form on the Dev site (not Test just yet) - can you have another go?

**Comment by DavidRoy** [comment]
The sections draw ok but the route saving does not work.  The page gets stuck with the pop-up box title 'Saving route' with text 'Saving the route data for section S2.
Saving Route...'

The one I am trying is: http://dev-butterfly-monitoring.pantheonsite.io/ebms-site-details?id=7060

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
log_browser modules is already enabled.

**Comment by Gary-van-Breda** [comment]
@DavidRoy : I'd missed a permission on the ajax proxy pass thorough that I've just now changed: can you try again?
I've set it on both Dev and Test environments

**Comment by DavidRoy** [comment]
Route now saves, but get this error when trying to save section details:
{"success":"multiple records","outer_table":"location","outer_id":7061,"struct":

{"model":"location","id":7061,"created_on":"2019-04-03 11:41:48","updated_on":"20190403 11:42:22","children":[{"model":"location_attribute_value","id":6590,"created_on":"2019-04-03 11:41:48","updated_on":"2019-04-03 11:41:48"},{"model":"location_attribute_value","id":"6592","created_on":"20190403 11:42:22","updated_on":"20190403 11:42:22"},{"model":"location_attribute_value","id":0},{"model":"location_attribute_value","id":0},{"model":"location_attribute_value","id":0},{"model":"location_attribute_value","id":0}]},"transaction_id":"S1"}

**Comment by Gary-van-Breda** [comment]
This was a jQuery version clash: the jquery.forms plugin that comes with IForm is incompatible with the jQuuery that comes with Drupal 8, but if you are an admin (or can see the masquerade block/admin toolbar) then the jquery.forms plugin that comes with Drupal is l;oaded in, which means the form works.
@DavidRoy : new version of IForm module loaded into Dev only (not Test yet) which loads in the Drupal jquery.forms plugin.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I just loaded to test now.

**Comment by BirenRathod** [comment]
@Gary-van-Breda & @DavidRoy 
The live environment of this has just created now. here is the URL -> http://live-butterfly-monitoring.pantheonsite.io/

**Comment by DavidRoy** [comment]
@Gary-van-Breda works well on dev, not on test.  On test, the map when adding route does not default to line drawing tool

**Comment by Gary-van-Breda** [comment]
I think this was because the Drupal caches need to be cleared after the new IForm code was deployed on Test: I've done this now, and it looks OK to me - can you confirm?

**Comment by Gary-van-Breda** [comment]
Also done on Live just to be safe.

**Comment by DavidRoy** [comment]
Thanks.  Tested and ok on both test and live
