### ISSUE TITLE
ButterflyCount app: 15 minutes counts doesn't track the route

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#330]
One frequent user of 15-min counts, Jurrien from the Netherlands told me today he was doing a 15-min count and the app didn't record the route even when he keeps the app open and not blocking the phone. After he finished the 15-min count the app didn't allow him to submit it. 

Any idea to suggest to him how to fix this issue? he is normally using the app and the 15-min count so I doubt if it is a problem of his phone. 
Thanks
@DavidRoy @kazlauskis

**Comment by CrisSevilleja** [comment]
Hi again, it looks like the app is not working well. Jurrien told me he tried today the app again and it only tracks the route for the first few seconds. He didn't see any butterfly, so it also didn't track anything when he finished the 15 minutes...

So the app is not tracking well the route. @DavidRoy

**Comment by kazlauskis** [comment]
Thanks for raising the ticket here. What is the operating system (Android/iOS) and its version the user is using, also which app version and which survey is it for? There are two 15min count surveys now (under experimental features).

**Comment by CrisSevilleja** [comment]
I asked him all these details. I hope to tell you something soon

**Comment by CrisSevilleja** [comment]
@kazlauskis Jurrien has an Android phone with the latest update from 19 March 2021 and version V1.10.0(3). He didn't know about the precise 15-min count, so I don't think he is using that option, just the normal 15-min count

**Comment by kazlauskis** [comment]
I've spoken to Chris about this issue and it looks like the GPS works if the screen is unlocked. This should be fixed with #214 so I am closing this.

**Comment by CrisSevilleja** [comment]
Thank you @kazlauskis
