### ISSUE TITLE
Add single species 15-min count survey

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#331]
Based on 15-min precise count survey but with a single species pre-selected and no options to add other species.

**Comment by kazlauskis** [comment]
@DavidRoy do you want me to create a separate survey on the warehouse with its own ID or should I reuse the 15min survey and just flag the records with some extra sample attribute?

**Comment by DavidRoy** [comment]
@kazlauskis a separate survey makes it more explicit that this is something different I think.  Even if in real terms the data is no different

**Comment by kazlauskis** [comment]
Thanks, I'll duplicate the 15min survey with a new name then.
