### ISSUE TITLE
walk-data-entry-2 time values reverting to 12-hour clock

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#333]
![image001](https://user-images.githubusercontent.com/2699478/113318662-94c6a580-9308-11eb-8705-0b7aa05b7804.png)

If you enter "13:05", it displays "01:05" and then it doesn't allow you to go on. Error message

This has also been reported for the UKBMS
https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/209

**Comment by Gary-van-Breda** [comment]
@DavidRoy : do you still consider this an issue?
(see narrative in https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/209 )

**Comment by DavidRoy** [comment]
We can close this one now, thanks
