### ISSUE TITLE
walk-data-entry2. Option for blank species list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#334]
Currently, the page gives a list for the site (whatever has been recorded there) etc
These spp. can then be displayed either in taxonomic order or alphabetically.

Is it possible to give an option to start with a blank list with the option of adding the species one by one?
Reason: some transects have over 70 butterfly spp. and over 30 moth spp. during a whole season. On spp. entry things can get messy and confusing seeing lots of empty spp. rows coming/predicted from the yearly/monthly/whatever period transect data.

**Comment by Gary-van-Breda** [comment]
@DavidRoy "None" now added to options. This is the default for existing walks (when it actually shows just the existing occurrences).

**Comment by CrisSevilleja** [comment]
It is a good option. Thanks
