### ISSUE TITLE
Pause GPS tracking when survey is paused

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#335]
From Andras:

>  If you pause the survey (counter) to identify a butterfly or for any other reason, either tracklog recording must be off or it should be excluded from the area calculation; (I have raised this issue earlier)

**Comment by CrisSevilleja** [comment]
I am not completely sure if this function is really needed. If I pause the time, it means I will stay in the same place and the GPS will record the place where I stop. 
If this function is applied to the app, I would like to include the automatic switch of the GPS on when the time is running again, then we avoid starting the Time count and the GPS remains off

**Comment by kazlauskis** [comment]
I agree, let's close this one.
