### ISSUE TITLE
GPS of ButterflyCount app not working well

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#337]
Hello @kazlauskis. I received some comments from Irma Wynhoff and Chris van Swaay that the GPS of the ButterflyCount app is not working well with the 15-min counts, doing huge jumps while recording the route. They have Android and iOS phones, so it doesn't look like it is an error of the phone system. I attach a picture from Irma's route, with the huge jumps of several km (see the final monitoring area and jumps between small towns)
![IMG-20210421-WA0000](https://user-images.githubusercontent.com/25052478/116100398-2a0d4d80-a6ad-11eb-877f-f210f7773a2d.jpg)

I tried today two 15-min counts in my neighborhood and in principle, the GPS works well, doing big jumps when the phone is blocked or switching to another app/part of the phone (as we know). The only thing I saw quite strange, it was the end of my first count the GPS didn't record well my position, so I started the second 15-min count the starting point was incorrect with 20-30 metres of error from my position. Later walking the GPS managed to come back to my real position (after several minutes).

I think I will recommend on the guides to check always the route on the map and edit if there are big differences in the route done. I hope you can resolve this issue soon. Thank you so much in advance.

**Comment by Irmawyn** [comment]
This is why we love butterfly work so much!

Love, Irma


----------------------------------------------------------------------------------------

Dit bericht is verzonden door / This message was sent by

Dr. Irma Wynhoff

De Vlinderstichting / Dutch Butterfly Conservation

Butterfly Conservation Europe

Postbus 506 / P.O. Box 506

NL - 6700 AM  Wageningen

Mennonietenweg 10, Wageningen

[T]  (+31) 0317 467346 / direct (+31) 0317 467320 / mob (+31) 06 44 67 46 49

[E}: ***@***.******@***.***>,

[I]: vlinderstichting.nl<http://www.vlinderstichting.nl/>  bc-europe.e<http://www.bc-europe.org/>u  facebook.com/bluesinthemarshes/<http://www.facebook.com/bluesinthemarshes/>

-----------------------------------------------------------------------------------------

Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------------------------------------------------------------------

No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.



________________________________
Van: Cristina Sevilleja ***@***.***>
Verzonden: maandag 26 april 2021 16:33
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [BiologicalRecordsCentre/ABLE] GPS of ButterflyCount app not working well (#337)


Hello @kazlauskis<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkazlauskis&data=04%7C01%7Cirma.wynhoff%40vlinderstichting.nl%7C190d4a5b4ce6435bfb7508d908c04e0b%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637550444307512777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b6BTwH8%2B%2FMVFIn%2FMnhEGuaM%2BLB6%2Bmb64tDkn%2FjR3gxA%3D&reserved=0>. I received some comments from Irma Wynhoff and Chris van Swaay that the GPS of the ButterflyCount app is not working well with the 15-min counts, doing huge jumps while recording the route. They have Android and iOS phones, so it doesn't look like it is an error of the phone system. I attach a picture from Irma's route, with the huge jumps of km (see the final monitoring area)
[IMG-20200110-WA0013]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F25052478%2F116099823-a5223400-a6ac-11eb-976b-13c4bc2c3075.jpg&data=04%7C01%7Cirma.wynhoff%40vlinderstichting.nl%7C190d4a5b4ce6435bfb7508d908c04e0b%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637550444307522772%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xUW1jo9Lb1guLD%2BDmfJrJw0tsComDRfHI%2B9VQTW8Re4%3D&reserved=0>

I tried today two 15-min counts in my neighborhood and in principle, the GPS works well, doing big jumps when the phone is blocked or switching to another app/part of the phone (as we know). The only thing I saw quite strange, it was the end of my first count the GPS didn't record well my position, so I started the second 15-min count the starting point was incorrect with 20-30 metres of error from my position. Later walking the GPS managed to come back to my real position (aftter several minutes).

I think I will recommend on the guides to check always the route on the map and edit if there are big differences in the route done. I hope you can resolve this issue soon. Thank you so much in advance.
