### ISSUE TITLE
Problems with one user on the app and the website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#338]
One user cannot submit his 15-min counts registered with the app (it looks like the app crashed) and he doesn't want to lose the data. Now he cannot enter the visits of his transect through the eBMS website...

I suggested signing off and signing in again on the app but saving the data for later submit it and use another browser for the website.The website and app work perfectly for me and when I masquerade as him on the website as well. Any other suggestions for the user? @DavidRoy @kazlauskis 

Indicia Warehouse User ID: 251190
Phone details: Huawei p30 pro, Android Orange Software EU 11.0.0.2 (CT) 11.0.0.147 (C431E8R2P3), ButterflyCount app version 1.10

attach a picture of the server error on eBMS website
![visits not allowed_Felix](https://user-images.githubusercontent.com/25052478/117264734-cd9bf200-ae53-11eb-9f55-2e73a0fbd9de.png)

**Comment by kazlauskis** [comment]
@CrisSevilleja Is the issue here that this person can't upload a 15min survey from the app? Is there some error or does it just silently fail? This person has created 2 accounts of which only one is verified.

**Comment by CrisSevilleja** [comment]
The user cannot log in and he got the message the user and password were incorrect when he reset the password several times. 

Yes he has two accounts and he knows one is verified, it is the one he uses to submit data on the website. He doesn't give me any information more and it is difficult to communicate with him by email... He didn't send me any screenshots or anything. I hope you can find the problem.

**Comment by kazlauskis** [comment]
I would need more information to help this person. Like a screenshot of the screen, which email is in use, time of the day that the login was made, which app version etc. as much as possible really as I can't see anything in the logs right now.
