### ISSUE TITLE
Create new site - on save should return to My sites list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#34]
After creating a new site, page should goto:
http://dev-butterfly-monitoring.pantheonsite.io/sites-list

Current it goes to http://dev-butterfly-monitoring.pantheonsite.io/ebms-site-details

**Comment by Gary-van-Breda** [comment]
Can I clarify this? I thought when a new site is saved, the page should re-open (with the same site) on the route tab, to allow the section routes to be entered.

**Comment by DavidRoy** [comment]
Yes, that’s better - reopen to draw route.  Thanks

**Comment by Gary-van-Breda** [comment]
@DavidRoy : following the changes I've just put on (see #33), I think this works now.

**Comment by DavidRoy** [comment]
Still returns to site details page for new site on save

**Comment by Gary-van-Breda** [comment]
@DavidRoy : New Code dropped into Dev (not Test yet).

**Comment by DavidRoy** [comment]
@Gary-van-Breda works well.  Please deploy to test

**Comment by Gary-van-Breda** [comment]
Deployed to Test and Live

**Comment by DavidRoy** [comment]
That works on test and live, thanks
