### ISSUE TITLE
Improve backend error messages

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#340]
Use better error/warning messages to indicate the account registration stage users have reached.

**Comment by DavidRoy** [comment]
Example improvement.
User has not activated their account but creates a survey.  This shows in their list of pending (see below).  But clicking on the 'Upload' button does nothing.  A warning message is required to inform recorder that they need to activate their account.  Also give the option to request a new activation email.

![cr](https://user-images.githubusercontent.com/2699478/118975070-7cb7ed80-b96b-11eb-9fa4-557f39855ac1.jpg)
