### ISSUE TITLE
15-min single species count missing real zero count

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#342]
My colleague Jurrien from Vlinderstichting did a 15-min single species count for a species but he didn't found any individual during the 15 minutes. He was wondering if he submits that 15-min how the system knows it was a zero count for which specific species because he didn't write it because there were not individuals. 

Maybe we can include a request to enter the species name if there were not individuals to registers after the 15-min and in that way, make a real zero count for that specific species. There is not a hurry in implementing this function but it is a bug of this specific 15-min count. 

Thanks, @kazlauskis @DavidRoy

**Comment by DavidRoy** [comment]
This should result in a sample being created (i.e. with location, date, weather information) but no associated occurrences (species recorded).  The 15-min count should be submitted as this gives information on zero counts

**Comment by CrisSevilleja** [comment]
Indeed, the sample will be submitted and several variables are recorded, but currently, it is not possible to know which species you are recording if you don't have individuals.

**Comment by DavidRoy** [comment]
I'm not sure I understand what you mean.  If you have no individuals for a species then the count is zero?  For most species, the count is zero in any timed count....

**Comment by kazlauskis** [comment]
I think Cristina is saying that the survey at the moment doesn't capture the taxon if the abundance is 0. In the database, it will look like there is a survey sample but you won't know which species this is for.

**Comment by DavidRoy** [comment]
ah, sorry.  I had missed that this is related to the '_single-species_' count.  My bad!
is one option to create an occurrence record but with occurrence.zero_abundance = TRUE

**Comment by CrisSevilleja** [comment]
ah sorry, I didn't explain well, but yes it is like Karolis mentioned it. Thanks!

**Comment by CrisSevilleja** [comment]
Hi @kazlauskis did you apply this already? I was thinking that the option of the zero_abundance could work but currently, when you add a new species immediately the app gets the coordinates and put directly 1 individual by default.
Maybe we can resolve this issue of having a real zero count for the 15-min single species count, by asking at the end of the 15 minutes which species was being recorded to enter that species as a real zero.

**Comment by kazlauskis** [comment]
Yes, this could work but I haven't had the time to work on this yet.
