### ISSUE TITLE
eBMS website: My walks don't match with annual Report visits

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#344]
The user Indicia Warehouse User ID: 295127 realised one problem on the eBMs website. He registered one visit every week this year visualizing well the visits after submitting records on the My walks page. When he wanted to check his visits at Annual Report page https://butterfly-monitoring.net/annual-report one visit was missing in week 16 when it was registered without problems. 

When downloading the data that missing week was present and the rest of the data as well. It is not such a big issue but this volunteer was confused and maybe it can happen to others. Any idea how to solve it? @DavidRoy 

<img width="590" alt="Villanueva del Pardillo - week 16" src="https://user-images.githubusercontent.com/25052478/120204880-97227e80-c229-11eb-97f4-ccf758bc99f3.PNG">
<img width="598" alt="Villanueva del Pardillo - week 16 (2)" src="https://user-images.githubusercontent.com/25052478/120204890-9984d880-c229-11eb-8954-6d41f865d80d.PNG">

**Comment by Gary-van-Breda** [comment]
There is a mismatch in the "week" definitions between the my walks and annual summary pages:

- for the My walks it starts on Mondays, and week one includes 1st January.
- For Annual summary, week one starts on 1st Jan. 

This means week 16 for the Annual summary starts on the 16th April, and ends on the 22nd: there are no walks in this period, so I would expect it to be empty. 
I assume we wish to harmonise it between all the forms - which definitions is the correct one?

**Comment by CrisSevilleja** [comment]
Thanks, Gary, I didn't realise about the mismatch on the starting day for the week in my walks and annual summary page. So now I understand why week 16 is empty on the annual summary page because that "week" there was not any visit. However, the next week the 17 there are two visits, then the annual summary page should sum both visits. I checked some of the numbers and week 17 doesn't show the sum of the two visits (14-05 and 19-05) neither the numbers of one of the visits. 

For me, it will make more sense to start the week with Mondays as in My Walks, but I don't know how to place it for the 1st of January. Maybe starting with the Monday of that week although it can be from the year before?

**Comment by Gary-van-Breda** [comment]
At the moment, the annual summary does not sum multiple walks in a week, but averages them.
@DavidRoy : what are your preferences on both fronts?

**Comment by DavidRoy** [comment]
@Gary-van-Breda it should be an average when multiple walks per week as otherwise the plots will not make sense

Week 1 should always start on 1st January, so the start of the week will change each year.  This makes most sense to interpret butterfly numbers

**Comment by Gary-van-Breda** [comment]
@DavidRoy @CrisSevilleja 
I have left the Annual summary averaging multiple walks. I have also left its week definition alone, as it is the correct one.  
I have changed the week definition on "My walks" and "Scheme walks", so that week one starts on the 1st January. This means that for 2021, the first day of the week as shown in the grid, is a Friday. It may be worth communicating this to the users, as this may cause some confusion, especially as this is a change from how it was displayed up to now.

**Comment by CrisSevilleja** [comment]
Okey good to know the changes and that now both pages, My walks and annual summary show the same week. I will mention how the visits are shown on the week on the page text and announce it to the volunteers. Thanks
