### ISSUE TITLE
Download files for ButterflyCount data

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#345]
Reports required for download files (via website links and API)

1. 15 minute count surveys (survey.id = 565)
SampleID
Date
Start Time
End Time
Recorder Name
Area sampled (m2)
Geom (GEOJson?)
% Cloud
Temp (Deg C)
Wind Direction
Wind Speed
Species (preferred latin name)
Count (summed over sub-samples/occurrences - #note that precise survey option include occurrence for each individual butterfly)

2. Single-species 15 minute count (survey.id = 645)
SampleID
Date
Start Time
End Time
Recorder Name
Area sampled (m2)
Geom (GEOJson?)
% Cloud
Temp (Deg C)
Wind Direction
Wind Speed
Species (preferred latin name)
Present/absence (true/false)
Count (integer value or set to zero if presence = false)

3. Detailed occurrences (survey.id  = 565,645).  Restrict to 'precise' surveys, e.g. where sub-samples are captured
SampleID
OccurrenceID
Date
Recorder Name
Latitude
Longitude
Co-ordinate precision
Species (preferred latin name)

@johnvanbreda please estimate when you can have these reports available

**Comment by johnvanbreda** [comment]
Hi @DavidRoy we already have the following page which covers survey 565: https://butterfly-monitoring.net/downloads. Is this requirement an extension of that page, or a new page?

Should we be looking to download samples from the PostgreSQL table, accepting lower performance, as opposed to Elasticsearch where empty samples will be omitted?

**Comment by DavidRoy** [comment]
@johnvanbreda thanks.  Extending the existing page to reflect the more detailed data from the app.

Immediate-term, PostreSQL is ok.  Longer term, everything from ElasticSearch (will require extending to handle all sample attributes, sub-sample structure and samples without occurrences?)

**Comment by johnvanbreda** [comment]
Thanks @DavidRoy. Also - is GeoJSON a requirement, or is WKT (well-known text) OK? E.g.
```
POLYGON((-3.83622531847131 52.9755482703573,-3.83626342172516 52.9764467282979,-3.83477495806397 52.9764697192794,-3.83473688564969 52.9755712605935,-3.83622531847131 52.9755482703573))
```
The latter is slightly easier, but I can do GeoJSON if required.

**Comment by DavidRoy** [comment]
Start with WKT but having GeoJSON is a good option to have going forward?

**Comment by johnvanbreda** [comment]
Sorry @DavidRoy - thinking of questions as I go along - will reports 1 & 2 output a row with a blank species, if nothing was recorded for the sample? Or is it only a report summarising the species within the samples?

**Comment by DavidRoy** [comment]
@johnvanbreda 
report 1 only includes species within the sample/sub-sample
report 2 to report the target species with a zero count if not present, and absent in presence/absence column.  I believe the app submits an occurrence record but with zero_abundance = true

happy to chat through this via zoom if easier

**Comment by johnvanbreda** [comment]
@DavidRoy I've added a report for 1 & 2 to the demo page (sent via email). Question regarding report 2, if a species has presence=true, but no count data (which seems quite common in the data on the warehouse) then what should be output?

**Comment by johnvanbreda** [comment]
All 3 reports are now on the text page with just the above question outstanding.

Once checked, we need to decide where in the list of reports on the existing download page these should be inserted, or if they replace existing ones. I also need to integrate the non-Elasticsearch reports with the permissions filter.

**Comment by DavidRoy** [comment]
@johnvanbreda nearly there.  A couple of comments on the reports on the dev site.
1. The third link on the page should be labelled 'Download species occurrences from **timed-count samples**..' - it currently is labelled '....from transects...'
2. The first report looks good - Download timed-count samples with species
3. The second report does not include all the data.  'Download single species timed-count samples with species'.  Only three records and the record count is zero in all cases?  There are 13 samples from this survey.
4. The third report 'Download species occurrences from transects' is good other than the [Co-ordinate precision] field is always set to 50 so does not include the app GPS precision value?

**Comment by johnvanbreda** [comment]
@DavidRoy 
1. Done
2. Good.
3. I've corrected the logic in the record count (although this just results in not recorded). However, there are 11 samples in this polygon for survey ID 645 and only 3 are top level, 8 are child samples providing an exact location for each species. So the number of rows being 3 is correct from what I can see.
4. I can't see any GPS precision value attribute for the 2 surveys that this report includes data for. 50 is just the default value. Is the app actually collecting this and, if so, where does it put the value @kazlauskis?

**Comment by kazlauskis** [comment]
@DavidRoy the app doesn't collect the GPS accuracy information yet. Shall I create a ticket to add this?

**Comment by DavidRoy** [comment]
4. @kazlauskis yes, please add a ticket for capturing GPS accuracy information

3. @johnvanbreda I'll test survey 645 but I'm surprised there is no count information in the files.  Also, if I filter to Src  = 118|645 on https://butterfly-monitoring.net/elastic/all-records I see 13 records from 7 samples (combination of date, location, recorder)

**Comment by johnvanbreda** [comment]
@DavidRoy the test page is configured to show only data from Italy. The following SQL lists the parent sample IDs, child sample IDs and species names:
```sql
select distinct s.id, sc.id, cttl.preferred_taxon
from cache_samples_functional s
left join cache_samples_functional sc on sc.parent_sample_id=s.id
left join occurrences o on o.sample_id=sc.id
left join cache_taxa_taxon_lists cttl on cttl.id=o.taxa_taxon_list_id
where 216069=ANY(s.location_ids)
and s.survey_id=645
and s.parent_sample_id is null
```
There are 8 records, but only 3 unique combinations of taxon and parent sample ID so the report should include 3 rows.

**Comment by DavidRoy** [comment]
@johnvanbreda thanks, I'd missed this was restricted to Italy for the test page.  That explains the numbers.  The only remaining issue is why the count is missing a value?

**Comment by johnvanbreda** [comment]
@DavidRoy the following query uses a sub-query to list the relevant occurrence IDs, then joins across to find all the attributes that are actually recorded for these. The only attribute present is Life Stage:
```sql
select distinct a.caption
from occurrence_attributes a
join occurrence_attribute_values v on v.occurrence_attribute_id=a.id
where v.occurrence_id in (
	select distinct o.id
	from cache_samples_functional s
	left join cache_samples_functional sc on sc.parent_sample_id=s.id
	left join occurrences o on o.sample_id=sc.id
	left join cache_taxa_taxon_lists cttl on cttl.id=o.taxa_taxon_list_id
	where 216069=ANY(s.location_ids)
	and s.survey_id=645
	and s.parent_sample_id is null
)
```

**Comment by DavidRoy** [comment]
@kazlauskis is there an issue capturing the count for the single-species 15m count. I noticed there was no count within the record details, e.g. https://butterfly-monitoring.net/mydata/details/record?occurrence_id=20656726

Or was the idea to count the number of occurrences as each individual is given an occurrence?

**Comment by kazlauskis** [comment]
Yes, that's correct, in the app there isn't a separate count attribute, the number presented is the number of the occurrences i the list.

<img width="220" alt="Screenshot 2021-06-22 at 16 00 54" src="https://user-images.githubusercontent.com/7383162/122948795-17dd2200-d373-11eb-97ba-81dbeb09659f.png">

<img width="221" style="display:inline-block" alt="Screenshot 2021-06-22 at 16 00 44" src="https://user-images.githubusercontent.com/7383162/122948793-17448b80-d373-11eb-8a6c-1f62981e40ec.png">


<img width="228" style="display:inline-block" alt="Screenshot 2021-06-22 at 16 00 41" src="https://user-images.githubusercontent.com/7383162/122948790-16135e80-d373-11eb-9c16-0fe03381e4eb.png">

**Comment by DavidRoy** [comment]
@kazlauskis that makes sense
@johnvanbreda can you update the report count to be based on number of occurrences within the sub-samples

**Comment by kazlauskis** [comment]
Worth noting that some of the occurrences might not have a subsample wrapper (in case the GPS has failed). Also, a subsample can only have a single occurrence in the app.

**Comment by CrisSevilleja** [comment]
a great job was done in the reports @johnvanbreda  a few things to add: 

1. In the third report, "species occurrences from timed-count samples" I am missing the time of the occurrence was taken, I think it is information recorded on the app as well as the precise coordinate that David mentioned before. 

2. The recorded area is saved on the first report, however, I was thinking that maybe some users would like to get the coordinate routes in other formats as .kml or .shp, there are people not handy with data managing and using only GIS programs, for us it doesn't make sense separately files per route by I am sure for other yes. What do you think @DavidRoy ? should it be provided another file with all the recorded 15-min count routes in a GIS file or added as an option in each sample done? 

The rest is quite good or has been mention before the missing parts. Thank you!

**Comment by johnvanbreda** [comment]
@DavidRoy I've changed the way the count works on the 2nd report as described. On the third report - @CrisSevilleja is suggesting adding the time of the occurrence - we have the start time and end time of the sample in the sample data I think. Are there any other sample attributes that I should include on this report?

Also let me know about the 2nd idea in the post above.

**Comment by DavidRoy** [comment]
@johnvanbreda I agree that time would be a good addition.  This would be the time of the occurrence record creation if the app captures and submits this (e.g. date extracted from occurrence.created_on ?)
Thanks for fixing the 2nd report which now gives what's needed

On the second point about GIS formats, the advantage of GEOJSon is that it fits in a table of records.  Could other GIS formats fit in this structure? We have a separate download for the tracks in .shp and .kml format.  Link given on the Downloads page (https://butterfly-monitoring.net/downloads) to https://butterfly-monitoring.net/my-timed-counts-samples-gis-download.  Once the ButterflyCount reports are ready we need to provide links/explanation on the downloads page

**Comment by johnvanbreda** [comment]
I've included the time formatted from occurrence.created_on as a new column in the third report. But, I can see a couple of problems with this:
1. The time will capture when the record was submitted to the warehouse, not when the record was added to the app. I've not used this app but if it is similar to the iRecord app then the record might not be synced to the warehouse till sometime after it was input.
2. The time captured will be in the timezone of the server, not the timezone of the app.

So, I wonder if the sample start time is a more reliable value?

**Comment by DavidRoy** [comment]
@johnvanbreda good point.  I suggest you remove this from the report for now and I'll pick up the options with karolis.  I think it's best for this to come from the app clock and to store in a occurrence attribution

**Comment by johnvanbreda** [comment]
Agreed and done.

**Comment by DavidRoy** [comment]
@johnvanbreda now the report formats are setup, can you integrate with the permissions on the site and make available via: https://butterfly-monitoring.net/downloads

**Comment by johnvanbreda** [comment]
@DavidRoy do the new buttons just go at the bottom, inside the 15 minute timed-count downloads section header? Or do you want some other ordering or section header for them?

**Comment by DavidRoy** [comment]
@johnvanbreda yes, within the 15 minute timed count downloads section

**Comment by johnvanbreda** [comment]
@DavidRoy done.

**Comment by DavidRoy** [comment]
@johnvanbreda I've tested in a few cases and works well.
However, when masquerading as user: https://butterfly-monitoring.net/nl/users/chrisvanswaay there is an extra drop-down to selected 'all data' or 'Netherlands' but the download files are empty.  Is there a conflict between roles?

**Comment by johnvanbreda** [comment]
@DavidRoy fixed - the reports had the region as a mandatory parameter whereas it needed to be optional for users with all data access.

**Comment by CrisSevilleja** [comment]
Are the download reports for 15-min count active on the website https://butterfly-monitoring.net/elastic/my-records? I am not able to see those buttons yet

**Comment by DavidRoy** [comment]
@CrisSevilleja can you raise this as a separate issue - download via my-records
@johnvanbreda when masquerading as user: https://butterfly-monitoring.net/nl/users/chrisvanswaay there is still an extra drop-down to selected 'all data' or 'Netherlands' and the download files are empty.

**Comment by johnvanbreda** [comment]
@DavidRoy the only report I find is empty is the "Download single species timed-count samples with species (*.csv)" report, when Netherlands is selected. That's because although there are 3 samples for survey ID 645 in the Netherlands, none appear to have occurrences and this report only includes samples with occurrences.

**Comment by DavidRoy** [comment]
@johnvanbreda thanks.  I'll ask others to test the downloads.  Can you remind me why https://butterfly-monitoring.net/nl/users/chrisvanswaay has the option for all data/Netherlands.  Does this relate the verification role and filters?

**Comment by johnvanbreda** [comment]
@DavidRoy yes, there is a verification filter for all records which is causing the all data option. The Netherlands option comes from the Drupal profile scheme coordinator configuration.

**Comment by DavidRoy** [comment]
@johnvanbreda the 'Download timed-count sample data' does not include samples without any occurrences (i.e. no species were seen).   Including **all** samples is essential for analysis purposes.  An example of a missing sample.id is https://butterfly-monitoring.net/mydata/samples/details?sample_id=14988363 for user = https://butterfly-monitoring.net/nl/users/chrisvanswaay.

The tracks for samples-without-occurrences are also essential

**Comment by johnvanbreda** [comment]
In https://test-butterfly-monitoring.pantheonsite.io/sample-downloads-test, there is a new download linked to the new Elasticsearch samples index (currently populated only for EBMS and Fit counts). This includes zero occurrence samples. Once Gary gives the all-clear to upgrade the code, I can swap this download for the "timed-count sample data" download on the live site. 

But, note that this download is limited to survey ID 565, but the example record you gave above (14988363) is from survey ID 645 so it is not included. Is this survey limitation correct?

As far as I can see the tracks downloads should already include samples without occurrences. Is there an example where this is not happening?

**Comment by DavidRoy** [comment]
Thanks @johnvanbreda.  A couple of replies:
1. Survey 565 is for 15-minute timed counts.  We will need an equivalent report for Survey 645 which is 'single-species' 15-minute timed counts.  The same basic survey but the 'single species' version only targets one species
2. The download file masquarading as Chrisvanswaay and selecting Netherlands data, doesn't seem quite right.  I don't think the sub-samples have been aggregated?  There are many rows where the sample attributes are missing (e.g. Area sampled) and occurrence = 1

**Comment by johnvanbreda** [comment]
1. I've added a second button for survey 645.
2. I was thrown a bit by the fact that survey 565 data started off as flat, but has had 2 sample levels since April 2021. I think this should be OK now?

I thought the plan was for the app to record an individual count of 1 as a default? At the moment there are lots of data with no individual counts so this column isn't reliably populated in the download.

**Comment by johnvanbreda** [comment]
@kazlauskis for survey 645 - the zero_abundance=true value is fine. For data added prior to the new app version, am I right in saying that the occurrence was missing, so we don't know what was searched for? This seems to be the case - e.g. https://butterfly-monitoring.net/mydata/samples/details?sample_id=15194638. @DavidRoy is it OK therefore that the single species timed count only includes the samples where we actually have an occurrence (presence or absence) in the database?

**Comment by johnvanbreda** [comment]
Also, I can't see any zero abundance data for survey 645, presumably this is just because there hasn't been any submissions where the searched species wasn't observed yet?

**Comment by johnvanbreda** [comment]
@DavidRoy the single-species occurrences download now covers all the columns from the samples download. If the data are structured as described above, then the samples download becomes unnecessary for the single species searches. Shall I remove it?

**Comment by DavidRoy** [comment]
@kazlauskis.  Can you confirm the functionality for the single-species survey.  There should be always be an occurrence submitted.  Either with a count or zero_abundance=true

@johnvanbreda, yes the single-species samples download is redundant and can be removed.

**Comment by johnvanbreda** [comment]
The single-species samples download has been removed.

**Comment by kazlauskis** [comment]
> @kazlauskis for survey 645 - the zero_abundance=true value is fine. For data added prior to the new app version, am I right in saying that the occurrence was missing, so we don't know what was searched for? This seems to be the case - e.g. https://butterfly-monitoring.net/mydata/samples/details?sample_id=15194638. @DavidRoy is it OK therefore that the single species timed count only includes the samples where we actually have an occurrence (presence or absence) in the database?

There should always be an occurrence, that was so even before the last update. Having said this, there is currently a bug (missing validation) that allows to upload a survey without any species added to it. Essentially it allows to upload a top-level sample alone. @Vilius-Stankaitis is fixing this right now and it will come out today or shortly after as (v.1.14.1).

**Comment by DavidRoy** [comment]
Closing. Will raise more specific issues as required
