### ISSUE TITLE
Verification system on the eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#347]
When I enter on the Verification page it gives the constant message "Elasticsearch query failed". If you can fix it @Gary-van-Breda 
I was wondering, Is the verification system currently working? I mean it registers as correct records based on flight season and distribution?

Also, @DavidRoy  I want to edit some records of Coenonympha orientalis that were wrongly recorded in the 15-min Counts but every time I try to do it, the page doesn't allow me. Do you need to give me rights for that?
I will send you the updated list of the Lithuanian common names that have some wrong species and for that reason, the Lithuanian coordinator submitted wrongly C. orientalis instead of C. pamphilus. 

Thank you

**Comment by DavidRoy** [comment]
@johnvanbreda can you pick up the two things in this issue.
- error message on the verification page
- enabling verifiers to edit records

@CrisSevilleja we haven't implemented any automatic rule-checks the data

**Comment by johnvanbreda** [comment]
@DavidRoy both issues should now be sorted. I copied the edit generic record form over from iRecord.

**Comment by DavidRoy** [comment]
thanks @johnvanbreda 
can you check @CrisSevilleja, and close if resolved

**Comment by CrisSevilleja** [comment]
The verification page is not giving an error message anymore. Although I cannot edit the records I want I don't think is a problem with that page, it is regarding the common species list. I open another issue for that. 

Thank you for the prompt reply.
