### ISSUE TITLE
Capture GPS accuracy information

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#348]
The app currently doesn't store the accuracy information for the top survey sample when saving the walked trail as a GeoJSON shape as well as for the subsamples (precise occurrence locations). We should add this.

#345

**Comment by Vilius-Stankaitis** [comment]
Would like to capture altitude as well? @DavidRoy

**Comment by DavidRoy** [comment]
yes please, altitude and its accuracy
