### ISSUE TITLE
ButterflyCount to capture time of occurrences

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#349]
request is to capture the time of each occurrence record from the precise 15m survey.  Time taken from the phone clock and stored within an occurrence attribute

links to report requirement BiologicalRecordsCentre/ABLE#345

**Comment by johnvanbreda** [comment]
@DavidRoy did you mean to close this or #345?

**Comment by DavidRoy** [comment]
Neither!

**Comment by kazlauskis** [comment]
@johnvanbreda we are adding the time of sighting occurrences. This links to the report you have developed in the mentioned ticket. Would you like us to send the time in specific format e.g "hh:mm" or a do you want a full ISO string?

**Comment by kazlauskis** [comment]
@johnvanbreda we'll be sending ISO strings, let us know if you wanted this different.

**Comment by johnvanbreda** [comment]
@kazlauskis ISO format should be fine as it's stored in a text field.
