### ISSUE TITLE
Move site onto test site, linked to live warehouse

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#35]
Move site onto:
http://test-butterfly-monitoring.pantheonsite.io/

including linking to live Indicia Warehouse 2

**Comment by BirenRathod** [comment]
@DavidRoy 
Moved dev site onto test and linked to live warehouse2.

**Comment by DavidRoy** [comment]
thanks

**Comment by Gary-van-Breda** [comment]
Re-opening this: the move to the Live warehouse seems to be producing errors on some pages (like the walk data entry), and some of the individual pages need re-configuration.

**Comment by DavidRoy** [comment]
@BirenRathod can you look into this please, reconfigure pages as necessary

**Comment by Gary-van-Breda** [comment]
@DavidRoy , @BirenRathod : I think it'd be best if I do it.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Yes, please do so. Thanks.

**Comment by Gary-van-Breda** [comment]
I've done this - moved over all the form configuration, and checked the dev site as well.
I've put a fix in for the transect allocation, and pushed it to both dev and test.

When we transfer to Live, as the test site is already pointing at the Live warehouse there will not need to be the same level of reconfiguration.
Further down the line, when we move warehouse, then the form configurations will have to be revisited as well.

**Comment by Gary-van-Breda** [comment]
Currently all the forms reference the EBMS Butterflies list - do you wnat them moved over to the ABLE butterfly list?

**Comment by DavidRoy** [comment]
No, stick to eBMS list in the short term

**Comment by Gary-van-Breda** [comment]
Then I think this can be closed again....

**Comment by DavidRoy** [comment]
Thanks
