### ISSUE TITLE
download 15-min count via my-records

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#350]
On the page My 15-min count https://butterfly-monitoring.net/elastic/my-records it is still not possible to see the buttons to download the different reports.  
@johnvanbreda

_Originally posted by @CrisSevilleja in https://github.com/BiologicalRecordsCentre/ABLE/issues/345#issuecomment-867618636_

**Comment by johnvanbreda** [comment]
@CrisSevilleja at the bottom of the Records tab on this page, you should be able to see a Download button. If you click this then you should be transferred to the Downloads tab where a download of your records will be prepared.

**Comment by CrisSevilleja** [comment]
Okey, I didn't understand this simple process... thank you so much for explaining it to me. Everything works well thanks!
