### ISSUE TITLE
Improve editing of 15minute count data

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#352]
@johnvanbreda links to #351 and #345 
require improved functionality to edit 15minute counts from the app

**Comment by johnvanbreda** [comment]
Is there anything specific required here @DavidRoy?

**Comment by DavidRoy** [comment]
@CrisSevilleja to define requirement

**Comment by CrisSevilleja** [comment]
How to do the edition of the 15-min counts' records:

- Starting on the Sample details page and add the edition button.
![eBMS edit records - explanation1](https://user-images.githubusercontent.com/25052478/127487858-4cf4a2c5-b9d7-47a1-b826-62f4f813b759.png)

-That will enter in _Edit Sample Details page_, where the map with the sample route and every individual coordinate is shown. I took the current table of the edit page https://butterfly-monitoring.net/enter-app-record?sample_id=6706366 where all the recorded species are shown with the abundances, comments, media and life stage.
![eBMS edit records - explanation2](https://user-images.githubusercontent.com/25052478/127487904-ca908e00-2d8b-46d9-babb-a6b73b9ad663.png)

- How to edit a record: you can click on the map or on the row which will activate and show all the coordinates of the individual. With the row activated then you can edit everything: the species name, abundance, delete one coordinate (= one individual), add, see or delete pictures of that record. At the bottom of the list, there should be an option to add a new species. 
How to add a new individual of a species already seen? I think the best will be to add the coordinate clicking on the map and write the species name; if that species is already on the list, it would add that new coordinate to that species (this part is not completely clear to me or not sure it is possible to do it like that).
![eBMS edit records - explanation3](https://user-images.githubusercontent.com/25052478/127487920-dab54f8e-c252-4148-b885-106b67e8b9eb.png)

-Below the species table, it is showing the rest of the variables that can be edited. I added two new things, which species groups have been recorded (by default butterflies) and how many recorders were counting, by default 1 with the option to add new (I have to ask Karolis to include this on the app). 
![eBMS edit records - explanation4](https://user-images.githubusercontent.com/25052478/127487978-57b02c42-3a3c-4ced-8f87-d9e65ec76bb2.png)


I hope I explained it well and it makes sense to do the editions like that. Thank you @johnvanbreda

**Comment by DavidRoy** [comment]
@johnvanbreda are you ok to pick this up after #351 
@CrisSevilleja one thing that might need adding is the ability to change the species name on one occurrence?

**Comment by DavidRoy** [comment]
@johnvanbreda can you add functionality for editing the species name/abundance for an individual occurrence

**Comment by CrisSevilleja** [comment]
Please, also add the ability to edit the route (especially to correct GPS errors). Thanks

**Comment by DavidRoy** [comment]
Closing this issue so final changes can be picked up through more specific issues
