### ISSUE TITLE
Remove the maximum 35C temperature restriction ☀️

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#354]
Users are recording in 35C+ temperatures and we'd like to capture that in the survey. 
- [x] Add new warehouse IDs
- [x] Update app ranges
- [x] Update app Weather API mapping

**Comment by kazlauskis** [comment]
@johnvanbreda @Gary-van-Breda What is the best way to remove the restriction? Shall we just add another +15C values to the dropdown ranges or is there some better way?

**Comment by johnvanbreda** [comment]
I'm not sure I'm particularly keen on the way it's been setup, using terms to map directly to a range of numbers, but as we have already gone down that route it may be easier just to add extra terms as you suggest. 
An integer field with max/min is cleanest, but it doesn't have a "Not recorded" value.

**Comment by kazlauskis** [comment]
@DavidRoy what do you think, should we just add +15C values to the range? This will then show up in the app and the website forms.

**Comment by DavidRoy** [comment]
@kazlauskis yes, add extra temperatures to the term list seems best

**Comment by kazlauskis** [comment]
Thanks, we'll make it 10-50C then. Would it make sense to make it 10-40C and a 40C+ option for anything above 40?

**Comment by DavidRoy** [comment]
Go with 10-40C and with 40+ as the final value.  We can always change this again if there are people crazy enough to be recording in such conditions!
