### ISSUE TITLE
Possibility to download the Transect visit summary in a file

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#355]
Some volunteers asked for the possibility to download a transect visit summary after they have entered the transect data. This summary should have all the information about the visit (as shown in the picture): 
- Transect date and time
- Recorder name
- Environmental variables: temp, % clouds, wind and notes
- Species and abundances per section
- Total number of individuals and species* (variables not included yet on the website, good to include if possible)

All this information organised in a pdf or/and .cvs to be able to download after entered the visit data. For example, to click on a button to produce the summary report or something like that and produce the files to download. 

<img width="349" alt="transect visit summary" src="https://user-images.githubusercontent.com/25052478/124922052-65a38c80-dff9-11eb-941c-0499b748d56f.PNG">

This possibility will give them more security to save their data by themselves. Some of the volunteers don't know how to download the data from the Annual Report page.

Thank you in advance @DavidRoy

**Comment by CrisSevilleja** [comment]
One small remark, if possible, only include the species with abundances for the visit of the summary, not the complete list that appear by default (in some transects the list is quite long). thank you

**Comment by Gary-van-Breda** [comment]
New download button included at bottom of the species grid page.

**Comment by CrisSevilleja** [comment]
perfect. I have already seen it and it works well. Thank you so much.
