### ISSUE TITLE
15-min single species count unable to do more than one count

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#356]
@kazlauskis  @DavidRoy 
Jurrien van Deijk, my colleague at the Vlinderstichting trying to use the 15min single species count method, he got some error messages while doing it today: "I got this message when I want to do a second 15 minute species specific count. I can upload it, but can't do the next one."

First image: er bestaat een eerder concept. Wilt u hiermee doorgaan? -> There is a previous concept. Do you want to continue with it? 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/25052478/125077821-d4e4b380-e0c1-11eb-9c39-56dcfab51446.png)

Second image (the count saved): Deze waarneming is ingediend en kan niet meer gewijigd worden binnn de app -> This observation has been submitted and can no longer be changed within the app 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/25052478/125077837-d910d100-e0c1-11eb-98eb-7e0e45e66f4b.png)

The app appears in Dutch and the counts are not for Apollo, it is for the P proserpina
Any clue what is going on? Thank you in advance

**Comment by kazlauskis** [comment]
Thanks for raising it here. It seems that the app thinks the uploaded record is still a draft. I have fixed this issue now and will push the update asap. The current user can wait for the update which might take a few days for app stores to review or delete this uploaded survey on the device (swipe left to delete), this will also allow a new survey to be started.
