### ISSUE TITLE
Add new BMS options and languages to eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#357]
I realised some BMS are not available to choose when registering on eBMS. Please could you add the following BMS?
- Romania BMS
- France BMS
- Greece BMS
- Slovakia BMS
- Denmark BMS

And the languages Romanian and Danish. Thank you in advance. 

@DavidRoy

**Comment by DavidRoy** [comment]
@CrisSevilleja that should be setup.  Please close this issue if all ok

**Comment by CrisSevilleja** [comment]
Thank you @DavidRoy, I see you included all the new BMS on the system. 

I am missing the Danish and Romanian languages, not hurry to have it soon I am still looking for translators

**Comment by CrisSevilleja** [comment]
Hello again, 

@DavidRoy I realised I missed one scheme, the Madeira BMS, could you include it, please? 
sorry for not mentioning before

**Comment by DavidRoy** [comment]
@CrisSevilleja Madeira is not a country so doesn't fit.  Shall we look at options when the regional co-ordinator role in available?

**Comment by DavidRoy** [comment]
additional languages added now

**Comment by CrisSevilleja** [comment]
@DavidRoy okey, I didn't think about Madeira cannot be a scheme right now... okey let's investigate that option with the regional coordinator role. Thank you for the languages added
