### ISSUE TITLE
Nolink Menu options have a link 

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/ABLE#36]
Even though several menu items are specified as route:<nolink>, they seem to be being rendered with linkes: e.g. the "Sites" and "Walks" menu items in "My Data" are both no-link, but seem to have links to the ebms-sites-details page.

**Comment by DavidRoy** [comment]
@BirenRathod please investigate

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
I didn't get this. I know that Nolink menu option is not displaying link for anonymous users. Apart from that I'm can't see any problem.

**Comment by Gary-van-Breda** [comment]
I can see it for anonymous users...
If I go in as anonymou and select the Projects->BGEMS page, and then look under the My Data menu item, there is a single submenu "Reporting" which has a single entry "Mapping". The "Reporting" submenu item is configured to by a "route:<nolink>", but is rendered as an <a> with an empty href. This means that if the "Reporting" is clicked, it will reload the current page.
All the other "route:<nolink>" menu items act the same way: when clicked they reload the current page.

**Comment by DavidRoy** [comment]
@BirenRathod please can you resolve this, thanks

**Comment by DavidRoy** [comment]
Now resolved.  @Gary-van-Breda we can discuss further when next catch-up if any remaining issues
