### ISSUE TITLE
Submit abundance = 1 for each occurence within the 15-minute count samples

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#360]
links to BiologicalRecordsCentre/ABLE#351 
Makes data more internally consistent to set occurrence_attribute = abundance (quantity?) to equal 1 for each occurrence within a 15m count.  Extending the data submitted by the app

**Comment by kazlauskis** [comment]
@Vilius-Stankaitis could you squeeze this into your current update before the weekend?
