### ISSUE TITLE
Create SPRING tab; move ABLE tab on eBMS

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#361]
Hi, @DavidRoy I have updated the information on the ABLE tab https://butterfly-monitoring.net/able rephrasing everything to past tense to be accurate now the project is over. I think the ABLE tab should be moved to the Projects tab https://butterfly-monitoring.net/projects and create a new tab for the SPRING project. 

Please if you can do it, I can start filling in some information about the project. When you have time. 

thank you

**Comment by DavidRoy** [comment]
@CrisSevilleja I agree and I have moved the ABLE menu item under the projects menu.  I have created a blank page for SPRING as a new project menu item

SPRING will have its own website so I suggest we keep the SPRING page quite simple?
