### ISSUE TITLE
My 15-minute count samples - page lacking area sampled (sample attribute)

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#362]
The new samples summary page should have area_sampled within the data grid, e.g. it is currently lacking
https://butterfly-monitoring.net/mydata/samples

Also, should be included within the 'details view' of each sample, e.g.
https://butterfly-monitoring.net/mydata/samples/details?sample_id=15376801

**Comment by johnvanbreda** [comment]
I've added the column to mydata/samples, but it is only present for some samples. 

It does appear on the details view where present, e.g. https://butterfly-monitoring.net/mydata/samples/details?sample_id=7788860. The value is not present in the database on the example you gave.

Please close if OK.

**Comment by DavidRoy** [comment]
@kazlauskis - is there an issue with the app submission that area sampled is not in the database for this sample?  https://butterfly-monitoring.net/mydata/samples/details?sample_id=15376801

**Comment by kazlauskis** [comment]
Sure, we'll have a look at this tomorrow.
