### ISSUE TITLE
Expand Dutch species names list

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#366]
Would it be possible to add the Dutch vernacular names to one of the upcoming updates? So far only the Dutch names for species occuring in NL are shown, which means that outside NL people have to use scientific names for species not occurring in NL. No big deal for me, but more and more people only seem to use those names, so this will make the app more accessible to them.

#### Tasks:
- [x] Add extra names to Indicia Warehouse
- [x] Pull in the names to the app

**Comment by chrisvanswaay** [comment]
Hi @kazlauskis (and @CrisSevilleja and @DavidRoy) , I also attach the Dutch vernacular names for moths. We want to use them in January as we hope to use the 15 min counts in the Butterfly Count app for counts of https://www.vlinderstichting.nl/vlinders/overzicht-vlinders/details-vlinder/meidoornspanner. People would like to use the Dutch names. Would this be possible? So updating the Dutch vernacular names for butterflies and moths
[ABLE MothList 2020 07 08_incl_dutch_names.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/7726886/ABLE.MothList.2020.07.08_incl_dutch_names.csv)
?

If this is not possible, let me know, then we will have to use another app. Would be a pity though.

**Comment by larspett** [comment]
A related question - the id that you use, for instance 459359 for Acantholipes regularis, what does that refer to? I was thinking GBIF but taht does not seem to be the case (it is 4532488) ?

**Comment by chrisvanswaay** [comment]
No idea, @CrisSevilleja sent that to Jurrien van Deijk. Maybe she can help.

**Comment by CrisSevilleja** [comment]
The Dutch vernacular names were added to a list I had from the whole Lepidoptera group of ABLE. Therefore the ID number is referring to the eBMS ID we have in the system

**Comment by johnvanbreda** [comment]
@larspett it is an internally generated sequential taxon ID from the Indicia database.

**Comment by kazlauskis** [comment]
@johnvanbreda let me know once you have the common names in the warehouse and we'll pull it into the app.

**Comment by DavidRoy** [comment]
@johnvanbreda are you able to take this on?

**Comment by johnvanbreda** [comment]
@kazlauskis you should find all the names are in place now - are you OK to extract the IDs?

**Comment by kazlauskis** [comment]
We've pulled in the new moth common names in to the app now.

**Comment by CrisSevilleja** [comment]
With the new app update last June, the Dutch names applied on the system are not longer there @JurrienVanDeijk 
When being outside of the Netherlands and trying to use the Dutch names for species outside NL, they don't appear. 

The complete butterfly list for Europe was sent with the vernacular names in Dutch. It would be good to have a look for next update. Thanks

**Comment by CrisSevilleja** [comment]
Dutch common names don't appear on the ButterflyCount app, there were included before but with the last update those names dissapeared. 

Could be possible to include them again on the app specifically and also on the website? @kazlauskis @DavidRoy  @chrisvanswaay

**Comment by kazlauskis** [comment]
@CrisSevilleja I can still see the Dutch names in the latest app version, e.g searching Bosparelmoervlinder. Can you give an example of a species you can't find?

**Comment by chrisvanswaay** [comment]
The problem is not with Dutch species in NL (as Bosparelmoervlinder), but with non-Dutch species in other countries. As Wedewitje for Pieris ergane when on holiday in Croatia or Italy.

**Comment by kazlauskis** [comment]
Wedewitje isn't in the app because it isn't added to the database as a synonym for `Pieris ergane`. Is there another species name I can check that you find missing?

**Comment by chrisvanswaay** [comment]
Actually all European species have Dutch names, so it concerns the species which have never been reported from NL, e.g. almost all Erebia species (as Simplonbergerebia - Erebia christi, or the much more widespread 'gestreepte heivlinder' (Hipparchia fidia) ). I though you had an excel with all names? Otherwise I can provide them to you.

**Comment by JimBacon** [comment]
I'm just looking at another issue with common names, https://github.com/BiologicalRecordsCentre/ABLE/issues/461
There are only 78 butterfly names in Dutch (compared to 810 in English)
Perhaps something went wrong when John did the import.

**Comment by johnvanbreda** [comment]
@JimBacon I think the import I did for Dutch vernaculars was the moth list and there are ~2,500 names in Dutch on that list.

**Comment by chrisvanswaay** [comment]
I just checked and I sent it to @kazlauskis on 30 August 2021. But no problem to put it here, it should get attached to this message (if github does what I think it does)
[European checklist Dutch vernacular names.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/9363945/European.checklist.Dutch.vernacular.names.xlsx)
.

**Comment by chrisvanswaay** [comment]
Would be great if this could be added, so Dutch recorders can also record butterflies with Dutch names outside NL.

**Comment by JimBacon** [comment]
> I think the import I did for Dutch vernaculars was the moth list and there are ~2,500 names in Dutch on that list.

That would explain why the butterfly names are missing :-)
I can see about importing them in to the database.

**Comment by JimBacon** [comment]
I am trying to import the Dutch butterfly vernacular names. Can you review the following @chrisvanswaay and provide advice.

The following species are not currently in the EBMS list and my Google research indicates they are North African. Can I omit these?

Papilio saharae, Euchloe falloui, Anthocharis belia, Cigaritis zohra, Cigaritis siphax, Cigaritis allardi, Apharitis myrmecophilia, Tomares mauretanicus, Lycaena phoebus, Tarucus rosaceus, Maurus vogelii, Kretania martini, Kretania allardi, Polyommatus atlantica, Lysandra punctifera, Melitaea deserticola, Hipparchia ellena, Hipparchia hansii, Hipparchia powelli, Pseudochazara atlantis, Berberia abdelkader, Berberia lambessanus, Hyponephele maroccana, Pyronia janiroides, Coenonympha vaucheri, Coenonympha arcanioides, Spialia doris, Muschampia mohammed, Muschampia leuzeae, Thymelicus hamza.

The following species are not in the EBMS list but my research says they are present in Europe. Shall I add them to the EBMS list? We would need to determine the presence attributes indicating which countries they can be found in.

Polyommatus eleniae, Polyommatus galloi, Polyommatus gennargenti, Melitaea nevadensis

Finally, for information, I had to change some names in your file to match the names in the EBMS list. If you want to review any of those names, that can be a separate issue.

Name in csv file | Name in EBMS list
| --- | --- |
Argynnis aglaja | Speyeria aglaja
Argynnis adippe | Fabriciana adippe
Argynnis niobe | Fabriciana niobe
Colias croceus | Colias crocea
Phengaris telejus | Phengaris teleius
Lysandra caelestissimus | Lysandra caelestissima
Lysandra hispanus | Lysandra hispana
Argynnis elisa | Fabriciana elisa
Euphydryas beckeri | Euphydryas aurinia beckeri
Melanargia pherusia | Melanargia pherusa
Hipparchia occidentalis | Hipparchia azorina
Erebia triaria | Erebia triarius
Erebia aethiopella | Erebia aethiopellus
Erebia avernensis | Erebia arvernensis
Erebia calcaria | Erebia calcarius
Carcharodus tripolina | Carcharodus tripolinus
Carcharodus boeticus | Carcharodus baeticus
Carcharodus floccifer | Carcharodus floccifera
Carterocephalus silvicolus | Carterocephalus silvicola
Thymelicus lineolus | Thymelicus lineola

**Comment by JimBacon** [comment]
@chrisvanswaay, one more question.
Where the spreadsheet lists
```
Polyommatus celina	mediteraans blauwtje 
Polyommatus celina	mediteraans icarusblauwtje 
```
Am I correct to understand those are two possible common names for the same species?

**Comment by chrisvanswaay** [comment]
@JimBacon Actually both are wrong, sorry for that, it should be: Mediterraan icarusblauwtje (so with double rr in Mediterraan).

**Comment by JimBacon** [comment]
For info, the following query was used to insert the additional Dutch common butterfly names. The temporary table, [dutch_common.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/9696915/dutch_common.csv), is attached.

```
-- Combine new name with preferred taxon information needed
-- to create taxon record
WITH taxa_info as (
	SELECT ttl.id, taxon, dc.common, taxon_group_id, external_key
	FROM jim.dutch_common dc
	JOIN cache_taxa_taxon_lists ttl
		ON ttl.taxon = dc.scientific
		AND ttl.taxon_list_id = 251
),
-- Create new taxon record returning new id.
-- NB. 11 is language_id for Dutch.
new_taxa AS (
	INSERT INTO taxa
	(taxon, taxon_group_id, language_id, external_key, scientific,
		created_on, created_by_id, updated_on, updated_by_id)
	SELECT common, taxon_group_id, 11, external_key, false, now(), 2, now(), 2
	FROM taxa_info RETURNING id AS taxon_id, external_key
),
-- Combine new id with existing taxon_meaning_id needed
-- to create taxa_taxon_list record
taxa_info_2 AS (
	SELECT new_taxa.taxon_id, ttl.taxon_meaning_id
	FROM cache_taxa_taxon_lists ttl
	JOIN new_taxa ON 
		new_taxa.external_key = ttl.external_key AND
		ttl.preferred = true AND
	    ttl.taxon_list_id = 251
)
-- Create new taxa_taxon_list record.
INSERT INTO taxa_taxon_lists
(taxon_list_id, taxon_id, taxon_meaning_id, preferred,
	created_on, created_by_id, updated_on, updated_by_id)
SELECT 251, taxon_id, taxon_meaning_id, false, now(), 2, now(), 2
FROM taxa_info_2
```

**Comment by JimBacon** [comment]
The additional Dutch common names for butterflies are available on the website, see screenshot. 
To close this issue, the names need pulling in to the app @kazlauskis.

![image](https://user-images.githubusercontent.com/2545390/193564816-14cae01e-5108-4f8c-b353-8b367840b36d.png)

**Comment by kazlauskis** [comment]
That's done now and will appear in the Beta app shortly.

![Screenshot 2022-10-03 at 14 52 34](https://user-images.githubusercontent.com/7383162/193571019-0c2b2f00-e8ac-45b8-ae06-aac66fba32cd.png)

**Comment by chrisvanswaay** [comment]
Great, thanks!
