### ISSUE TITLE
ButterflyCount: add buttons of +5 +10 

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#368]
Add buttons to raise the number of individuals larger, +5 and +10
(typing one by one individual when there are many butterflies is annoying). 
I suggest placing it on the _occurrence page_ of the species; the species has to be registered once and after that entering on the page of the species you can see the +5 and +10 buttons like on the image below

@DavidRoy do you agree? 

<img width="540" alt="increase indiduals" src="https://user-images.githubusercontent.com/25052478/134905419-1895e14a-3995-4edc-b906-67a09fabb1a7.png">

**Comment by kazlauskis** [comment]
@DavidRoy Would this then add +5/10 occurrences to this list and each of the new occurrences would get assigned the same location?

**Comment by DavidRoy** [comment]
@CrisSevilleja I see the requirement but would it work better on the species list page, rather than going via the occurrences.  Then when touch (+1) or +5 +10 is selected an occurrence is created with the associated quantity (1,5,10)

@kazlauskis could you mock something up?

**Comment by DavidRoy** [comment]
Thanks.  i think that's a good solution

**Comment by CrisSevilleja** [comment]
Yes, I think that is a good solution @kazlauskis

**Comment by kazlauskis** [comment]
Thanks, do you need the choice of the +5 and +10 or can we just default the long-tap to +5? I'm asking this because if the +10 is going to be rarely (?) used then it is more efficient to avoid the extra taps.

**Comment by DavidRoy** [comment]
I suggest we only go for +5 as the aim of this survey is to count while walking and to capture the details of occurrences.  We could extend to +10 in future if there is clear demand?

**Comment by CrisSevilleja** [comment]
I agree, let's go only for +5 for now and see how people uses it and if more it is needed
