### ISSUE TITLE
CSS Issues

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/ABLE#37]
There are some CSS issues: the pages that have a filter bar (like the annual report, and the year and section plots) have a font colour and background colour the same.

**Comment by DavidRoy** [comment]
@BirenRathod can you pick up CCS/styling issues for the site as it relates to how the Bootstrap theme is applied to Indicia pages I think

**Comment by johnvanbreda** [comment]
Just checking that the bootstrap theme is selected instead of the generic style on the Indicia settings page.

**Comment by BirenRathod** [comment]
In this case, It doesn't make any difference if select generic or bootstrap theme on the Indicia settings page.

Anyway I added styles for these controls. I think this is the problem only for Indicia pages only. We have experienced same problem on NPMS website too.

**Comment by DavidRoy** [comment]
@Gary-van-Breda can we close this now.  Report page styling looks ok to me

**Comment by Gary-van-Breda** [comment]
Looks good.
Closing
