### ISSUE TITLE
Update input_form field

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#371]
Comes from BiologicalRecordsCentre/ABLE#352.

**Comment by johnvanbreda** [comment]
@kazlauskis If the survey ID is 565 or 645, please set the input_form to 'mydata/samples/edit'. Otherwise leave it as it is.
Thanks

**Comment by kazlauskis** [comment]
Thanks

**Comment by kazlauskis** [comment]
A transect survey should point to another page.
