### ISSUE TITLE
Capture length walked in 15-minute count

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#373]
Requires new sample attribute

update to ButterflyCount interface

update to website editing forms and downloads

**Comment by kazlauskis** [comment]
@DavidRoy Does this require a new input in the app to set the distance walked? Or do we simply rely on the existing GPS tracking (or manually drawn lines)? I'm asking this because a user can also draw an area on the map which would be hard to translate to a walked distance.

**Comment by DavidRoy** [comment]
Closing as I think this covered already?
