### ISSUE TITLE
15m count - my samples page improvements

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#375]
https://butterfly-monitoring.net/mydata/samples
- [ ] Replace existing menu item. To My data -> My 15-minute counts
- [ ] Add a records tab to the ES report. As currently exists for https://butterfly-monitoring.net/elastic/my-records
- [ ] Add a species tab to the ES report.  As currently exists for https://butterfly-monitoring.net/elastic/my-records
- [ ] Remove 'Download' tab

**Comment by johnvanbreda** [comment]
Done
