### ISSUE TITLE
Improvement to layout of My Downloads page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#376]
https://butterfly-monitoring.net/mydata/downloads

Break downloads into three sections:
1. BMS transect downloads (as currently exists)
2. 15-minute count downloads
3. 15-minute single species count downloads

As per this example, although the 'download 15-min single-species occurrences' is no longer needed
![download ebms](https://user-images.githubusercontent.com/2699478/140064794-9c7ebbe9-aa1b-4b25-bace-7abdd671bcbb.png)

**Comment by johnvanbreda** [comment]
Done, but will need checking that it's exactly what you wanted. Is the GPX download still required and should we offer it for both normal timed-counts and single species, as well as for both samples and occurrences for the normal timed-counts?

**Comment by DavidRoy** [comment]
Looks good,  Could you improve the layout.  Currently there is no gap before the headings and a big gap after the heading

**Comment by johnvanbreda** [comment]
Layout improved on both download pages.
