### ISSUE TITLE
Assigning user to a country when role = scheme co-ordinator

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#38]
links to #18 

We now have the role setup for 'Scheme co-ordinator'.  We then need to assign this scheme co-ordinator to a country for reports/permissions.  Is this covered by the user account setting of 'Country/scheme you are part of' or does it need a separate permission setting?

**Comment by Gary-van-Breda** [comment]
@DavidRoy 
If we do it properly, this should be covered by the user account setting.
We may have to give consideration to whether the 'Scheme co-ordinator' should be allowed to change their country setting.

**Comment by DavidRoy** [comment]
Thanks.  Let's leave it as it is in that case.  It is very unlikely that a scheme co-ordinator will have their country set as somewhere other than where they co-ordinate
