### ISSUE TITLE
the Image carousel of eBMS website is on every page

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#380]
I think from the recent migration/update of the eBMS website, the image carousel that appeared only on the home page, not it is present on every page of the website. Nothing important but it would be better to remove it and leave the image carousel only on the home page.

**Comment by DavidRoy** [comment]
hi @BirenRathod  can you pick up this please

**Comment by BirenRathod** [comment]
@CrisSevilleja That has resolved now.
