### ISSUE TITLE
eBMS website - Enable Field Guides page for entering text

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#384]
The Field Guide page https://butterfly-monitoring.net/field-guides was created and only shows the home page, it doesn't allow me to add text. 

@johnvanbreda  or @Gary-van-Breda could you enable this page to add text? Thank you in advance

**Comment by johnvanbreda** [comment]
@CrisSevilleja are you sure you actually created this page? I cannot find it on the content list: https://butterfly-monitoring.net/admin/content?title=field+guides&type=All&status=All&langcode=All.

**Comment by CrisSevilleja** [comment]
It is on the menu https://butterfly-monitoring.net/admin/structure/menu/manage/main
Under Butterfly Monitoring -> Materials -> Field Guides

**Comment by johnvanbreda** [comment]
@CrisSevilleja I assume you added a menu link and specified the path, rather than adding a content page then setting the menu link on the page's Edit tab? If you add a menu link directly, it doesn't actually create a content page.

**Comment by CrisSevilleja** [comment]
@johnvanbreda yes, it looks like I did that thinking it would work that way... sorry still learning the use of the website. 
Could you help me to create a content page for the Field Guide page under the Materials? or tell me how I can create a content page. Thanks in advance.

**Comment by CrisSevilleja** [comment]
I managed to create the content page
