### ISSUE TITLE
New transect cannot be saved

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#385]
Trying to create a new transect in My Sites https://butterfly-monitoring.net/my-sites doesn't save the data. See the picture below with the error message. I think it is happening for any transect you want to create. Any idea what this is happening @DavidRoy?

![image](https://user-images.githubusercontent.com/25052478/142167571-4d6d14a7-aecc-4fc9-b131-139e02728308.png)

**Comment by CrisSevilleja** [comment]
@johnvanbreda can you help me with this? It is not possible to create a new transect on the website.

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you pick this up please

**Comment by johnvanbreda** [comment]
@DavidRoy I've just started to look - it's something to do with new attributes that have been recently added for moth traps.

**Comment by DavidRoy** [comment]
Thanks.  Am tagging @JimBacon who is working on the moth element

**Comment by johnvanbreda** [comment]
The reason is that the EBMS Location Editor form type does not have a parameter for the survey dataset, so the location is posted against the website. This causes the warehouse to think that all the required location attributes linked to that website should be applied when validating, even though some are linked to specific survey datasets. Jim has added required attributes for the moth trapping, so they are preventing the transects from being saved.

@Gary-van-Breda should the location editor form in use here have a survey_id parameter added?

**Comment by JimBacon** [comment]
In the short term, we can remove the 'required' setting on the new attributes as they are for work that is still in development.

**Comment by CrisSevilleja** [comment]
Okey, I hope if the required setting is removed, adding new transects works again. 
Also the Transect allocation page https://butterfly-monitoring.net/scheme-transects-allocation is not working. I can imagine for the same reason. thanks for checking it.

**Comment by JimBacon** [comment]
I am not clear who is taking responsibility for this issue currently. I will remove the required setting on the new attributes and hope that does not cause confusion for anyone else.

**Comment by DavidRoy** [comment]
@Gary-van-Breda for the transect allocation page.  He's in the middle of working on the site.

**Comment by JimBacon** [comment]
Cristina reports "now the creation of new transect function is working again. Although the page of the Transect Allocation https://butterfly-monitoring.net/scheme-transects-allocation is not working yet." It is possible there are two issues to resolve.

**Comment by JimBacon** [comment]
This issue was only temporarily worked around. It is likely to recur.
