### ISSUE TITLE
Some transect pages of eBMS not working

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#387]
Since some things were changed on the website for the moth trap data entry, there were some errors on the page of Transect Allocation https://butterfly-monitoring.net/scheme-transects-allocation still not working the filters and not possible to see the volunteers allocated to the transects. This page is the only place for coordinators to check users and see who is under their BMS. 

Also, I found another page the Annual Report https://butterfly-monitoring.net/annual-report is not working. I wanted to download some data and the page is not loading, no data is shown from the transects or years... 

Any idea what is happening @DavidRoy? these pages are quite useful and needed. I hope you can manage to solve it. Thank you in advance.

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you investigate these issue please

**Comment by CrisSevilleja** [comment]
Hello @Gary-van-Breda, sorry for insisting on this; I give in two days a workshop explaining the use of the website and I would like to show, how to download data and see the transects, so I need those functions working. I hope you can help me and thank you in advance.

**Comment by DavidRoy** [comment]
@johnvanbreda - are you able to look at this if Gary is not around?

**Comment by johnvanbreda** [comment]
@DavidRoy I'll have a look.

**Comment by johnvanbreda** [comment]
@CrisSevilleja as I am not so familiar with the Scheme Transects Allocation page, please can you give me an examples of how you use the page and what exactly it should do, e.g. the steps you would take when filtering, or trying to view the volunteers allocated to a transect.

**Comment by CrisSevilleja** [comment]
@johnvanbreda I normally used the Transects Allocation page to allocate transects to the different users. Basically, the first filter selects the country and then the other two filters are sorted based on the selected country. So, I select Austria, and then in the second filter appears only the Austrian transects to select, and in the third filter appears only the users registered under the Austria scheme. Once the filters are sorted by the country I use the second or the third filter to see all the scheme transects and allocate transects to that selected user or the other way around. Right now the first and second filters work but the user filter is not working and any information is shown. 

I think there is something more going on in the website, because the Annual Report page is not working either, and this one works selecting transects and data for the login user. Thank you so much for helping with this.

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : I'll look at this

**Comment by johnvanbreda** [comment]
@Gary-van-Breda thanks. My investigations so far lead me to think that the iform module is partially upgraded, so some new Fancybox related code is failing. I would suggest bringing the whole iform module up to the current master branch.

**Comment by CrisSevilleja** [comment]
@Gary-van-Breda thanks for looking at this. Trying to check if the Annual Summary page works https://butterfly-monitoring.net/annual-report, I saw the current data from people is loaded but the use of the filter doesn't work. Do you think it is possible to fix it soon? Thank you in advance

**Comment by CrisSevilleja** [comment]
The pages are working again. Thank you so much for solving these issues
