### ISSUE TITLE
Downloaded data from eBMS website is wrong 

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#392]
Trying to get some summary numbers of 15-min counts done this year, we found the downloaded file of 15-min counts don't include all the data, for both occurrences and samples files. Data got it from https://butterfly-monitoring.net/downloads

Specifically checking how many 15-min counts were done per recorders (dt= time count sample data file for all eBMS)
#- Number of visits per recorder per year -----------------------
names(dt)[1] <- "visit_id"
nvispy <- dt[,list(nvisits=length(unique(visit_id))), by=list(Recorded.by, year)]
[nvisit_perRecorder_perYear.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/7728440/nvisit_perRecorder_perYear.csv)

I attached the csv produced with this code, the number of visits per recorder per year. As recorder I am "papilion, cristina" with 1 sample for 2021, when I did more than 50 for this year; van Swaay, Chris only 13 for 2021, when he did close to 100 and the same for van Deijk, Jurrien, with less samples in 2021 than in 2020, when we know that is wrong. 

Now I am worried about what we are exactly downloaded and how much data we are missing. Maybe I did something wrong but the code is quite simple. 

Also please check the button for Download sample (visit) information from transects is not working, not even creating the zip file to download. Several BMS coordinators complained about that.

**Comment by JimBacon** [comment]
Hi Cristina

I am trying to replicate your issue.
I have masqueraded as you and gone to https://butterfly-monitoring.net/downloads where I have done "Download timed-count sample data"

I see the following

```
dt[Recorded.by == "papilion, cristina", list(nvisits=length(unique(visit_id))), by = list(Recorded.by, year)]

        Recorded.by year nvisits
1: papilion, cristina 2019       3
2: papilion, cristina 2020      14
3: papilion, cristina 2021     106
4: papilion, cristina 2022      43

> data1[Recorded.by == "van Swaay, Chris", list(nvisits=length(unique(visit_id))), by = list(Recorded.by, year)]

        Recorded.by year nvisits
1: van Swaay, Chris 2019      16
2: van Swaay, Chris 2020     107
3: van Swaay, Chris 2021     310
4: van Swaay, Chris 2022     382

> data1[Recorded.by == "van Deijk, JurriÃ«n", list(nvisits=length(unique(visit_id))), by = list(Recorded.by, year)]

           Recorded.by year nvisits
1: van Deijk, JurriÃ«n 2020     272
2: van Deijk, JurriÃ«n 2021     380
3: van Deijk, JurriÃ«n 2022     410
```

I get the same results using a pivot table in Excel
![image](https://user-images.githubusercontent.com/2545390/214917407-deded8f8-a6ea-45cd-bae0-f4e672d2ffaa.png)

Have I done the same as you? Our results are quite different.

**Comment by DavidRoy** [comment]
@CrisSevilleja we have worked on the process for updating the ElasticSearch Index from the database.  As noted above, the numbers were consistent when last checked.  Am closing this issue but please raise new issues if any problems found
