### ISSUE TITLE
ButterflyCount: Moth survey trap setup (finalise trap and lamp categories)

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#393]
Review moth trap setup, particularly trap and lamp types 
https://test-brc-ebms.pantheonsite.io/my-moth-trap-sites

@JurrienVanDeijk

**Comment by JurrienVanDeijk** [comment]
I have changed the set-up a little so that it is hopefully clearer. It may be a bit confusing, so I think it's helpful if I explain it digitally. Jim do you have time today (ill send you an email as well)? I have a two-week holiday after today.

[different moth traps.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/7767886/different.moth.traps.xlsx)

**Comment by JimBacon** [comment]
Hi @JurrienVanDeijk. Could you take a look at https://test-brc-ebms.pantheonsite.io/moth-trap-details-v2 to see if I have succeeded in creating a form which allows the selection of moth-trap and lamp-types as you wanted?

It now enables a user to describe a trap with any number of lamps of any type which I think was the principal aim.

![image](https://user-images.githubusercontent.com/2545390/154089944-d7853bd3-e38d-4e17-91fd-aceb8f02530a.png)

**Comment by JurrienVanDeijk** [comment]
Yep, looks good! Is it also possible for an admin to add a new lampmtype in the default list? For example when a new favorite is commonly used in a few years?

**Comment by DavidRoy** [comment]
In general, it is good to keep some control of term lists. Otherwise, things get out of hand with duplicates etc.  I suggest that for the being that requests for new trap types etc come to Jim

**Comment by kazlauskis** [comment]
Is this is done now? Can we use the current categories in the app?

**Comment by JimBacon** [comment]
No. See https://github.com/BiologicalRecordsCentre/SPRING/issues/41. I think they are talking about the same thing even though they are in different repos which is not helping me.

**Comment by kazlauskis** [comment]
Thanks Jim.

@DavidRoy apart from the actual lamp/trap categories do you think this [trap form ](https://butterfly-monitoring.net/moth-trap-details) structure is now finalised? We can build the trap set up based on the form in the app and then update the categories when these are done on the website.

**Comment by JimBacon** [comment]
@kazlauskis For info, as it may not be immediately obvious, the current implementation allows a person to describe a trap with any possible combination of lamps. You can add multiple lamp types, with descriptions for each if needed, and a quantity for each. This all gets wrapped up as JSON and stored in a single location attribute.

**Comment by DavidRoy** [comment]
@kazlauskis - yes go ahead with the current process for setting up the traps.  The term lists may change but I think the process is less likely to change

**Comment by larspett** [comment]
> No. See [BiologicalRecordsCentre/SPRING#41](https://github.com/BiologicalRecordsCentre/SPRING/issues/41). I think they are talking about the same thing even though they are in different repos which is not helping me.

sorry about that, I posted a suggestion to https://github.com/BiologicalRecordsCentre/SPRING/issues/41 on April 25th suggesting that that separate thread is closed but that post seems to be missing (posted via email thread). Anyway, this is what I wrote since some of it can be useful for this thread:

> **I think that it might be good with a general overview of the options (including trap type) so maybe stick with the current ones and wait for some more feedback before tinkering with the options. I am not sure what TL means and suspect that many will not know what E27 means. In fact, I suspect that some of the light sources  labelled E27 are actually E39/40, at least our 250 W MV lamps have those sockets. So maybe that categorized part of the dropdown needs to be tweaked a little (bit overall, I think we can keep it for the time being)**

**Comment by kazlauskis** [comment]
The app allows the creation of moth traps and uses a fixed list of lamp types. Are the lamp categories finalised now and can this be closed then?
