### ISSUE TITLE
Add 'Unknown' moth species to the other languages

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#394]
Currently, 'Unknown' moth species exist only in the English language.

- [x] Add Dutch
- [ ] other languages ?

**Comment by kazlauskis** [comment]
@chrisvanswaay what is the 'Unknown' (as in unknown species) in Dutch?

**Comment by chrisvanswaay** [comment]
Hi Karolis,
First of all I want to wish you a good 2022.
And 'Unknown' will be 'Onbekend' or "Onbekende'. In this case 'Unknown species' would become 'Onbekende soort'.
Best wishes,
Chris


--

De Vlinderstichting is een organisatie zonder winstoogmerk. Voor een deel van ons werk zijn wij afhankelijk van de steun van donateurs. Wilt u bijdragen aan bescherming van vlinders en libellen? Neem dan een kijkje op onze website<https://www.vlinderstichting.nl/help-mee/donateur-worden> en help ons!


Chris van Swaay
De Vlinderstichting
Mennonietenweg 10
Postbus 506
6700 AM  Wageningen

[t] algemeen (+31) 0317 467346 / direct (+31) 0317 467342

[e] ***@***.******@***.***>
[i] www.vlinderstichting.nl<http://www.vlinderstichting.nl/>
[twitter] www.twitter.com/vlinderNL<http://www.twitter.com/vlinderNL>
[facebook] www.facebook.com/Vlinderstichting<http://www.facebook.com/Vlinderstichting>
[instagram] www.instagram.com/vlinderstichting<http://www.instagram.com/vlinderstichting>
[linkedin] www.linkedin.com/company/vlinderstichting<http://www.linkedin.com/company/vlinderstichting>

------------------------------
Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------
No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.

________________________________
Van: Karolis Kazlauskis ***@***.***>
Verzonden: maandag 3 januari 2022 15:10
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Chris van Swaay ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [BiologicalRecordsCentre/ABLE] Add 'Unknown' moth species to the other languages (Issue #394)


@chrisvanswaay<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchrisvanswaay&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C193cb559b0284ccd055608d9cec2c0d9%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637768158133433519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=W%2BTPxGNPQU6qkvDvm7i4%2FArgWEBZpd64VujbQ2J%2BYpo%3D&reserved=0> what is the 'Unknown' (as in unknown species) in Dutch?

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBiologicalRecordsCentre%2FABLE%2Fissues%2F394%23issuecomment-1004117403&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C193cb559b0284ccd055608d9cec2c0d9%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637768158133433519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Iwy7EBPVNUjb3EsLamMsN7hek5Ufzm0%2BOUD9O0ggCzg%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGFP2NN6JDN2LG2EI7VJDDTUUGU4DANCNFSM5LFJU5PQ&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C193cb559b0284ccd055608d9cec2c0d9%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637768158133433519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=j4%2B1GuMYIaktP10mPbPmcaz60UcpIr1Tf4x%2BwRY8N3s%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C193cb559b0284ccd055608d9cec2c0d9%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637768158133433519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OHCZ%2BKMUSfPmXnBnGTJOfD7Hqr7X4ThnT4UPDRAGmgA%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cchris.vanswaay%40vlinderstichting.nl%7C193cb559b0284ccd055608d9cec2c0d9%7C94e10a529c02479bb9e5efb937389e5f%7C0%7C0%7C637768158133433519%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hmISoCb0PjDsrga7aflJrD2PmNSbfxEi0ziqwLtbQKs%3D&reserved=0>.

**Comment by kazlauskis** [comment]
@JimBacon I have added this new Dutch term for 'Unknown' to the moths list in the Warehouse. Does the English and the Dutch entries need to be linked together to hold the same meaning, like kind of synonyms? or is it OK just to leave it as is
![Screenshot 2022-01-03 at 16 25 20](https://user-images.githubusercontent.com/7383162/147942023-279ab665-5cfe-4691-bd75-763cf463b04e.png)
?

**Comment by johnvanbreda** [comment]
I've attached Onbekend as a synonym of Unknown. Here's the SQL for reference:
```sql
update taxa_taxon_lists set taxon_meaning_id=243426, preferred=false, updated_on=now(), updated_by_id=3 where id=541352
```

**Comment by kazlauskis** [comment]
@johnvanbreda great, thanks!

**Comment by kazlauskis** [comment]
@DavidRoy this should get the moth trap survey ready for Beta testing in the Netherlands. We should ideally add all the other language options, no? Here is the list of currently supported languages in the app, what is the best way to get the translations for these?

```json
{
"bg-BG": "Български",
"sr-RS": "Cрпски",
"cs-CZ": "Čeština",
"de-DE": "Deutsch",
"en": "English",
"es-ES": "Español",
"hr-HR": "Hrvatski",
"it-IT": "Italiano",
"lt-LT": "Lietuvių",
"nl-NL": "Nederlands",
"pt-PT": "Português",
"ru-RU": "Pусский",
"sl-SI": "Slovenščina",
"fi-FI": "Suomi",
"sv-SE": "Svenska",
"tr-TR": "Türkçe"
}
```

**Comment by JimBacon** [comment]
Hi @kazlauskis 

If you are adding further translations, you can do this by going to https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/538737 and putting more entries in the Common Names field.

**Comment by DavidRoy** [comment]
Closing as the list of translations is quite complete in the warehouse
