### ISSUE TITLE
ButterflyCount: allow to set temperature below 10 degrees

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#397]
Enable -0, 0 .... 40, +40 range for the two 15min count surveys and also the transect survey. This does not include the moth trap survey.

**Comment by DavidRoy** [comment]
@CrisSevilleja we are not capturing weather data for the moth trap survey so is this needed?  For the timed counts, we only want weather recorded when insects are actively flying?  To account for the relationship between weather and detectability?

Even when counting butterfly eggs/larvae the weather data is not relevant as it does not affect the detection of individuals?

**Comment by DavidRoy** [comment]
Confirm that the minimum temperature should be zero.  Requirement for bumblebee recording

**Comment by JurrienVanDeijk** [comment]
In addition to the catches with the traps, I also want to do a 15 minutes count for moths, for example winter moths or larvae. Some of the species are also active from 0 degrees Celsius, and my preference would be to adjust the temperature to this as well.

**Comment by DavidRoy** [comment]
Agreed.  Make this for all taxa as in most cases the weather information is automatically populated. That is the simplest options rather than vary this by taxon groups

**Comment by kazlauskis** [comment]
@DavidRoy do you want us to enable -0, 0 .... 40, +40 range for the two 15min count surveys and also the transect survey but not the moth trap survey, is that right?

**Comment by CrisSevilleja** [comment]
We should allow those temperatures for moths also; they can place moth traps with cold temperatures. 
@DavidRoy can you confirm?

**Comment by kazlauskis** [comment]
@CrisSevilleja do you mean the moth survey or moths recorded in other surveys? We don't yet collect temperature in the moth survey.

**Comment by CrisSevilleja** [comment]
Indeed, sorry we don't have that field for moth trap yet. However, moth species can be recorded with the 15-min counts and my moth colleague asked me to be able to record under 10 degrees @kazlauskis So, allow from -0 up to +40 for transects and the two 15-min counts. Thanks!

**Comment by kazlauskis** [comment]
@DavidRoy This temperature attribute (ID=1388) that is in use in the app is also shared with `EU Pollinator - Transects` and iRecord Butterflies single species count surveys. Is it OK to change the values for it or would you like us to create a new attribute?

**Comment by DavidRoy** [comment]
@kazlauskis thanks for checking this.  Best to create a new attribute given its wider use
