### ISSUE TITLE
Calender view on live/test does not open up walk entry form

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#40]
From the my walks page, calendar view
http://live-butterfly-monitoring.pantheonsite.io/my-walks

Clicking on a date links to the wrong url.
http://live-butterfly-monitoring.pantheonsite.io/ebms-input-data?location_type_id=107&date=05/04/2019

Equivalent links do work on test, e.g.
http://dev-butterfly-monitoring.pantheonsite.io/ebms-input-data?site=6256&date=05/04/2019

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Done: also fixed the the same issue for the timed counts.

**Comment by Gary-van-Breda** [comment]
Done on both Test and Live : working url above is Dev.

**Comment by DavidRoy** [comment]
Now resolved, thanks
