### ISSUE TITLE
My sample page has an error - eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#400]
On the eBMS website,  My sample page https://butterfly-monitoring.net/mydata/samples shows an error "The form structure references an unrecognised extension control [misc_extensions.localised_text_js]."

Also, some functions on the table below are not working (small icons on the right), only the edit sample is working well.

**Comment by JimBacon** [comment]
I can see the localised_text_js function was deleted in https://github.com/Indicia-Team/client_helpers/commit/bfde99c9093ab2e2dff9dab44daa041241014a26#diff-53fa79fbc8e97405d48efb61a445a1cae22cad039c306347011398d23e714380L718

The reason for the change is given as "code amended to comply with drupal 8, 7 & non drupal site."

@BirenRathod, can you see any problem with me restoring this function?

**Comment by BirenRathod** [comment]
@JimBacon No, that is fine.

**Comment by JimBacon** [comment]
I've made a fix to the code and have installed it on the eBMS site.
@CrisSevilleja, please check it has solved your problem and close this issue if it has.

**Comment by CrisSevilleja** [comment]
Great, thank you @JimBacon now the problem is solved!
