### ISSUE TITLE
Weather data for moth trap samples

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#401]
Suggestion to include:
- Temps (Celsius)(opening, closing and nightly minimum values);
- Clouds (%);
- Moon (phase. e.g. "2/3+" = two thirds growing);
- Wind (Beaufort scale, optionally direction)

**Comment by larspett** [comment]
Maybe the moon phase or amount of moonlight can be calculated (and suggested) for a given site rather than entered by the app user? Here is a commercial site that does that https://www.meteomatics.com/en/api/available-parameters/moon/ but there are other ones available (although I haven’t been able to find one with equally rich information content)

From: "David Roy (CEH)" ***@***.***>
Reply to: BiologicalRecordsCentre/ABLE ***@***.***>
Date: Thursday, 24 March 2022 at 13:47
To: BiologicalRecordsCentre/ABLE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BiologicalRecordsCentre/ABLE] Weather data for moth trap samples (Issue #401)


Suggestion to include:

  *   Temps (Celsius)(opening, closing and nightly minimum values);
  *   Clouds (%);
  *   Moon (phase. e.g. "2/3+" = two thirds growing);
  *   Wind (Beaufort scale, optionally direction)

**Comment by Vilius-Stankaitis** [comment]
@DavidRoy Hi, I could implement this, I just need a complete list for values (temps, moon, wind)

**Comment by DavidRoy** [comment]
@Joao-Nunes-Moths could you make a suggestion for this please.
@JurrienVanDeijk and @marcbotham to review

**Comment by larspett** [comment]
This weather metadata listing from Vlinderstichting is quite detailed & good as a starting point, although moon phase would be good too (see page 15-16).

[71880391-6065-474d-9a86-bf0be9f77e9b.pdf](https://github.com/BiologicalRecordsCentre/ABLE/files/11488701/71880391-6065-474d-9a86-bf0be9f77e9b.pdf)

**Comment by JurrienVanDeijk** [comment]
Just to double check, we won;t ask this to out volunteers, but get this data directly from other sources right?

**Comment by DavidRoy** [comment]
Yes, weather data from web services and can be modified by recorders if possible. Is there an api for moon phase?

**Comment by JurrienVanDeijk** [comment]
I've never used it, but I founs several on Google. But I am not aware of any which works the best

**Comment by larspett** [comment]
It might be a case for a separate thread, but we should allow  data from **more than one night** to be uploaded. Many permanent traps are emptied every second day or so, That would have implications for the weather data (although we could still just use the last night as the default even for multiple-night trappings).

**Comment by larspett** [comment]
> 

I can have a look which one the astronomers use, one such site is listed together with the Unihedron (Sky Quality Meters) products and they seem to be the leading manufacturer

**Comment by DavidRoy** [comment]
This feels like a new requirement as so far we have developed on the principle of a single night of trapping

**Comment by larspett** [comment]
yes I agree. Should I add it?

**Comment by marcbotham** [comment]
Set-up conditions often rapidly change and collection conditions may be well after the moths are active and so I'm not sure how indicative there are? Is it possible to record a mean temperature over the time the trap was operating? If so could we record mean ToC over period trap operating from hourly?? measurements,  the min temp, and the max temp?  Data loggers by traps on a recent project showed the reason why we got some unexpectedly poor catches when set-up and collection temperatures recorded by the recorders were good, was because during the night the temperatures dropped for long periods before picking up again. The same is true for % cloud cover and wind?  

Sorry if all of this has already been discussed and I'm late to it

**Comment by Joao-Nunes-Moths** [comment]
I agree with @larspett, the metadata from Vlinderstichting seems to be a good starting point. I think moon phase can be easily obtained by some app/service and be automatically associated with the records. 

In the portuguese moth recording scheme we are not prepared to ask the volunteers for some of the variables, such as temperature and humidity. Moreover, to avoid human errors and ensure some stability, most of these variables should be obtained elsewhere, to my way of thinking. I see we're in tune.

It is imperative to add the start and finish time of the trapping session.

**Comment by Joao-Nunes-Moths** [comment]
@marcbotham The mean can be obtained knowing the weather variables at the start and finish time. I know it can be a rough approximation in some nights but it is probably the best we can have.

**Comment by Vilius-Stankaitis** [comment]
1. We don't need API for the moon phase it can be determined by the time.
2. Temperature, cloud, and wind values we can get from OpenWeatherAPI which we currently use in the app 

Just an idea if 

I could add "Start time and End time" inputs as well.

![Screenshot 2023-05-17 at 09.48.02.png](https://zube.io/files/biologicalrecordscentre/b4d1b066bf95034abaf87e83209eddbb-screenshot-2023-05-17-at-09-48-02.png)

![Screenshot 2023-05-17 at 09.50.36.png](https://zube.io/files/biologicalrecordscentre/4727f503e9e5d950471b548e072597f0-screenshot-2023-05-17-at-09-50-36.png)

Opening weather / closing weather or Initial weather / final weather

**Comment by larspett** [comment]
It might be good to pull more than start and end weather if possible. Minimum temperature during the night plays a role up here in Northern Europe. Probably more than further south I guess. But getting that could involve (depending on the API configuration) multiple weather downloads (or a single minimum-over-time-interval if the API allows that)

**Comment by Vilius-Stankaitis** [comment]
API allows to fetch hourly data with start and end times, so it should be possible to do it with single download. Obviously, I need to test it. But if it works I could add additional input for Closing weather. 

![Screenshot 2023-05-17 at 10.38.27.png](https://zube.io/files/biologicalrecordscentre/af4c1f772e0891c46ef7d437337ee7ca-screenshot-2023-05-17-at-10-38-27.png)

**Comment by Vilius-Stankaitis** [comment]
Hi all, 

Open/closing weather could be merged into one as average weather. It's not difficult to implement this. Just let me know which approach is the best for you.

Also, could someone explicit provide values for weather? Maybe, it would be possible to use values that are in the current app version? 
 
1. temperature - currently in the app range is from 0 to 40 Celsius
2. wind  (Smoke rises vertically, Smoke rises vertically,  etc..)
3. wind direction (N, NW, S , etc)
3. moon - ( New, Waxing Crescent, First Quarter, Waxing Gibbousm, Full, Waning Gibbous, Last Quarter Waning, Crescent) 

Thank you

**Comment by DavidRoy** [comment]
@Vilius-Stankaitis Thanks for this.

My suggestion
- [x] Add 'Trap start time' and 'Trap end time' to the sample details.  Could these default to the sunset and sunrise time with the ability to be edited.
- [x] Add the weather categories as you suggest
- [x] Add the weather associated with the date/start and date/end times set by the user

If we need anything more complicated for analysis, this can be done afterwards

**Comment by Joao-Nunes-Moths** [comment]
I fully agree with @DavidRoy.

**Comment by Vilius-Stankaitis** [comment]
Might be some inaccurate data for analysis with sunset/sunrise times as default time.

eg. 
1. Trap selected at 10pm (eg sunset 9pm) - finishes at 3 am (eg sunrise 5am ).
  - real time surveying - 5 hours surveying.
  - default surveying time 8 hours. This time difference will be uploaded to the warehouse. Which is a bit far off the real time surveying.


2. survey starts at 11 am (eg sunrise 6am) - to 1 pm (eg sunset 9pm.).
 - real time surveying - 2 hours surveying.
 - default surveying time 15 hours. This time difference will be uploaded to the warehouse. Which is **far** off the real time surveying.


Wouldn't be better to set 'Trap start time' when trap is selected and set 'Trap end time' when Finish button is pressed? Like we do in the Transect survey?

**Comment by larspett** [comment]
The way I would use it (and already am doing) is to enter everything when I empty the trap. Since it is not possible to have a trapping session over more than one night, this can mess up the weather data unless weather data becomes optional. I use the app for our permanent traps that have been running for many years and that are emptied most days but not every day and then we run into these issues, both in terms of weather estimation and number of individuals per night.

**Comment by DavidRoy** [comment]
I agree that all the data is typically entered when the trap is emptied.  All the start/end times and dates plus weather should be pre-populated but editable.  This still allows Lars’ use case?

My suggestion above still makes sense for the most typical use case.

complicated analysis requirements can be dealt with in post processing

**Comment by Vilius-Stankaitis** [comment]
Thank you, I have added this feature to the app, please let me know if something you want to improve. The default time will be set when the trap is selected and based on the trap location. 
https://butterflies.app.flumens.io/demo.html

**Comment by CrisSevilleja** [comment]
Thank you @Vilius-Stankaitis for the great work on this, I have been reading to understand which functions will be ready on the app for moth traps. I think these weather characteristics are good and important to include in the app. 

If I could add one small detail, in the moon phase, could it be possible to add some simple icons? https://www.vectorstock.com/royalty-free-vector/moon-phases-icons-vector-12077771 English is not my mother tongue and I don't really know all these names for the moon phases, it is something easy to correct and I imagine more users will find difficult to understand. If possible to add, great, if it generates a lot of complication, just ignore it. 

Thanks!

**Comment by Vilius-Stankaitis** [comment]
@CrisSevilleja  Hi, I could add the emoji next to the label. What do you think? 
 
![Screenshot 2023-05-31 at 09.10.29.png](https://zube.io/files/biologicalrecordscentre/12fd0307c2de3ef9ae807fbbe7478ec0-screenshot-2023-05-31-at-09-10-29.png)

**Comment by CrisSevilleja** [comment]
perfect thanks @Vilius-Stankaitis !

**Comment by Joao-Nunes-Moths** [comment]
The weather associated with the start and end time is not being pre-filled in the app. 
Moreover, can we add this feature, i.e., pre-fill of the start and end times according to sunrise and sunset times, as well as the weather variables according to date/start and date/end times (which is apparently not working even in the app) to the website?

**Comment by kazlauskis** [comment]
This is fixed and will be available in the next app release v1.23.0.
