### ISSUE TITLE
Mysterious string in eBMS website

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#406]
String hash 1e76bda3c41587f12e95208c3ec0b96c

says "Records which user has read which content."

What is the meaning of this?

**Comment by DavidRoy** [comment]
which page does it occur on?

**Comment by johnvanbreda** [comment]
@larspett would you be able to copy and paste the web page address you saw the message on please?

**Comment by larspett** [comment]
I got it in Transifex so no chance of knowing where it shows up but I googled it and found that it seems to be core Drupal text, seen here for instance https://www.drupal.org/docs/8/core/modules/history/overview I used the Drupal context and provided a Swedish translation based on that. The text snippet in itself is pretty difficult to understand for anyone not googling it, though. For me, you can close this issue

**Comment by johnvanbreda** [comment]
Ok, thanks @larspett, that makes more sense. Closing.
