### ISSUE TITLE
app Guide Transifex issues

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#408]
•	The texts Pyrgus-foulquieri-description and Pyrgus-cirsii-description confused me since they refer to “This grizzled skipper” so I thought it was Pyrgus malvae (Grizzled Skipper) But I closed the Transifex issue now, saw what the reason was.

•	Agriades-aquilo-description has a typo, it says “It lives on Arctic Grasslands on shale in elevations between 0 and 900m asl.” Shouldn’t be a zero there. This issue remains, I think it should be easy to check the original text and update it.

**Comment by kazlauskis** [comment]
@CrisSevilleja are you able to edit the English descriptions in Transifex?

**Comment by CrisSevilleja** [comment]
@kazlauskis I can do it, but I don't know how to exactly edit the source string in Transifex. If you tell me where I can apply the description. 

Sorry @larspett this is the original text for Agriades aquilo from the Climatic Risk Atlas: "This species occurs exclusively in Nothern Fennoscandia. It occurs on slate and shale rocks with patches of grassy vegetation and with Crowberry (Empetrum nigrum), especially in areas sheltered from the northwestern wind. It lives in elevations between 0 and 900 m asl....". If you know the specific elevation for this butterfly we can edit it. 

Regarding the Pyrgus we can edit the text and avoid mentioning "This grizzled skipper" and place "This butterfly". On the Atlas it appears like "This grizzled skipper"

**Comment by larspett** [comment]
Hi again , I had a quick look at GBIF and

**Comment by kazlauskis** [comment]
@CrisSevilleja the species descriptions are simple English translations in Transifex so all you need to do is just open up a English translation and edit the text

**Comment by CrisSevilleja** [comment]
Sorry @kazlauskis I don't know exactly where you find the English translation, maybe it is quite obvious but I cannot only see the different languages to translate. Could you show me in a screenshot where to find it? Maybe I don't have the rights to do it. Thanks

**Comment by kazlauskis** [comment]
@CrisSevilleja Ah, sorry! It seems that editing the source file in Transifex is a premium feature. Can you confirm how and which terms I need to change? Thanks

**Comment by CrisSevilleja** [comment]
thank @kazlauskis then I know I cannot edit the English text. Here are the changes to do on species description resource of eBMS:

Agriades-aquilo-description: This species occurs exclusively in Nothern Fennoscandia. It occurs on slate and shale rocks with patches of grassy vegetation and with Crowberry (Empetrum nigrum), especially in areas sheltered from the northwestern wind. It lives from sea level all the way up to 900 m asl.

Pyrgus-foulquieri-description and Pyrgus-cirsii-description starting with: "This butterfly" instead of "This grizzled skipper"

**Comment by kazlauskis** [comment]
Thanks, I've changed it now. It will come out with the next app release.
