### ISSUE TITLE
Full site sections data download not working

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#41]
From page: http://live-butterfly-monitoring.pantheonsite.io/my-sites

Clicking on: Full Site Sections data download (CSV)
 
Throws up an error page

{"error":"There was an SQL error: ERROR:  syntax error at or near \"AND\"\nLINE 102:   AND EXISTS (SELECT id FROM location_attribute_values lav W...\n            ^ - \n   select  \n      l.id  as  site_id,\n      l.name  as  site_name,\n      l.code  as  site_code,\n      ctt.term  as  site_type,\n      l.centroid_sref,\n      l.centroid_sref_system, \n      l2.id  as  section_id,\n      l2.name  as  section_name,\n      l2.code  as  section_code\n  ,\nlocation18.id as attr_id_location_18,\nlocation18.int_value as attr_location_18,\nlocation1.id as attr_id_location_1,\nlocation1.int_value as attr_location_1,\nlocation2.id as attr_id_location_2,\nlocation2.int_value as attr_location_2,\nlocation3.id as attr_id_location_3,\nlocation3.int_value as attr_location_3,\nltt3.term as attr_location_term_3,\nlocation4.id as attr_id_location_4,\nlocation4.int_value as attr_location_4,\nlocation6.id as attr_id_location_6,\nlocation6.int_value as attr_location_6,\nltt6.term as attr_location_term_6,\nlocation7.id as attr_id_location_7,\nlocation7.int_value as attr_location_7,\nltt7.term as attr_location_term_7,\nlocation8.id as attr_id_location_8,\nlocation8.int_value as attr_location_8,\nltt8.term as attr_location_term_8,\nlocation9.id as attr_id_location_9,\nlocation9.int_value as attr_location_9,\nltt9.term as attr_location_term_9,\nlocation10.id as attr_id_location_10,\nlocation10.int_value as attr_location_10,\nltt10.term as attr_location_term_10,\nlocation11.id as attr_id_location_11,\nlocation11.int_value as attr_location_11,\nltt11.term as attr_location_term_11,\nlocation12.id as attr_id_location_12,\nlocation12.text_value as attr_location_12,\nlocation2_5.id as attr_id_location2_5,\nlocation2_5.int_value as attr_location2_5,\nlocation2_21.id as attr_id_location2_21,\nlocation2_21.int_value as attr_location2_21,\nltt2_21.term as attr_location2_term_21,\nlocation2_13.id as attr_id_location2_13,\nlocation2_13.int_value as attr_location2_13,\nltt2_13.term as attr_location2_term_13,\nlocation2_14.id as attr_id_location2_14,\nlocation2_14.int_value as attr_location2_14,\nltt2_14.term as attr_location2_term_14,\nlocation2_15.id as attr_id_location2_15,\nlocation2_15.int_value as attr_location2_15,\nltt2_15.term as attr_location2_term_15,\nlocation2_16.id as attr_id_location2_16,\nlocation2_16.int_value as attr_location2_16,\nltt2_16.term as attr_location2_term_16,\nlocation2_17.id as attr_id_location2_17,\nlocation2_17.text_value as attr_location2_17\n   from  locations l\n  JOIN cache_termlists_terms ctt ON ctt.id=l.location_type_id\n  JOIN locations l2 ON l2.parent_id=l.id\n  LEFT JOIN locations_websites lw ON l.id = lw.location_id AND lw.deleted = FALSE\n  LEFT JOIN location_attribute_values location18 ON location18.location_id=l.id AND location18.location_attribute_id=18 AND location18.deleted=false\n LEFT JOIN location_attribute_values location1 ON location1.location_id=l.id AND location1.location_attribute_id=1 AND location1.deleted=false\n LEFT JOIN location_attribute_values location2 ON location2.location_id=l.id AND location2.location_attribute_id=2 AND location2.deleted=false\n LEFT JOIN location_attribute_values location3 ON location3.location_id=l.id AND location3.location_attribute_id=3 AND location3.deleted=false\nLEFT JOIN cache_termlists_terms ltt3 ON ltt3.id=location3.int_value\n LEFT JOIN location_attribute_values location4 ON location4.location_id=l.id AND location4.location_attribute_id=4 AND location4.deleted=false\n LEFT JOIN location_attribute_values location6 ON location6.location_id=l.id AND location6.location_attribute_id=6 AND location6.deleted=false\nLEFT JOIN cache_termlists_terms ltt6 ON ltt6.id=location6.int_value\n LEFT JOIN location_attribute_values location7 ON location7.location_id=l.id AND location7.location_attribute_id=7 AND location7.deleted=false\nLEFT JOIN cache_termlists_terms ltt7 ON ltt7.id=location7.int_value\n LEFT JOIN location_attribute_values location8 ON location8.location_id=l.id AND location8.location_attribute_id=8 AND location8.deleted=false\nLEFT JOIN cache_termlists_terms ltt8 ON ltt8.id=location8.int_value\n LEFT JOIN location_attribute_values location9 ON location9.location_id=l.id AND location9.location_attribute_id=9 AND location9.deleted=false\nLEFT JOIN cache_termlists_terms ltt9 ON ltt9.id=location9.int_value\n LEFT JOIN location_attribute_values location10 ON location10.location_id=l.id AND location10.location_attribute_id=10 AND location10.deleted=false\nLEFT JOIN cache_termlists_terms ltt10 ON ltt10.id=location10.int_value\n LEFT JOIN location_attribute_values location11 ON location11.location_id=l.id AND location11.location_attribute_id=11 AND location11.deleted=false\nLEFT JOIN cache_termlists_terms ltt11 ON ltt11.id=location11.int_value\n LEFT JOIN location_attribute_values location12 ON location12.location_id=l.id AND location12.location_attribute_id=12 AND location12.deleted=false\n LEFT JOIN location_attribute_values location2_5 ON location2_5.location_id=l2.id AND location2_5.location_attribute_id=5 AND location2_5.deleted=false\n LEFT JOIN location_attribute_values location2_21 ON location2_21.location_id=l2.id AND location2_21.location_attribute_id=21 AND location2_21.deleted=false\nLEFT JOIN cache_termlists_terms ltt2_21 ON ltt2_21.id=location2_21.int_value\n LEFT JOIN location_attribute_values location2_13 ON location2_13.location_id=l2.id AND location2_13.location_attribute_id=13 AND location2_13.deleted=false\nLEFT JOIN cache_termlists_terms ltt2_13 ON ltt2_13.id=location2_13.int_value\n LEFT JOIN location_attribute_values location2_14 ON location2_14.location_id=l2.id AND location2_14.location_attribute_id=14 AND location2_14.deleted=false\nLEFT JOIN cache_termlists_terms ltt2_14 ON ltt2_14.id=location2_14.int_value\n LEFT JOIN location_attribute_values location2_15 ON location2_15.location_id=l2.id AND location2_15.location_attribute_id=15 AND location2_15.deleted=false\nLEFT JOIN cache_termlists_terms ltt2_15 ON ltt2_15.id=location2_15.int_value\n LEFT JOIN location_attribute_values location2_16 ON location2_16.location_id=l2.id AND location2_16.location_attribute_id=16 AND location2_16.deleted=false\nLEFT JOIN cache_termlists_terms ltt2_16 ON ltt2_16.id=location2_16.int_value\n LEFT JOIN location_attribute_values location2_17 ON location2_17.location_id=l2.id AND location2_17.location_attribute_id=17 AND location2_17.deleted=false\n \n  WHERE (l.website_id in (2) or l.website_id is null)\n    AND l.deleted = false AND l2.deleted = false\n    AND (l.public=TRUE OR lw.website_id IS NOT NULL);\n  AND EXISTS (SELECT id FROM location_attribute_values lav WHERE lav.location_id = l.id\n      AND lav.location_attribute_id = 19\n      AND lav.int_value = 26 AND lav.deleted=false)\nAND l.location_type_id=107\n\n  ORDER BY l.name, l2.id\n  ","code":44,"file":"D:\\web sites\\warehouse2\\system\\libraries\\drivers\\Database\\Pgsql.php","line":342,"trace":[]}

**Comment by Gary-van-Breda** [comment]
New report version with dodgy semi-colon removed
@BirenRathod : can your drop the latest master version of the indicia-reports module onto the testwarehouse, warehouse2 and warehouse1? Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Reports have been pulled down on all three warehouses.

**Comment by DavidRoy** [comment]
Reports still not working.  The link ends up at with a site not found and link:
https://warehouse2.indicia.org.uk/index.php/services/report/requestReport?report=projects/ebms/ebms_site_sections_download.xml&reportSource=local&mode=csv&nonce=23d5200b4dbda6c5b5dbde7c7bed065ba5c6473e&auth_token=7edc547b43f72169c0a5bd9ef86cdd385ea920f9&cms_user_id=26&cms_attribute_id=19&location_type_id=107&locattrs=18,1,2,3,4,6,7,8,9,10,11,12&loc2attrs=5,21,13,14,15,16,17

**Comment by Gary-van-Breda** [comment]
New report version with changed sql.
@BirenRathod : can your drop the latest master version of the indicia-reports module onto the testwarehouse, warehouse2 and warehouse1? Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
latest version of indicia-reports have been pulled down now.

**Comment by DavidRoy** [comment]
Still throws up an error in the SQL

{"error":"There was an SQL error: ERROR:  column l.website_id does not exist\nLINE 99:   WHERE (l.website_id in (2) or l.website_id is null)\n                  ^\nHINT:  Perhaps you meant to reference the column \"lw.website_id\". - \n   select  \n      l.id  as  site_id,\n      l.name  as  site_name,\n      l.code  as  site_code,\n      ctt.term  as  site_type,\n      l.centroid_sref,\n      l.centroid_sref_system, \n      l2.id  as  section_id,\n      l2.name  as  section_name,\n      l2.code  as  section_code\n  ,\nlocation18.id as attr_id_location_18,\nlocation18.int_value as attr_location_18,\nlocation1.id as attr_id_location_1,\nlocation1.int_value as attr_location_1,\nlocation2.id as attr_id_location_2,\nlocation2.int_value as attr_location_2,\nlocation3.id as attr_id_location_3,\nlocation3.int_value as attr_location_3,\nltt3.term as attr_location_term_3,\nlocation4.id as attr_id_location_4,\nlocation4.int_value as attr_location_4,\nlocation6.id as attr_id_location_6,\nlocation6.int_value as attr_location_6,\nltt6.term as attr_location_term_6,\nlocation7.id as attr_id_location_7,\nlocation7.int_value as attr_location_7,\nltt7.term as attr_location_term_7,\nlocation8.id as attr_id_location_8,\nlocation8.int_value as attr_location_8,\nltt8.term as attr_location_term_8,\nlocation9.id as attr_id_location_9,\nlocation9.int_value as attr_location_9,\nltt9.term as attr_location_term_9,\nlocation10.id as attr_id_location_10,\nlocation10.int_value as attr_location_10,\nltt10.term as attr_location_term_10,\nlocation11.id as attr_id_location_11,\nlocation11.int_value as attr_location_11,\nltt11.term as attr_location_term_11,\nlocation12.id as attr_id_location_12,\nlocation12.text_value as attr_location_12,\nlocation2_5.id as attr_id_location2_5,\nlocation2_5.int_value as attr_location2_5,\nlocation2_21.id as attr_id_location2_21,\nlocation2_21.int_value as attr_location2_21,\nltt2_21.term as attr_location2_term_21,\nlocation2_13.id as attr_id_location2_13,\nlocation2_13.int_value as attr_location2_13,\nltt2_13.term as attr_location2_term_13,\nlocation2_14.id as attr_id_location2_14,\nlocation2_14.int_value as attr_location2_14,\nltt2_14.term as attr_location2_term_14,\nlocation2_15.id as attr_id_location2_15,\nlocation2_15.int_value as attr_location2_15,\nltt2_15.term as attr_location2_term_15,\nlocation2_16.id as attr_id_location2_16,\nlocation2_16.int_value as attr_location2_16,\nltt2_16.term as attr_location2_term_16,\nlocation2_17.id as attr_id_location2_17,\nlocation2_17.text_value as attr_location2_17\n   from  locations l\n  JOIN cache_termlists_terms ctt ON ctt.id=l.location_type_id\n  JOIN locations l2 ON l2.parent_id=l.id\n  LEFT JOIN locations_websites lw ON l.id = lw.location_id AND lw.deleted = FALSE\n  LEFT JOIN location_attribute_values location18 ON location18.location_id=l.id AND location18.location_attribute_id=18 AND location18.deleted=false\n LEFT JOIN location_attribute_values location1 ON location1.location_id=l.id AND location1.location_attribute_id=1 AND location1.deleted=false\n LEFT JOIN location_attribute_values location2 ON location2.location_id=l.id AND location2.location_attribute_id=2 AND location2.deleted=false\n LEFT JOIN location_attribute_values location3 ON location3.location_id=l.id AND location3.location_attribute_id=3 AND location3.deleted=false\nLEFT JOIN cache_termlists_terms ltt3 ON ltt3.id=location3.int_value\n LEFT JOIN location_attribute_values location4 ON location4.location_id=l.id AND location4.location_attribute_id=4 AND location4.deleted=false\n LEFT JOIN location_attribute_values location6 ON location6.location_id=l.id AND location6.location_attribute_id=6 AND location6.deleted=false\nLEFT JOIN cache_termlists_terms ltt6 ON ltt6.id=location6.int_value\n LEFT JOIN location_attribute_values location7 ON location7.location_id=l.id AND location7.location_attribute_id=7 AND location7.deleted=false\nLEFT JOIN cache_termlists_terms ltt7 ON ltt7.id=location7.int_value\n LEFT JOIN location_attribute_values location8 ON location8.location_id=l.id AND location8.location_attribute_id=8 AND location8.deleted=false\nLEFT JOIN cache_termlists_terms ltt8 ON ltt8.id=location8.int_value\n LEFT JOIN location_attribute_values location9 ON location9.location_id=l.id AND location9.location_attribute_id=9 AND location9.deleted=false\nLEFT JOIN cache_termlists_terms ltt9 ON ltt9.id=location9.int_value\n LEFT JOIN location_attribute_values location10 ON location10.location_id=l.id AND location10.location_attribute_id=10 AND location10.deleted=false\nLEFT JOIN cache_termlists_terms ltt10 ON ltt10.id=location10.int_value\n LEFT JOIN location_attribute_values location11 ON location11.location_id=l.id AND location11.location_attribute_id=11 AND location11.deleted=false\nLEFT JOIN cache_termlists_terms ltt11 ON ltt11.id=location11.int_value\n LEFT JOIN location_attribute_values location12 ON location12.location_id=l.id AND location12.location_attribute_id=12 AND location12.deleted=false\n LEFT JOIN location_attribute_values location2_5 ON location2_5.location_id=l2.id AND location2_5.location_attribute_id=5 AND location2_5.deleted=false\n LEFT JOIN location_attribute_values location2_21 ON location2_21.location_id=l2.id AND location2_21.location_attribute_id=21 AND location2_21.deleted=false\nLEFT JOIN cache_termlists_terms ltt2_21 ON ltt2_21.id=location2_21.int_value\n LEFT JOIN location_attribute_values location2_13 ON location2_13.location_id=l2.id AND location2_13.location_attribute_id=13 AND location2_13.deleted=false\nLEFT JOIN cache_termlists_terms ltt2_13 ON ltt2_13.id=location2_13.int_value\n LEFT JOIN location_attribute_values location2_14 ON location2_14.location_id=l2.id AND location2_14.location_attribute_id=14 AND location2_14.deleted=false\nLEFT JOIN cache_termlists_terms ltt2_14 ON ltt2_14.id=location2_14.int_value\n LEFT JOIN location_attribute_values location2_15 ON location2_15.location_id=l2.id AND location2_15.location_attribute_id=15 AND location2_15.deleted=false\nLEFT JOIN cache_termlists_terms ltt2_15 ON ltt2_15.id=location2_15.int_value\n LEFT JOIN location_attribute_values location2_16 ON location2_16.location_id=l2.id AND location2_16.location_attribute_id=16 AND location2_16.deleted=false\nLEFT JOIN cache_termlists_terms ltt2_16 ON ltt2_16.id=location2_16.int_value\n LEFT JOIN location_attribute_values location2_17 ON location2_17.location_id=l2.id AND location2_17.location_attribute_id=17 AND location2_17.deleted=false\n \n  WHERE (l.website_id in (2) or l.website_id is null)\n    AND l.deleted = false AND l2.deleted = false\n    AND (l.public=TRUE OR lw.website_id IS NOT NULL)\n  AND EXISTS (SELECT id FROM location_attribute_values lav WHERE lav.location_id = l.id\n      AND lav.location_attribute_id = 19\n      AND lav.int_value = 26 AND lav.deleted=false)\nAND l.location_type_id=107\n\n  ORDER BY l.name, l2.id\n  ","code":44,"file":"D:\\web sites\\warehouse2\\system\\libraries\\drivers\\Database\\Pgsql.php","line":342,"trace":[]}

**Comment by Gary-van-Breda** [comment]
@BirenRathod : can you confirm the indicia-reports have been pulled correctly on warehouse2 and testwarehouse? It looks like it is OK on warehouse1, but the old version is on warehouse2 and it is completely missing on testwarehouse.
Thanks

**Comment by DavidRoy** [comment]
Now working on live so closing, thanks
