### ISSUE TITLE
eBMS: update bumblebee species list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#411]
taxon list id = 261 (https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/461252)

- [x] Add missing recording aggregates from the Luxembourg list to the eBMS bumblebee list
- [x] Add taxon_list attributes for countries from taxon_list.id=251 (butterflies) to taxon_list_id.261 (bumblebees)
- [x] Add term_list (id = 816) to taxon_list attributes.
- [x] Populate taxon_attribute LU with value 'P' for bumblebees on Luxembourg list
- [x] Add Dutch common names
- [x] Populate taxon_attribute AT with value 'P' for bumblebees on Austria list 
- [x] Populate taxon_attribute CH with value 'P' for bumblebees on Switzerland list 
- [x] Populate taxon_attribute DE with value 'P' for bumblebees on Germany list 

[Bumblebee species for Luxembourg](https://github.com/BiologicalRecordsCentre/ABLE/files/8520932/List_of_bumblebee_species_for_butterflyCount_app.xlsx)

**Comment by JimBacon** [comment]
In the Luxembourg list where they have e.g. _Bombus bohemicus_, list 261 has _Bombus (Psithyrus) bohemicus_

Where they have an aggregate like _Bombus bohemicus/vestalis_, I can add _Bombus (Psithyrus) bohemicus/vestalis_

However, where they have an aggregate like _Bombus hortorum/ruderatus/jonellus_, how do I write an aggregate of _Bombus (Megabombus) hortorum_,  _Bombus (Megabombus) ruderatus_, and _Bombus (Pyrobombus) jonellus_?

**Comment by JimBacon** [comment]
The Luxembourg list also contains sub-species. Do you want me to omit those?

There is one aggregate which contains a sub-species (_Bombus lapidarius/ruderarius/soroeensis proteus_)

**Comment by JimBacon** [comment]
For reference, country attributes copied to bumble bee species list by query
```
WITH attrs AS (
	SELECT taxa_taxon_list_attribute_id as id 
	FROM taxon_lists_taxa_taxon_list_attributes
	WHERE taxon_list_id = 251
	AND deleted = false
)
INSERT INTO taxon_lists_taxa_taxon_list_attributes
(taxon_list_id, taxa_taxon_list_attribute_id, created_on, created_by_id)
SELECT 261, id, now(), 2 FROM attrs
```

**Comment by DavidRoy** [comment]
@JimBacon for the aggregates we can do without the Genus synonyms in brackets.  There is an argument for removing them from the whole list but let's leave for the time being

@xaviermestdagh do you need the sub-species for your transect recording?

**Comment by JimBacon** [comment]
@CrisSevilleja, for the species of Austria, Switzerland and Germany, is the species presence 'P' in all cases?

**Comment by CrisSevilleja** [comment]
@JimBacon yes exactly, the species shown for these countries all are present 'P'

**Comment by JimBacon** [comment]
For reference, a query like the following populated the taxon attributes. 
```
CREATE TEMPORARY TABLE austria (taxon text);

INSERT INTO austria
VALUES ('Bombus alpinus'),
...
('Bombus wurflenii');

WITH species_list AS (
	SELECT id, regexp_replace(taxon, ' \(.+\)', '') nice_taxon
	FROM cache_taxa_taxon_lists ttl
	WHERE taxon_list_id = 261
	AND taxon_rank_id = 26
)
INSERT INTO taxa_taxon_list_attribute_values
(taxa_taxon_list_id, taxa_taxon_list_attribute_id, int_value,
created_on, updated_on, created_by_id, updated_by_id)
SELECT species_list.id, 85, 16407, now(), now(), 2, 2
FROM species_list
JOIN austria a ON a.taxon = species_list.nice_taxon
```

261 is the bumblebee species list ID
26 is the ID of the taxon rank, 'species'
85 is the ID of the taxon attribute for Austria.
16407 is the ID of the termlists_term for 'P'
2 is my user ID

**Comment by JimBacon** [comment]
Hi @CrisSevilleja In the list for Austria, you include _Bombus maxillosus_ and _Bombus barbutellus_.
I had to look up _B. maxillosus_ as it was not in our list and it appears to be a synonym of _B. barbutellus_. See https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=714950. If you are in agreement, we can omit _B. maxillosus_.

**Comment by DavidRoy** [comment]
@xaviermestdagh can you respond on this?  We are aiming to update the app species lists in May

**Comment by CrisSevilleja** [comment]
@JimBacon okay, I agree on omitting B. maxillosus. Thanks

**Comment by xaviermestdagh** [comment]
Hi! Sorry I didn't notice this conversation. I will check with my colleague Sarah Vray.

**Comment by xaviermestdagh** [comment]
Hi @DavidRoy 
Sorry it took so long, I transfer you the answer from Sarah Vray (she says not having access to this GitHub): 
-	For the sub-species: yes the sub-species would be good to keep, because indeed the 2 sub-species of B. soroeensis are very different and fall in 2 different groups. But if it is not possible, it’s not a big problem, we would just to keep in mind that the group Bombus lapidarius/ruderarius/soroeensis only includes the sub-species proteus. It cannot include the ssp soroeensis as it is completely different (and maybe even not present in LU), and I guess people will understand that (?). So for our own use it would be ok to not display the “proteus” (but people outside our scheme might be confused). But at least I hope they will keep the sub-species in the species list (i.e. non aggregate groups) because for species like B. humilis it is interesting to keep this info…
-	For the sub-genera (e.g. Bombus (Psithyrus)…), we don’t need them. I even didn’t include them in the file I sent (?).

**Comment by DavidRoy** [comment]
@JimBacon - can you update the lists accordingly

**Comment by JimBacon** [comment]
For info, to update the `attrs_json` field in the `cache_taxa_taxon_lists` table, I ran the following query.
```
INSERT INTO work_queue (task, entity, record_id, priority, cost_estimate, created_on)
SELECT DISTINCT 'task_cache_builder_attrs_taxa_taxon_list', 
	'taxa_taxon_list', ttl.id, 3, 60, now()
FROM taxa_taxon_lists ttl
-- Skip any without an attribute.
JOIN taxa_taxon_list_attribute_values av ON 
	av.taxa_taxon_list_id = ttl.id AND
	av.deleted=false
WHERE ttl.deleted = false AND
	ttl.taxon_list_id = 261;
```

**Comment by CrisSevilleja** [comment]
> Include Dutch common names of bumblebees [bumblebees_NL_202011.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/8531302/bumblebees_NL_202011.xlsx)
> 
> Bumblebees species for Austria, Switzerland and Germany [BumblBee.list_Au_CH_DE.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/8531405/BumblBee.list_Au_CH_DE.xlsx)

@JimBacon Dutch recorders asked me to include the dutch common names of bumblebees. Could it be possible? thanks

**Comment by JimBacon** [comment]
The Dutch common names are present in the database.
I see just one missing: Koekoekshommel onbekend, Bombus (Psithyrus) spec.

**Comment by CrisSevilleja** [comment]
okay thank you Jim, then they have to be included in the app
