### ISSUE TITLE
Translation of some pages not working 

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#414]
I applied the translation of many languages on the website. While navigating between pages the languages stays the same, however this is not happening for certain pages: 

- My sites https://butterfly-monitoring.net/my-sites
- My walks https://butterfly-monitoring.net/my-walks
- Annual Report https://butterfly-monitoring.net/annual-report
- butterfly monitoring https://butterfly-monitoring.net/BMS

when you are in another language and try to click on one of these pages, it will turn immediately to English. It happens to all languages and for these pages only.  @DavidRoy

**Comment by JimBacon** [comment]
Hi Cristina,

If I go to the home page and switch to Spanish I see the following menu items which navigate me to Spanish versions of the pages which are in Spanish:

- Mis datos > Mis Transectos: https://butterfly-monitoring.net/es/mis-transectos
- Mis datos > Mis Visitas: https://butterfly-monitoring.net/es/mis-visitas
- Mis datos > Informes > Resumen Anual: https://butterfly-monitoring.net/es/informe-anual
- Seguimiento de Mariposas: https://butterfly-monitoring.net/es/bms

This seems to be working as you would expect. 

On the other hand, if I switch to Dutch, and navigate to the same menu items and the Dutch versions of the pages, they contain English content:

- Mijn data > Mijn transecten: https://butterfly-monitoring.net/nl/node/32
- Mijn data > Mijn transectbezoeken: https://butterfly-monitoring.net/nl/node/37
- Mijn data > Mijn transect overzichten > Mijn jaaroverzicht: https://butterfly-monitoring.net/nl/node/43
- Dagvlindermonitoring: https://butterfly-monitoring.net/nl/bms

My first thought is that you need to edit the Dutch pages and replace the English content with Dutch content. 

Checking Bulgarian, all appears okay, with the exception that the page https://butterfly-monitoring.net/bg/bms is mostly still in English.

I did notice that our test website has a problem similar to what you are describing so perhaps something has already been done to resolve this issue.

**Comment by CrisSevilleja** [comment]
Yes, now the translation of these pages are changing when you are in a certain language. Thanks @JimBacon  it is working well now. 

About the Bulgaria page and Dutch, that is referring to the content, that they didn't provide it to me and I have to add it. The main thing is the page language doesn't change while navigating between pages.

Everything solved. Thanks

**Comment by JimBacon** [comment]
I did not change anything so this is rather a mystery!

**Comment by CrisSevilleja** [comment]
so strange, now it is working well...

**Comment by CrisSevilleja** [comment]
Hi @JimBacon sorry but this problem came back and now more pages are not switching properly to the languages... The same ones as before and several main pages on the menu:

Butterfly monitoring https://butterfly-monitoring.net/BMS 
My scheme https://butterfly-monitoring.net/my-scheme
eBMS data https://butterfly-monitoring.net/ebms-data-summary
Scheme admin https://butterfly-monitoring.net/scheme-admin
Inside the tab Scheme admin the following pages are not switching the language properly:
Scheme transect allocation https://butterfly-monitoring.net/scheme-transects-allocation
Scheme sites https://butterfly-monitoring.net/scheme-sites
Scheme visits https://butterfly-monitoring.net/scheme-walks

Inside the tab My data the following pages are not switching the language properly:
My sites https://butterfly-monitoring.net/my-sites 
My walks https://butterfly-monitoring.net/my-walks
Annual Report https://butterfly-monitoring.net/annual-report

I tried several languages in different ways and those are the pages that do not switch to the selected languages and change to English automatically. The rest of the pages work correctly. 
I am making available all the pages to all the languages because if not you get an error if the page doesn't have the translation applied (doesn't mean everything is in that language but at least it doesn't give the error). I don't think this is the problem but just to inform you.

**Comment by CrisSevilleja** [comment]
It happens again @JimBacon ! now the pages are running well, I was checking yesterday the whole day switching from pages to pages in different languages and some of them were turning into English all the time. But today no... I don't understand, I don't think you did anything but now the translation on the pages is working well. 

Maybe I need just your revision on that to make it running! XD Thank you for having a look. 

I close this issue again.

**Comment by JimBacon** [comment]
I didn't change anything so it seems, as they say, that time is a great healer.
This makes me wonder if it is a cache issue causing problems, either in your browser or the server.
If it happens again you could try clearing your browser cache to see if that helps.
Perhaps, once all the pages for translation have been created, we won't see this again.

**Comment by CrisSevilleja** [comment]
Okay, if it happens again I will try to use another browser or clean the cache. Indeed it looks like the time is the key point. 
Thank you for your patience Jim, let's hope this doesn't disturb us again.

**Comment by CrisSevilleja** [comment]
Hi @JimBacon again this problem is back. I cleaned the cache and I used Google Chrome and Microsoft Edge and the translation of the pages is not happening when you select a language different from English. 

I am sure all these pages (like before were failing: My transect sites, My transect walks, Annual Report...) have the translation applied. 

Again if you can have a look, maybe we resolve it again without knowing how... thanks

**Comment by JimBacon** [comment]
Hi @CrisSevilleja, I still can't replicate this!
If I go to, e.g., https://butterfly-monitoring.net/my-sites, and change the language to German or Spanish I see the translated page.

I am using the language selector in the top right corner to change the language and my account setting is for English. (I can imagine, having two places where you can choose the language, could lead to conflict and confusion.)

**Comment by DavidRoy** [comment]
maybe a quick zoom might pin this down?

**Comment by CrisSevilleja** [comment]
Yes, maybe we need to meet to show exactly the problem. 

The issue is not related if there is a translation or not, the problem happens when you want to navigate between pages, the language always changes to English on the same pages and does not keep the selected language. So I am in Italian I select another page and suddenly the web changes to English when it should stay in Italian. 

Let's discuss it by email one day to meet. Sorry @JimBacon  for not explaining well.

**Comment by JimBacon** [comment]
I believe I understand your problem. Look at the url of the page you are on and, before clicking a menu item, the url that the browser says it will navigate to, finally the url of the page you arrive at. They should all contain the language code as high-lighted in this screenshot, assuming you are using the language switcher in the top right of the page to select the language.

![image](https://user-images.githubusercontent.com/2545390/185409300-a1daec63-98eb-4da9-9098-903bacd41e43.png)

**Comment by CrisSevilleja** [comment]
This issue is solved, it is related to the language preference selected. When a language is selected on the account settings, this navigation problem of turning pages into English is not happening. 
The problem is when you select another language on the language selector (on the top-right) and is different from your account settings. Then when you navigate between pages normally the pages turn into the selected language of your account settings. Still to solve this but for the moment I close this issue.
