### ISSUE TITLE
eBMS website and app: add common names to butterfly lists

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#416]
Common names for Catalan, Danish, Polish, Slovenian, Bulgarian, Croatian and Lithuanian to be added to butterfly checklist.  Files sent by email.

- [x] incorporate within Indicia checklist
- [x] incorporate within ButterflyCount app

**Comment by JimBacon** [comment]
Awaiting updated files from @CrisSevilleja having the accented characters correctly encoded.

**Comment by CrisSevilleja** [comment]
Files sent by email @JimBacon 

incorporate "unknown" to the species list of butterflies

**Comment by kazlauskis** [comment]
We have now updated the common names lists in the app. 

@DavidRoy Catalan and Danish languages don't have any interface translations in Transifex. We can still push these common names for these languages but it will be strange if a user chooses on of those languages and it is still all in English, only the search results would be changed. What would you like us to do?

**Comment by DavidRoy** [comment]
@CrisSevilleja can you confirm we should go ahead with the common names but not the wider translation.  I think this is ok

**Comment by kazlauskis** [comment]
This is done now.
