### ISSUE TITLE
eBMS moth checklist - add flag for 'day-flying'

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#417]
to enable them to be recorded alongside butterflies

- [x] new taxon list attribute for moth list.id = 260 as 'Day-active' with true/false values
- [x] flag the following taxa as 'Day-active' = TRUE

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/dbr/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/dbr/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

id | taxon
-- | --
458114 | Scotopteryx chenopodiata
459370 | Euclidia glyphica
457098 | Macrothylacia rubi
460602 | Cerapteryx graminis
457094 | Lasiocampa quercus
459510 | Autographa gamma
458182 | Epirrhoe alternata
460629 | Anarta myrtilli
448693 | Phymatopus hecta
457702 | Ematurga atomaria
459627 | Panemeria tenebrata
459049 | Tyria jacobaeae
457723 | Bupalus piniaria
458534 | Perizoma albulata
457302 | Chiasmia clathrata
457146 | Saturnia pavonia
459227 | Phytometra viridaria
457312 | Petrophora chlorosata
458171 | Camptogramma bilineata
457334 | Pseudopanthera macularia
459005 | Diacrisia sannio
459047 | Euplagia quadripunctaria
459045 | Callimorpha dominula
459372 | Euclidia mi
458947 | Orgyia antiqua
458149 | Xanthorhoe montanata
458449 | Odezia atrata
455121 | Zygaena filipendulae
457232 | Abraxas grossulariata
457187 | Macroglossum stellatarum
457239 | Lomaspilis marginata

</body>

</html>

**Comment by JimBacon** [comment]
Added the Day-active taxon attribute (ID 194).
Flagged all the species in the list above, including Cristina's additions, as Day-active.

I.e. Both tasks completed. I don't seem to have permissions to mark the tasks completed or to close this issue.

**Comment by DavidRoy** [comment]
Thanks.  I've hopefully given you admin rights for this repository
