### ISSUE TITLE
ebms: new taxon list attribute 'Europe' for butterfly taxon list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#419]
Required to enable extension of ButterflyCount/eBMS beyond Europe.  Need to be able to identify taxa on the European list, versus elsewhere (e.g. Kenya, Japan etc).

- [x] new taxon_list attribute as 'Europe'
- [x] term list of attribute is term list.id 816 (Species presence code)
- [x] add the 'Europe' taxon_list attribute to taxon_list_id = 251
- [x] set value = 'P' for existing taxa on the European list (any taxa with any code other than 'A' for country taxon attributes, with the exclusion of KE)

**Comment by JimBacon** [comment]
@DavidRoy There is something ugly going on.

There is a deleted taxon list, ID 255, called ABLE Butterflies.
For this, it seems, all the country attributes were duplicated (IDs 129 to 174)
In addition, the species presence termlist was duplicated (ID 839)

The taxon list, ID 251, uses country codes with IDs  83 - 128, 175, 176, 191 in association with the species termlist ID 816.
However, one of the new countries, TRA, has picked termlist 839 instead.

Using two different termlists for the same thing is going to get us in a muddle at some point.

I propose updating the TRA attribute to refer to temlist 816, deleting termlist 839 and deleting all the duplicate country codes before proceeding with the tasks in this issue. Are you aware of any problem with this?

By the way, what standard are you using for country codes? I don't recognise TRA and there is no metadata to explain.

**Comment by DavidRoy** [comment]
@JimBacon agreed on any tidying you suggest
TRA is Asian part of Turkey. see #178

**Comment by JimBacon** [comment]
For reference, I ran the following queries to delete the duplicate attributes and the duplicate termlist:
```
UPDATE taxon_lists_taxa_taxon_list_attributes
SET deleted = true
WHERE taxon_list_id = 255;

UPDATE taxa_taxon_list_attribute_values
SET deleted = true, updated_on = now(), updated_by_id = 2
WHERE taxa_taxon_list_attribute_id >= 129
AND taxa_taxon_list_attribute_id <= 174

UPDATE taxa_taxon_list_attributes
SET deleted = true, updated_on = now(), updated_by_id = 2
WHERE id >= 129
AND id <= 174

UPDATE termlists_terms
SET deleted = true, updated_on = now(), updated_by_id = 2
WHERE termlist_id = 839

UPDATE terms
SET deleted = true, updated_on = now(), updated_by_id = 2
WHERE id >= 15545 AND id <= 15550

UPDATE termlists
SET deleted = true, updated_on = now(), updated_by_id = 2
WHERE id = 839
```
The taxon attribute TRA (id = 176) was a little confused, having some attribute values referencing termlist 816 and some 839. To fix that I ran the following;
```
UPDATE taxa_taxon_list_attribute_values
SET int_value = 16407, updated_on = now(), updated_by_id = 2
WHERE taxa_taxon_list_attribute_id = 176
AND int_value = 16594
```

**Comment by JimBacon** [comment]
@DavidRoy Just checking that you intend the Asian part of Turkey to be counted in Europe. The naming is counter-intuitive.

**Comment by DavidRoy** [comment]
@JimBacon no, TRA should not be included in the 'European' list of names

**Comment by JimBacon** [comment]
If TRA is out then this must mean AM (Armenia) is out too. I will proceed accordingly.

**Comment by JimBacon** [comment]
I've done a thorough cross-check. I need to leave out Kenya (KE), Armenia (AM) and the Asian part of Turkey (TRA). Georgia is not in either list.

I note that initially, TR implied the European part of Turkey and RU implied the European part of Russia. We then had to invent TRA for the Asian part of Turkey. Now we are adding a Europe flag we could remove TRA and instead use TR for all of Turkey, 'TR and Europe' for the European part of Turkey, and 'TR and not Europe' for the Asian part of Turkey.

**Comment by JimBacon** [comment]
Note:
The published list contains 496 species
I find 502 when checking our list for European species.
I discover the following additions in our list which all have some presence somewhere in Europe.

- Pyrgus armoricanus/serratulae (eBMS198)
- Leptidea sinapis/juvernica (eBMS210)
- Colias hyale/alfacariensis (eBMS220)
- Apatura ilia/iris (eBMS436)
- Euphydryas aurinia beckeri (eBMS453.1)
- Polyommatus icarus/celina (eBMS725)

**Comment by JimBacon** [comment]
@DavidRoy There is one species in the European list, _Hypolimnas misippus_ which is not present in any European country, but is an irregular vagrant in 3.
You have asked me to set the European presence flag to P for all species in the list. Would it be better for it to be I in this instance?
All the other species are present in at least one country.

**Comment by DavidRoy** [comment]
@JimBacon - yes, that makes most sense

**Comment by JimBacon** [comment]
For reference, the inserting of European presence values was done with the query
```
WITH eu_p AS (
SELECT ttl.id, ttl.taxon, ttl.external_key, string_agg(tt.term, ',')
FROM cache_taxa_taxon_lists ttl
LEFT JOIN taxa_taxon_list_attribute_values v
	ON v.taxa_taxon_list_id = ttl.id AND v.deleted = false
LEFT JOIN taxa_taxon_list_attributes a
	ON a.id = v.taxa_taxon_list_attribute_id AND a.deleted = false
LEFT JOIN cache_termlists_terms tt
	ON tt.termlist_id = a.termlist_id
	AND tt.id = v.int_value
WHERE ttl.taxon_list_id = 251
AND ttl.preferred = true
AND tt.term != 'A'
AND a.caption not in ('KE', 'AM', 'TRA')
GROUP BY ttl.id
HAVING string_agg(tt.term, ',') SIMILAR TO '%P,%|%P'
ORDER BY ttl.external_key
)
INSERT INTO taxa_taxon_list_attribute_values
(taxa_taxon_list_id, taxa_taxon_list_attribute_id, int_value,
created_on, updated_on, created_by_id, updated_by_id)
SELECT eu_p.id, 195, 16407, now(), now(), 2, 2 FROM eu_p
	
-- Pieris wollastoni
INSERT INTO taxa_taxon_list_attribute_values
(taxa_taxon_list_id, taxa_taxon_list_attribute_id, int_value,
created_on, updated_on, created_by_id, updated_by_id)
VALUES (432221, 195, 16411, now(), now(), 2, 2)

-- Hypolimnas misippus
INSERT INTO taxa_taxon_list_attribute_values
(taxa_taxon_list_id, taxa_taxon_list_attribute_id, int_value,
created_on, updated_on, created_by_id, updated_by_id)
VALUES (432434, 195, 16410, now(), now(), 2, 2)
```
251 is the ID of the EBMS butterfly list
195 is the ID of the Europe taxon attribute
164047 is the termlist_term ID for P(resent)
16410 is the  termlist_term ID for I(rregular)
16411 is the  termlist_term ID for Ex(tinct)
2 is my user ID

**Comment by JimBacon** [comment]
Need to trigger update of `cache_taxa_taxon_lists.attrs_json`

**Comment by JimBacon** [comment]
Thanks. I'd found it and am just waiting for the work queue to do its thing.
I executed the query
```
INSERT INTO work_queue 
	(task, entity, record_id, priority, cost_estimate, created_on)
SELECT DISTINCT 'task_cache_builder_attrs_taxa_taxon_list', 
	'taxa_taxon_list', ttl.id, 3, 60, now()
FROM taxa_taxon_lists ttl
WHERE deleted=false
AND taxon_list_id = 251
AND preferred = true;
```
