### ISSUE TITLE
Segment order incorrect in Swedish BMS transects

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#420]
I tried one of the imported SEBMS transects in ButterflyCount today and the listed segment order was not the correct one. Maybe segments (for the ordering of items) have been given numbers based on seg_uid (geo_seg_segmentid in the exported file) or some other number. The correct one is seg_sequence (geo_seg_sequence). The names S1-S4 are correct but the list order wrong see illustration:
![image](https://user-images.githubusercontent.com/19598308/166229491-28e5e19a-73c5-4670-95c2-6f48f2508197.png)

**Comment by DavidRoy** [comment]
@JimBacon @kazlauskis can you liaise on the best way to resolve this.  Thanks

**Comment by JimBacon** [comment]
The order in which the transects are imported is not something I had any obvious control over. They are in whatever order QGIS saved them in to the SHP file I guess. I imagine the app is showing them in order by Indicia location ID. See screenshot.

They need to be in order by code. Sadly, there is an 'S' stuck on the code which means sorting on the column doesn't work easily as S11 will be sorted before S2. Is it using a report, @kazlauskis, to get the list? If so, I can fix it on the warehouse fairly easily. If not then I guess I run an update on the warehouse to recreate the sections in order. I presume any update to the app is unspeakably time consuming and irksome unless other updates are in progress.

![image](https://user-images.githubusercontent.com/2545390/166432143-adee0bbc-31b8-4b51-ab92-ba07d944912f.png)

**Comment by kazlauskis** [comment]
Hi all, yeah, the app currently shows the list in the order it receives from the warehouse. It also fetches the code for each section and I can use it to sort the list that way in the app. There are some updates coming out so I will bundle this together. 

@JimBacon Do you know if the code is always in the same format - **S**{NUMBER}?

**Comment by larspett** [comment]
So in this case, a resupply to the warehouse with sections sorted on geo_seg_sequenceid would be best?

**Comment by JimBacon** [comment]
@kazlauskis The website ensures that the code for each section is in the format S{NUMBER}. I copied that when importing the Swedish transects. A check in the database confirms all sections follow this format.

@larspett It will be more robust to sort on section code than the Indicia location ID. Say you created a transect with two sections, S1 with ID=x and S2 with ID=x+1 and then wanted to insert a new section between S1 and S2. The new section will have ID=y where y > x+1. The section codes are renumbered but the IDs are not.

**Comment by JimBacon** [comment]
Yes, the Indicia warehouse returns data sorted by ID by default. It would be easy for the app to request the response to be sorted by code but the result would be wrong because the 'S' makes it an alphabetic sort rather than a numeric sort :-(

**Comment by larspett** [comment]
Would it be possible to run a resupply? There is a field which indicates the segment number (seg_sequence, in the export this should be called geo_seg_sequencid)

/Lars

**Comment by JimBacon** [comment]
Hi @larspett,
Are you saying that this is still a problem? It has been closed which means it should be fixed.
