### ISSUE TITLE
Import Croatian Observation Data

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/ABLE#423]
Import observations made on transects in 2020-21 from file supplied by email.

**Comment by JimBacon** [comment]
Hi @DavidRoy 

I have suggested to Martina that I import the data in to the `EBMS ad-hoc imports` survey because it lacks the below fields required for the transects survey. However, that suggestion was based solely on the appropriate name of the survey and suitable attributes! Is this a bad idea? I see only one sample in this survey and I don't know if the website will show records in this survey.

Fields not in data
- start time
- end time
- temperature
- wind speed

**Comment by DavidRoy** [comment]
@JimBacon I think it's best to import into the standard EBMS transect survey.  There is a 'Not recorded' option for temperature and wind speed I believe.  For the start and end time, if they are required fields please set as '00:00'

**Comment by DavidRoy** [comment]
These all need to be added as new taxa for recording.
For the Genus-level aggregates, these can be marked as 'P' for all of Europe
For the other aggregates, we'll need to review these with other countries.
For the sub-species records, we'll also need to review these with other countries

This final point means we'll need a way of reviewing taxa x country lists through a web interface at some point.  We discussed this before in the context of FIT Counts etc?

**Comment by JimBacon** [comment]
For info I have done the following
1. On the warehouse,
    1. Updated transect section, Đakovo_Jošava - S1  to [Đakovo, Jošava - S1](https://warehouse1.indicia.org.uk/index.php/location/edit/290315)
    4. Added synonym _Polyommatus semiargus_ to _[Cyaniris semiargus](https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/432337)_ 
	5. Updated taxon Thymelicus lineolus/sylvestris to [Thymelicus lineola/sylvestris](https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/434662)
	6. Added missing taxa
	   - Argynnis sp, Aricia sp., Carcharodus sp., Colias sp., Cupido sp., Hipparchia sp., Lycaena sp., Polyommatus sp., Pyrgus sp., Spialia sp.
	   - Melitaea athalia/aurelia/britomartis, Plebejus argus/idas
       - Colias cf. hyale, Cupido cf. alcetas, Gonepteryx cf. cleopatra, Melitaea cf. athalia, Plebejus cf. argyrognomon
       - Phengaris alcon alcon, Phengaris alcon rebeli

1. From the spreadsheet of occurrences, extract a list of walks based on unique transect name, date and observer.
5. With the spreadsheet of walks, 
    1. Add columns for start time, end time and wind speed. For each walk, set these values to '00:00', '00:00', and 'Not recorded/no data', respectively.
    2. Combine the x and y coordinate columns in to a single spatial reference.
    6. Add a column with a unique external key for each walk. (Must not contain characters that are invalid in file names.)
    7. Upload to the samples table with the following settings and column mappings
        1. Spatial ref. system set to HTRS96 / Croatia TM
        4. Sample method set to transect
        9. Location type set to transect 
        1. External key maps to sample:external key
        2. Transect name maps to sample:Location (from controlled termlist)
        12. Spatial reference maps to sample:Grid ref or other spatial ref
        13. Date maps to sample:date
        14. Observer maps to smpAttr:recorder name
        15. Start time maps to smpAttr:start time
        16. End time maps to smpAttr:end time
        17. Wind speed maps to smpAttr:wind speed (from controlled termlist)
3. With the spreadsheet of occurrences,
    1. Add and populate a column for the external key of the parent sample
    3. Add and populate a column for the transect-section name by appending ' - S1' to the transect name as all the transects have just one section.
    4. Modify the life stage column to be consistent with terms for the Butterfly life stage attribute
    5. Upload to the occurrences table with the following settings and column mappings
        1. Spatial ref. system set to HTRS96 / Croatia TM
        2. Species list set to EBMS Butterflies
        3. Record status set to accepted
        4. Sample method set to transect section
        8. Parent sample method set to transect
        9. Location type set to transect section
        10. External key maps to sample:Parent sample external key (from controlled termlist)
        11. Section name maps to sample:Location (from controlled termlist)
        12. Spatial reference maps to sample:Grid ref or other spatial ref
        13. Date maps to sample:date
        18. Species maps to occurrence:Species or taxon name
        19. Count maps to occattr:Abundance count
        20. Stage maps to occattr:Butterfly life stage (from controlled termlist)

**Comment by JimBacon** [comment]
Forgot that I still have to set the species presence for the genus-level aggregates.
I will raise a separate issue for a way of reviewing taxa x country lists through a web interface.

**Comment by JimBacon** [comment]
I inserted the species presence for the genus-level aggregates as follows. I didn't follow the suggestion to "mark as 'P' for all of Europe" because there were countries where all members of the genus were absent. For the Europe-wide attribute, the outcome was naturally 'P' for all cases.
```
WITH genera AS (
	-- Get the meaning_ids for the list of genera
	SELECT taxon, taxon_meaning_id
	FROM cache_taxa_taxon_lists ttl
	WHERE taxon_list_id = 251
	AND preferred = true
	AND taxon IN ('Argynnis', 'Aricia', 'Carcharodus', 'Colias', 'Cupido',
		'Hipparchia', 'Lycaena', 'Polyommatus', 'Pyrgus', 'Spialia')
),
genus_country_presence_agg as (
	-- For each genus in each country, aggregate the presence attribute
	-- for all the lower taxa
	SELECT g.taxon genus,  a.caption country, a.id, array_agg(tt.term) presence
	FROM cache_taxa_taxon_lists ttl
	JOIN cache_taxon_paths tp ON tp.taxon_meaning_id = ttl.taxon_meaning_id
	JOIN genera g ON g.taxon_meaning_id = ANY(tp.path)
	LEFT JOIN taxa_taxon_list_attribute_values v
		ON v.taxa_taxon_list_id = ttl.id AND v.deleted = false
	LEFT JOIN taxa_taxon_list_attributes a
		ON a.id = v.taxa_taxon_list_attribute_id AND a.deleted = false
	LEFT JOIN cache_termlists_terms tt
		ON tt.termlist_id = a.termlist_id
		AND tt.id = v.int_value
	where ttl.preferred = true
	-- Species aggregate or lower
	AND ttl.taxon_rank_sort_order >=290
	-- Exclude non-European countries and Croatia which was addded manually.
	AND a.caption not in ('KE', 'AM', 'TRA', 'JP', 'HR')
	GROUP BY genus, country, a.id
	ORDER BY genus, country, a.id
),
genus_country_presence as (
	-- Convert the aggregate array to a single presence value
	SELECT genus, country, id, presence,
	CASE WHEN 'A' = all(presence) THEN 'A' 
		WHEN 'P' = any(presence) THEN 'P'
		WHEN 'P?' = any(presence) THEN 'P?'
		WHEN 'M' = any(presence) THEN 'M'
		WHEN 'I' = any(presence) THEN 'I'
		WHEN 'Ex' = any(presence) THEN 'Ex'
	END present	
	FROM genus_country_presence_agg
	ORDER BY genus, id
),
genus_country_presence_ids as (
	-- Obtain relevant id to insert in attribute values table. 
	SELECT ttl.id ttl_id, ttl.taxon,
		gcp.id ttl_attribute_id, gcp.country,
		tt.id tt_id, tt.term
	FROM cache_taxa_taxon_lists ttl
	JOIN genus_country_presence gcp 
		ON gcp.genus || ' sp.' = ttl.taxon
	JOIN cache_termlists_terms tt
		ON tt.term = gcp.present
	WHERE ttl.taxon_list_id = 251
	AND tt.termlist_id = 816
)
-- Insert attribute values for the presence of the genus
-- aggregates in all European countries.
INSERT INTO taxa_taxon_list_attribute_values
(taxa_taxon_list_id, taxa_taxon_list_attribute_id, int_value,
	created_on, updated_on, created_by_id, updated_by_id)
SELECT gcpi.ttl_id, gcpi.ttl_attribute_id, gcpi.tt_id, 
	now(), now(), 2, 2 
FROM genus_country_presence_ids gcpi
```
This was followed by 
```
INSERT INTO work_queue 
	(task, entity, record_id, priority, cost_estimate, created_on)
SELECT DISTINCT 'task_cache_builder_attrs_taxa_taxon_list', 
	'taxa_taxon_list', ttl.id, 3, 60, now()
FROM cache_taxa_taxon_lists ttl
WHERE taxon_list_id = 251
AND taxon IN ('Argynnis sp.', 'Aricia sp.', 'Carcharodus sp.',
	'Colias sp.', 'Cupido sp.', 'Hipparchia sp.', 'Lycaena sp.',
	'Polyommatus sp.', 'Pyrgus sp.', 'Spialia sp.');
```

**Comment by JimBacon** [comment]
Hi @CrisSevilleja 

There is one species list for eBMS.

For each species there are presence attributes indicating which species are present in which country.

When entering data via the app or website, the entire list (which now includes Japanese and Kenyan species too) could be filtered to only show species found in the country of the transect. I do not think the website does this but I think the app does. While the website shows the changes immediately, the app won't show changes until the next release. (For example, I can go to the website, pick a test transect in France and add Kenyan species. Fixing this is work in progress, https://github.com/BiologicalRecordsCentre/ABLE/issues/233 )

Updates to names and synonyms will apply everywhere those names can be seen.

The new genus-level aggregates have had the presence in each European country set based upon the presence of species in that genus in that country. For example, in the Netherlands we have the following.
| Taxon           | Presence |
|-----------------|----------|
| Argynnis sp.    | P        |
| Aricia sp.      | P        |
| Carcharodus sp. | P        |
| Colias sp.      | M        |
| Cupido sp.      | P        |
| Hipparchia sp.  | P        |
| Lycaena sp.     | P        |
| Polyommatus sp. | P        |
| Pyrgus sp.      | P        |
| Spialia sp.     | Ex       |

This was my more complex interpretation of David's instruction 'these can be marked as 'P' for all of Europe'

The other new taxa i.e.
 - aggregates like Plebejus argus/idas
 - uncertain identifications like Colias cf. hyale
 - sub-species like Phengaris alcon alcon
 
have only had presence set for Croatia because David said 'we'll need to review these with other countries'

Does that answer your question?

**Comment by CrisSevilleja** [comment]
Hi @JimBacon , yes totally, you replied to my question perfectly. I wanted to know this exactly: "Updates to names and synonyms will apply everywhere those names can be seen." For the other new taxa is okay and understandable, we need to check it first. 

quite complicated task but well organised. Thank you Jim.
