### ISSUE TITLE
Selecting the English language doesn't change the species names

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#425]
By default on the app when the English language is selected the common names of the species appear in English and the Latin name disappears. Some users know the Latin names and not English, important to keep the Latin names. 

- change to have the possibility to select the English language but keep the species name in Latin on the Picture Guide. 

I was thinking that maybe add another field on the App Setting for selecting the species name in English or Latin. Could be possible like that? @DavidRoy @kazlauskis

**Comment by DavidRoy** [comment]
@crissevilleja - is this a wider requirement for recorders to choose their language choice? Latin or common names in different languages?
