### ISSUE TITLE
Add picture and comment on the transect section- ButterflyCount

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#428]
when registering data per section in a transect, be possible to add the fields of taking pictures and comment on the section

**Comment by kazlauskis** [comment]
@CrisSevilleja like here in the screenshot, yeah?

![butterflies app flumens io_(iPhone SE) (1)](https://user-images.githubusercontent.com/7383162/168757303-29172704-fc9e-4146-9dfc-9edfa6caa49a.png)

**Comment by CrisSevilleja** [comment]
exactly @kazlauskis like that is good. Thanks
