### ISSUE TITLE
Walk data entry page - species list does not load

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#43]
Species list does not load.

When selecting 'All species' list option, the list of species does not load (the page gets stuck on spinning circle in dropbox)

Page being tested: http://live-butterfly-monitoring.pantheonsite.io/ebms-input-data?location_type_id=107&date=06/04/2019

**Comment by Gary-van-Breda** [comment]
Code change dropped into dev and test - not live yet.
Note there is some interaction with #44: #44 causes a JS error, which can mean the change event for the species list is not set up: in which case changing the species list does nothing.

**Comment by DavidRoy** [comment]
Works as expected on test.  Please deploy to live

**Comment by Gary-van-Breda** [comment]
Now deployed to Live.

**Comment by DavidRoy** [comment]
Thanks, works well
