### ISSUE TITLE
eBMS: add Japanese species list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#431]
- [x] Create new taxon_list attribute for Japan - JP
- [x] Create new languages entry for Japanese - jpn
- [x] Match genera to existing taxon list 251 and add missing genera to the list.
- [x] Match list against GBIF backbone to obtain authority and an external key for species.
- [x] Match species to existing taxon list 251.  Set [JP] = 'P' where Japanese species already in the list.
- [x]  Match species to existing taxon list 251.  Where Japanese species are already in the list, add the Japanese common name.
- [x] Add missing species to the taxon list, with [JP] = 'P'
- [x] Update the attrs_json field in the cache_taxa_taxon_lists table

List emailed separately

**Comment by kazlauskis** [comment]
@JimBacon do you know if the Japanese list is now in the warehouse? no problem if not.

**Comment by JimBacon** [comment]
@DavidRoy can you clarify a few points regarding the species list please.

- Does the _sp._ abbreviation indicate a species aggregate?
- Why are there two records for _Papilio sp._ (Code 115 and 185)?
- Why are there three records for _Brenthis sp._ (Code 1410, 1415 and 1425)?
- Why are there two records for _Argynnis adippe_ (Code 1502, 1505)?

**Comment by DavidRoy** [comment]
@JimBacon sp. means a species within the Genus.  It can be in the list as a Genus entry but will need to be available for data entry - e.g. where it is not possible to identify the individual species

Argynnis adippe x 2 is a duplication error.  One can be removed

**Comment by JimBacon** [comment]
@DavidRoy If we are encouraging data entry by genus (it is currently available for any genus, I think) then that begs a couple of questions:

1. Do we need to set the country presence attributes on genera?
2. Do we want to allow recording against some genera and not others?

Creating a record, e.g. _Papilio sp._ as a child of the _Papilio_ genus with taxon rank of species sounds easier to me.

I've noticed that the duplicates I listed above have differing Japanese names so I will treat them as alternate common names.

**Comment by DavidRoy** [comment]
@JimBacon I agree that 'Papilio sp.' is a better option for cases where this is needed.  You are right that using the Genus names is more complicated.

**Comment by JimBacon** [comment]
All of the families in the Japanese list already exist in taxon_list 251 but the genera in the following file do not.
We can import them from the file via the warehouse web interface, mapping the Family column to the parent taxon. 
[new-genera.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/8941146/new-genera.csv)

**Comment by JimBacon** [comment]
Species that are new to the list can be imported via the warehouse web interface from the following file. The GBIF_code column is mapped to the Search Code field and the GBIF_preferred_code is mapped to the External Key field. The Genus column is mapped to the the parent taxon.
[new-species.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/8941690/new-species.csv)

**Comment by JimBacon** [comment]
For info, using the attached file containing data on Japanese species already present in the EBMS butterfly list, the following query created and set the JP attribute values. 
[existing-species.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/8942006/existing-species.csv)
```
WITH jptaxa AS (
	SELECT * FROM (VALUES 
		(432126),
                 ...,
		(549154)
	) 
)
INSERT INTO taxa_taxon_list_attribute_values
(taxa_taxon_list_id, taxa_taxon_list_attribute_id, int_value,
created_on, updated_on, created_by_id, updated_by_id)
SELECT jptaxa.id, 196, 16407, now(), now(), 2, 2 
FROM  jptaxa
```
196 is the ID of the JP taxon attribute
16407 is the termlist_term ID for P(resent)
2 is my user ID

**Comment by JimBacon** [comment]
For info, the following query created taxa and taxa_taxon_list records for Japanese names of existing species.
```
WITH jptaxa AS (
	SELECT * FROM (VALUES 
                (432126, 'キアゲハ'),
                 ...,
		(549154, 'チャバネセセリ')
	) AS t (id, name)
), 
-- Combine new name with preferred taxon information needed
-- to create taxon record
taxa_info AS (
	SELECT ttl.id, taxon, name, taxon_group_id, external_key
	FROM cache_taxa_taxon_lists ttl
	JOIN jptaxa ON jptaxa.id = ttl.id
),
-- Create new taxon record returning new id
new_taxa AS (
	INSERT INTO taxa
	(taxon, taxon_group_id, language_id, external_key, scientific,
		created_on, created_by_id, updated_on, updated_by_id)
	SELECT name, taxon_group_id, 22, external_key, false, now(), 2, now(), 2
	FROM taxa_info RETURNING id AS taxon_id, external_key
),
-- Combine new id with existing taxon_meaning_id needed
-- to create taxa_taxon_list record
taxa_info_2 AS (
	SELECT new_taxa.taxon_id, ttl.taxon_meaning_id
	FROM cache_taxa_taxon_lists ttl
	JOIN new_taxa ON 
		new_taxa.external_key = ttl.external_key AND
		ttl.preferred = true AND
	    ttl.taxon_list_id = 251
)
-- Create new taxa_taxon_list record.
INSERT INTO taxa_taxon_lists
(taxon_list_id, taxon_id, taxon_meaning_id, preferred,
	created_on, created_by_id, updated_on, updated_by_id)
SELECT 251, taxon_id, taxon_meaning_id, false, now(), 2, now(), 2
FROM taxa_info_2
```

**Comment by JimBacon** [comment]
For info, the following query will update the attrs_json field for all the taxa in the species list.
```
INSERT INTO work_queue 
	(task, entity, record_id, priority, cost_estimate, created_on)
SELECT DISTINCT 'task_cache_builder_attrs_taxa_taxon_list', 
	'taxa_taxon_list', ttl.id, 3, 60, now()
FROM taxa_taxon_lists ttl
WHERE deleted=false
AND taxon_list_id = 251
AND preferred = true;
```

**Comment by JimBacon** [comment]
@kazlauskis The Japanese list is now in the warehouse. May take a short while for caches to update.

I'm conscious that we may have introduced a problem by obtaining `external key` and `search_code` from the GBIF Backbone Taxonomy rather than assigning eBMS codes. As not all the names have a match in GBIF there are some null values. Indexing via ElasticSearch is where I think this may come to be an issue to fix.

**Comment by kazlauskis** [comment]
We have added Japan 🇯🇵 and its species to the [app demo](https://butterflies.app.flumens.io/demo.html) now. 

@CrisSevilleja, please forward this to the Japanese translator to double-check everything is correct. We can then push this to the Beta testing.

![localhost_8000_survey_precise-area_60af069d-573b-4f45-9d44-2adbd1af8bf4_edit_taxon(iPhone SE) (1)](https://user-images.githubusercontent.com/7383162/174776404-6f39f269-6ed9-4d70-b884-edae6e1af414.png)
![localhost_8000_survey_precise-area_60af069d-573b-4f45-9d44-2adbd1af8bf4_edit_taxon(iPhone SE)](https://user-images.githubusercontent.com/7383162/174776400-bf25052a-8962-4bdd-9b3c-233946d9484a.png)
