### ISSUE TITLE
eBMS: add Kenyan species list

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/ABLE#432]
Match list against GBIF backbone to obtain authority and an external key.
Add missing genera to existing taxon list 251. Can be added as children of families with no need to use sub-families.
Add missing species to taxon list 251 as children of respective genera.
Set existing taxon_list attribute for Kenya - KE, id=191 - to  'P' for all species in list

List emailed separately

**Comment by JimBacon** [comment]
All of the families in the Kenyan list already exist in taxon_list 251 but none of the genera do.
We can import them from the following csv file via the warehouse web interface, mapping the Family column to the parent taxon.
[ebms_kenya_genera.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/8862763/ebms_kenya_genera.csv)

**Comment by JimBacon** [comment]
The species can be imported via the warehouse web interface from the following csv file.
The GBIF_code column is mapped to the Search Code field and the GBIF_preferred_code is mapped to the External Key field.
[ebms_kenya_species.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/8868581/ebms_kenya_species.csv)

**Comment by JimBacon** [comment]
@DavidRoy I stumbled on a possible typo. The list includes _Nepheronia bugueti_ (synonym: _Nepheronia buquetii_). Google doesn't show anyone else spelling it with a 'G'. Can you confirm?

**Comment by JimBacon** [comment]
The import revealed a bug, https://github.com/Indicia-Team/warehouse/issues/438, which caused the authority of some species to be incorrect. The following query rectified the problem in the data.
```
UPDATE taxa t
SET authority = null, updated_on = now(), updated_by_id = 1
FROM taxa_taxon_lists ttl
WHERE t.authority = 'taxon:authority' AND
	t.deleted = false AND
	ttl.taxon_list_id = 251 AND
	ttl.taxon_id = t.id AND
	ttl.deleted = false
```

**Comment by DavidRoy** [comment]
@CrisSevilleja can you check with Kenya colleagues about the species name?

**Comment by CrisSevilleja** [comment]
@JimBacon _Nepheronia buquetii_ is the correct name, as you said it had been a mistake. Getting close to get Kenyan species on eBMS! Thanks

**Comment by JimBacon** [comment]
Note: Import to warehouse complete but not exported to ElasticSearch. Null `external_key` and `search_code` fields will have to be filled before doing the export.
