### ISSUE TITLE
SPRING Moth trap data download - for individuals

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#433]
Add moth trap download to my_data -> downloads page, to allow individuals to download their own data
https://butterfly-monitoring.net/mydata/downloads

Same download report as available for role = regional co-ordinator under 
https://butterfly-monitoring.net/downloads

@johnvanbreda can you pick this up on the assumption that it's a small job?

**Comment by Helder-Cardos** [comment]
Reinforcing the need for this feature

**Comment by johnvanbreda** [comment]
@DavidRoy there are 2 surveys for moth data - 616 and 681. Which survey does this requirement relate to?

**Comment by DavidRoy** [comment]
@johnvanbreda 
It is 681
thanks

**Comment by johnvanbreda** [comment]
Done

**Comment by DavidRoy** [comment]
Thanks John. @Helder-Cardos - please raise a new issue with any problems or extra requirements
