### ISSUE TITLE
Incorrect link entering records- Transect Input 

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#438]
@kazlauskis reviewing the demo, I found one error when increasing the individuals on the Transect Input part (section). Better to explain with an image:
Below in the picture, when pressing the number on the left, that works increasing the number but the app brings you to the Edit occurrence page (red arrow) - Incorrect link 
When pressing on the species name, the app brings you to the Edit occurrence page (green arrow) - Correct link 

![Entering records-app](https://user-images.githubusercontent.com/25052478/172350046-67c50f2e-98e8-40e2-bc1f-4026cab1739b.png)

could you correct the incorrect link, and only allow to increase the number of individuals. Thanks

**Comment by kazlauskis** [comment]
Ah, thanks, the demo isn't perfect but this actually works in the real app.
