### ISSUE TITLE
Walk data entry page - unable to search for species

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#44]
http://live-butterfly-monitoring.pantheonsite.io/ebms-input-data?location_type_id=107&date=06/04/2019

Trying to add a species for recording, using the 'Add species to the list:' option.  Names not found - text box gets stuck with the spinning circle

**Comment by Gary-van-Breda** [comment]
@DavidRoy : I think this was a clash between the masquerade block autocomplete and the IForm one. I have disabled the masquerade block on all indicia pages on Dev, Test and Live.
Could you double check this is now working for you?

**Comment by DavidRoy** [comment]
that's worked, thanks
