### ISSUE TITLE
Translation of new functions: Entry Walk Data - eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#440]
@DavidRoy @JimBacon @Gary-van-Breda 
All the new improvements and functions applied to the eBMS website are great but I am worried about volunteers not understanding English and not being able to register data (I heard some already). 

I was wondering how I can include the translation of the new message "Mandatory Section Data", the top-down list for Reliability, and the question, Any butterfly? Without understanding those functions, especially the last one it is not possible to include data on the web. I look for those strings on the translation source (locale) on the website https://butterfly-monitoring.net/admin/tmgmt/sources/locale/default?label=Any%20butterfly%3F&missing_target_language=&context= and I was not able to find those strings there. 

Thanks
![2022-06-08_08h56_48](https://user-images.githubusercontent.com/25052478/172876416-6d4b1308-ec23-43c9-9170-0c642858e585.png)

**Comment by CrisSevilleja** [comment]
I just found "Any Butterflies?" and request the translation, but I am sure the connection with Transifex is not working properly...

**Comment by JimBacon** [comment]
Text on the forms created by the Indicia software is mostly available for translation through Drupal. (Note to developers. Text which is passed through the Indicia lang::get() function is made available in this way provided the configuration is set in helper_config.php, ref https://github.com/BiologicalRecordsCentre/ABLE/issues/390)

Follow the admin menu to Translation > Sources and select 'Locale' in the drop down list labelled 'Choose source'. Alternatively use this link, https://butterfly-monitoring.net/admin/tmgmt/sources/locale/default

The table shown on the page lists text available for translation. My understanding is this list is built from failed attempts at translation, i.e. you have to try to view a page in a non-English language for the system to discover that translation is required.

Type the start of the text you want to translate in the 'Source text' box (better still, copy and paste) and click the Search button to quickly find text to translate. It is case sensitive.

By this method I can find, e.g.,

- 'Any Butterflies?' and 'Any Moths?' as mentioned above (Note capital letters).
- 'You must enter the highlighted section related data before you may enter any species counts.' from the dialog above
- 'Combine data for...' options for the annual report page


Unfortunately, the dialog heading, 'Mandatory Section Data', mentioned above, is hard-coded in English.

The reliability options come from a termlist in the warehouse (https://warehouse1.indicia.org.uk/index.php/termlist/edit/837?tab=terms). Like species common names, the mechanism for translating them is to add the translations to the warehouse and then include the desired language in the web service request which obtains the values to display. This will need a modification to the code in addition to adding the translations to the warehouse. The change to the code is dependent on the outcome of https://github.com/BiologicalRecordsCentre/ABLE/issues/472
