### ISSUE TITLE
ButterflyCount: handling of missing weather data

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#441]
@chrisvanswaay reports on latest test version
_All went well, except that I got a problem trying to upload a count without weather data (as we were in a place without connection). It gave an error, but it worked when I entered a temperature by hand. It didn't complain about the other weather parameters (cloud, wind) missing._

@kazlauskis can you review how this scenario is handled.  my view is that weather should default to 'Not recorded' but there should then be a message on submission to warn the recorder of this and to give the option to add values by hand.  Should be a rare occurrence as weather data is typically available automatically.

**Comment by kazlauskis** [comment]
Thanks. I've fixed this one now; it was a Beta app issue.
