### ISSUE TITLE
Moth common names stop working

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#445]
### Describe the issue

I used the new version of the app several times this weekend and activated day-flying moths. First, I was able to use the Swedish common name Ängsmätare for <i>Ematurga atomaria</i>Then I saw a “Blåbärslundmätare” <i>Jodis putata</i> which is also day-active. However, the common name didn’t pull any name from the search field. I supposed this was because it might not have been tagged as day-flying (my bad, in that case) but tried the scientific name which (to my surprise) worked. However, after that Ängsmätare no longer worked as a common name (but the scientific one still does). Weird. 

### App Version

1.17.0 build 185

### Device

iPhone 13 pro

### When did this happen

Sunday, several times

**Comment by kazlauskis** [comment]
@larspett thanks, we're looking into this now.

**Comment by CrisSevilleja** [comment]
Also reported for Dutch common names for day-flying moths. Thanks @kazlauskis for having a look

**Comment by kazlauskis** [comment]
Thanks again for reporting this. This is fixed now and will come out with the next beta release soon
