### ISSUE TITLE
Button styling on data entry forms

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#45]
@BirenRathod Can you look at these web page styling issues.
On walk data entry page, e.g. http://live-butterfly-monitoring.pantheonsite.io/ebms-input-data?sample_id=11570

Buttons not displaying on walk details page.
![able2](https://user-images.githubusercontent.com/2699478/56205465-c1ad1f80-6041-11e9-8132-3c79719f5fe9.png)

Buttons at bottom of the page not displaying as expected on count entry page.
![able1](https://user-images.githubusercontent.com/2699478/56205394-90345400-6041-11e9-9a56-02a24923d818.png)

**Comment by BirenRathod** [comment]
@DavidRoy 
Styles have been implemented now on both pages.

**Comment by BirenRathod** [comment]
@DavidRoy 
Can you check it now?

I have implemented button and & links styles, so should look more appropriate.

**Comment by DavidRoy** [comment]
Better, but there is some overlap between the 'button/link style' and the search box above. See this example.  Could the text/links be moved further down the page?
![able3](https://user-images.githubusercontent.com/2699478/56301682-2f377980-6130-11e9-8e2b-3367917857fa.png)

**Comment by BirenRathod** [comment]
@DavidRoy 

Added bit more margin, so should not overlap.

**Comment by DavidRoy** [comment]
Thanks, that worked
