### ISSUE TITLE
Issue: species for Kenya incomplete?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#453]
### Describe the issue

Set country - Kenya
Go to guide and suggests country species list = 5.  It should be many more

need to check if problem with warehouse report or app

### Expected behavior

Correct number of species for kenya

### To Reproduce

Go to menu-settings-app 
Set country = Kenya
Go to Guide
Text says guide covers 2 out 5 species country 

### App Version

1.17.0 (190)

### Device

iPhone 12

### When did this happen

30/6/22

### Screenshots

![71F9DE93-0854-4BA7-A0AA-160959E9FD27](https://user-images.githubusercontent.com/2699478/176715933-2c2e78b6-f2ce-4b02-8f6b-a8d482350efd.png)

**Comment by kazlauskis** [comment]
Most of the Kenyan species don't yet have the profile texts or pics. This guide only shows the ones that have both.

**Comment by DavidRoy** [comment]
I still don’t understand why the right total of 217 is not given.  I understand the profile information is mostly missing.

can you easily fix?
