### ISSUE TITLE
Duplicate section records on walks

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/ABLE#459]
There are many walks where, instead of having one sample for each section, there are many samples for a section. This was observed in https://github.com/BiologicalRecordsCentre/ABLE/issues/317#issuecomment-1184572698.

Over the EBMS transects there are thousands of such duplicates. Mostly this looks like errors introduced when importing Spanish records. This unexpected data arrangement means reports will not return records as intended. For example, https://butterfly-monitoring.net/walk-data-entry?sample_id=8423891 shows only a few of the occurrences that I think should appear for this walk.

**Comment by DavidRoy** [comment]
Sorry for the Spanish loading issue - my bad

**Comment by CrisSevilleja** [comment]
@JimBacon what I get is that this issue is different for the #317 duplicated sections you already solved, am I right? 

Regarding the Spanish data import, the coordinator was reporting always problems with visualizing well the Spanish data imported in the migration (before 2020). Also, this brings me to another issue #325 about data visualization where a data fix is needed. Do you know something about this @JimBacon or is this completely different? Thanks

**Comment by JimBacon** [comment]
Hi Cristina,
This is exactly the same problem that was reported in #325!

**Comment by JimBacon** [comment]
As an initial step to fixing this, I am checking if any of the duplicate samples have attributes which need to be managed. Mostly they don't. Where they do, there is mostly only one sample in the set of duplicates for a transect section having attributes. 

There are only two instances where more than one sample in a duplicate set for a section on a walk has attributes, as follows

```
walk_id   section                           sample    attrs_json
8386203   "Jardín Botánico Albacete - S1"   8386207   "{"1387":"90","1457":"10"}"
8386203   "Jardín Botánico Albacete - S1"   8386209   "{"1387":"90"}"
```
and 
```
8641339   "Jardín Botánico Albacete - S1"   8641341   "{"1387":"90","1457":"10"}"
8641339   "Jardín Botánico Albacete - S1"   8641345   "{"1387":"90"}"
```

I am going to mark the attribute values for sample IDs 8386209 and 8641345 as deleted as this will simplify operations with no loss of information once all the duplicates on a section are merged.

**Comment by JimBacon** [comment]
Second step is, where one sample in a duplicate set has attribute values, to consolidate the records for that transect section on to the sample with attribute values. 

Firstly we re-assign the occurrences of the duplicate samples to the sample we are going to keep. Then we can delete the duplicate samples. 

```
WITH ebms_sections AS (
	SELECT l.* 
	FROM locations l
	JOIN locations_websites lw
		ON lw.location_id = l.id
		AND lw.website_id = 118
	WHERE l.deleted = false
		AND l.location_type_id = 778
),
walks_with_multiple_samples_per_section AS (
	SELECT s.parent_id walk_id, s.location_id section_id, l.name section_name, count(s.id) samples_in_section
	FROM samples s
	JOIN ebms_sections l
		ON l.id = s.location_id
	WHERE s.survey_id = 562
		AND s.deleted = false
	GROUP BY s.parent_id, s.location_id, l.name
	HAVING count(s.id) > 1
	ORDER BY count(*) desc
),
samples_having_attributes AS (
	SELECT w.walk_id, w.section_id, w.section_name, s.id, snf.attrs_json
	FROM cache_samples_functional s
	JOIN walks_with_multiple_samples_per_section w
		ON w.walk_id = s.parent_sample_id
		AND w.section_id = s.location_id
	JOIN cache_samples_nonfunctional snf
		ON snf.id = s.id
	WHERE snf.attrs_json is not null
	ORDER BY s.parent_sample_id, s.location_name
),
duplicates_of_samples_having_attributes AS (
	SELECT walk_id, sha.id keep_id, section_name, s.id duplicate_id
	FROM samples_having_attributes sha
	JOIN cache_samples_functional s
		ON s.parent_sample_id = sha.walk_id
		AND s.location_id = sha.section_id
		AND s.id != sha.id
	ORDER BY walk_id, section_name, duplicate_id
)

UPDATE occurrences o
SET sample_id = keep_id, updated_on = now(), updated_by_id = 2
FROM duplicates_of_samples_having_attributes dups
WHERE o.sample_id = duplicate_id
```
and
```
UPDATE samples s
SET deleted = true, updated_on = now(), updated_by_id = 2
FROM duplicates_of_samples_having_attributes dups
WHERE s.id = duplicate_id
```

**Comment by JimBacon** [comment]
Finally, for the remaining duplicate sets, we can consolidate around an arbitrary sample (taken as the one with the lowest id) 

Again we re-assign the occurrences of the duplicate samples to the sample we are going to keep. Then we delete the duplicate samples.

```
WITH ebms_sections AS (
	SELECT l.* 
	FROM locations l
	JOIN locations_websites lw
		ON lw.location_id = l.id
		AND lw.website_id = 118
	WHERE l.deleted = false
		AND l.location_type_id = 778
),
walks_with_multiple_samples_per_section AS (
	SELECT s.parent_id walk_id, s.location_id section_id, l.name section_name, count(s.id) samples_in_section
	FROM samples s
	JOIN ebms_sections l
		ON l.id = s.location_id
	WHERE s.survey_id = 562
		AND s.deleted = false
	GROUP BY s.parent_id, s.location_id, l.name
	HAVING count(s.id) > 1
	ORDER BY count(*) desc
),
samples_to_keep AS (
	SELECT walk_id, section_id, section_name, min(id) keep_id
	FROM cache_samples_functional s
	JOIN walks_with_multiple_samples_per_section w
		ON w.walk_id = s.parent_sample_id
		AND w.section_id = s.location_id
	GROUP BY walk_id, section_id, section_name
	ORDER BY walk_id, section_name
),
duplicates AS (
	SELECT walk_id, section_name, keep_id, s.id duplicate_id
	FROM samples_to_keep stk
	JOIN cache_samples_functional s
		ON s.parent_sample_id = stk.walk_id
		AND s.location_id = stk.section_id
		AND s.id != stk.keep_id
	ORDER BY walk_id, section_name, duplicate_id
)

UPDATE occurrences o
SET sample_id = keep_id, updated_on = now(), updated_by_id = 2
FROM duplicates dups
WHERE o.sample_id = duplicate_id
```
and
```
UPDATE samples s
SET deleted = true, updated_on = now(), updated_by_id = 2
FROM duplicates dups
WHERE s.id = duplicate_id
```

**Comment by JimBacon** [comment]
The data should now be organised correctly. It appears so in one example tested. https://github.com/BiologicalRecordsCentre/ABLE/issues/325#issuecomment-1245047114

**Comment by xaviermestdagh** [comment]
Hi, 
We also observed duplicated records on section walks, but I don't know if this is related to the same issue. For instance the same species is observed up to 5x1 individual on the same section walk, all 5 records with a unique occurrence ID.
FYI, records have been exported from butterfly-monitoring.net through the annual report https://butterfly-monitoring.net/annual-report. 
Could you have look for instance to the following records I highlighted? 
[Duplicate records on section walks.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/10400286/Duplicate.records.on.section.walks.xlsx)
Thanks!

**Comment by JimBacon** [comment]
The above comment relates to a separate issue. See https://github.com/BiologicalRecordsCentre/ABLE/issues/543
