### ISSUE TITLE
Downloads tab on annual summary - error message

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#46]
On: http://live-butterfly-monitoring.pantheonsite.io/annual-report?userID=all

Page shows error message:
Internal Config error: directory does not exist sites/default/files/reportsDownloads/

@BirenRathod can you take this on as relates to configuration on Pantheon?

The download links all work fine though

**Comment by BirenRathod** [comment]
@DavidRoy 
That is easy to resolve, just to create that folder. I have created in files folder, so should be work now.

**Comment by DavidRoy** [comment]
thanks
