### ISSUE TITLE
Drawn section length are wrong for Japan: eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#460]
Japanese BMS started to draw transects on the eBMS system and the coordinator realised the section length are wrong for Japan (presumably for outside of Europe). One transect as an example, Tokyo Institute for Nature Study ID 297025 with 9 sections, the total length is 21.000 m and some sections have 4km of length on the eBMS. 
I include a pdf with the real length per section being a few 100 m. 

Can someone check how the section length are calculated and if they are only based on Europe? @DavidRoy @JimBacon @Gary-van-Breda 

<img width="600" alt="2022-07-26_15h46_51" src="https://user-images.githubusercontent.com/25052478/181184327-470fca64-8831-44e3-9ab0-3700cc530c82.png">
<img width="549" alt="2022-07-26_15h47_15" src="https://user-images.githubusercontent.com/25052478/181184424-f507973a-54b2-45bd-ad77-47bc31571e83.png">

[Tokyo Institute for Nature Study_transect.pdf](https://github.com/BiologicalRecordsCentre/ABLE/files/9195943/Tokyo.Institute.for.Nature.Study_transect.pdf)

**Comment by DavidRoy** [comment]
@JimBacon can you look into this please

**Comment by JimBacon** [comment]
The section length calculation is as follows:
```
var sectionLen = Math.round(indiciaData.currentFeature.geometry.clone().transform(indiciaData.mapdiv.map.projection, 'EPSG:27700').getLength());
```
The geometry of the transect is being transformed to the British National Grid prior to the length calculation. This is giving very wrong results for Japan but it will also be giving somewhat wrong results for mainland Europe.

I can fix the code and I can correct all the section and transect lengths stored in the database, but does this have wider implications? For example, do you do any analysis based on occurrences per unit length of walk?

**Comment by DavidRoy** [comment]
@JimBacon thanks for tracking this down.  Please update the code and make the data correction.  There is analysis using the transect lengths but this will not cause a major problem for Europe analysis

**Comment by JimBacon** [comment]
Code fixed and deployed. Section lengths for the example Japanese transect updated. @CrisSevilleja, the Japanese coordinator can check and continue entering transects.

Further updates of section lengths to follow.

**Comment by CrisSevilleja** [comment]
Great! so efficient @JimBacon Thank you for the fast fixed. I have checked the Japanese transects and now the length makes more sense.

**Comment by JimBacon** [comment]
To update the lengths of transect sections I ran the following query:
```
UPDATE location_attribute_values lav
SETint_value = round(ST_Length(ST_Transform(l.boundary_geom, 4326)::geography, true)),
	updated_on = now(),
	updated_by_id = 2
FROM locations l, locations_websites lw
WHERE lav.location_id = l.id
	AND lw.location_id = l.id 
	AND lav.location_attribute_id = 220
	AND l.location_type_id = 778
	AND lw.website_id = 118
	AND lav.deleted = false
	AND l.deleted = false
	AND lw.deleted = false
	AND boundary_geom is not null
	AND lav.int_value != round(ST_Length(ST_Transform(boundary_geom, 4326)::geography, true))
```
Unexpectedly, a couple of dozen sections had multiple attribute values for section length. To remove the duplicates I ran the following update:
```
WITH dups AS(
	SELECT
		l.id, name, count(lav.id)
	FROM locations l
	JOIN locations_websites lw
		ON lw.location_id = l.id AND lw.deleted = false
	LEFT JOIN location_attribute_values lav
		ON lav.location_id = l.id
		AND lav.location_attribute_id = 220
		AND lav.deleted = false
	WHERE lw.website_id = 118
		AND l.deleted = false
		AND location_type_id = 778
		AND boundary_geom is not null
	GROUP BY l.id, name
	HAVING count(lav.id) > 1
	ORDER BY count(lav.id) desc
),
to_keep AS (
	SELECT DISTINCT ON(dups.id)
		lav.id 
	FROM location_attribute_values lav
	JOIN dups 
		ON dups.id = lav.location_id
		AND lav.location_attribute_id = 220
		AND  deleted = false
	ORDER BY dups.id, lav.id
),
to_delete AS (
	SELECT lav.id
	FROM location_attribute_values lav
	JOIN dups 
		ON dups.id = lav.location_id
		AND  lav.location_attribute_id = 220
		AND deleted = false
	LEFT JOIN to_keep
		ON to_keep.id = lav.id
	WHERE to_keep.id IS null
	ORDER BY dups.id, lav.id
)
UPDATE location_attribute_values lav
SET deleted = true, updated_on = now(), updated_by_id = 2
FROM to_delete
WHERE lav.id = to_delete.id
```
Then, to update the total transect lengths I ran the following query:
```
WITH transects_with_lengths as (
	SELECT
		l.id, name, 
		lav.int_value old_len
	FROM locations l
	JOIN locations_websites lw
		ON lw.location_id = l.id 
		AND lw.deleted = false
	LEFT JOIN location_attribute_values lav
		ON lav.location_id = l.id
		AND lav.location_attribute_id = 217
		AND lav.deleted = false
	WHERE lw.website_id = 118
		AND l.deleted = false
		AND location_type_id = 777
		AND lav.id is not null
	ORDER BY id
),
new_lengths AS (
	SELECT twl.id, twl.name, twl.old_len, sum(lav.int_value) new_len
	FROM transects_with_lengths twl
	JOIN locations l
		ON l.parent_id = twl.id 
		AND l.deleted = false
	LEFT JOIN location_attribute_values lav
		ON lav.location_id = l.id
		AND lav.location_attribute_id = 220
		AND lav.deleted = false
	WHERE l.deleted = false
		AND location_type_id = 778
		AND lav.int_value is not null
	GROUP BY twl.id, twl.name, twl.old_len
	ORDER BY twl.id
)
UPDATE location_attribute_values lav
SET int_value = nl.new_len, updated_on = now(), updated_by_id = 2
FROM new_lengths nl
WHERE lav.location_id = nl.id
	AND location_attribute_id = 217
	AND (nl.old_len - nl.new_len) != 0
```
What this has achieved is to update lengths where they had previously been incorrectly calculated. Generally the errors were only one or two metres in Western Europe and up to a few tens of metres in Eastern Europe. 

Whilst doing this it was observed that numerous sections have no length attribute set. These are probably from transects imported without length values. I'll raise this as a separate issue.

**Comment by CrisSevilleja** [comment]
thanks, @JimBacon for the update. Indeed the Japanese coordinator complained about the section length again but now after this update, I think the length of the sections is correct and more accurate.
