### ISSUE TITLE
Searching common names not working on eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#461]
Common names from many different languages are included on the eBMS system and possible to search on the app. However, for the website, it is still not possible.

Previously we have all the available common names shown on the website when searching but it was confusing for volunteers and we removed it. But now it is only possible to search species by scientific name or in English. 

Could it be possible to add the function of searching common names in different languages when including data on the website? I am wondering if it would be a possibility based on the scheme/language you set up on your account. So people that set up Lithuanian can only search for scientific, English and Lithuanian and not seeing the rest of the common names when searching. 

I am making this issue due to the Japanese coordinator cannot find the Japanese species in Japanese, they have different alphabet so it is even more confusing for volunteers. But all languages with common names are affected.
@DavidRoy @JimBacon @Gary-van-Breda

**Comment by JimBacon** [comment]
Hi @CrisSevilleja 

I think this actually works almost exactly as you suggest.
If you edit your account and change your language setting from English to another language then the list of species suggestions when you start typing are in Latin and your chosen language.

What is confusing is that the language selector on the top-right of the page does not reflect the user preference and does not affect the list of species.

For example, if I select Dutch in my account, the header appears as follows:
![image](https://user-images.githubusercontent.com/2545390/185153378-090aedba-d54e-4da2-b76e-a8ed76996c2d.png)

and I can select by Dutch common name as below:
![image](https://user-images.githubusercontent.com/2545390/185154329-a827a4aa-37ff-4d2a-bedf-50c12a782cc6.png)

It is less than perfect but it may help our friends in Japan.

**Comment by JimBacon** [comment]
Sorry, just spotted that the code will need updating to support Japanese common names.
Only the following languages are currently allowed for in `client_helpers/prebuilt_forms/ukbms_sectioned_transects_input_sample_2.php`

          // Map Drupal codes to 3 digit codes held in warehouses
          $langMap = [
            'cs' => 'ces', // Czech
            'de' => 'deu', // German
            'en' => 'eng',
            'es' => 'spa', // Spanish
            'hr' => 'hrv', // Croatian
            'hu' => 'hun', // Hungarian
            'nl' => 'nld', // Dutch
            'pl' => 'pol', // Polish
            'sv' => 'swe', // Swedish
          ];

**Comment by CrisSevilleja** [comment]
I was exactly checking and it is not working for other languages as well: 

- Bulgarian (butterfly examples - Азбучна опашатка, Синьопетниста опашатка, Невзрачна опашатка, Обикновено тигърче)
- Lithuanian
- Japanese 
- Danish
- Slovenian

The searching for common names is working for Dutch, Polish, German, Hungarian, Swedish and Czech. There are other languages that don't have common names (Italian, Spanish, Romanian).
I couldn't check for the Finish names because it is not included in the language list. I will create an issue for it. 

Thank for checking the code.

**Comment by CrisSevilleja** [comment]
Also, it is annoying when a certain language is selected in the user account and in the upper part appears the English language. Although the website translate the pages into that language. Do you think it could be possible to change that? I think I should ask Jonh.

**Comment by JimBacon** [comment]
@CrisSevilleja I've updated the code to support the missing languages.

**Comment by CrisSevilleja** [comment]
This issue is solved, it is necessary to select on account settings the preferred language to see its common names in the searching bar. For the moment this is done although we will need to work further on how to select the language on the website, at the moment two ways to select the languages with different preferences.

Thanks Jim for this
