### ISSUE TITLE
No endtime in sample downloads 15 min counts anymore

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#465]
@DavidRoy @kazlauskis @CrisSevilleja 
While working with the 15 minute count sample data, I noticed that in most (but not all) recent samples the endtime is missing, including my own data. I checked and this started in my counts from 2 June 2022 onwards (from that date onwards all my endtimes are missing). I might have missed something, but this comes as a surprise to me. It also means we cannot distinguish shorter than 15 minute counts from counts which did last 15 minutes anymore.
But of course I might also have misinterpreted something in the sample download file (@johnvanbreda ?).
Does this date ring any bells (e.g. was that soon after the release of a new (test?) version of the app)?
I notice that it gets more and more (in the beginning I was the only one with no endtime, the last week almost all counts have no endtime). Maybe still people using an old version of the app do generate the endtime?

**Comment by kazlauskis** [comment]
@chrisvanswaay Sorry, I've just noticed a bug in the app. We'll fix it asap.

@Vilius-Stankaitis We're uploading the end time with an incorrect warehouse ID. Can you please change it from `surveyEndTime` to whatever the correct warehouse attribute ID is?

**Comment by chrisvanswaay** [comment]
Thanks for the quick reaction @kazlauskis

**Comment by Vilius-Stankaitis** [comment]
Fixed

**Comment by chrisvanswaay** [comment]
@Vilius-Stankaitis Thanks. Does this mean all endtimes will become available also from 'old' data when I download again, or only from now on with new counts?

**Comment by Vilius-Stankaitis** [comment]
Unfortunately, only from now on.
