### ISSUE TITLE
Add an option to delete user account in the app

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#471]
Same as [irecord-butterflies-app#107](https://github.com/NERC-CEH/irecord-butterflies-app/issues/107)

- [x] app
- [x] website

**Comment by kazlauskis** [comment]
@andrewvanbreda, I know you've added your account delete code to FIT, iRecord and NPMS sites. Have you added it to any other sites like https://butterfly-monitoring.net?

**Comment by andrewvanbreda** [comment]
Hi @kazlauskis 

No I haven't, just the ones I knew had the apps with the delete functionality.

I don't work on these other projects, and they are not on my pantheon dashboard so I know very little about their day to day operation.

For websites without apps, an urgent update shouldn't really be necessary as I think most (if not all) the websites don't allow standard users to delete their accounts from the website anyway.
So it should only be ones with deletion on the app that would need this in the short term.

If you think a project needs it, I will have to request access to the project and some budget to work on the project, or I can write some simple instructions for Biren/Jim to do the update for all BRC's projects.

If it is a standard project that runs the easy_login module, the main deletion code might already be there if it has been updated to run the latest Indicia master code.
In that case only that small module I wrote to hide the Cancel account button on the website would need installing (if it is undesirable to allow Cancellation from the website).

Andy

**Comment by DavidRoy** [comment]
@andrewvanbreda we can cover your costs for working on the website updates to support app updates

**Comment by andrewvanbreda** [comment]
@kazlauskis @DavidRoy 
Do you have a full list of projects that might need updates? Technically I suppose it should probably be all BRC's Indicia websites. However, as mentioned above, ones which don't have an app and don't allow account cancellation on the website can probably be left for now as the deletion code will get put on those sites with general Indicia updates that admin do.

**Comment by kazlauskis** [comment]
@andrewvanbreda Right now, it is only the butterfly site that requires it: https://butterfly-monitoring.net (Pantheon)

These will also need it at some point but probably can wait for now.
https://esurveyor.ceh.ac.uk (Pantheon)
https://dunescapes.brc.ac.uk (Pantheon)
https://european-mammals.brc.ac.uk (Pantheon?)

**Comment by DavidRoy** [comment]
Yes, that's the list and all are on pantheon

**Comment by andrewvanbreda** [comment]
Hi @JimBacon @Gary-van-Breda 
I think Biren is away, so not sure who to contact regarding the administration of EBMS .
I need to need make sure the recent user anonymiser development is operational on the Eurean Butterfly Monitoring site for Karolis.

Do you know if this site is running the very latest Indicia Master code for indicia_features?

If that is the case, then we just need to enable the "Admin only account cancel" module which I can see is actually already present on the site but is in a disabled state.

If not, the site will need to be updated to the latest indicia_features code, which I could do but I don't currently have Pantheon Dashboard access for this project.

Cheers for any thoughts

**Comment by JimBacon** [comment]
Hi @andrewvanbreda 

No, the indicia_features module is not up to date. Easy_login reports being on version 5.0 and the current is 8.2

It would be good to know whether @Gary-van-Breda has made any local changes to it which could get overwritten by an update.

**Comment by andrewvanbreda** [comment]
@JimBacon 
Great thanks Jim, both of those are really useful thoughts.

**Comment by andrewvanbreda** [comment]
Hi @JimBacon 
Are you able to add the EBMS project to me in Pantheon?
What I can do is just update indicia_features/easy_login. I can use Git diff should allow me to detect if I were overwriting anything which is project specific.
Cheers

Failing that I can write some simple notes for someone else to do it.

Hi @kazlauskis I notice the "Cancel Account" button is enabled for users on the website?
Is that because you have already enabled to cancelling permission?
I just need to know if the site was always like this, or whether it was changed for the app and I need therefore need to install the "Admin only account cancel" module.

**Comment by andrewvanbreda** [comment]
@kazlauskis Are you able to add me to this project? then I can assign people on issues correctly.
Cheers

**Comment by andrewvanbreda** [comment]
Hi @JimBacon 
Thanks Jim, I can see the project in Pantheon now.

**Comment by JimBacon** [comment]
Hi @andrewvanbreda 

I've added you to the EBMS team.
Since we will both be working on it at the same time I suggest any commits you make are done in to a branch which is merged in to master when you are ready.
Any commits to master I'll assume can be deployed to live.

**Comment by kazlauskis** [comment]
>Is that because you have already enabled to cancelling permission?

@andrewvanbreda yes, we've enabled it for the app to function. It wasn't enabled before.

**Comment by andrewvanbreda** [comment]
Hi @JimBacon,

I have examined the situation with ebms indicia_features.

It doesn't look like the easy_login module has any customisations.
The other modules inside indicia_features have too many changes to tell, however those modules are not enabled on ebms so I can only assume there are no customisations either.

So I suggest I update the site to Master indicia_features.

However I will need to check this on dev/test as I think some new fields are going to be installed we won't want that I will need to disable.

I assume though to do that can't done from a branch?
So should I just push straight to dev site, then I can let you know when I am done checking.

You will need to hold off pushing anything to live until I say, but it shouldn't take long. If things go very pear-shaped I can always revert back to the way indicia_features previously was.

Andy

**Comment by JimBacon** [comment]
Hi @andrewvanbreda ,

Each branch gets its own copy of the files and database so it is perfect for what you are doing. See https://pantheon.io/docs/guides/multidev

I think you should try it this way to gain the experience and you'll probably never want to work any other way again!

**Comment by andrewvanbreda** [comment]
Hi @JimBacon 
Yes I agree this is very nice. I hadn't realise I would get a site with the branch, and it all seems nice and easy.

I have merged into Dev master.

There is only one thing I noticed, the easy_login module will say to the user something all the lines of "let us know about the area you record in" after they save their account, it never used to do that.
I am not suite sure if this is a bug in the latest easy login, or if that is a correct behaviour.
If it is problematic on the site, the Recording Location field can be deleted, this is disabled anyway, and that will remove the message.

This "Admin only account cancel" module also needs enabling. I dunno if you want to do that next time live is in maintenance mode?

**Comment by kazlauskis** [comment]
The app-side is done now. @andrewvanbreda please close the ticket once your update is live.

**Comment by andrewvanbreda** [comment]
@kazlauskis 
Done now.
However should the other websites also be updated before closing this?
How soon does those other ones need doing by?

@Gary-van-Breda 
Note about Recording Location in above comment (copied below for convenience). 

"There is only one thing I noticed, the easy_login module will say to the user something all the lines of "let us know about the area you record in" after they save their account, it never used to do that.
I am not quite sure if this is a bug in the latest easy login, or if that is a correct behaviour.
If it is problematic on the site, the Recording Location field can be deleted, this is disabled anyway, and that will remove the message."

I have not removed this field as am not in charge of this site..

**Comment by kazlauskis** [comment]
@andrewvanbreda let's close this one and create new tasks in other repos. I am not sure about the other sites yet. The next one we'll need next month will be https://european-mammals.brc.ac.uk/ (Pantheon). I've created a task for it now.
