### ISSUE TITLE
ButterflyCount: Add Saint Helena as country option

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#474]
We now have Saint Helena in the species list and it is being used for a new BMS on the island.  Can you add this to this list of countries for the app setup

**Comment by Vilius-Stankaitis** [comment]
@DavidRoy Hi, maybe I have miss something, but I cant find Saint Helena in this report. 

https://butterfly-monitoring.net/api/v1/reports/projects/ebms/ebms_app_species_list.xml?taxon_list_id=251 

In this report species is assigned by country.
eg:( 
{
  ...
            "preferred_taxon": "Aglais io",
            "attributes": "AD=P | AL=P | AM=P | AT=P | BA=P | BE=P | BG=P | BY=P | CH=P | CY=A | CZ=P | DE=P | DK=P | EE=P | ES=P | ES: CA=A | Europe=P | FI=P | FR=P | GB=P | GR=P | HR=P | HU=P | IE=P | IS=I | IT=P | JP=P | LI=P | LT=P | LU=P | LV=P | MD=P | ME=P | MK=P | MT=I | NL=P | NO=P | PL=P | PT=P | PT: AZ=A | PT: MA=A | RO=P | RS=P | RU=P | SE=P | SI=P | SK=P | TR=P | TRA=P | UA=P",
            "language_iso": "eng"
   })

Without it guide page for Saint Helena will be empty

![Screenshot 2023-05-10 at 12.05.51.png](https://zube.io/files/biologicalrecordscentre/b123d9ce11b5b5008336146d14a76b50-screenshot-2023-05-10-at-12-05-51.png)

**Comment by DavidRoy** [comment]
Attribute (SH-SH) is now added and populated for the (short) St helena list.

**Comment by Vilius-Stankaitis** [comment]
Good morning, I have pulled the list, it is short haha. Just to validate is this correct?

![Screenshot 2023-05-11 at 10.54.19.png](https://zube.io/files/biologicalrecordscentre/e64aebce50f1112b81cda92a7afad867-screenshot-2023-05-11-at-10-54-19.png)

**Comment by DavidRoy** [comment]
yes :-)

**Comment by DavidRoy** [comment]
Vanessa carduie should be in guide?

**Comment by Vilius-Stankaitis** [comment]
In the report only 3 species have this SH-SH attribute (Danaus plexippus, Lampides boeticus, Hypolimnas misippus)

**Comment by DavidRoy** [comment]
I must have missed 1! Can you set SH-SH as ‘P’ for Vanessa cardui

**Comment by Vilius-Stankaitis** [comment]
Done

**Comment by kazlauskis** [comment]
At the moment, the country codes in the warehouse don't strictly follow ISO 3166 codes, but it would be useful to keep them close to it. Before we release the new app version with St Helena in it, I wonder how easy it is to correct the `SH-SH` to simply `SH`?

**Comment by DavidRoy** [comment]
I think it should be: SH-HL as the app does not cover Tristan or Ascension islands
https://en.wikipedia.org/wiki/ISO_3166-2:SH

**Comment by kazlauskis** [comment]
@DavidRoy Sounds good, but to keep it consistent with other country codes, can we use underscores `SH_HL`?

**Comment by DavidRoy** [comment]
Yes, no problem. We could do with a review of this as I think we also use : as a separator for the taxon attribute names?

**Comment by kazlauskis** [comment]
I agree, we should review the list of country codes in the warehouse. Now that multiple projects use these, it would be good to keep the codes consistent. Can we rename the `SH-SH` to `SH_HL` ourselves or should we ask Jim or someone to do it?

**Comment by DavidRoy** [comment]
Happy for you to edit as the app is the main (only?) use of the country codes

**Comment by kazlauskis** [comment]
This is done now. You were right that we already use colons for countries in the warehouse. We transform colons and spaces into underscores in the app, so let's keep St Helena consistent with other warehouse entries. I have renamed [this term](https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list_attribute/edit/197) from `SH-SH` to `SH: HL`.
