### ISSUE TITLE
Wrong string on Transifex

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#476]
@kazlauskis there is an issue with one string on transifex that apparently is wrong. Please could you check it? I don't know from where that sentence is coming, so I don't know how to edit it. 
Thank you
![302202832_465266975613683_3136544062755974583_n](https://user-images.githubusercontent.com/25052478/188255929-7c46349c-a33e-4d66-927a-e85d1e76ad6a.jpg)

**Comment by kazlauskis** [comment]
@CrisSevilleja this doesn't come from the app but is part of the website translations project.

**Comment by DavidRoy** [comment]
maybe @JimBacon to advise?

**Comment by JimBacon** [comment]
The string is the description of the History module, which is not enabled. I see no reason to translate it as it is part of the administration interface that only a few people see. It is not impossible that the exact same string is used for some other purpose but I doubt it. 

One might re-write this as "Keeps a record of the content that each user has read".

**Comment by CrisSevilleja** [comment]
@DavidRoy can you remove the string "Records which user has read which content." from the eBMS website on Transifex. 
It is confusing and does not need to be translated?

I don't have access to the strings on transifex to remove them. After completed this issue can be closed.

**Comment by DavidRoy** [comment]
That's done
