### ISSUE TITLE
Change underlying reports on All Sites and Country Sites pages

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/ABLE#48]
@DavidRoy : should we change the underlying report on the All Sites and Country Sites pages to match those on the UKBMS site?
Whilst there isn't a performance issue in this area at the moment, this may change as the coverage increases.
See [UKBMS Issue 108](https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/108)

**Comment by DavidRoy** [comment]
Yes please

**Comment by Gary-van-Breda** [comment]
Done on both Test and Live.
@DavidRoy : if you are happy, I'll close.

**Comment by DavidRoy** [comment]
Thanks.  happy to close
