### ISSUE TITLE
Common (vernacular) names for dragonflies

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#480]
During our 'recordersday' last Saturday we got the 'complaint' that for dragonflies in the 15min count it is not possible to enter a species by its Dutch vernacular name. I hope this can be made possible. Attached is a file with the vernacular names of dragonflies for quite a few languages, would be great if they could be included. The person to contact if questions arise is Roy van Grunsven (roy.vangrunsven@vlinderstichting.nl).
[CommonNames_RoyVanGrunsven.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/9696119/CommonNames_RoyVanGrunsven.xlsx)

**Comment by DavidRoy** [comment]
@JimBacon can you add this requirement to your 'to-do' list, thanks

**Comment by RoyvanGrunsven** [comment]
There are quite some people interested in using the app and 15min counts for dragonflies but common names would make it easier for many. I do not know if the file that Chris attached is usable for this, otherwise you van ask me or send me a dummy file to fill.

**Comment by JimBacon** [comment]
Thanks @RoyvanGrunsven. I think the file format will be fine. It may be a few weeks before I start on this. I'll be in touch if I have any questions.

**Comment by RoyvanGrunsven** [comment]
I was more thinking about synonyms in the scientific names and things like that, I can easily fix those. 
In a few weeks would be great. In winter this is not used a lot anyway but I want to promote the 15min counts coming spring before the season. Thanks @JimBacon

**Comment by JimBacon** [comment]
That would be helpful. I will need our lists to match by scientific name. I spotted one synonym by eye and one extra species in  the [current EBMS list](https://github.com/BiologicalRecordsCentre/ABLE/files/9704677/ebms-dragonflies.csv).

EBMS has _Stylurus flavipes_ instead of _Gomphus flavipes_ and the additional species is _Sympetrum nigrifemur_

Hi @kazlauskis, when is the next release of the EBMS app expected? It would be good to include dragonfly common names if possible.

**Comment by kazlauskis** [comment]
We haven't planned the next release yet but it looks like @DavidRoy has created [Autumn 2022 app priorities](https://github.com/BiologicalRecordsCentre/ABLE/milestone/15) milestone, so I assume that's something we'll do this calendar year.

**Comment by RoyvanGrunsven** [comment]
Great, those two are quite easily fixed. There are also two additional species, Onychogomphus cazuma, recently described from Spain and the Italian populations of Coenagrion mercuriale are split off as Coenagrion castellani
I'll try to get the file as complete as possible and update here.
[ebms-dragonflies.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/9707849/ebms-dragonflies.csv)

**Comment by CrisSevilleja** [comment]
Any news on this? @JimBacon Do you know if the common names have been included? thanks

**Comment by JimBacon** [comment]
Not done yet and not planned in the next few weeks.

**Comment by chrisvanswaay** [comment]
@JimBacon  Any developments here? It would be very very welcome before the start of the field season.

**Comment by JimBacon** [comment]
Not yet but I am meeting @DavidRoy tomorrow to discuss my priorities for the next few weeks.

**Comment by chrisvanswaay** [comment]
Thanks. Lets hope for the best.

**Comment by RoyvanGrunsven** [comment]
If I can help by adjusting the file with the names just let me know.

**Comment by DavidRoy** [comment]
@andrewvanbreda can you add this to your (long) list

**Comment by chrisvanswaay** [comment]
@andrewvanbreda Hope these Dutch dragonfly names can still be included. I also attach the bumblebee names (already emailed them to @DavidRoy last week)
[Bumblebees_sci_nl_names.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/11373239/Bumblebees_sci_nl_names.xlsx)

**Comment by andrewvanbreda** [comment]
Hi @chrisvanswaay
I just went to add those bumblebees manually, however I think they must have already been imported into the database (Warehouse).  I didn't check every row of the file, but a random selection had the Dutch present for every case.
I think though, these names need to be explicitly then added to the app after they were imported, so if you are not seeing them in app ,that is likely cause. 
I am not exactly sure how that process works as I haven't not worked on the app directly, but any delay on that might be because we are waiting for names in other languages to be imported first.
@DavidRoy might be able to confirm

@DavidRoy @JimBacon 
For the dragonfly import, I think we might have the same problem as we had for the Swedish moth import where any existing common names will be overwritten unless the names are directly imported as a database script, which would need Jim.

**Comment by DavidRoy** [comment]
@kazlauskis can you confirm that you include common names for other taxa in the app.  Do you need an update to the report you use to obtain names from Indicia?

**Comment by kazlauskis** [comment]
@DavidRoy At the moment, only the butterflies and moths have common names in the app, but we can add other groups.

@JimBacon We are using the `reports/projects/ebms/ebms_app_species_list.xml` report to fetch species common names, which returns English dragonfly names now. Should this also return other languages?

**Comment by DavidRoy** [comment]
@kazlauskis @JimBacon yes, please extend the report and app to include all common names available

**Comment by JimBacon** [comment]
The EBMS dragonfly list (taxon_list_id = 265) contains 134 latin names and 134 English names. When names in other languages are added to the list, the existing report will return them.

**Comment by Vilius-Stankaitis** [comment]
Hi all, any update on when common names for other languages will be added? 

Cheers

**Comment by JimBacon** [comment]
When do you need it? I can look at it this week if it is holding you up.

**Comment by Vilius-Stankaitis** [comment]
I will release a new app version for beta testing this Friday.

**Comment by JimBacon** [comment]
Having imported the spreadsheet of common names in to a temporary table in the database, the following query was executed  for each language listed in the file with the exception of English. English common names were already present in the database.

```sql
-- Obtain additional information required to insert names.
-- NB. 265 is the taxon_list_id for 'EBMS Dragonflies'
WITH dragonflies AS (
	SELECT ttl.preferred_taxa_taxon_list_id, ttl.taxon_meaning_id, ttl.external_key, ttl.preferred_taxon, d.*
	FROM temp_ebms_dragonfly_names d
	JOIN cache_taxa_taxon_lists ttl
		ON ttl.taxon = d.scientific
		AND ttl.taxon_list_id = 265
),
-- Create new taxon records returning new id.
-- NB. 107 is the taxon_group_id for 'insect - dragonfly (Odonata)' and 
--     7 is the language_id for German
new_taxa AS (
	INSERT INTO taxa
	(taxon, taxon_group_id, language_id, external_key, scientific,
		created_on, created_by_id, updated_on, updated_by_id)
	SELECT german, 107, 7, external_key, false, now(), 2, now(), 2
	FROM dragonflies 
	WHERE german IS NOT null
	RETURNING id as taxon_id, external_key
)
-- Create new taxa_taxon_list records.
INSERT INTO taxa_taxon_lists
(taxon_list_id, taxon_id, taxon_meaning_id, preferred,
	created_on, created_by_id, updated_on, updated_by_id)
SELECT 265, new_taxa.taxon_id, dragonflies.taxon_meaning_id, false, now(), 2, now(), 2
FROM new_taxa 
JOIN dragonflies 
	ON dragonflies.external_key = new_taxa.external_key
```	

Currently still waiting for scheduled tasks to process the changes and add them to the cache tables.

**Comment by JimBacon** [comment]
Now ready for you @Vilius-Stankaitis.

**Comment by Vilius-Stankaitis** [comment]
@JimBacon Thank you!

**Comment by RoyvanGrunsven** [comment]
Great, I just checked a few languages and it works.
Thanks
