### ISSUE TITLE
Common moth names on the EBMS website

### ISSUE THREAD

**Issue by JurrienVanDeijk** [BiologicalRecordsCentre/ABLE#482]
Could it be possible to also add the common names of moths to the website? These names are already available in the app. It is about the following page (https://butterfly-monitoring.net/enter-moth-trap-records?sample_id=20382666):

![image](https://user-images.githubusercontent.com/96239244/194878897-775b080e-24f6-4348-8da1-fb39bc858466.png)

**Comment by JimBacon** [comment]
Hi @JurrienVanDeijk 

I have changed a setting for "Species Names Filter" to "Allow common names or preferred latin names".
This should help.
![image](https://user-images.githubusercontent.com/2545390/195103759-1b1dd61a-e26c-4f70-9cda-978f424b142e.png)

**Comment by JurrienVanDeijk** [comment]
Is this a setting I could have changed myself?

**Comment by JimBacon** [comment]
Probably not.
You need edit permissions on https://butterfly-monitoring.net/node/146/edit

**Comment by JurrienVanDeijk** [comment]
Okay, but thanks for changing, now it works!
