### ISSUE TITLE
ButterflyCount: Painted Lady Survey

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#483]
First requirement is a mockup for:

idea is to add to the ‘15m Single Species Count’ – accessed by ‘long-pressing’ the (+) in the bottom centre of the home screen.  This survey then asks for a target species.  
If Painted Lady was selected, we would then add additional categories of information to provide.  
All information is mandatory versus and no default values.                                                                                                                                          
Information provided at the survey level, not individual occurrence

The page on the app first shows two options below the species name: Behaviour and Wing condition.  Each will open a new page or show the values already set.

Behaviour page
First data field =  Behaviour. 4 boxes: migration, nectaring, mating behaviour, egg-laying
If Migration selected, other fields are shown:
1.1	flight direction (to be indicated as N, NW, WNW, etc. by the observer). 
#could also potentially use the phone to provide this information if users point the phone in the direction of migration?
1.2	flight altitude above the ground, 0-0.5m; 0.5-1m; 1-2m, 2-5m, 5m+

If Nectaring is selected: a field to indicate which are the nectar sources that are being used.
If Mating behaviour is selected: include two options, territorial defence (specifying hill-topping, and other types of territorial defence, e.g. guarding a nectar source, a forest margin, etc.), and mating.
If Egg-laying selected, a list of hostplants is available to select: (thistles, mallow, desert nettle, others - ask for name). 
#we could enable a photo of the plant to be taken and then use the @Plantnet classifier to suggest an ID?

If Other selected – (e.g. mud-puddling, roosting, etc. – that is, behaviours that are very rarely recorded and probably don’t need a specific box, i.e. free text
 
Wing condition page
Second data field: Wing condition. 3 boxes: fresh, normal, worn. I can provide a picture exemplifying each condition (butterflies in the wild). It should be possible to tick more than one option -and indeed is quite usual that migrations combine butterflies of different origin/wing wear-.
#this could be a set of example pictures for the recorder to select, or to provide a number under each category?

**Comment by Vilius-Stankaitis** [comment]
@DavidRoy Hi, would be possible to get the final list for these options?
 -  "Egg-laying hostplants" (currently 3 options: thistles, mallow, desert nettle)
 -  "Mating behaviour" 
(territorial defence -> hill-topping,  guarding a nectar source, forest margin and other option mating)

I want to create the warehouse ids for these options. 

Also, would be possible to get images of wing condition and behaviour?

**Comment by DavidRoy** [comment]
@Vilius-Stankaitis I've asked my colleague for photos.  
For the attributes.

"Egg-laying hostplants". Three options (multi-select).
- thistles
- mallow
- desert nettle

"Mating behaviour". Three options (single-select)
- mating
- territorial defence: hill-topping
- territorial defence: guarding a nectar source

**Comment by canliro** [comment]
I sent several images of PLs (showing different wing wear, i.e. fresh, average, worn) and a selection of common hostplants to David Roy. He may select those that could work in the app.

I've also a couple of comments.

1) If Mating behaviour is selected: include two options, territorial defence (specifying hill-topping, and other types of territorial defence, e.g. guarding a nectar source, a forest margin, etc.), and mating.


I would distinguish instead "hill-topping" and; more generally, "other types of territorial defence". I would not refer only to "guarding a nectar source", which is much more rarely seen that e.g. a male sitting on the ground nearby a protruding object (such a high tree, etc.).

2) "Egg-laying hostplants". Three options (multi-select): thistles, mallow, desert nettle

In addition to these three categories of host plants, I would add a fourth category as "others", because PLs can indeed use many other types of host plants.


3) I miss the possibility of entering data on larvae/eggs, instead of adults. However, I think this can be done using the simple 15-min app, which gives the opportunity of recording immatures as well as adults. Right? But in such a case, the type of host plant needs also to be added.

**Comment by DavidRoy** [comment]
Thanks @canliro. Yes, you can select adult or other life stages for the timed count.
Please note that the 'attributes' are at the 'sample/survey' level and not for individual occurrences within the count.  This might cause difficulty because individual PLs may be using different foodplants for example - this is why the foodplants enable multiple options to be selected.  We need to decide for other categories, whether a single option is chosen for the 15m count or multiple options can be selected. 

@Vilius-Stankaitis we can finalise this survey now I think.  I will send you photos for the app - can you clarify which images you want to include.

"Mating behaviour". Three options (single-select)
mating
territorial defence: hill-topping
territorial defence: other

"Egg-laying hostplants". Four options (multi-select).
thistles
mallow
desert nettle
other

**Comment by Vilius-Stankaitis** [comment]
@DavidRoy So, when the "other" option is selected should an additional free text area appear?

I need images for the wing options ("Fresh, Normal, "worn") and "Behaviour" all options ('Migrating, mating etc.) 

Could you check if everything is okay? 
Here is demo link ->

https://butterflies.app.flumens.io/demo.html

**Comment by CrisSevilleja** [comment]
I did a trial and it is quite good @Vilius-Stankaitis I have just two points to mention:

- When selecting Vannesa cardui in the 15min single species count, bring you to the page to fill in the additional details. I would include an introductory text in the upper part "This is a specific survey for the migration of Painted Lady (V. cardui)" or something like to introduce this specific survey
- When selecting nectaring as behaviour, the field nectar source is free text and compulsory to fill, I would specify a bit more what is expected. The text says, "enter the nectar source here" are you expecting common English names of plants? scientific names? a picture? just a plant? It can vary a lot in a free text. Maybe that is the intention, just to have a thought on it. @canliro 

Thanks for going further with this.
