### ISSUE TITLE
Problems reported with entering moth data

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#484]
Aniko Kovacs, who coordinates field work in Hungary and Romania, came up with these remarks:

Some further suggestions (also from earlier, therefore some of these
might be solved since then):

- there are no diurnal species on the list, howevere they cought some.
  CvS: I cannot reproduce this, when I try to enter Zygaena filipendulae this works.

- the website doesn't allow to export the data, only the sum numbers per
traps. It would be important to be able to export the species data and
the abundance data together, as we should provide this information to
the nature conservation authorities, who allowed us to make such
samplings at their sites.
CvS: the site needs revision indeed.

- You cannot edit the data (including the species names) later on, after
these were uploaded. It could be useful to make some corrections
sometimes in the light of increasing knowledge.
CvS: with 15 minute counts this is possible. Is this not possible for moths? 
If you can change the species names, then we apparently should make that function more clear.

- It would be useful, if people could add comments also per sampling
occasions, not only per traps (e.g. about the weather). Similarly, it
would be also good to upload pictures per sampling occasions about the
traps.
CvS: sounds like a useful addition.

**Comment by CrisSevilleja** [comment]
Hi @chrisvanswaay I think those issues are resolved, the only one is the possibility that editing the species is not possible on the website, there is already an issue for that https://github.com/BiologicalRecordsCentre/ABLE/issues/537

I think Helder and Joao were working on the downloads of moths, the diurnal species were corrected and comments are available per species plus per survey. 

As a tip, when creating an issue name someone with the @ or assign someone on the upper right part, if not, people can skip the issue without realising.
