### ISSUE TITLE
No number in Count field in moth occurrences download

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#487]
I'm not sure where this goes wrong (either in the app of @kazlauskis or website @JimBacon ), but when I download the moth data the field 'Count' is sometimes empty. For now I will proceed and interpret that as a 1 (why make a line for a species and enter no number?), but maybe we should make it impossible to enter no number (or put it to 1 as default).
Or do I miss a logical reason why there would be no Count when an observation is entered?

**Comment by johnvanbreda** [comment]
@JimBacon I did make some changes in the hope that it would fix this problem. For example, `task_cache_builder_attrs_sample` now handles deletion of its own work queue tasks and should only delete the tasks that have actually had their attributes JSON built. If this mechanism is working correctly, then the only other reason I can think of why the attrs are not being filled in is if the work queue tasks are not being queued in the first place.

**Comment by JimBacon** [comment]
Hi @chrisvanswaay, What you are seeing is the result of recording counts inside and outside traps. When there is an outside quantity but no inside quantity then an occurrence exists and you see a record in the download but it has a blank count.

**Comment by chrisvanswaay** [comment]
Thanks @JimBacon , that makes sense.

**Comment by chrisvanswaay** [comment]
(it would just be one field extra in the download)

**Comment by DavidRoy** [comment]
Agreed. Another one for your list @JimBacon

**Comment by JimBacon** [comment]
That is done.
Please try it out @chrisvanswaay and close the issue if you are happy.

**Comment by chrisvanswaay** [comment]
Thanks @JimBacon , looks perfect.
