### ISSUE TITLE
Entry Walk page: filter transects for coordinators

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#488]
At the moment, the coordinator role can select from all the eBMS transects when entering data on the Entry Walk Page
https://butterfly-monitoring.net/walk-data-entry?location_type_id=777&date=25/10/2022

You can see below I masqueraded as the Spanish coordinator and he can select any transect from eBMS, being annoying when there are several hundred transects to select. 
![image](https://user-images.githubusercontent.com/25052478/197781713-4c95c76b-eba9-42e7-b1c7-d5f49d4b1b72.png)

Please filter the transects by the scheme, so the coordinator only sees his/her scheme transects: the Spanish coordinator selects only from Spanish transects. Thank you. That is the case for the Annual report for example https://butterfly-monitoring.net/annual-report. Can @johnvanbreda help with this?

**Comment by Gary-van-Breda** [comment]
@CrisSevilleja : following the changes made for the region co-ordinator, I think this is no longer a problem. I've masqueraded in as the Spanish Scheme co-ordinator, and it looks like they can only pick from Spanish transects.

Can you check, and close this issue if you are happy?

**Comment by CrisSevilleja** [comment]
Indeed now the filter is working well showing only the transect assigned, for normal user and for scheme coordinators. 
Thank you, this issue can be closed.
