### ISSUE TITLE
Transect allocation page errors

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#49]
On: http://live-butterfly-monitoring.pantheonsite.io/transects-allocation

Error reported....

![error](https://user-images.githubusercontent.com/2699478/57065186-97559600-6cc0-11e9-9430-1895c10423ba.png)

**Comment by Gary-van-Breda** [comment]
Re-saved form, setting manager permission.
Error not appearing to me any more

**Comment by DavidRoy** [comment]
Thanks
