### ISSUE TITLE
Improve Scheme sites table

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#490]
For a better track of the coordinators, please add to the table of scheme sites: site code and site coordinates. 
https://butterfly-monitoring.net/scheme-sites

This is the current situation:
![image](https://user-images.githubusercontent.com/25052478/198874958-0fcb1c00-53f0-4af4-910c-979371bbe9b3.png)

**Comment by Gary-van-Breda** [comment]
@BirenRathod : As I don't yet have access to the new servers, could you arrange for the deployment of the latest version of reports/projects/ebms/ebms_branch_sites.xml from the indicia-reports repository? Thanks

**Comment by BirenRathod** [comment]
@Gary-van-Breda That ebms reports folder now has been updated.

**Comment by Gary-van-Breda** [comment]
@CrisSevilleja : this is now deployed, and I have checked. Looks OK to me, so if you are happy we can close this?

**Comment by CrisSevilleja** [comment]
thank you, the table looks good.
