### ISSUE TITLE
Scheme Sites - export shp error message

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/ABLE#492]
Hi,

I am having the here below error message when trying to export shapefile from here
https://warehouse1.indicia.org.uk/geoserver/wfs?request=GetFeature&service=wfs&version=1.0.0&outputformat=SHAPE-ZIP&srsName=EPSG:4326&typename=indicia:section_gis_download_view&format_options=filename:BranchSections-777.zip&cql_filter=website_id=%27118%27%20AND%20location_type_id=%27777%27%20AND%20location_attribute_id=%27233%27%20AND%20attr_value%20LIKE%20%27%25%7C216093%7C%25%27 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ServiceExceptionReport version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wfs/1.0.0/OGC-exception.xsd">
<ServiceException>
java.lang.RuntimeException: java.io.IOException java.io.IOExceptionorg.postgresql.util.PSQLException: ERROR: transform: couldn't project point (1.55533e+07 4.25079e+06 0): latitude or longitude exceeded limits (-14) ERROR: transform: couldn't project point (1.55533e+07 4.25079e+06 0): latitude or longitude exceeded limits (-14)
</ServiceException>
</ServiceExceptionReport>

**Comment by JimBacon** [comment]
The decoded url is 
```
https://warehouse1.indicia.org.uk/geoserver/wfs?
  request=GetFeature&
  service=wfs&
  version=1.0.0&
  outputformat=SHAPE-ZIP&
  srsName=EPSG:4326&
  typename=indicia:section_gis_download_view&
  format_options=filename:BranchSections-777.zip&
  cql_filter=website_id='118' AND location_type_id='777' AND location_attribute_id='233' AND attr_value LIKE '%|216093|%'
```
GeoServer is obtaining the data from the `section_gis_download_view` in the `ukbms` schema.

The definition of this view is 
```
CREATE OR REPLACE VIEW ukbms.section_gis_download_view
 AS
 SELECT section.id AS section_id,
    (COALESCE(l.code, l.name)::text || '.'::text) || "substring"(section.code::text, 2) AS section_code,
    section.code AS section_number,
    section.centroid_sref AS grid_ref,
    l.id AS site_id,
    l.code AS site_code,
    l.name AS site_name,
    lw.website_id,
    l.location_type_id,
    lav.location_attribute_id,
    ('|'::text || string_agg(lav.int_value::text, '|'::text)) || '|'::text AS attr_value,
    section.boundary_geom AS geom,
    round(st_length(st_transform(section.boundary_geom, 27700))) AS section_length
   FROM locations_websites lw
     JOIN locations l ON l.id = lw.location_id AND l.deleted = false
     JOIN locations section ON section.parent_id = l.id AND section.deleted = false
     LEFT JOIN location_attribute_values lav ON lav.location_id = l.id
  WHERE lw.deleted = false AND geometrytype(section.boundary_geom) = 'LINESTRING'::text
  GROUP BY section.id, ((COALESCE(l.code, l.name)::text || '.'::text) || "substring"(section.code::text, 2)), section.code, section.centroid_sref, l.id, l.code, l.name, lw.website_id, l.location_type_id, lav.location_attribute_id, section.boundary_geom, (round(st_length(st_transform(section.boundary_geom, 27700))))
  ORDER BY l.name;
```

It contains a transformation to the spatial reference system, 27700, which is a UK-centred system. 
When it tries to operate on locations far from the UK, e.g. location id 297027 in Japan, an error arises.

This is similar to https://github.com/BiologicalRecordsCentre/ABLE/issues/460

**Comment by chrisvanswaay** [comment]
@JimBacon  Wouldn't it be more logical to use a global projection, e.g. epsg 4326 (WGS84) in the database. It can always be easily transfered to a local system (as epsg 27700) for national use.

**Comment by johnvanbreda** [comment]
@chrisvanswaay we chose Web Mercator as the internal projection since most mapping will be done using that projection, therefore it reduces the processing load on the server as reprojection takes quite a bit of CPU effort.

**Comment by chrisvanswaay** [comment]
Web mercator is EPSG:3857 (and very similar to 4326), but Jim said it was epsg 27700. That confused me.

**Comment by JimBacon** [comment]
Yes, the geometry is stored using a global system in the database. It is being transformed to a UK-centred system in order to do a length calculation. This is because EBMS took advantage of work already done for UKBMS. While EBMS was constrained to Europe it was reasonably accurate but this is no longer the case. Having diagnosed the issue my next task is to come up with a resolution.

**Comment by JimBacon** [comment]
My planned solution is to replace
` round(st_length(st_transform(section.boundary_geom, 27700))) AS section_length`
with
` round(st_length(st_transform(section.boundary_geom, 4326)::geography, true)) AS section_length`

A comparison for UK transects showed the results to be the same as before, plus or minus a metre, and the method will work globally.

**Comment by JimBacon** [comment]
@johnvanbreda I have updated the view directly on warehouse1. Is there a repository where I should be committing this?
@xaviermestdagh would you like to test the export now works as expected?

**Comment by johnvanbreda** [comment]
@JimBacon I'm not aware of a repository for this view. Maybe https://github.com/Indicia-Team/support_files is a good place?

**Comment by xaviermestdagh** [comment]
@JimBacon 
Exporting a .shp works, thansk. There is at least one missing site (newly created) "Moulin de Bigonville 2022". Perhaps there is something wrong with the site code ("Luxembourg" vs "Luxemburg").  
![image](https://user-images.githubusercontent.com/24294138/205910080-9c12c1eb-cb34-47b6-b61c-a8ebde5dcedc.png)

Related or not with theis issue, I am not able to see the section on the maps in the editing view 
![image](https://user-images.githubusercontent.com/24294138/205910484-4a8fdb94-d689-49f9-8bda-4261fce8f70a.png)

And I am not able as well to delete transects (for example "Test_4_FW", one of the many sites people created associated to Luxembourg...)

**Comment by JimBacon** [comment]
I am closing this issue as complete.

@xaviermestdagh , the problem with Moulin de Bigonville 2022 is a separate issue. The sections appear not to have been drawn. Each section has the same centroid and none of them have a path stored in the boundary_geom field of the database.
