### ISSUE TITLE
URGENT: eBMS website not working!

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#495]
Please @DavidRoy @Gary-van-Breda @johnvanbreda @JimBacon the eBMS website is not working at the moment. 

I have an important workshop this weekend with volunteers showing the website and it is not working on all the pages showing or collecting data. 

Message: "An error occurred whilst connecting to Elasticsearch. 7: Failed to connect to warehouse1.indicia.org.uk port 443: No route to host" on the page https://butterfly-monitoring.net/my-walks

Message: "Failed to connect to warehouse1.indicia.org.uk port 443: No route to host"    https://butterfly-monitoring.net/annual-report

I placed you all here in case someone can fix it. Thank you!

**Comment by kazlauskis** [comment]
I believe there is some server maintenance until 9am 14/11/2022. This probably affects the ElasticSearch database 😕
