### ISSUE TITLE
Add Papilio demoleus to eBMS butterfly list and update app list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#496]
Species present in Cyprus and Turkey (Europe part)

**Comment by JimBacon** [comment]
Added as https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/570518

**Comment by DavidRoy** [comment]
@kazlauskis can you include this in the next app release

**Comment by DavidRoy** [comment]
@kazlauskis was this new butterfly included in the latest ButterflyCount app release?

**Comment by kazlauskis** [comment]
I've updated the app's species list today and it is ready for Beta testing. This will be bundled with the Japanese language update under v1.18.2 release. If nothing new comes up then we'll release this version later next week.
