### ISSUE TITLE
Issue: End time doesn't appear on main transect page

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#497]
### Describe the issue

 It is related to the End time of the transect, which doesn't show the time you select. Before the app showed you by default the selected time and you decided whether you agreed or wanted to change the time. Now it doesn't show you the End time selected on the main page for Transect registration. 

Although the app shows the End time when you Finish the transect and see it on the pending surveys. There you can see the End Time selected before although you were not able to see it on the main page for Transect registration. A bit confusing for users. 

A attach a video showing how it works at the moment the app for transects and selecting times

### Expected behavior

Show the selected End time on the main transect page when doing the transect. Even better to include a buttom to save the selected time (Start and End time), bring you back to the main transect page and see the selected times. 

### To Reproduce

1. Go to "Start an eBMS transect" pressing longer the purple + bottom
2. select the "Start time"
3. fix a time and go back
4. Select the "end time"
5. fix a time and go back

### App Version

v1.18.1

### Device

Iphone SE iOs 15.6

### When did this happen

today 18/11/2022

### Screenshots

I attach a video recording of my screen to show you how the End Time doesn't appear on the main transect page. 
You can see at the end of the video when going to Pending surveys, if you enter on the transect finished but not submitted the End time appears as selected but not before. 
https://user-images.githubusercontent.com/25052478/202705200-9f397416-cd47-4c05-83af-0f0f2b6b9cf5.mp4

**Comment by kazlauskis** [comment]
Thanks for the video 👏🏻 love it 😄 I can reproduce this issue and we'll fix it asap.
