### ISSUE TITLE
2-way exchange of records with other systems

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#5]
Explore option of 2-way exchange of records with iNaturalist and/or Observado, i.e. expose butterfly data to the iNat/iObs verification/review system(s)

**Comment by johnvanbreda** [comment]
@DavidRoy do we need to work on the assumption that Indicia will do all the work to push/pull the changes, or can we expect development at the iNaturalist/Observado end to implement a similar set of API requests to Indicia?

**Comment by DavidRoy** [comment]
@johnvanbreda we will need some engagement with the other systems.  At the stage of scoping, is one approach to develop a preferred option to then take to the other systems?

**Comment by DavidRoy** [comment]
Closing this one as too general
