### ISSUE TITLE
Rename page text to 'Scheme' from 'Branch'

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#50]
When viewing a site as a 'scheme co-ordinator' the user allocation section has labels as 'Branch' (a carry-over from the UKBMS).  This should be changed to 'Scheme site allocation' e.g. 

![err](https://user-images.githubusercontent.com/2699478/57065709-39c24900-6cc2-11e9-9bf6-078d9a9f9da0.png)

**Comment by Gary-van-Breda** [comment]
Done.

**Comment by DavidRoy** [comment]
Thanks
