### ISSUE TITLE
Issue: Japanese not available on app

### ISSUE THREAD

**Issue by hm77777** [BiologicalRecordsCentre/ABLE#502]
### Describe the issue

Japanese language not available in list of options. I re-downloaded newest version of app and joined beta programme, but it's still not there. 

### Expected behavior

To see Japanese or 日本語 in list

### To Reproduce

Settings > language > select Japanese

Or select Japanese from fresh install

### App Version

v1.18.1

### Device

Huawei P30

### When did this happen

Friday 2nd December 3:45 PM

### Additional context

Also tried on a Google phone and couldn't see Japanese

**Comment by kazlauskis** [comment]
The Japanese hasn't been released yet because it still has some translations missing. It is available to view on the app's demo page here though: https://butterflies.app.flumens.io/demo.html

Once the interface is fully translated, then we'll release it to the public.

**Comment by CrisSevilleja** [comment]
The Japanese language is translated 99% on transifex and it was before on the app. @kazlauskis when is the next release of the app?

**Comment by CrisSevilleja** [comment]
great thanks!

**Comment by kazlauskis** [comment]
The demo app is now updated. Can the translator check that the Japanese language looks alright there? 
https://butterflies.app.flumens.io/demo.html

**Comment by DavidRoy** [comment]
Yasuhiro confirms that Japanese translation in the app is complete and can be included in next release

**Comment by Vilius-Stankaitis** [comment]
The app should be in beta testing later today. If everything will be alright we will publish it live next week.
