### ISSUE TITLE
Download data from allocated transects

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#503]
At the moment, eBMS users can only download data from their data submitted through My data --> My downloads --> Downloads species occurrences from transects. 

Some transects have several users and they want to download the whole data of those transects. The best would be to be able to download the data of the allocated transects. Could it be possible @JimBacon ? @DavidRoy 

Maybe this is related to https://github.com/BiologicalRecordsCentre/ABLE/issues/501 on my Annual reports you can see all the data submitted from other users to your transects but not possible to download it.

**Comment by JimBacon** [comment]
This would be a download filtered by allocated transect rather than by user.
I am sure this would be possible to implement.
As you say, maybe review this with #501 and decide how you want all the downloads to work.

**Comment by CrisSevilleja** [comment]
indeed this is related to #501. I close this one
