### ISSUE TITLE
eBMS butterfly list - new taxon aggregate

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#504]
- [x] Add new name to species list
- [x] Make available in next release of ButterflyCount app

Hipparchia volgensis/semele/senthes - in genus http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/432108

**Comment by DavidRoy** [comment]
@JimBacon I've add in this species aggregate.  Can you check I have done this right?
http://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/570969

**Comment by CrisSevilleja** [comment]
Did you include Papilio demoleus in the eBMS list? Just to check, I saw the issue about it, https://github.com/BiologicalRecordsCentre/ABLE/issues/496  people in Cyprus asked me about it

**Comment by kazlauskis** [comment]
This is done in the app. It will come out live shortly.

**Comment by JimBacon** [comment]
Hi @DavidRoy 

How do you define species presence in a country for an aggregate?

The aggregate is only given a species presence in BG whereas the individual species have presence in many countries. 
If you only want the aggregate to have a presence in countries where all three are present then we should add AL too.

**Comment by DavidRoy** [comment]
@JimBacon - a good question but one without any implications at the moment.  The country lists are not used other than to filter the guide in the app (asaik).  Aggregates don't currenty have any info for the guide.  So as an interim, it is beneficial for aggregrates not to be assigned to countries and therefore not appear on the 'country' list.  When we have an interface to view/edit the county assignments or make more use of the country lists, we can revisit your question
