### ISSUE TITLE
Add a moth species to the list

### ISSUE THREAD

**Issue by Helder-Cardos** [BiologicalRecordsCentre/ABLE#516]
Hello,

We have noticed that _Coscinia chrysocephala_ (Hübner, 1804) is missing from the moth list. This is a fairly common species in the south of Iberian Peninsula. It was split some years ago from _Coscinia cribraria_ Linnaeus, 1758. This is a fairly urgent issue since the species will start to get caught in March/April.

@DavidRoy 

Thank you very much.

**Comment by Joao-Nunes-Moths** [comment]
I also suggest to add Mythimna sicula (Treitschke, 1835) without forms, i.e. without f. scirpi or f. sicula. In the way as the system is, our participants have to choose one of the given forms, which is pointless and can lead to some confusion.

Thank you.
João Nunes

**Comment by DavidRoy** [comment]
@Helder-Cardos @Joao-Nunes-Moths those two names have been added and should be available via the website immediately

@kazlauskis - can you pick up these extra names for moths when you next push an update to ButterflyCount

**Comment by Helder-Cardos** [comment]
Excellent! I´ve confirmed, the 2 species are already available on the website.

Thank you.

**Comment by DavidRoy** [comment]
Great. For those who use the app for entering data, they can use the app for most of the species and then add any additions via the website. I'll close this issue and raise a new one for the app update

**Comment by larspett** [comment]
How can you check if the common names are available or not in your language? I am getting German common names in Swedish but am quite sure that we have supplied Swedish moth names

**Comment by Joao-Nunes-Moths** [comment]
Hello,

Can we add the entries Noctua fimbriata/tirrenica and Caradrina flavirena/noctivaga to the moth species list? Those are two pairs of species that can only be separated through dissection. It might be useful in the future to have them instead of "only" Noctua sp. or Caradrina sp.

@DavidRoy 

Thank you
