### ISSUE TITLE
Add French, Hungarian and Catalan languages to ButterflyCount

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#517]
@kazlauskis could it be possible to add the new translations in the ButterflyCount app? French, Hungarian, and Catalan languages are new and translated on transifex to be included in the app. Hungarian only to 80% but at least, the main parts have translation and can be reviewed by the translator. Also, if you include updates of other languages as well. I would appreciate it. 

Could you tell me when these languages are included? or the new app version will be done? We need these languages for the next butterfly season and be checked before that, then I can keep the translators/coordinators in the loop and check the translation soon. Thank you

**Comment by kazlauskis** [comment]
I'll update the demo app today and then we can push it to the app stores if everything is correct.

**Comment by CrisSevilleja** [comment]
thank you

**Comment by kazlauskis** [comment]
The new languages are now in the demo app: https://butterflies.app.flumens.io/demo.html

**Comment by CrisSevilleja** [comment]
thank you I saw French and Catalan are included and the translators are already checking. However, I am not able to see the Hungarian, did you included it? I saw the Hungarian option but the app doesn't change to Hungarian.

**Comment by kazlauskis** [comment]
My bad! Hungarian is fixed now 🙂

**Comment by CrisSevilleja** [comment]
Hi @kazlauskis translators already checked their languages on the demo and applied some corrections in Transifex. French, Hungarian and Catalan are ready to push to the live app. Please, load again the translations from Transifex as they did some changes. Thanks

**Comment by CrisSevilleja** [comment]
Hi @kazlauskis do you know when these new languages will be released to the live app? Coordinators are asking me and they would like to know a date. Thanks in advance

**Comment by kazlauskis** [comment]
Don't know yet, we're very busy these next few weeks but we'll do this with the next milestone work.

**Comment by CrisSevilleja** [comment]
Yes, sorry I can imagine there is a lot to do before spring. It is the reason the coordinators are pushing me to have these languages for next season. I would appreciate it if you can give this a bit of priority in the next milestone. Thank you Karolis.

**Comment by CrisSevilleja** [comment]
Hi @kazlauskis some time passed since the coordinators checked the language on the demo app. Could it be possible to include those languages on the app? butterfly season is starting in southern areas. Thank you
@DavidRoy

**Comment by kazlauskis** [comment]
I can push the latest translations to a live app tomorrow.

**Comment by CrisSevilleja** [comment]
thank you

**Comment by kazlauskis** [comment]
I've pushed all the latest translations and code to live. It should appear in the app stores within a few days.
