### ISSUE TITLE
Annual report page, should use 'Scheme' not 'Branch' for drop-down lists

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#52]
http://live-butterfly-monitoring.pantheonsite.io/annual-report?userID=branch

Drop-down lists use 'Branch' instead of 'Scheme'.  Text to be replaced in drop-down lists

![err](https://user-images.githubusercontent.com/2699478/57066466-29ab6900-6cc4-11e9-9871-eab253c9a9e8.png)

**Comment by Gary-van-Breda** [comment]
Done

**Comment by DavidRoy** [comment]
Thanks
