### ISSUE TITLE
Repair slow loading of eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#521]
Several users claim the website loads slowly pages, especially the ones registering data: https://butterfly-monitoring.net/my-sites, https://butterfly-monitoring.net/mydata/downloads, https://butterfly-monitoring.net/mydata/samples, https://butterfly-monitoring.net/walk-data-entry, https://butterfly-monitoring.net/annual-report

Great problems entering the majority of the times in https://butterfly-monitoring.net/my-walks recurrent message mentioned: "The application did not respond in time." 

It can be frustrating when registering data and trying to search from previous data. Also for users without a good internet connection, it can be so time demanding to enter data on the website. 

Any possibility to improve the load time of the website? @JimBacon @johnvanbreda

**Comment by johnvanbreda** [comment]
A configuration change was made yesterday evening as a result of server performance issues and it seems much better at the moment. Please can you comment below if the performance drops again.

**Comment by DavidRoy** [comment]
@CrisSevilleja we are also part way through a migration to new infrastructure which should improve performance from ~April onwards.  Sorry for the frustrations!

**Comment by DavidRoy** [comment]
@CrisSevilleja - data entry through the app should perform better at the moment

**Comment by DavidRoy** [comment]
@CrisSevilleja can you check that performance is better now.  With more improvement coming in ~April

**Comment by CrisSevilleja** [comment]
Users using the Hungarian version of the eBMS website (reporting data per section) suffer a slow time loading pages for uploading data.  

Other users didn't report recently, so far I think the performance is better in the normal load of pages I normally do (I have a good internet connection normally) @DavidRoy
