### ISSUE TITLE
Transect Code missing from some records in scheme transect occurrences download.

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#523]
Coming from issue #489 where Xavier mentioned:

" Looking to the occurrences export from the Downloads part, there is the "Transect Code" which is not in the sample (visit) export of the same download part.
On my side, I would be in favour to also have "Transect Code" in the sample (visit) export as well because it was the only site ID available in the annual report (based on which I build all my data management), and have the "Section Code" in the occurrence export for the same reason.
As you can see, this Transect Code is missing for some records, although not missing for records within the same Transect Sample ID..."

**Comment by JimBacon** [comment]
Transect code missing for some records in occurrence download fixed in https://github.com/BiologicalRecordsCentre/ABLE/issues/493#issuecomment-1632568917
Columns added to sample download in https://github.com/BiologicalRecordsCentre/ABLE/issues/551
