### ISSUE TITLE
Change term ¨Guide¨ on transifex app resource

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#528]
@kazlauskis some translators reported that there is a term repeated on the ButterflyCount app confusing. We use the term Guide for general instructions of the app (blue circle) and for the photo guide (red circle). 

I suggest changing the Guide term for general instructions of the app (blue circle) into "Instructions" to avoid confusions and help in the translation. 

![image](https://user-images.githubusercontent.com/25052478/216994230-8864407c-51d6-4a84-aff0-5fecc387e2c6.png)

Could you change this on Transifex? thank you

**Comment by CrisSevilleja** [comment]
thanks

**Comment by kazlauskis** [comment]
I won't be able to change this just yet as we are working on other projects right now but if you could attach this ticket (and any other ticket for that matter) to the next milestone, then David can prioritise it and we'll do it with the next app update.
