### ISSUE TITLE
ButterflyCount - update to moth species list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#534]
To pick up recent additions and make them available in the app. See:
BiologicalRecordsCentre/ABLE#516

**Comment by Joao-Nunes-Moths** [comment]
I suggest to add Tephronia lhommaria (Cleu, 1928) to moth species list.
Thank you.

Best regards,
João Nunes

**Comment by DavidRoy** [comment]
Tephronia lhommaria is added to the list and available via the website data entry page

**Comment by Joao-Nunes-Moths** [comment]
I suggest to replace **Clepsis razowskii Gastón, Vives & Revilla, 2017** by **Clepsis eatoniana (Ragonot, 1881)** in the moth species list. It is also necessary to add **Afriberina salemae Skou & Sihvonen, 2019**.

Thank you.

Best regards,
João Nunes

**Comment by Vilius-Stankaitis** [comment]
Hi,

I have added Tephronia lhommaria (Cleu, 1928)  to the app. 

Is there any update on this new species (Clepsis eatoniana, Afriberina salemae Skou & Sihvonen, 2019)?

**Comment by DavidRoy** [comment]
@Joao-Nunes-Moths I've added a new taxon for Afriberina salemae

for C. razowkii, i've added a synonym as Clepsis eatoniana

@Vilius-Stankaitis do you include synonyms in the app list of names?  Can you check these new taxa appear in the taxon report used for the app?

**Comment by Joao-Nunes-Moths** [comment]
Hello, 

Can we add the entries Noctua fimbriata/tirrenica and Caradrina flavirena/noctivaga to the moth species list? Those are two pairs of species that can only be separated through dissection. It might be useful in the future to have them instead of "only" Noctua sp. or Caradrina sp.

Thank you.
