### ISSUE TITLE
Moth trap downloads issues

### ISSUE THREAD

**Issue by Joao-Nunes-Moths** [BiologicalRecordsCentre/ABLE#535]
Hello,

We have noticed that the excel files exported from Moth trap sampling can be significantly improved:

1) If possible, we would like to join both files, "moth trap ocurrences" and "moth trap samples", in just one. In this way, every record would have information about the method with which it was obtained. It would be also great to add some columns such as "family", "region", "municipality", "identifiedBy" and "verifiedBy", "moth trap geometry/type" and "light bulb type", and, most important, the "verification status" and "acceptance rank", i.e. Plausible, Accept as correct and so on. Species name should also include the author of the species (e.g. _Ochropleura plecta_ (Linnaeus, 1761) instead of _Ochropleura plecta_). 

This would facilitate the management and publication of our results.

2) This one is a priority from my perspective. It seems like that when a participant records the same species twice in the same sampling event, two entries are generated in the export file, instead of "concatenating" the records by summing the number of specimens.

Imagine a case where 10 specimens of species A are recorded together with 2 specimens of a possible species B. If I redetermine the identification of species B to be A, the exported table keeps 2 entries with exactily the same information (species, local, date, recorded), except of number of specimens.

3) There is a problem with the export of "moth trap samples" comments. Random entries are created with the information in comment. I think it should be a problem with delimiters.

Thank you very much,
João Nunes

**Comment by chrisvanswaay** [comment]
Hello @Joao-Nunes-Moths , I'm not sure I agree with you. We need two separate files (one for the samples, and one for the occurrences) to be able to identify samples without moths. This might be rare in your region (lucky you), but helas it happens regularly in my garden. It's very easy to combine them in programs as R (which I use) or MS Access. This also applies to the names, families, etc. You can make your own table and add that to the species by combining your table with the one from the download. 
Maybe one download can me made for recorders, but for me as coordinator it is vital to be able to distinguish samples without moths.

**Comment by Joao-Nunes-Moths** [comment]
Ok, I understand your point @chrisvanswaay and I agree with you. As a coordinator I though of these changes to simplify the use of the data, but you are right, some of the suggested columns are straight forward to add. However, my suggestions (2) and (3) remain valid.

Changing my suggestion a bit (1), I think it is still worth it to add the columns "identifiedBy", "verifiedBy", "verification status", "acceptance rank", "moth trap geometry/type" and "light bulb type". The last two should probably be added to the "moth trap samples" file.

**Comment by Joao-Nunes-Moths** [comment]
The point 3. of my first comment is still a problem for working with "moth trap samples" data. A problem with delimiters in the "comments" columns is producing a csv. download file with many problems.

**Comment by CrisSevilleja** [comment]
Thanks, Joao for making those points. 

**Number 3)** is happening to all the downloads with comments. Excel produces that problem not visualizing well the records per row and understanding the delimiters wrong. That is not an issue if you open the documents with R or Notepad, but the majority of the users use Excel. 

To sum up **number 1)** to add the following columns to the download file of 'moth trap samples':
-Moth_trap_type
- Light_bulb_type
Also, the weather data and time are not included in downloads #499 , I would include those columns too: Start_Time, End_Time, Wind_Direction, Wind_Speed, Moon_Phase, Cloud_Cover

 Columns to add to the file 'moth trap occurrences':
- AcceptanceRank
- IdentifyBy
- VerifiedBy
Also, we need a column to differentiate between day-flight moths, and micro-macro moths. Those categories, or at least the species list for each group are specified on eBMS, so it will help coordinators to clean and explore data to extract some of these groups, and not only by species name. What do you think about this last part @DavidRoy and @chrisvanswaay

**Comment by JimBacon** [comment]
Is the discussion about opening files in Excel in https://github.com/BiologicalRecordsCentre/ABLE/issues/489#issuecomment-1298400886 and https://github.com/BiologicalRecordsCentre/ABLE/issues/489#issuecomment-1303625022 helpful?

**Comment by Joao-Nunes-Moths** [comment]
@JimBacon here is an example of how the data of moth trap samples comes from eBMS. Even with the text import wizard is not possible to correct this, as the data in "comment" column is on different lines.

![imagem](https://github.com/BiologicalRecordsCentre/ABLE/assets/120634514/8492e3df-cd1c-485f-8291-f6b8ead1209e)

**Comment by JimBacon** [comment]
Well, this is how it looks for me!
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/d49e9902-a24a-424a-a669-91ec8a545eea)

**Comment by Joao-Nunes-Moths** [comment]
Well, please, tell me how you do it. I just exported the data and opened the .csv file.

**Comment by JimBacon** [comment]
As stated in https://github.com/BiologicalRecordsCentre/ABLE/issues/489#issuecomment-1303625022, either 

1. Start Excel without any file open, go to the Data tab and click From Text/CSV
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/21d97b22-c7b7-47cb-a592-67976475eccd)
or
1. Change the file extension from csv to txt before opening it in the normal way.

Then use the text import wizard with the settings shown in https://github.com/BiologicalRecordsCentre/ABLE/issues/489#issuecomment-1298400886

The vital settings are that the delimeter is a comma (,) and the text qualifier is a quotation mark (")

Let me make that bigger: 
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/a5317791-3dd9-4952-921e-0cee31337ba2)

Hope that works now!!!

**Comment by Joao-Nunes-Moths** [comment]
Hello,

Can anyone please give me some feedback on the need to at least add the "Determiner" or "identified by" column to the download file?
Start and End times would also be appreciated.

This information is already associated with each record. We just need you to put it available in the download files.

Thank you.

**Comment by DavidRoy** [comment]
@Joao-Nunes-Moths this issue has become a bit unwieldy.  I'll raise your reminder as a separate issue. If anything else is left from this original issue, please raise as new (single-item) issue(s)
