### ISSUE TITLE
Verification filters not being applied?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#536]
I have setup a verification filter
https://butterfly-monitoring.net/admin/filter-edit?filters_user_id=14109

And assigned role = verifier to the user.

However, the verification page does not filter to the region as expected

**Comment by JimBacon** [comment]
Looks okay to me.

![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/f869d3d9-55f9-448f-99b8-8526dc078793)

**Comment by CrisSevilleja** [comment]
the filter for this verifier is for Spain and Andorra, I think the filter is working good.

**Comment by DavidRoy** [comment]
Thanks!
