### ISSUE TITLE
Unable to edit moth species names from samples

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#537]
See: https://butterfly-monitoring.net/enter-moth-trap-records?sample_id=21451832
Masquarading as https://butterfly-monitoring.net/user/1198
@JimBacon - why no edit symbol by species name?

![moth](https://user-images.githubusercontent.com/2699478/225916447-dd1f4f57-cf74-41c1-999c-1f82b4af3ad7.png)

**Comment by larspett** [comment]
Where in the menus is this one to be found? I can access it at https://butterfly-monitoring.net/enter-moth-trap-records but not figure out how to select it directly? Are there other similar new ones that are a bit difficult to find in the dropdowns?

**Comment by DavidRoy** [comment]
Under My-Data -> My Moth Trap Samples menu
shows the calendar view of your samples.  Select one to see the data

**Comment by larspett** [comment]
Ah, the way it looked/looks at the UKBMS data entry, was looking for a direct menu link

**Comment by CrisSevilleja** [comment]
Still not able to edit species names on the website for moths. 

By the way, I changed the name of the heading menu for moths, [My moth site](https://butterfly-monitoring.net/my-moth-site) and [My moth site samples ](https://butterfly-monitoring.net/my-moth-site-samples) when creating the manual of use. My moth trap didn't make much sense when explaining the different steps to do.

**Comment by CrisSevilleja** [comment]
this issue is urgent @DavidRoy without the possibility to edit moth records, the errors will accumulate.

**Comment by CrisSevilleja** [comment]
@JimBacon do you think you can have a look at this? I don't think it is complicated to add the edition of moth names, please if you don't mind adding them, we will improve the moth recording data. Thank you

**Comment by JimBacon** [comment]
This issue should now be fixed. @CrisSevilleja, please check and close if okay.
