### ISSUE TITLE
Report for co-ordinators: showing summary of all moth trap samples

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#538]
When I try to view trapping events where no animals have been found,, nothing appears in the https://butterfly-monitoring.net/elastic/all-records . I am not sure if I could select from the table options to make them appear? Shouldn't these be possible to view in order to view both successful and unsuccessful trapping events? Am not sure if it is a full join vs inner join thing or if it is the intended behaviour.

**Comment by DavidRoy** [comment]
Have edited the requirement after email discussion.  
@andrewvanbreda - can you add in a new report and menu item.

- [ ] - new menu item under 'Scheme Admin' menu as 'Scheme moth trap samples'
- [ ] - new report under the new page, based on https://butterfly-monitoring.net/mydata/samples but only available for 'Scheme-co ordinator' role and based on their country.  Restricted to survey.id = 681

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy ,

I notice the My Samples page already allows for a country/region to be used as a filter, and it also claims that it should  display moth samples.

So actually is a separate page even needed?

From my point of view my thoughts are:

1. To default the country filter to the country for a scheme coordinator

2. Contact John. as I think the problem may be a similar a problem we have had on other projects, where Elastic Search does not show empty samples (a problem that a new page would also have if it were Elastic based)

What do you think? or am I barking up the wrong tree?

**Comment by DavidRoy** [comment]
Thanks @andrewvanbreda 
I agree, please can you discuss with John.
If the current page can be updated as you suggest, that is a good solution

Could the filter options from https://butterfly-monitoring.net/elastic/all-records be made available on this sample report page?

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
Do you agree with my conclusion above? and is the Elastic Search index able to be changed if I am right?

Page is this one
https://butterfly-monitoring.net/elastic/all-records

**Comment by larspett** [comment]
This looks good @andrewvanbreda if only the samples with no animals recorded could be viewed too. I was wondering if it could be toggled on/off using the grid column settings? I suspect that many will not want to see "empty" samples.

BTW is there an issue for translation in the https://butterfly-monitoring.net/elastic/all-records ? I keep getting moth common names in German although I believe we have supplied Swedish common names?

**Comment by andrewvanbreda** [comment]
Hi @larspett,

I will need to find out first whether those empty samples can be included, or whether we need another page.
However I have noted your toggle preference, and will see if David wants that implemented.

I am still relatively new to working on this particular project (although I have lots of experience of other similar projects).
This does mean I can't tell you exactly what has been entered on Github.
Perhaps it might be worth raising an issue with examples of species you know definitely have had Swedish supplied and aren't working, so someone can look at the problem.

**Comment by johnvanbreda** [comment]
@andrewvanbreda you can't include empty samples in the occurrences index, but there is a separate index for samples which has one document per sample, plus a small amount of statistics (number of records, species etc). So a separate page for samples is a possibility. This would be similar to My Data > My Samples.

**Comment by larspett** [comment]
Ok I see the problem. Our workaround in cases like this in Sweden is to have a dummy "empty observation" entry but that floods the database with empty information and is something we will phase out. The "My samples" view (if it is the one with the calendar @johnvanbreda ?)lacks the list view that is attractive with the one we are discussing here. As a scheme administrator, you would have to click your way through each date to view what has been happening in the scheme instead of simply scrolling.

**Comment by DavidRoy** [comment]
@larspett does the my samples page not give you what you need? You may need to switch it on but it has a column for number of species in the sample. Null = empty?
https://butterfly-monitoring.net/mydata/samples

**Comment by larspett** [comment]
Yes @DavidRoy it absolutely does, when adapted for scheme admins. 
I was mixing it up with the https://butterfly-monitoring.net/my-walks . Seeing my confusion (despite being very motivated to find the correct menu options and with some experience of the site) might be an indication that we might want a general revision of the menus (structure, design, workflows) to improve the GUI that users encounter.  I am thinking a general a priori systematic design revision from whatever first principles we would want. The workflows are evolving and features are being added added somewhat independently and I feel the time is right for a general review of the structure. I don't think that necessarily would take all that much time or be very difficult (since it is just links being moved around in a Drupal menu system).

**Comment by DavidRoy** [comment]
Very happy for someone to take this on if they have relevant experience and resources

**Comment by larspett** [comment]
@DavidRoy I might be able to look into this and could potentially involve some LU competence as well as the web designers responsible for our home page. I don't think that would be all that expensive and we (LU) could probably pay for a limited number of hours if we do the menu updating ourselves. Could you make an issue for this?

**Comment by DavidRoy** [comment]
Closing an old issue
