### ISSUE TITLE
Add the Czech Republic as a country for creating transects

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#539]
When creating a transect, the country has to be selected and the Czech Republic is not on the current list. 
Please add it asap, thank you

@andrewvanbreda? @JimBacon?

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
Problem fixed.
This happened because the Czech Republic is referred to Czechia in the Warehouse database, but it was referred to as Czech Republic in the page configuration, so the system didn't understand and ommitted it.

**Comment by CrisSevilleja** [comment]
so fast, thank you!

**Comment by andrewvanbreda** [comment]
No problem :)
