### ISSUE TITLE
Role for coordinators in SPRING project

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#541]
It would be good if the regional/national moth-coordinators in SPRING could overview what is being entered, check records and download all data if needed. Could someone give such a role to them (@JimBacon  maybe?). It would concern:

- Constanti Stefanescu for Spain
- Lars Pettersson and Harriet Arnberg for Sweden
- Imre Demeter and Aniko Kovacs for Hungary
- Martin Musche and Josef Settele for Germany

**Comment by DavidRoy** [comment]
@chrisvanswaay we can easily do this.  Can you ask each to confirm that they have an account setup on the system so we can grant the role

**Comment by chrisvanswaay** [comment]
OK, will do.

**Comment by CrisSevilleja** [comment]
I checked them:

- For Spain, Constanti doesn't have an account, better to put it to Andreu Ubach (currently he has the role of Spanish coordinator) user/1302

- Lars Pettersson and Harriet Arnberg for Sweden, both have an account, user/1281) and user/2240

- Imre Demeter and Aniko Kovacs for Hungary, he has an account but without any other role apart from normal user: user/3327

- Martin Musche and Josef Settele for Germany, he has an account and he is a verifier at the moment: user/1573

**Comment by chrisvanswaay** [comment]
@CrisSevilleja Thanks for helping out. But Constanti has entered his data in the system, he says under his general email address. So in theory he should have a usercode.

**Comment by CrisSevilleja** [comment]
I tried to include the verifier role for Harriet, Imre and Constanti on the eBMS website. I added the role verifier on their accounts and while doing the second step of ‘Add a permission filter’ under https://butterfly-monitoring.net/admin/filters-list, it didn't allow me to complete this task. 

I followed the steps as you told me @DavidRoy, I defined the country and select verifiers. However, when I wanted to save this filter a message appears "Please fill in who this filter is for":
![error adding verifier](https://user-images.githubusercontent.com/25052478/229153137-689296d0-3520-4641-a4d9-26a65791ec63.png)
The field " For Who?" was filled with the username and when selecting the field "Who", only allows "Only include my records". I don't think this field has to be selected...
![error adding verifier2](https://user-images.githubusercontent.com/25052478/229153613-dd2c5b56-b87a-48ec-b055-c7e5cfdd3b22.png)

Any idea what is going on? I tried also other filters like downloading and happened the same. Thanks

**Comment by DavidRoy** [comment]
you have to select an email from the drop-down list under 'For who?'.  I've done this for imre.
https://butterfly-monitoring.net/admin/filter-edit?filters_user_id=14203

You also need to assign the role as scheme co-ordinator

**Comment by DavidRoy** [comment]
Imre's account was in training mode but I've switches this off

**Comment by CrisSevilleja** [comment]
Thank you @DavidRoy I see now Imre, Constanti and Andreu as verifiers on the list. 
I tried to include Harriet, but it happened the same for me, I don´t see any drop-down list under ´For who?´. Sorry, but I am missing something or not understanding well this process. Please can you add Harriet as a verifier of Sweden? 

After adding her, this issue can be closed.
