### ISSUE TITLE
Unable to remove a 15 min count sample

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#546]
I am probably missing something obvious, but then it should be made more clear. I cannot find how to delete a 15 min sample.
Here I cannot delete a sample (only go to edit of view):
 
![image](https://user-images.githubusercontent.com/25886005/230787488-86f3e556-2292-4212-badc-aadb7c75cecc.png)

Then I edit, and get a page where I can make changes or delete records, but not the whole sample (which is a test from inside the house, nothing real):
 
![image](https://user-images.githubusercontent.com/25886005/230787524-e6db4773-d811-40c7-8d3a-8cee967ca0fb.png)

The whole sample is crap (fake). I'm lost.

What am I missing?

**Comment by chrisvanswaay** [comment]
btw I could remove it from the app (i.e. in the uploaded counts I could swipe it away), but that didn't delete it from the website.

**Comment by JimBacon** [comment]
Doesn't the red button saying 'Delete list of records' do what you want?

**Comment by chrisvanswaay** [comment]
I assumed it would delete the observations, but would leave the sample there. Gave it a try and noticed the sample was still in the list. However clicking on the edit-button showed it was not existing anymore. Maybe better change the text of the red button to: "Delete this count"?

**Comment by chrisvanswaay** [comment]
BTW: also after a few minutes it is still in my list of samples (though empty).

**Comment by chrisvanswaay** [comment]
An hour or so later and the sample is still in my list of samples, but without observations. That will generate a sample without observations (zero), and that is not as intended.

**Comment by JimBacon** [comment]
I am looking in to it.
It has definitely deleted the sample from the PostgreSQL database, which is good.
It can take up to 15 minutes for it to be deleted from the ElasticSearch index which supplies the data for the list of samples.
However, this has not happened which is a problem.

For the button label, we could do one better and actually add a Dutch translation for you!

**Comment by chrisvanswaay** [comment]
Thanks

**Comment by JimBacon** [comment]
A fix to the ElasticSearch index is in progress. It may take a day to complete.

About that button label - the same form is used for editing moth trap surveys (and possibly others) so text that applies equally to all survey types is desirable.

**Comment by chrisvanswaay** [comment]
thanks

**Comment by JimBacon** [comment]
The problem with deleted samples still being listed is fixed. 
The deletion process now runs every 5 minutes so they do not vanish immediately.

**Comment by chrisvanswaay** [comment]
Great.
