### ISSUE TITLE
ButterflyCount app gps switching off (and how to solve it)

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#547]
@kazlauskis 
If we (@JurrienVanDeijk and me) use the ButterflyCount app on Android "out of the box" the standard functionality is that it uses an 'optimalized' battery consumption. In practice this means that if there are not many butterflies around (as typical in NL in April, helas) the gps is switched off by the phone when I put the phone in my pocket, and only wakes up when I see a butterfly and want to enter it. However as the route in between has not been gps-ed, it shows a weird form jumping up and down, certainly when you see only one or even no butterflies (which helas is not so unregular here). It sometimes is even completely wrong.

If I want to record my precise route I have to dive deep into the settings (settings - apps - ButterflyCount app - battery and then change from optimalised to unlimited, see screenshot below - in Dutch, but I guess the message is clear). Now we use many more apps who use gps, and in all of them this issue does not happen. Would it be possible to do this for the ButterflyCount app too? 

![image](https://user-images.githubusercontent.com/25886005/231090866-44c249db-38ac-49a6-b5cf-eef5dc772c9a.png)

**Comment by kazlauskis** [comment]
@chrisvanswaay thanks, we'll check it up.

@Vilius-Stankaitis can you upgrade the geolocation plugin version to the latest one and check the GPS doesn't go to sleep after a few mins using the optimised battery? There is this plugin issue discussed [here](https://github.com/capacitor-community/background-geolocation/issues/89).

**Comment by Vilius-Stankaitis** [comment]
Hi @chrisvanswaay, is this still an issue with the 1.20.0 version? I have updated the packages and tested them with my old Android device and seem working fine. 

What device (version, model) are you using? I assume this is only an issue with old devices.

Nevertheless, there is a workaround for this problem, but I need to know if this is still an issue.

Cheers

**Comment by chrisvanswaay** [comment]
I have v 1.20 and still the same settings as above (so unlimited use). Actually it is not an old phone, but a Zenfone 8 with Android 13. And I know Jurriën had the same issues with a half year old Samsung S22. Since we changed the settings the problem is gone.

**Comment by kazlauskis** [comment]
@Vilius-Stankaitis is this one working OK now?

**Comment by Vilius-Stankaitis** [comment]
Hi @chrisvanswaay,

 Could you check if is it fixed in the v1.21.0?

**Comment by chrisvanswaay** [comment]
Tried it today, and it seems to work fine. I downgraded the battery to the default, and the path looked fine.



--

De Vlinderstichting is een organisatie zonder winstoogmerk. Voor een deel van ons werk zijn wij afhankelijk van de steun van donateurs. Wilt u bijdragen aan bescherming van vlinders en libellen? Neem dan een kijkje op onze website<https://www.vlinderstichting.nl/help-mee/donateur-worden> en help ons!


Chris van Swaay
De Vlinderstichting
Mennonietenweg 10
Postbus 506
6700 AM  Wageningen

[t] algemeen (+31) 0317 467346 / direct (+31) 0317 467342

[e] ***@***.******@***.***>
[i] www.vlinderstichting.nl<http://www.vlinderstichting.nl/>
[twitter] www.twitter.com/vlinderNL<http://www.twitter.com/vlinderNL>
[facebook] www.facebook.com/Vlinderstichting<http://www.facebook.com/Vlinderstichting>
[instagram] www.instagram.com/vlinderstichting<http://www.instagram.com/vlinderstichting>
[linkedin] www.linkedin.com/company/vlinderstichting<http://www.linkedin.com/company/vlinderstichting>

------------------------------
Aan de inhoud van dit e-mailbericht kunnen geen rechten worden ontleend. De informatie is uitsluitend bestemd voor de geadresseerde. De Vlinderstichting staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mailbericht noch voor tijdige aankomst daarvan.
-----------------------------
No rights may be claimed from the contents of this e-mail. The information is only intended for the addressee. Dutch Butterfly Conservation cannot be held responsible for the correctness and completeness of the contents of an e-mail, nor for its arrival on time.

________________________________
Van: Vilius Stankaitis ***@***.***>
Verzonden: zaterdag 20 mei 2023 07:15
Aan: BiologicalRecordsCentre/ABLE ***@***.***>
CC: Chris van Swaay ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [BiologicalRecordsCentre/ABLE] ButterflyCount app gps switching off (and how to solve it) (Issue #547)


Hi @chrisvanswaay<https://github.com/chrisvanswaay>,

Could you check if is it fixed in the v1.21.0?
