### ISSUE TITLE
Add French and Slovenian butterfly names to eBMS system

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#548]
I prepared the French and Slovenian common names of butterfly species to be included in the eBMS system. I have already checked the species list based on the eBMS butterfly list.
[eBMS_list_plus_Eng&French.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/11212178/eBMS_list_plus_Eng.French.xlsx)
[eBMS_list_plus_Eng&Slo.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/11212188/eBMS_list_plus_Eng.Slo.xlsx)

 @JimBacon I think you are dealing with the species names, please if you can add those lists I would appreciate it. French and Slovenian are starting butterfly season soon, so I would give them a bit of priority. Thank you in advance.

**Comment by JimBacon** [comment]
Hi @CrisSevilleja 
In the French list you have given two names for _Hipparchia hermione_, Petit Sylvandre and Sylvandre helvète.
Could you confirm this is correct? Thanks.

**Comment by JimBacon** [comment]
Slovenian names were imported last year.
See https://github.com/BiologicalRecordsCentre/ABLE/issues/416

**Comment by JimBacon** [comment]
All French names imported except Sylvandre helvète

**Comment by CrisSevilleja** [comment]
thank you @JimBacon for including them. 

Please @kazlauskis could it be possible to add French and Slovenian butterfly common names to the app? Also, if you make the new update of the app, include the new translations done on Transifex, like the Hungarian. Thank you in advance.

**Comment by kazlauskis** [comment]
This is done now and will come out with the next app release v1.20.0.
