### ISSUE TITLE
New report - count of records and samples by species

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#55]
Filtered by survey_id.  Needed for ABLE app for top species recorded leaderboard
@kazlauskis will need to access via an API end point.  From ElasticSearch

**Comment by johnvanbreda** [comment]
@DavidRoy warehouse1 or warehouse2?

**Comment by DavidRoy** [comment]
@johnvanbreda warehouse 1

**Comment by johnvanbreda** [comment]
Here's a demo in PHP. I'll send @kazlauskis the values he requires for the connection variables in an email:

```php
<?php

// connection variables TBD
$user = '';
$secret = '';
$restServiceUrl = '';
$endpoint = '';
$surveyId = 0;

$query = <<<JSON
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "metadata.survey.id": $surveyId
          }
        }
      ]
    }
  },
  "aggs": {
    "by_species": {
      "terms": {
        "field": "taxon.accepted_name.keyword",
        "size": 50,
        "order": {
          "_count": "desc"
        }
      },
      "aggs": {
        "sample_count": {
          "cardinality": {
            "field": "event.event_id"
          }
        }
      }
    }
  },
  "size": 0
}
JSON;

$url = "$restServiceUrl/$endpoint/_search";
$session = curl_init($url);
curl_setopt($session, CURLOPT_POST, 1);
curl_setopt($session, CURLOPT_POSTFIELDS, $query);
curl_setopt($session, CURLOPT_HTTPHEADER, [
  'Content-Type: application/json',
  "Authorization: USER:$user:SECRET:$secret",
]);
curl_setopt($session, CURLOPT_REFERER, $_SERVER['HTTP_HOST']);
curl_setopt($session, CURLOPT_SSL_VERIFYPEER, FALSE);
curl_setopt($session, CURLOPT_HEADER, FALSE);
curl_setopt($session, CURLOPT_RETURNTRANSFER, TRUE);
// Do the POST and then close the session.
$response = curl_exec($session);
$headers = curl_getinfo($session);
curl_close($session);
if (array_key_exists('charset', $headers)) {
  $headers['content_type'] .= '; ' . $headers['charset'];
}
header('Content-type: ' . $headers['content_type']);
echo $response;

```

**Comment by johnvanbreda** [comment]
One comment on the above - I'm not sure that the query part of the request which limits to a given survey ID is necessary since the Elasticsearch alias is already limited to the appropriate website ID.

**Comment by kazlauskis** [comment]
Thanks @johnvanbreda @DavidRoy, I am working on the reports now. The app (i.e. client-side) isn't a secure environment to protect any connection secrets so I wonder can we expose the credentials to allow the app direct access to this endpoint or should we wrap this up under another API layer?

**Comment by johnvanbreda** [comment]
@kazlauskis There is already a Drupal proxy for connecting to Elasticsearch which can be protected by Drupal auth. Is that the sort of thing you mean?

**Comment by kazlauskis** [comment]
Yes, where can I find more info about this? I'd like this for the eBMS site.

**Comment by johnvanbreda** [comment]
@kazlauskis probably the best bet is to point you at an example in the code:
https://github.com/Indicia-Team/media/blob/d9871e759ec38d4227afdf4eb88dc9db5184c2ab/js/indicia.datacomponents/jquery.idc.recordDetailsPane.js#L214

Although the endpoint (esproxy_rawsearch) takes a nid as a parameter, for the rawsearch method it is OK to just pass 0 or any number.

**Comment by kazlauskis** [comment]
Cheers, I've been playing with this this morning and I am puzzled with why I get different results when hitting thr ES directly and using the proxy. Any thoughts on why is that? Is there any ES logs I could access?

### Proxy
POST to `https://butterfly-monitoring.net/iform/esproxy/rawsearch/1` (or `searchbyparams`)
```
aggs[by_species][terms][field]: "taxon.accepted_name.keyword"
aggs[by_species][aggs][sample_count][cardinality][field]: "event.event_id"
size:0
```

I get
```json
{
    "took": 9,
    "timed_out": false,
    "_shards": {
        "total": 4,
        "successful": 4,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 27264,
        "max_score": 0.0,
        "hits": []
    },
    "aggregations": {
        "by_species": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": []
        }
    }
}
```

### Direct
POST to `https://warehouse1.indicia.org.uk/index.php/services/rest/es-able/_search`
```json
{

  "aggs": {
    "by_species": {
      "terms": {
        "field": "taxon.accepted_name.keyword"
      },
      "aggs": {
        "sample_count": {
          "cardinality": {
            "field": "event.event_id"
          }
        }
      }
    }
  },
  "size": 0
}
```

I get 
```json
{
    "took": 46,
    "timed_out": false,
    "_shards": {
        "total": 4,
        "successful": 4,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 27264,
        "max_score": 0.0,
        "hits": []
    },
    "aggregations": {
        "by_species": {
            "doc_count_error_upper_bound": 302,
            "sum_other_doc_count": 13159,
            "buckets": [
                {
                    "key": "Maniola jurtina",
                    "doc_count": 2906,
                    "sample_count": {
                        "value": 2904
                    }
                },
                {
                    "key": "Coenonympha pamphilus",
                    "doc_count": 2169,
                    "sample_count": {
                        "value": 2168
                    }
                },
              ...
```

**Comment by kazlauskis** [comment]
@johnvanbreda Another quesion, does iForm module have any way of specifying CORS headers? Calling the proxy from the app will require adding some headers to the response of the module.

**Comment by johnvanbreda** [comment]
I didn't implement CORS headers as so far we've only used this from the same domain. I'll have a look at what needs to be done.

I've added logging of the ES requests we send - can you try both your requests again and let me know the exact time you sent them please so I can dig them out of the logs.

**Comment by johnvanbreda** [comment]
@kazlauskis for the CORS changes, do you want me to just set Access-Control-Allow-Origin: * on the header, or would JSONP be the preferred way to go?

**Comment by kazlauskis** [comment]
@johnvanbreda I have just posted the two reqests (17:31). I think two headers would be necessary for CORS:
```
   Access-Control-Allow-Origin: *
   Access-Control-Allow-Methods: GET, POST, OPTIONS
```

**Comment by johnvanbreda** [comment]
There are 2 differences between the requests you sent at 17:31. First, the proxy is adding a filter on the metadata.trial field automaticallly (to exclude training records). I assume that's OK. The second difference though is that in one of the requests the field names are wrapped in escaped quotes. E.g.
```
{
  "field":" \\"taxon.accepted_name.keyword\\""
}
```
Are the extra quotes being added at your end? Looking at the example you gave I think so.

**Comment by kazlauskis** [comment]
I have removed the quotes and sent another request at 18:31 but the result is the same. Yes, I don't think the trial flag should make a difference here.

**Comment by kazlauskis** [comment]
@johnvanbreda I got his working - I was using request params instead of the body to send the query. Could I somehow add the CORS response headers to the website?

**Comment by kazlauskis** [comment]
@johnvanbreda this works now, I am not sure what has changed but I can close the ticket.

**Comment by johnvanbreda** [comment]
@kazlauskis Does that mean you don't need CORS headers specifically added? I was looking into this today, but found that you need to enable CORS globally on the Drupal site according to the instructions at https://www.drupal.org/node/2715637. I found it slightly disconcerting as I'd rather just enable it for the Elasticsearch proxy.

**Comment by kazlauskis** [comment]
I have enabled these CORS settings for the site some time ago, this was required for the Indicia API module to work. I am not sure what has changed now, but I can now also make calls to the proxy as well. If you wanted to restrict the origins but still allow the app then you can change it to:
`allowedOrigins: ['http://localhost:8100', 'http://localhost:8000', 'http://ebms.herokuapp.com']`
