### ISSUE TITLE
Training records to be made non-training

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#553]
@andrewvanbreda 
can you run some sql to set training = false for the set of records defined for:

time period: 8th and 9th april 2023 
username = ahospers 
recorder name = Andre Hospers 

let me know if you need the email address

**Comment by andrewvanbreda** [comment]
@DavidRoy 
My SQL access to Warehouse 1 is read only.
However, I have done read only SQL queries and set these samples to non-training using the Warehouse visual user interface.
21606260,21606259,21606258,21606256,21606255,21606254,21606253,21602603,21602602,21602601,
21602600,21602599,21602598,21602597,21602596,21602595,21602594,21602592,21602591,21602590,
21602589,21602588,21602587

Note these are all for the 9th, I couldn't find anything for 8th.

Note this issue has re-alerted me to an issue with the database; Setting the sample training flag to true, is not automaitcally triggering the occurrences as training.
There is an issue for that somewhere I will need to re-trackdown.

**Comment by DavidRoy** [comment]
thanks, @andrewvanbreda 
@chrisvanswaay can you ask Andre to confirm that his records have moved from training to non-training?  
Please close the issue when it's resolved

**Comment by chrisvanswaay** [comment]
Yes, he confirmed. I will close this issue. Thanks.
