### ISSUE TITLE
New report - count of occurrences and samples by species and user

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#56]
filtered by survey_id. Needed for ABLE app report so users can see which are their most recorded species
@kazlauskis will access via API end point.  Based on ElasticSearch

**Comment by johnvanbreda** [comment]
@kazlauskis Is this for website ID 118 on warehouse1? If so can you let me know once there are a few records posted so I can test what I am doing, thanks.

**Comment by johnvanbreda** [comment]
I think this is the same as #55, with the addition of a user filter? If so then the query for this can be applied to the metadata.created_by_id field using standard Elasticsearch search API syntax. The list of fields available is documented at https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/document-structure.md (apologies for the rubbish rendering of the table in GitHub!).

**Comment by kazlauskis** [comment]
This is done now.
