### ISSUE TITLE
eBMS moth survey samples

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/ABLE#560]
Very often I need to take some moths/images of moths away and study them further to identify to species, and this cannot be done on the day I make a moth survey on the app. So I leave it open so i can complete it later. If I then want to make a new sample I cannot until I have finished the previous one, but I may not get round to finishing the previous one for some time. It would be much better if one could hold the first sample as a draft and be allowed to start a new survey sample without having to finish the previous one first. This is how other surveys on the app seem to work and it would be good if this functionality also persisted for the moth trap surveys. Then I can complete them at a later date, finish them and then submit them.

**Comment by DavidRoy** [comment]
@kazlauskis @Vilius-Stankaitis is this much work to hold suveys in 'draft'?

**Comment by kazlauskis** [comment]
It would be easy to allow multiple drafts per survey. We currently do that in the iRecord App. If we do this for the moths survey then I suggest we allow multiple drafts for the other 3 surveys too to keep it consistent.

**Comment by DavidRoy** [comment]
This would be a helpful addition.  I agree to implementing this for all surveys.
