### ISSUE TITLE
Keep records on ButterflyCount despite changing devices or uninstalling the app

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#563]
Small detail and not urgent but good functionality for the app.
Some users are not satisfied when changing their phone or need to uninstall the app, they "loss" their records done on the app. Basically, you cannot see the records done before on another device if you change your phone or uninstall the app. It is a bit frustrating for the users because they cannot see their total numbers of records, species and so on). 

It is a really small detail and I am not sure if it is easy to apply it. Just asking if that could be possible to do if it is easy and feasible for the app. I think it should connect with the website to recover the records submitted, I am not talking about non-uploaded records, only the ones submitted to the website.

What do you think @DavidRoy @kazlauskis?

**Comment by kazlauskis** [comment]
I would very much like it too. 

Worth pointing out that showing ALL uploaded records using a virtual infinite scroll or a paginated list (with offline support) is more challenging than adding a simple stats chart or an aggregated user records table report.

**Comment by kazlauskis** [comment]
@johnvanbreda for this app requirement, I need to fetch users' past records into the ButterflyCount app. I can fetch samples and occurrences using ES and REST, but I need to be able to reconstruct records with attributes and full model structures: `sample`->`subsample(*)`->`occurrence(*)`. Is there a certain way you'd like me to query Indicia to get this?

For example, the warehouse sample [20583766](https://warehouse1.indicia.org.uk/index.php/sample/edit/20583766) has two subsamples, each in turn having an occurrence. What do you think is the best way for me to download that?

Ideally, there was an endpoint that would return the full model with its structure. If REST or ES returned child model IDs, I could reconstruct the model by fetching top-level samples and traversing down each sub-model. At the moment, I can do that by running this below but this is probably not as efficient as fetching child models by IDs:

*  POST `https://warehouse1.indicia.org.uk/index.php/services/rest/es-samples/_search`
```
{
    "query": {
        "bool": {
            "must": [
                {
                    "match": {
                        "event.parent_event_id": 20583766
                    }
                }
            ]
        }
    }
}
```

I've tried both:
* GET `https://warehouse1.indicia.org.uk/index.php/services/rest/samples/20583766?verbose=1`
*  POST `https://warehouse1.indicia.org.uk/index.php/services/rest/es-samples/_search`
```
{
    "query": {
        "bool": {
            "must": [
                {
                    "match": {
                        "id": 20583766
                    }
                }
            ]
        }
    }
}
```

**Comment by kazlauskis** [comment]
@johnvanbreda, are you OK if I fetch complete records by searching the ES index using parent ids? Or is there anything more efficient?

```
{
    "query": {
        "bool": {
            "must": [
                {
                    "match": {
                        "event.parent_event_id": 20583766
                    }
                }
            ]
        }
    }
}
```

**Comment by johnvanbreda** [comment]
@kazlauskis in ES, all fields are first-class citizens in terms of being filterable, so this query is going to be about as efficient as anything else. If you only need a few fields from the response you can use `?filter_path=...` in the request URL to limit to those fields, e.g. if you just wanted the occurrence ID you can do `filter_path=hits.hits._source.id` (see https://www.elastic.co/guide/en/elasticsearch/reference/8.8/common-options.html#common-options-response-filtering)
