### ISSUE TITLE
Include Slovak butterfly names

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#564]
Hello, we go further with Slovakia and I got the species list of butterflies in Slovak. I prepared the list together with the eBMS list and check for the names, so it should be possible to include them directly.  
[eBMS_list_plus_Eng&Slovak.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/11450772/eBMS_list_plus_Eng.Slovak.xlsx)
I don't include the csv due to it doesn't read the special slovak characters properly.

Please add Slovak names to eBMS system, I think @JimBacon is dealing with vernacular names. thanks for this.

@DavidRoy

**Comment by JimBacon** [comment]
The following file was imported to a temporary table in the warehouse.
[Slovak butterfly names.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/11479084/Slovak.butterfly.names.csv)

The following query added the new names.
```sql
-- Create new taxon records returning new id.
-- NB. 104 is the taxon_group_id for 'insect - butterfly' and 
--     24 is the language_id for Slovak
WITH new_taxa AS (
	INSERT INTO taxa
	(taxon, taxon_group_id, language_id, external_key, scientific,
		created_on, created_by_id, updated_on, updated_by_id)
	SELECT slovak, 104, 24, external_key, false, now(), 2, now(), 2
	FROM temp_slovak_butterfly_names 
	RETURNING id as taxon_id, external_key
)
-- Create new taxa_taxon_list records.
-- NB. 251 is the taxon_list_id for 'EBMS Butterflies'
INSERT INTO taxa_taxon_lists
(taxon_list_id, taxon_id, taxon_meaning_id, preferred,
	created_on, created_by_id, updated_on, updated_by_id)
SELECT 251, new_taxa.taxon_id, slovak.taxon_meaning_id, false, now(), 2, now(), 2
FROM new_taxa 
JOIN temp_slovak_butterfly_names slovak 
	ON slovak.external_key = new_taxa.external_key
```

Currently waiting for scheduled tasks to complete a backlog of work and add the new taxa to the cache tables.

**Comment by JimBacon** [comment]
Slovak butterfly names now ready for inclusion in the next app release, @kazlauskis. Close when done.
