### ISSUE TITLE
Move Painted Lady migration page under eBMS mobile application

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#565]
Hi @DavidRoy I saw the promotion for the Painted Lady new survey, I think is great and useful. 
I think it would be good to include the Painted Lady page https://butterfly-monitoring.net/painted-lady-migration as a subpage under the eBMS mobile application page https://butterfly-monitoring.net/ebms-app to be accessible and clear for everyone. 

I am not sure how to do that, for that I create this issue. 

Also, I am considering creating more subpages under eBMS page including the different surveys of the app and their explanations. So basically, eBMS app page would contain
- subpage transects
- subpage 15min counts
- subpage moth traps
- subpage Painted Lady migration
What do you think? 
At the moment eBMS app is getting long explaining the surveys and I think not practical with a long text

**Comment by DavidRoy** [comment]
@CrisSevilleja the painted lady page is moved.  I'm happy with your suggested change to the app pages.  Can you do this yourself?

**Comment by CrisSevilleja** [comment]
thanks @DavidRoy I already created those pages and included the corresponding text.
