### ISSUE TITLE
Improve app map view to show all of own records from the past

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#566]
For users who want to see their past records, we could update the map report to show all of your records. At the moment, the map only shows what you currently have saved on the device, but we could do it similarly to the iRecord App, where we show all of your past records aggregated to squares at the top zoom level and then individual records when zoomed in.

![IMG_4326](https://github.com/BiologicalRecordsCentre/ABLE/assets/7383162/a468022c-2822-438e-9608-0dc3c8c77af8)
![IMG_4327](https://github.com/BiologicalRecordsCentre/ABLE/assets/7383162/9c21feb7-28b0-4f82-bbc7-abb3310bb507)
![IMG_4328](https://github.com/BiologicalRecordsCentre/ABLE/assets/7383162/c929e8a8-508f-4f1c-8a11-0c7f817042ba)

**Comment by chrisvanswaay** [comment]
I'm sure many would be very happy with this.

**Comment by DavidRoy** [comment]
Good idea. thanks
