### ISSUE TITLE
EBMS showing language drop-down module errors in logs

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/ABLE#572]
Hi @BirenRathod

Am noticing live EBMS is showing errors relaating to that Language Drop-Down module, how can we go about correcting that situation?

Thanks

Andy

**Comment by BirenRathod** [comment]
@andrewvanbreda Do you know the actual problem? is it a but or something else?

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 

![Screen Shot 2023-05-26 at 16 06 39](https://github.com/BiologicalRecordsCentre/ABLE/assets/2463614/e6aff9e4-21d8-451b-9a63-8a1358b011cb)


![Screen Shot 2023-05-26 at 16 07 28](https://github.com/BiologicalRecordsCentre/ABLE/assets/2463614/75d8e2e0-b6ad-479c-a99c-d354301113ac)

All the messages are complaining about that module, but actually I looked and it seems to be as up to date as the other sites.
Of course it could be something to do with the way EBMS is using that module.
If I go to the my records page it mentions, I don't get an error, so it might be something particular users are doing.
As I uninstalled this for testing (as we previously spoke about) then this wouldn't of been picked up.

**Comment by BirenRathod** [comment]
@andrewvanbreda this warning about undefined array key is due to some page, block or menu had not been translated. Due to that, the module struggled to get relevant links using that language code.

In ebms, lots of languages were added but not all blocks, pages & menus were created using each of that language codes. That is my understanding while I was doing the same for the fitcount website.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Ok thanks. I was just worried if use actually see bigger on screen. But if you think ok.
BTW I did notice one PHP notice I can fix myself, so just gonna put site in mainteance mode for 5 mins

**Comment by CrisSevilleja** [comment]
Hi @andrewvanbreda and @BirenRathod I have been adding the languages to eBMS website and indeed, not all pages have the translation included and I am still missing some languages to include. 

Could I know which drop-down languages are giving errors? I was not able to translate any of them. 
Thanks

**Comment by BirenRathod** [comment]
@CrisSevilleja do you know which particular language is troubling? give me just one example of it first and then I will investigate into it.

**Comment by CrisSevilleja** [comment]
I have been working on the translation of the eBMS website doing the connection with Transifex and it is not working properly especially for the Turkish language for example, also for Croatian and Czech for some jobs I sent to translate. 

I think there is a problem with the connection between Transifex and eBMS website. But I am not sure, this is what you were talking about previously.

**Comment by andrewvanbreda** [comment]
Note, the original problem noted in this issue is now fixed in the following issue
https://github.com/BiologicalRecordsCentre/ABLE/issues/578

**Comment by JimBacon** [comment]
Closing as original issue is fixed.
Connection to Transifex is the subject of https://github.com/BiologicalRecordsCentre/ABLE/issues/458.
