### ISSUE TITLE
15 minute counts vibration

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#573]
Back from holidays, done a lot of 15 minute counts, and noticed that when the phone is in sleeping mode it DOES vibrate at the 3 minute warning, but NOT at the end of the count. I use a Asus Zenfone 8 with Android 13. Would be great if the vibration could come to the end of the count as well.  @kazlauskis

**Comment by kazlauskis** [comment]
Thanks, that's useful to know. I have linked this info with the original app vibration ticket, so closing this one.
