### ISSUE TITLE
Slovak butterfly names- to place second word in lowercase

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#575]
Hi, the Slovak coordinator reported the Slovak butterfly names to appear wrong on the ButterflyCount app (and I supposed this as well on the website). They are wrong because the second name always starts with a lowercase letter. At the moment, the first letter of the second name is capitalized. It should be as scientific names, the first word with first letter capitalised and the second word completely lowercase.

Please change it if possible, @JimBacon @andrewvanbreda @Vilius-Stankaitis thanks

**Comment by JimBacon** [comment]
Names were imported in to the warehouse from the file at https://github.com/BiologicalRecordsCentre/ABLE/issues/564#issue-1705477130 with the same use of capitals. There are occasions where the second name has a capital, e.g. Mlynárik Mannov (_Pieris mannii_) but generally they are lower case.

I suspect it is a bit of CSS styling in the app to make the appearance of names more consistent.
