### ISSUE TITLE
Include Slovakia country and Slovak language -eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#576]
Hello, I thought this was already reported. Please add Slovakia to the list of countries and the Slovak language as well. 

Thanks, @DavidRoy  
Maybe you can explain to me how to do it to avoid you future work on this. Cheers.

**Comment by CrisSevilleja** [comment]
I am getting translations in Slovak to apply on the website but I don't have the language ready, please @david, @JimBacon or someone else can include this language on the eBMS website. Thank you

**Comment by DavidRoy** [comment]
I've added Slovak as a language in Drupal, and made available for translation in Transifex.  I notice that Drupal used 'sk' and transifex 'sk_SK' so we might need to check if this has any implications. Please close the original issue is resolved

**Comment by CrisSevilleja** [comment]
thanks David, indeed we will need to check if that mismatching generates a problem.

**Comment by CrisSevilleja** [comment]
Hi @DavidRoy sorry I open this issue again, the Slovak language name is in English, could it be possible to place Slovenský instead of Slovak to select the language on the drop-down list of languages? thank you!

**Comment by DavidRoy** [comment]
@CrisSevilleja that should be done. Close if resolved. thanks

**Comment by CrisSevilleja** [comment]
thanks!

**Comment by DavidRoy** [comment]
@CrisSevilleja we can also change the text for any other languages in the selector.  I think they usually default to English?

**Comment by CrisSevilleja** [comment]
The drop-down list to select the language on the website appears in its language, however, when creating the account and selecting the preferred language is by default in English except for Slovak now. 

It would be good if this last one can be changed to the local language

**Comment by DavidRoy** [comment]
Can you raise a new issue for this please and we'll investigate

**Comment by CrisSevilleja** [comment]
done #587
