### ISSUE TITLE
Issue: repetition 15min counts uploaded on the website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#577]
### Describe the issue

Indicia Warehouse User ID  329815 reported submitting 26 surveys (15min counts from the app) and they appear repeated on the website. Checking his users, indeed there are two surveys repeated; 21st May 3 times repeated and 20thMay several times repeated. They all have the same time, area but different ID:
![andrei_issue2](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/37c365b7-7f1d-4263-92ee-7d974f8c5782)

Checking the species also they are showing the same species and abundances:
![andrei_issue](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/dc76578a-67a2-4a68-9ac6-134f7cb18721)

Also he mentioned from the 26 surveys, only he can edit 24. I will ask which ones exactly he is missing. I am not sure if this issue is coming from the app @kazlauskis @Vilius-Stankaitis or if it is a problem with the website @andrewvanbreda @DavidRoy Other users reported repetitions on the website, there is something going on. 

### Expected behaviour

Show surveys without repetitions

### To Reproduce

1. Create 15min count survey
2. Finish and upload them
3. Go to https://butterfly-monitoring.net/ and go to My samples https://butterfly-monitoring.net/mydata/samples 

### App Version

Butterfly Count app v1.20.0 (241)

### Device

Huawei P Smart, FIG-LX1

### When did this happen

21 and 22 May 2023 surveys submitted

**Comment by CrisSevilleja** [comment]
I think it is a problem with the website, I found repetitions on my samples of moth traps done last year, 23/07/2022 including 9 species: 
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/ae40d238-95b1-4a1c-8172-69ef93d4a80b)

Also, I realised that always I enter this page, I don't see the last records uploaded, but this moth's sample on 2022. Is this table ordered based on the survey type instead of the recent date?

thanks in advance

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
I am noticing the reason for the apparent duplicate is that the system is trying to return occurrences instead of samples.
So if a sample has multi occurrences it is showing several rows.
However I think this is supposed to show sample rows isn't it, not occurrences?
The ID on the left is an occurrence ID, notice that actually that ID doesn't duplicate, only the sample information is the same.
I think the table is default ordered by that ID descending.

My other test sites are showing the same behaviour, which indicates it is either an old problem, or it is a problem with the data that Elastic Search is returning (rather than being a problem with the configuration of the website itself).

When did you first notice it wasn't doing what you were expecting?

**Comment by CrisSevilleja** [comment]
Hi @andrewvanbreda thanks for checking this. 

Indeed on My samples page https://butterfly-monitoring.net/mydata/samples the first tab is for "Samples" so, it should return samples not occurrences, for reporting occurrences is the second tab "Records". 
The table should be ordered by default by more recent Date. 

I notices the order was wrong a long time ago, but it was not a big issue. The replications I think started at the beginning of May.

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
Thank you for the information, and also about when it started.
I will see if I can get to the bottom of this.

**Comment by andrewvanbreda** [comment]
Hi @johnvanbreda 
Would it be possible for you to take at look at the configuration of this page if you have a sec?
I have tried to create a simpler version of the page on my test site and it is doing the same thing even if I simplify it the most I can.
One thing I noticed is that it is returning samples and occurrences onto the same grid, that doesn't seem right to me.
Is the Elastic Search index correct?
We can see this as the sample rows have all the columns filled in like they should be.
e.g.
22048192 is returned and is a sample
27251183 is returned and is an occurrence

**Comment by johnvanbreda** [comment]
I don't know why it was set up this way (possibly a mistake) but the es-able-samples-admin end-point was set up to point to an alias configured on Elasticsearch called occurrence_search_able_samples_admin which existed on both the occurrences index and samples index, so data from both were being searched. I've just removed the alias from the occurrences index which fixes the issue.

It may be worth looking out for pages where the es-able-samples-admin end-point was in use - I doubt there was an intention to include occurrences in the results but worth checking just in case.

**Comment by andrewvanbreda** [comment]
@johnvanbreda 
Thanks that is brilliant thanks.

I can see an edit was made in early May, but I do not think it would have been deliberate either...perhaps an experiment on a test site that was accidently copied to live is only thing I can think of.
Thanks for the tip, I will look at that before closing this issue.

**Comment by CrisSevilleja** [comment]
is this issue resolved @andrewvanbreda ? just because I think there are not more duplications on the website page

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
Yes it is.
John did suggest I should check the site's other pages in case of similar issues, but doing that has not been high enough priority on my task list to get around to doing yet (as other pages have not actually had problems reported).
If you feel this is fixed, you can close this issue if you lik,e as I have a note on my task list about checking the other pages sometime.
