### ISSUE TITLE
creating new subpages on eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#579]
Hi @JimBacon I am creating new subpages under https://butterfly-monitoring.net/ebms-app 
I managed to create two of them, however I am not able to create the pages empty to be able to add text later, instead the home page appear. 

Could you tell me how to create the empty page without the home page? Sorry if it is so obvious, I don't manage to find it. 

Here is the structure I thought for subpages:

eBMS mobile app page: 
- Transects - app
- 15min counts -app
- Moth traps - app
- Painted Lady migration - app

**Comment by JimBacon** [comment]
Hi Cristina, 

I can see that you have created the menu items but I do not see that you have created any pages. Alternatively I could say you have worked on Structure but not Content.

If I go to the list of Content and filter for 'Basic page' in 'Site's default language', none of the sub pages that you want are present.

I recommend you create the content first and then assign it a place in the menu system.

It seems reasonable that, when you create a menu item for which there is no content, it should redirect to the home page.

I hope you understand my meaning but, if not, let me know and I can give you precise instructions.

**Comment by CrisSevilleja** [comment]
Hi Jim, 

Thank you so much, I was doing the opposite, creating the menu items but not the content... thanks 
Now I understood it and I created all the pages including the menu link. 
Everything fine. Thanks for the help! 

I was a bit lost. Cheers
