### ISSUE TITLE
enable login via email address

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#58]
enable login to accept both username and email address.  Currently only accepts username.
http://live-butterfly-monitoring.pantheonsite.io/user/login

**Comment by Gary-van-Breda** [comment]
LoginToboggan module is not currently available for D8
"Login Email or Username" login_emailusername contrib module installed on Dev, Test, and Live; activated on all 3; tested on all 3.
@DavidRoy : is this OK?

**Comment by DavidRoy** [comment]
Thanks.  Confirmed on live.
