### ISSUE TITLE
Extend 15m count downloads

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#580]
Final requirement from: https://github.com/BiologicalRecordsCentre/ABLE/issues/481

Need to include the additional information in downloads - https://butterfly-monitoring.net/downloads
And reports - https://butterfly-monitoring.net/mydata/samples

Will require an update to ElasticSearch Index?

**Comment by johnvanbreda** [comment]
I would hope that the ES index does not need updating, as the sample custom attribute with ID 1735 should be present in the attributes json.

**Comment by CrisSevilleja** [comment]
Did we include in the 15min downloads the life stage recorded (butterfly, egg, larvae...)? At the moment, this column is not included and people who is recording other stages, apart from butterflies, need it. 

Please add the column life stage for the download file of occurrences for 15 min counts and 15min single species count. 
thanks 
@DavidRoy

**Comment by DavidRoy** [comment]
@JimBacon - relates to wider requirement for changes to the download formats?

**Comment by JimBacon** [comment]
On https://butterfly-monitoring.net/downloads

- Added life stage to 
  - Download timed-count occurrences
  - Download single-species timed-count occurrences
- Added species groups to
  - Download timed-count sample data

On https://butterfly-monitoring.net/mydata/downloads
- Added life stage to 
  - Download 15-min count occurrences
  - Download 15-min single-species occurrences
- Added species groups to
  - Download 15-min count samples
