### ISSUE TITLE
Inconsistent data structure in 15 Minute Counts

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/ABLE#582]
This issue arises from https://github.com/BiologicalRecordsCentre/ABLE/issues/581 where it was requested that the 15 Minute Count with parent_sample_id = 22070930 be restored from deletion.

- It was immediately apparent that this sample had not been deleted.
- The sample is not visible to the recorder in the list of samples, https://butterfly-monitoring.net/mydata/samples, which would explain why they thought it deleted.
- Viewing the [sample](https://butterfly-monitoring.net/mydata/samples/details?sample_id=22070930) incicates that it has an occurrence marked confidential which is the reason for hiding it.
- This was confusing as none of the occurrences on any of the subsamples were marked confidential.
- On debugging the sample details page, it was found to use the `reports_for_prebuilt_forms/sample_details/sample_data` report to obtain the sample data and check for confidential records.
- This report is designed for sample-occurrence surveys, not sample-subsample-occurrence surveys.
- It turns out that this record has 4 occurrences attached to the parent sample and 18 to subsamples.
- This shows up if you [edit](https://butterfly-monitoring.net/mydata/samples/edit?sample_id=22070930) the record as the records without a subsample appear without a spatial reference.

By way of investigation, I queried the 15 Minute Counts survey (id = 565) to see how many occurrences and how many sub-samples were attached to each parent sample using a query like the following.
```sql
-- Create temp table of occurrences on parent sample.
select s.id, count (o.id) num
into temp table num_occs
from cache_samples_functional s
join cache_occurrences_functional o
	on o.sample_id = s.id
where s.survey_id = 565
and s.parent_sample_id is null
group by s.id

-- Create temp table of sub-samples on parent sample.
select s.id, count (ss.id) num
into temp table num_ss
from cache_samples_functional s
join cache_samples_functional ss
	on ss.parent_sample_id = s.id
where s.survey_id = 565
and s.parent_sample_id is null
group by s.id

select s.id, num_occs.num, num_ss.num, s.date_start, s.created_on
from cache_samples_functional s
left join num_occs on num_occs.id = s.id
left join num_ss on num_ss.id = s.id
where s.survey_id = 565
and s.parent_sample_id is null
order by s.id
````

What this shows is that the survey began collecting records in July 2019, at which time no sub-samples were created and occurrences were attached to the parent sample. Around May 2021 there was a transition to recording with sub-samples. However, records are still being generated today where all the occurrences are attached to the parent sample and not sub-samples (e.g. sample_id 22258861 on 5/6/2023, using Android and app version 1.20.0). 

The record which prompted this investigation is one of a small percentage which have both sub-samples and occurrences attached to the parent sample.

The graph below shows the results of the query, indicating the transition from one survey structure to another.
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/f7c9d92b-a0c3-49ec-a128-87c6a8553a90)

Thoughts...
- @kazlauskis Is it correct behaviour for the app to submit 15 Minute counts with occurrences but without sub-samples?
- The web pages don't seem to fully cope with both survey structures.
- It might have been a whole lot cleaner to segregate the different survey methods into different survey IDs
- I don't see any metadata describing the survey structure which would have helped me understand this situation.
- I don't actually know if there is a problem here or whether it is just complex and obscure.

**Comment by kazlauskis** [comment]
@JimBacon Yes, it is correct for the app to sometimes skip subsamples. Most of the time, occurrences should have parent subsamples, but if the location isn't set, the occurrence will default to the parent top-sample location.

**Comment by JimBacon** [comment]
Thanks, @kazlauskis. I'll close this issue as the problem was mostly lack of knowledge on my part. However, I will

- Add a description to the survey on the warehouse so there is some record of this information.
- Raise an issue around the Sample Details page on the website which I guess was not updated when subsamples were added to the survey.
