### ISSUE TITLE
not able to add a mothspecies in the app, but it works on the website

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#583]
@kazlauskis @JimBacon 
I was trying to enter some moth sampling I did on holidays in France. I tried to enter Arctia villica in the app, but the app only offered me the genus, no option for the species (see screenshot below). However on the website I was able to add this species. I thought the app and website used the same species list. Or am I missing something obvious?

![Screenshot_20230609-151918067](https://github.com/BiologicalRecordsCentre/ABLE/assets/25886005/a6715da1-c485-4d0d-acc9-e34d7b06cc23)

**Comment by Vilius-Stankaitis** [comment]
Hi @chrisvanswaay, I was able to reproduce this. The issue is that the "Use only day-flying moths" filter is active.  

We will fix this. Thanks for catching this issue!

**Comment by chrisvanswaay** [comment]
Thanks! Indeed, for a night with the moth trap the filter to day active moths should be made inactive. Have a nice weekend.

**Comment by szabadfalvi** [comment]
We have also run into this problem with several surveyors (dayflying moths + moths  checked simultaneously in the settings) >> shouldn't wre remove the dayflying moths  option completely?
I know, it limits the sp. selection list but it is hard to determine exactly which spp. is considered a dayflying moth (almost anything can be one )

**Comment by Vilius-Stankaitis** [comment]
@szabadfalvi Yes, this is fixed and will be available on the next release.
