### ISSUE TITLE
Set up languages on eBMS in their own language

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#587]
The drop-down list to select the language on the website appears in its language. 
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/59cd9977-f43a-43a7-8bca-789cd5e1e820)

However, when creating the account and selecting the preferred language is by default in English except for Slovak now.
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/fb0d64fc-1c8a-450b-9702-b57edba8fea7)

It would be good if the list of languages inside the user account/registering page can be changed to the local language.

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja
Fixed, close if happy.

**Comment by CrisSevilleja** [comment]
thanks!
