### ISSUE TITLE
EBMS transects in Moth trap data verification

### ISSUE THREAD

**Issue by Joao-Nunes-Moths** [BiologicalRecordsCentre/ABLE#588]
Hello,

In my verification menu also appear the data of the moths recorded during eBMS transects (butterflies). I think that happens because the filter is applied between moths and butterflies rather than between sampling methods or datasets (EBMS fixed moth trap and EBMS Transects). Can we change this so that the coordinators of moth trapping schemes only deal with the intended data?

Thank you.

**Comment by DavidRoy** [comment]
@Joao-Nunes-Moths This was deliberate.  Would be able to review the (day-flying) moth data for the transects?  Otherwise, we can change your verification filter

**Comment by Joao-Nunes-Moths** [comment]
I am able to do it from a taxonomic point of view, however, I am not the coordinator of that project. I do not know the volunteers and the records do not include any picture. Moreover, these data are not comparable with data generated with moth trapping. I think we can change my verification filter for "EBMS fixed moth trap".

Thank you.

**Comment by DavidRoy** [comment]
@Joao-Nunes-Moths that should now be done.  Please close this issue if resolved for you

**Comment by Joao-Nunes-Moths** [comment]
@DavidRoy My verification filter remains the same. Should I wait some time for the update?

**Comment by DavidRoy** [comment]
@Joao-Nunes-Moths apologies, I didn't commit the change.  Can you try again please

**Comment by Joao-Nunes-Moths** [comment]
@DavidRoy Perfect! Thank you very much.
