### ISSUE TITLE
Add Noctua fimbriata/tirrenica and Caradrina flavirena/noctivaga

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#589]
Can we add the entries Noctua fimbriata/tirrenica and Caradrina flavirena/noctivaga to the moth species list? Those are two pairs of species that can only be separated through dissection. It might be useful in the future to have them instead of "only" Noctua sp. or Caradrina sp.

_Originally posted by @Joao-Nunes-Moths in https://github.com/BiologicalRecordsCentre/ABLE/issues/534#issuecomment-1593079154_

**Comment by DavidRoy** [comment]
@kazlauskis that is now done.  Please close this issue when you've updated the list in the app
