### ISSUE TITLE
Translation eBMS website from Transifex: edit a translation applied

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#590]
Hi @JimBacon 
the Italian coordinator asked me to change the translation applied to the sentence ¨Any Butterflies?¨ when registering the visit transect data (second page). This is the question you need to click to be able to fill the species seen. The current Italian translation of this sentence is confusing for volunteers, and they would like to change it to _Hai trovato delle farfalle?

I tried in Translation Sources to change it but the translation from Transifex was already applied and there is no option to change it, as far as I know. Maybe in Transifex?
Actually, I would like to edit the English question ¨Any Butterflies?¨ to ¨Have you seen butterflies?¨ In this way, the question is clearer for the translation, that at the moment is a bit confusing. 

So maybe this item has to be removed completely and start a new item to translate in Transifex? what do you think is best?
thanks in advance

**Comment by JimBacon** [comment]
Cross-reference to https://github.com/BiologicalRecordsCentre/ABLE/issues/614#issuecomment-1669951378
