### ISSUE TITLE
Issue: Transect records submitted without abundance

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/ABLE#599]
### Describe the issue

When transect recording, you can delete the count value for a taxon. You can submit the record and it creates an occurrence without an abundance attribute.

### Expected behaviour

I'm not sure what I expected but I think I would like the app to prevent a record being submitted without an abundance. 

When analysing the submitted data, scheme organisers don't know what to make of such records and think something has gone wrong when they see one.

### To Reproduce

1. Start a new transect record and select a transect.
2. Add a species to the first section.
3. Drill down in to the species where you can edit the count
4. Tap on the number to open the text box and delete the number
5. Go back and you have a record with no count.
6. Submit this and an occurrence is created on the server with no count.

### App Version

v1.21.0 (261)

### Device

Google Pixel 3

### When did this happen

10/7/2023

### Screenshots

<img width="540" alt="Screenshot_20230710-170151" src="https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/d842b757-8ada-48b2-8021-791810cd8ea9">

### Additional context

It may be one of the causes of an [issue ](https://github.com/BiologicalRecordsCentre/ABLE/issues/522) I am trying to tidy up.

**Comment by JimBacon** [comment]
Occurrences 31179214, 31179215, 31179216 are examples with no abundance. They also carry a comment "Not to be recorded" which makes me wonder if the recorder didn't figure out the hidden swipe-to-delete and, therefore, if it might be good to add a more obvious delete mechanism on the Edit Occurrence page.

**Comment by DavidRoy** [comment]
@kazlauskis or not upload species occurrence where the count is missing?

**Comment by kazlauskis** [comment]
I agree the app shouldn't allow uploading occurrences with zero abundance. I have fixed this now.
