### ISSUE TITLE
Establish a GBIF IPT for sample data for Indicia

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#6]
Installing the IPT is fairly simple but does require that the server has a “Java servlet container” for it to run inside, such as the open source Tomcat. 
 
Once the IPT is installed, there are some fairly simple setup steps, then you can register a datasource. 

Extned the DwC format exports to match the full sample structure.

The registered datasource can be mapped to DwC terms which is again simple since the term names are already used in the output.

**Comment by DavidRoy** [comment]
links to https://github.com/BiologicalRecordsCentre/MammalNet-Europe/issues/5.  ABLE will piggy-back on this implementation

**Comment by johnvanbreda** [comment]
I've set up an export from iRecord for the ABLE data but there are only a couple of hundred accepted records at the moment, so is it worth waiting till the dataset is more complete before publishing?

When ready, there is a resource waiting for metadata to be added on the IPT: http://ipt.brc.ac.uk/ipt/manage/resource?r=ebms.

**Comment by DavidRoy** [comment]
@johnvanbreda I'd like to pick this up again but will raise a new issue given how old this is
