### ISSUE TITLE
Add site number to Transect Allocation page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#60]
request from @xaviermestdagh

Transect allocation: http://live-butterfly-monitoring.pantheonsite.io/transects-allocation
- Would it be possible to have the number of sites listed at the bottom of the table (with the filtered sites)?

**Comment by Gary-van-Breda** [comment]
Xavier,
Do you mean you would like the site ID number included with each row? Or do you want a count of the number of sites in the selected scheme/country put somewhere?

**Comment by xaviermestdagh** [comment]
Hello,
I mean a count of the number of sites shown in the grid like here below for
the "National sites".


Have a nice day,
Xavier

**Comment by Gary-van-Breda** [comment]
Done, and deployed to Live.
A Count of the number of sites is included in the footer (bottom) of the grid, on the right.

**Comment by DavidRoy** [comment]
Thanks.
@xaviermestdagh to check and close if happy
