### ISSUE TITLE
Import butterfly list for Botswana

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#604]
- [x]  add taxon attribute for Botswana
- [x]  add Botswana as scheme on butterfly-monitoring.net
- [x]  import species list into warehouse
- [x]  make list available in the ButterflyCount app

[BOTSWANA - JULY 2023.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/12092444/BOTSWANA.-.JULY.2023.xlsx)

**Comment by JimBacon** [comment]
@DavidRoy Does the Tribe and Subtribe need to be included in the import?
Currently we just have Family-Subfamily-Genus-Species as the hierarchy in the EBMS Butterflies list.

**Comment by DavidRoy** [comment]
@JimBacon no but could you retain any external key to allow us to link back if ever required?

**Comment by JimBacon** [comment]
There is no external key provided. Should we request one before importing?
For other countries I tried to obtain external keys from GBIF which was partially successful.

**Comment by DavidRoy** [comment]
Count you create a key based on 'ABMS' | the .csv row number?  e.g. ABMSID

**Comment by JimBacon** [comment]
Added the following new subfamilies via the warehouse user interface:

Family      | Subfamily
------------|----------
Hesperiidae | Tagiadinae
Hesperiidae | Coeliadinae
Lycaenidae  | Miletinae
Lycaenidae | Poritiinae
Nymphalidae | Biblidinae

**Comment by JimBacon** [comment]
Imported new genera from the attached file via the warehouse user interface.

[new-genera.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/12589181/new-genera.csv)

**Comment by JimBacon** [comment]
Imported new species and subspecies from the attached files via the warehouse user interface.

[new-species-present.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/12611032/new-species-present.csv)


[new-subspecies-present.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/12611589/new-subspecies-present.csv)

[new-parent-species.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/12611034/new-parent-species.csv)

**Comment by JimBacon** [comment]
I'm left with 17 taxa where we have existing records which are in conflict with records in the supplied file. 4 of those are differences in name spelling and 13 in the author punctuation.

taxa_taxon_list_id | Existing taxon | New taxon
--- | --- | ---
548704 | Acada biseriatus | Acada biseriata
548797 | Charaxes achaemeres | Charaxes achaemenes
549188 | Pseudacraea boisduvali | Pseudacraea boisduvalii
548943 | Cupidopsis iobates | Cupidopsis jobates

taxa_taxon_list_id | Taxon |  Existing authority| New authority
--- | --- | --- | ---
548882 | Coeliades pisistratus | Fabricius, 1793 | (Fabricius, 1793)
432141 | Pelopidas thrax | (Hübner, 1821) | (Hübner, [1821])
432282 | Azanus ubaldus | (Stoll, 1782) | (Stoll, [1782])
432317 | Freyeria trochylus | (Freyer, 1844) | (Freyer, [1844])
548790 | Byblia ilithyia | Drury, 1773 | (Drury, 1773)
548813 | Charaxes candiope | Godart, 1824 | (Godart, [1824])
548870 | Charaxes zoolina | Westwood, 1850 | (Westwood, [1850])
549223 | Tirumala petiverana | (Doubleday, 1847) | (Doubleday, [1847])
548726 | Acraea neobule | Doubleday, 1847 | Doubleday, [1847]
549173 | Precis antilope | Feisthamel, 1850 | (Feisthamel, 1850)
549085 | Melanitis leda | Linnaeus, 1758 | (Linnaeus, 1758)
548998 | Graphium antheus | (Cramer, 1779) | (Cramer, [1779])
548924 | Colotis ione | (Godart, 1819) | (Godart, [1819])

**Comment by JimBacon** [comment]
Updated external keys to be like "ABMS-BW" + \<spreadsheet row number\> as suggested in https://github.com/BiologicalRecordsCentre/ABLE/issues/603#issuecomment-1723442430

Also updated subspecies to be children of genus rather than children of species where no such species previously existed as this more closely resembles the supplied list. I'm thinking this will be better for data entry.

**Comment by DavidRoy** [comment]
@JimBacon please give preference to the ABMS names based on further details:

_1) Taxon names: The Afrotropical Butterflies taxon names are correct. The spellings of species names in the "existing" checklist are incorrect. These errors were probably typographical in origin, and were not picked up during proof reading.

2) Authorities: It seems that the differences between the "existing" checklist and the "new" one are all because of the (correct) usage of square brackets in the Afrotropical Butterflies checklist. Square brackets around a date of publication indicate that the publication itself was written over a period of some years, and the year given in the square brackets is the inferred actual year of publication. The IUZN Code allows only a single year, not multiple years. This can be important in determining the priority of names._

**Comment by JimBacon** [comment]
Refer to https://github.com/BiologicalRecordsCentre/ABLE/issues/603#issuecomment-1748956623 for resolution of naming conflicts.

**Comment by DavidRoy** [comment]
@kazlauskis can you implement for the app?

**Comment by kazlauskis** [comment]
I've added Botswana to the app now. It will be ready in v1.23.0 release sometime this week.
