### ISSUE TITLE
Mobile app will not start up

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/ABLE#605]
### Describe the issue

After downloading from the Google Play store, when trying to start the app for the first time, the purple splash screen appears momentarily and then the screen goes white and nothing further appears to happen.

### Expected behaviour

I expected the app to start normally.

### To Reproduce

Simply try to start the app.

### App Version

1.21.0

### Device

Google Nexus 5

### When did this happen

2023-07-20 10:25

### Additional context

It's an old phone on Android 6.0.1 but the app does declare itself to be compatible with 5.1 and up.

**Comment by kazlauskis** [comment]
Google Nexus 5 has 2GB of RAM. I typically suggest the app needs 4GB but can still (mostly) work with 3GB. I will add this requirement to the Play Store but I know this doesn't help you much 😕

**Comment by JimBacon** [comment]
Never mind. Updating the requirements is sufficient.
