### ISSUE TITLE
Walk data entry failing

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/ABLE#608]
After leaving the first page of Walk data entry, this message is displayed.

cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
URL:https://warehouse1.indicia.org.uk/index.php/services/data/location
Server response
{"error":"Validation error","code":2003,"errors":"Invalid format for integer column filter."}
cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
URL:https://warehouse1.indicia.org.uk/index.php/services/data/location
Server response
{"error":"Validation error","code":2003,"errors":"Invalid format for integer column filter."}
The website encountered an unexpected error. Please try again later.

**Comment by Gary-van-Breda** [comment]
@andrewvanbreda Can you give an example of User and Location/Date combination - I can't replicate.

**Comment by andrewvanbreda** [comment]
@Gary-van-Breda 
Masquerade as David Roy, and use his test walks. 
We also have a report of it failing for a Japanese user.

**Comment by andrewvanbreda** [comment]
@Gary-van-Breda 
This one does it if you are masquerading as David
https://butterfly-monitoring.net/walk-data-entry?location_type_id=777&sample_id=21188754

**Comment by Gary-van-Breda** [comment]
OK It happened for me when going to a sample the second time (after saving)

**Comment by andrewvanbreda** [comment]
@Gary-van-Breda 
OK, I have not have that situation. I have only have had it the first time, but I have only tried 5 or so times.

**Comment by Gary-van-Breda** [comment]
@andrewvanbreda : there is a problem with the location control on the front page. I'm looking at it.

**Comment by Gary-van-Breda** [comment]
@andrewvanbreda Code fixed, tested, pushing through to Live.

**Comment by andrewvanbreda** [comment]
@Gary-van-Breda 
OK great thanks :)

**Comment by andrewvanbreda** [comment]
@Gary-van-Breda 
Looks to be working, so shall I take site out of maintenance mode now?

**Comment by Gary-van-Breda** [comment]
@andrewvanbreda : code deployed to live, and checked. Test data removed.
If you selected a site from the My walks page before going to the walk page, or if you were viewing an existing sample (which had the location filled in) then you would get this issue when submitting the data: there was no location_id in the POST.

Did you put the site into maintenance mode? If so, do you want to take it out?

**Comment by andrewvanbreda** [comment]
@Gary-van-Breda 
Yes I will do that. Thanks for speedy response.
