### ISSUE TITLE
Transect allocation download not working

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#61]
when masquerading as @xaviermestdagh, the button 'Download allocation report' redirects to the site home page and does not produce the download file.

This functionality works fine for Admin.  The report needs to be available for users with role = 'Scheme co-ordinator'

Url of link that is not accessible
http://live-butterfly-monitoring.pantheonsite.io/iform/ajax/ebms_transects_allocation/downloadSiteAllocations/35?location_type_ids=107&attribute_id=20&region_location_type_id=213

**Comment by Gary-van-Breda** [comment]
Fixed.
The "Transect allocation" form is only available to Scheme coordinators, the supermanagers (i.e. Pan European managers, the tier above the scheme co-ordinators), and admin: this restriction also applies to the download.

**Comment by DavidRoy** [comment]
Checked and works when masquerading as Xavier
