### ISSUE TITLE
Check Annual report modifications - eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#611]
Some modifications to the Annual Report https://butterfly-monitoring.net/annual-report has been applied due to the new role of Regional coordinator #255 @DavidRoy @Gary-van-Breda 

In general, I like all, I think it is useful for Regional Coordinators to see all their regional sites at once or select by transect. 

However, I think the option "Combine data for all recorders" that disappeared is still necessary. Normal users that share a transect should be able to see that transect and download all the transect data, even if they didn't include data. At the moment, you can download data only from the user's transect submission when it would be good to allow the download of all data of shared/assigned transects #524 
- So under the filter Data set, I would include "Combine data for all recorders" to see shared transect data. 

Another modification I don't think some users and coordinators would like is to see under the Annual Report page all the data of the scheme they belong. I masqueraded as a normal user of Spanish BMS and on the Annual Report page, that user (and all) can see the data of every transect in the Spanish BMS. I don't see a problem with showing the option "Combine all sites in ... BMS" or "Combine all my .... sites together" in the filter by site, showing all the data of that scheme at the same time. However, per transect, the data show in much detail.
- I would remove the option Other sites in X BMS under the Filter by side (red square)

![annual report to fix](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/ff757fb7-5c95-4b32-8387-5f9fcfda2684)

I hope I didn't combine many things in this issue. Please David mention if you don't agree with something. 
Thank you in advance.

**Comment by Gary-van-Breda** [comment]
Changes applied and deployed to Live.
1) The Region and Scheme data set labels have been changed to make it clear that they represent all data for all users. (schemes labels unchanged for supermanagers)
2) Bugfix applied to remove non-assigned sites from the site lists of normal users.

In addition some of the site combination options have been removed if they are unneccessary - e.g. if the user only has one site, then there is no point in providing a "Combine all my sites" option.

Bouncing to @CrisSevilleja for review/closure.

**Comment by CrisSevilleja** [comment]
perfect @Gary-van-Breda now it makes more sense. Users can see the complete data of their scheme but not precise transects they don't have assigned. Thank you!

We can close this.
