### ISSUE TITLE
Download 15 min count - samples does not download

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#615]
This morning I wanted to download the samples and occurrences of the 15 min counts. All went smooth and normal for the occurrences, but for the samples I could see that the download was prepared and ready for download, but clicking 'Download zip-file' did not work (in contrast to the occurrences, where it did work). Tried on Edge and Opera browser, each time the same. I guess it's something small. See also screenshot below.

![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25886005/d1292415-87f1-413c-b289-a24c3d90e29a)

**Comment by JimBacon** [comment]
Hi @chrisvanswaay 
I have masqueraded as you, gone to https://butterfly-monitoring.net/downloads, selected All Data and successfully downloaded a zip file of 23333 records. Can you try again to see if the problem still exists from where you are?

**Comment by chrisvanswaay** [comment]
Thanks @JimBacon , now it worked without a problem. A small hickup somewhere.
