### ISSUE TITLE
Styling on Walk data entry page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#62]
The styling on the walk data entry page to be improved.  The drop-down list/text boxes are too wide.

e.g. http://live-butterfly-monitoring.pantheonsite.io/ebms-input-data?sample_id=11570

![p](https://user-images.githubusercontent.com/2699478/57434093-0b002180-7232-11e9-94b7-a28882e67943.png)

**Comment by BirenRathod** [comment]
@DavidRoy 
Removed the margin on all input boxes which looks fine now.

**Comment by DavidRoy** [comment]
Thanks
