### ISSUE TITLE
South Africa BMS page appears for other countries - eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#620]
@JimBacon a coordinator reported to me the South Africa BMS page https://butterfly-monitoring.net/sa-bms appears for the French users. I checked and this appears incorrectly for, I think, all the different countries (I checked 6 different countries) and the South Africa BMS page appears under My scheme together with the corresponding scheme. 

I think the newly created South Africa BMS page has been applied for all countries when it should appear only for South Africa. I hope you can fix this.

![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/6ad8d219-abfd-4780-a375-08cfb48f1079)

**Comment by DavidRoy** [comment]
That was an oversight on my part.  Should now be resolved
