### ISSUE TITLE
Area sampled calculated with 10m width? 15min counts

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#624]
One coordinator asked me how the area sampled (m2) is calculated. He thinks it is wrong or not calculated as he expected with 5 metre width for transects and 15min counts routes. He gave me the example of one 15min he did, 
[20230626_recorrido.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/12595732/20230626_recorrido.xlsx)

The area sampled is 8258 m2 for 827 route length of a15min count. For this area sampled, I expect it has been used 10m width for a 827m length route, instead of the 5m width expected (as the transect width), therefore the corrected area sampled 4129m2. 

Anyway, I need to corroborate the width used for calculating the area sampled in the 15min count routes and mention it on the website for users. 

Later, we can discuss if the 10m width is the correct, if we assume people is really recording 10m width in their surveys or we should determine the 5m width we normally used for transects (as in the manual is mentioned) @DavidRoy @chrisvanswaay 

David assign who you consider for this issue.

**Comment by chrisvanswaay** [comment]
Personally I would prefer to have the area replaced by length.

**Comment by CrisSevilleja** [comment]
Indeed, the length of the route should be included, I would prefer it as well. The coordinator calculated by himself from the track route.

**Comment by kazlauskis** [comment]
For 15min counts in the app, we do _Length x 2 x 5m_. I think it was always like this in the app, do you say it should be 2.5m to the sides? Was this ever changed?

**Comment by chrisvanswaay** [comment]
I still think the length is more logical than the area.

**Comment by DavidRoy** [comment]
We need both I think as some recorders will draw a polygon and then count within.  Although mostly the app is used by walking.  Maybe needs some thought based on how the app is used, e.g. GPS on/off, polygon of an area drawn or not?

**Comment by DavidRoy** [comment]
@kazlauskis we never concluded this discussion.  I think we need to take two actions:
1. The area calculation should be length * 2.5 * 2
2. We should also store both the length and area

Can you confirm the steps we need to take for this?

**Comment by CrisSevilleja** [comment]
Coming back to this issue, users are asking me again about the area sampled registered by the app is not correct and they would like it improved

@kazlauskis any news about this?

**Comment by kazlauskis** [comment]
I have fixed it now, which will appear in the next app version later this month.

**Comment by CrisSevilleja** [comment]
thank you!
