### ISSUE TITLE
Website recording of transects not working

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/ABLE#626]
When trying to enter abundance values for butterflies the spinning wheel never stops

![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/54c97645-40c6-48f9-a38b-6fa45d6848d4)

The post to the server is getting a response
```
    cUrl POST request failed. Please check cUrl is installed on the server and the $base_url setting is correct.
    URL:https://warehouse1.indicia.org.uk/index.php/services/data/save
    Server response {
      "error":"Validation error",
      "code":2003,
      "errors":{
        "occAttr:780":"There was an SQL error: 
          ERROR:  insert or update on table "occurrence_attribute_values" violates foreign key constraint fk_occurrence_attribute_values_occurrence"
          DETAIL:  Key (occurrence_id)=(353677370) is not present in table "occurrences".
      }
    }
```
This suggests a warehouse error because it generates the occurrence_id which is wrong. I note the warehouse code was updated yesterday.

UPDATE: UKBMS website, which works similarly, is not showing this problem so maybe not a warehouse error. Continuing to investigate.

**Comment by johnvanbreda** [comment]
@JimBacon I skimmed over all the code changes which were merged to master yesterday, I don't recall there being anything that would affect this area of code but I might be wrong.

**Comment by JimBacon** [comment]
I think it relates to the set_sample_occurrences_to_training_trigger

To quote MY_ORM.php comment

> Kohana relies on PostgreSQL lastval() to find the ID for inserted records,
> this fails if the table has a trigger on it which uses a sequence during
> the insert. 
>

**Comment by johnvanbreda** [comment]
@JimBacon I would suggest removing the new triggers at least temporarily then. We can review with @andrewvanbreda the best approach to fixing them later.

**Comment by JimBacon** [comment]
I have a fix working on the dev warehouse so I'll patch the live warehouse and then commit a hotfix to the repo.

**Comment by andrewvanbreda** [comment]
@johnvanbreda @JimBacon 
In the interests of avoiding something similar happening in the future, any thoughts on why this is fine on my own machine? (tested on a generalised dynamic_sample_occurrences form). Works even when occurrence attribute values and occurrence images are submitted as part of the sample.

**Comment by johnvanbreda** [comment]
@andrewvanbreda I think the problem is specific to training mode on forms that allow a sample to be added first, then the occurrences dynamically added on the fly afterwards. This means the normal transect walk data entry form but not other more standard data entry forms.

**Comment by johnvanbreda** [comment]
I used this query to look at the values in the various sequences:
```sql
select schemaname as schema, 
       sequencename as sequence, 
       last_value
from pg_sequences
order by last_value desc nulls last
```

The value mentioned in the original posted error is 353677370. This can only have come from the audit.logged_actions sequence which now stands at 353908785. There have been no intentional changes to the audit module recently so I don't know why this value is being retrieved or from where.

**Comment by JimBacon** [comment]
Effectively a duplicate of https://github.com/Indicia-Team/warehouse/issues/493
