### ISSUE TITLE
Saving walks without providing mandatory (Reliability) data

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#63]
e.g. http://live-butterfly-monitoring.pantheonsite.io/ebms-input-data?sample_id=11570

This transect walk was saved without mandatory data being entered (for Reliability value).

![p](https://user-images.githubusercontent.com/2699478/57434261-83ff7900-7232-11e9-9d4b-6ffcc2933f16.png)

**Comment by Gary-van-Breda** [comment]
Code change deployed, which sets the default reliability as defined in #64 for every section sample. If an attempt is made to change this to a blank value, it is not saved.

**Comment by DavidRoy** [comment]
When tested, the form does still save but reverts to the default value of 1.  With #64 implemented, this issue can be closed
