### ISSUE TITLE
Add New Zealand 

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#640]
- [x]  add taxon attribute for New Zealand
- [x]  add New Zealand as scheme on butterfly-monitoring.net
- [x]  add Māori as additional language
- [x]  import species list into warehouse
- [x]  make list available in the ButterflyCount app
- [x]  add additional photos and species descriptions to the app

**Comment by DavidRoy** [comment]
[List of NZ butterflies.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/13332362/List.of.NZ.butterflies.xlsx)

**Comment by johnvanbreda** [comment]
- Added taxon attribute for NZ to list 251.
- Added Māori language.
- Used warehouse UI to link 4 existing taxa to NS (code P=Present):
  - Lycaena
  - Lampides boeticus
  - Limenitis glorifica (plus added Honshu White Admiral as English common name)
  - Pieris rapae (plus added pepe me as common name for mri).

I've reformatted a spreadsheet for the import of the new names.

@DavidRoy any preference for the format of keys that I generate for these names? E.g. NZBMS...?

**Comment by DavidRoy** [comment]
@johnvanbreda that works, thanks

**Comment by johnvanbreda** [comment]
I've added the list changes now. There are still some tasks on the list above I've not touched.

@JimBacon with the new infrastructure, do you have a "recipe" for updating the taxa.yml and taxon_paths.yml files used by Logstash to lookup taxon details?

**Comment by JimBacon** [comment]
I have SSH access to the Elastic Stack so I would aim to do something like `scp taxa.yml elastic:/etc/logstash/data`.
(I have a .ssh/config file which allows me to abbreviate the server details)
Does that sound like an option for you?
If so, I will need to put in a request to IT as we don't have permissions to do that currently.
