### ISSUE TITLE
Add Nigeria

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#641]
- [x]  add taxon attribute for Nigeria
- [x]  add Nigeria as scheme on butterfly-monitoring.net
- [x]  import species list into warehouse
- [x]  make list available in the ButterflyCount app

**Comment by DavidRoy** [comment]
[Butterflies  AFRICA LIST - JULY 2023 as amended for iNat-Nigeria.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/13600151/Butterflies.AFRICA.LIST.-.JULY.2023.as.amended.for.iNat-Nigeria.xlsx)

Species for Africa indicated by spreadsheet column

**Comment by johnvanbreda** [comment]
@DavidRoy any preference for keys generated for names that need to be added? E.g. ABMS-NG...?

**Comment by DavidRoy** [comment]
@johnvanbreda yes, thanks

**Comment by johnvanbreda** [comment]
Importing the species - 
- created a temporary table with the family, subfamily, taxon and common name
- checked that all families already present (ok)
- checked that all subfamilies already present (Katreinidae and Pseudopontiinae were added manually)
- created an import file by comparing the temp table with the EBMS list to find missing genera and imported 107.
- created an import file by comparing the temp table with the EBMS list to find missing species and imported 1223, linking them to Nigeria via the attribute.
- updated the keys

All done apart from adding the scheme and work required in the app.

**Comment by DavidRoy** [comment]
@johnvanbreda let us know when the species list is ready for @kazlauskis to bring into the app

**Comment by johnvanbreda** [comment]
@DavidRoy - sorry, didn't make myself clear, the list is loaded into the warehouse now, ready to import into the app.

**Comment by DavidRoy** [comment]
@kazlauskis can you update the app to include Nigeria.  Also New Zealand #640
