### ISSUE TITLE
Download pages not working after migration

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#644]
@andrewvanbreda @DavidRoy 

Checking some of the website pages and from reports of coordinators, the connection with Elastic Search is not working properly for some pages:

- [x] My download https://butterfly-monitoring.net/mydata/downloads 
I downloaded my 15min counts, I have in total 158 samples of 15-minute counts, and in the download file there are 148 samples, 10 samples are missing. The visualization checking with my account and Chris's account looks correct. This is the file downloaded [my15mincount_samples23112023.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/13452002/my15mincount_samples23112023.csv)
For the transect downloads is happening the same, see more below. 

- [x] Downloads 
I downloaded all the sample data of transects and checked for a transect they are asking me to download all the data for this year. 
[Montesion_samples.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/13452235/Montesion_samples.xlsx)
The user, ID 246551, did 13 visits to the transect MONTESION transect code EBMS:España:5 and in the download file only 8 visits are shown: 
1. 14/03/2023
2. 04/04/2023
3. 25/04/2023
4. 18/05/2023
5. 04/06/2023
6. 31/08/2023
7. 19/09/2023
8. 03/10/2023

Missing visits for the dates 22/06, 4/07, 16/07, 30/07, 17/08 of 2023
I mascaraed as this user and downloaded his transect samples from My downloads page and it happened almost the same, now 9 visits were downloaded when there should have been 13 (04/07/2023 new visit added). This user is a regional coordinator, so I don't think he had the training mode on. The sample file downloaded from the user 
[allsamplesNacho_23112023.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/13452257/allsamplesNacho_23112023.csv)

This problem with downloading a lot of data from Downloads was mentioned before #527 I think downloading massive data in general always gives problems and a complete download never happens. Maybe we need to consider applying filters, in the majority of the cases the coordinators want data for this year, and not all the years together and maybe for a determined number of transects reducing the records. 

I didn't check for moth data, but I don't know how to check it. 

I hope all these descriptions are useful.

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja
Thanks for the feedback.
I think this might be because the Elastic Search indexes are being rebuilt (rather than a website code failure).

@DavidRoy will probably be able to confirm if that task is still ongoing.

If that is the case I think it might be a case of waiting.

**Comment by JimBacon** [comment]
The indexes are rebuilt. @CrisSevilleja If you are able to test this again I would be very grateful.

**Comment by CrisSevilleja** [comment]
I checked this example and now the downloads are working from My download page well. thank you
