### ISSUE TITLE
SHP format GIS section Download - error message

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/ABLE#647]
### Describe the issue

the here below message when trying to download SHP format sections 
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<ServiceExceptionReport version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wfs/1.0.0/OGC-exception.xsd">
<ServiceException>
Error occurred getting featuresUnable to obtain connection: Cannot create PoolableConnectionFactory (Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.) Cannot create PoolableConnectionFactory (Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.) Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. Connection refused (Connection refused)
</ServiceException>
</ServiceExceptionReport>

### Expected behaviour

a zip folder with an shapefile

### To Reproduce

from the scheme "scheme admin" part, then "scheme sites"
https://butterfly-monitoring.net/scheme-sites

### App Version

firefox 115.5.0 ESR 64bit

### When did this happen

today

**Comment by JimBacon** [comment]
That should be fixed now.

[For reference, the indicia:ukbms store on GeoServer had not been configured with the new database connection details.]

**Comment by xaviermestdagh** [comment]
indeed, thanks!
