### ISSUE TITLE
File upload menu missing from http://live-butterfly-monitoring.pantheonsite.io/mydata

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#65]
@xaviermestdagh reports that 'File upload' is missing from new site for his account.

![p png](https://user-images.githubusercontent.com/2699478/57434460-f2dcd200-7232-11e9-9753-1cfa13405579.gif)

**Comment by Gary-van-Breda** [comment]
Think this is now sorted.
Available for Administrator, scheme coordinators and supermanagers.
Had some oddities with menu permissions whilst setting up, but I think it is OK now.

We don't have the Downloads either: do you want this added?

**Comment by DavidRoy** [comment]
Let's discuss the function of these two menus

**Comment by DavidRoy** [comment]
Closing as menu changes implemented.  Will raise other navigation changes via specific issues
