### ISSUE TITLE
Photo recognition for moths not working

### ISSUE THREAD

**Issue by Helder-Cardos** [BiologicalRecordsCentre/ABLE#651]
### Describe the issue

The photo recognition used to help identify moths inside the app, is not working correctly. Gives back "unknown" for all species. This feature was working fairly well, until a few weeks ago. 

### App Version

v1.23.0 (299)

**Comment by kazlauskis** [comment]
@JimBacon the app receives a `500` response from the classifier proxy. Do you know anything about it?

From the website [logs](https://butterfly-monitoring.net/admin/reports/dblog/event/203732):
```
Error: Call to undefined function GuzzleHttp\Psr7\_caseless_remove() in Drupal\api_proxy_waarneming\Plugin\api_proxy\ApiProxyWaarneming->calculateHeaders() (line 134 of /code/web/modules/custom/api_proxy_waarneming/src/Plugin/api_proxy/ApiProxyWaarneming.php).
```

**Comment by JimBacon** [comment]
I reckon the upgrade to Drupal 10 resulted in an upgrade to the GuzzleHttp\Psr7 library. This function was removed between the v1 branch and the v2 branch that we are now using. Think it should be an easy fix.

**Comment by JimBacon** [comment]
@kazlauskis I found we fixed this module over a year ago but hadn't deployed the latest version to this site. I have done so now. Can you confirm the app now works and close the issue if okay?

**Comment by Helder-Cardos** [comment]
@JimBacon  just tested it with several species, and it seems to be working fine! Thank you.
