### ISSUE TITLE
Walk species data entry not working

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/ABLE#652]
@DavidRoy 
I have had a report from Japan and my own experimentation is showing the Walk data entry is now failing, possibly after a clash between Ajax and a Drupal upgrade last week.
Let me know if you want the site put in maintenance mode while this issue is outstanding.
(I am not sure if you prefer the site to be left online for people to access other areas)

**Comment by DavidRoy** [comment]
@andrewvanbreda if you can look at it as a priority we can leave the site out of maintenance so that the rest of the functionality is available. Thanks

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Awaiting feedback from John who is already working on similar fixes in general Indicia code.

**Comment by johnvanbreda** [comment]
@andrewvanbreda I've committed my fixes but not rolled anything out yet - will contact Biren about that in a moment. If you need to replicate the fixes in the custom code, then the fixes are:
https://github.com/Indicia-Team/drupal-8-module-iform/commit/813a5cef6361288ffa7c139bdd6765f2164f3beb
https://github.com/Indicia-Team/client_helpers/commit/4f835a7c94692466c4a7cabec24c2605a1ef06cc

You can see in that second commit that the functions in the prebuilt forms called ajax_* have been changed. Previously they echoed the responses but this no longer works. They must now return the response to the iform controller which will return the response as a proper Drupal response object to the AJAX request in the JavaScript. 

Note the response your ajax_* functions return can either be an array (which gets converted to a JSON AJAX response) or a string (which gets sent as it is).

**Comment by andrewvanbreda** [comment]
@johnvanbreda Thanks for info

@BirenRathod
As we can't yet just do a straight iform/client_helpers update on EBMS/UKBMS I will apply John's changes to those 2 sites manually and change custom code if needed.
(I am aware EBMS is broken, but UKBMS is not showing obvious trouble)

**Comment by BirenRathod** [comment]
@andrewvanbreda all I suggest is to let me first roll out the John's latest release on all sites. if you still don't see those on both sites you can then start implementing it. is that ok?

**Comment by andrewvanbreda** [comment]
@BirenRathod
But we can't roll out client_helpers changes onto EBMS/UKBMS unless it is just a merge of code line changes and not actually overwriting any files.

**Comment by BirenRathod** [comment]
@andrewvanbreda what I mean is once I update the upstream, John's changes will be available on all sites including EBMS/UKBMS sites too.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
OK, well do whatever you need to do, as long as files are not overwritten on EBMS/UKBMS from the Indicia-Team client_helpers repository.
If John's changed lines can be merged into the existing files on the EBMS/UKBMS sites, that is fine.

**Comment by johnvanbreda** [comment]
I don't think it will do a merge. Presumably UKBMS and EBMS are using custom versions of the iform module so cannot be using the upstream? Therefore you'll need to manually apply my changes, plus any additional ones of your own.

**Comment by andrewvanbreda** [comment]
@johnvanbreda @BirenRathod 
For EBMS I have created a multidev with the changes which can be merged once I have tested them. I can do the same for UKBMS after lunch.

**Comment by BirenRathod** [comment]
@andrewvanbreda & @johnvanbreda the upstream that I released had updated on both sites yesterday, so it will be the same as today too. 
If those files are the same as John's changes and if you have made changes after my release then you need to create a multidev site.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Ok. Well if same as yesterday got ahead and I will examine the sites after.
Let me know when you are done.

**Comment by BirenRathod** [comment]
@andrewvanbreda & @johnvanbreda All sites now updated with latest release of iForm module.

@andrewvanbreda Just for the safe side, I have created a multidev site of ukbms for you.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
OK thanks for doing this.
The problem I was seeing this morning that I considered a failure does indeed appear to have been fixed now.
I will email you about the exact nature of the updates that have been done so I understand if there are likely to be any knock-on effects of these.

**Comment by andrewvanbreda** [comment]
Closing.
Have received a useful description from Biren over email about what he did regarding this, and I don't think any customisations for EBMS/UKBMS would of been overwritten.
Have double-checked some at risk areas such as Annual Report and seem fine.

**Comment by andrewvanbreda** [comment]
Japan have reported continued problems with data entry

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
I have fixed EBMS. 
There were some further changes needed specifically for this website.
While I have adjusted all the required code as far as I can tell, some of the changes are in areas I cannot test (such as site allocation), so there is a slight risk there could still be issues. 
I think it is likely that area is working though as the changes are just the same as elsewhere. It will be obvious if it is broken.....it won't be wrong, it just won't work at all.
Please leave issue open for now, as I will need to double check UKBMS and Spring again.

**Comment by andrewvanbreda** [comment]
Have had confirmation from Japan that EBMS is now working for them.

Have also applied the required changes to UKBMS' project specfic code.
Have done the same for SPRING.

I have checked the following projects and I don't think any project specific changes are required.

NPMS
Plant Portal
UKPoMS
FIT Count
