### ISSUE TITLE
Implement long term Ajax Forms Drupal 10 fix

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/ABLE#653]
Hi @BirenRathod,

I am adding this issue to ABLE but actually this affects other projects too.

Do you remember during the Drupal 10 upgrades we had a problem with Ajax Form where we were getting errors like "function ajaxSubmit not found" (or similar).
I put in a temporary solution to add "core/internal.jquery.form" into iform.libraries.yml

I have now looked into this and discussed my findings with John.
The solution is 

1.
All prebuilt forms that use Ajax Forms must call the following line
data_entry_helper::add_resource('jquery_form');
(This is probably best added to the get_form function inside the file).

2. I will remove the core/jquery.form dependency from iform.libraries.yml (including removing the temporary solution core/internal.jquery.form)

3. I will remove the reference to 'jquery_form' in the $_iform_base_resources variable found in iform.module.

I will deal be dealing with altering indicia-team/iform for points 2 & 3 so those changes will just come in with an iForm update.

However point 1 needs doing first. 
I have done some tests and we can add that line to prebuilt forms even before 2 and 3 are done.

As some project specific prebuilt_forms are now only in Pantheon, I might need your help with this.

I can do point 1 for SPRING/EBMS/UKBMS
However I do not know about all projects or have access to all projects, so you might need to add that add_resource line to prebuilt forms for other projects.
Note: You only need to do this if the prebuilt form is ONLY in Pantheon and NOT in indicia-team/client_helpers.
(otherwise the required changes will come through with the next iForm update)

An example project I think you said you had problems with was Bee Walk (I think that was the name of the project if I remember correctly).
Does that project have any indicia prebuilt forms that are only in Pantheon that you need to add the add_resource line to?

Once that line is added to the required prebuilt forms, I will change indicia-team iForm module for points 1 & 2 so that those changes come though with the next iForm update.

As I say, I will do this for Spring/EBMS/UKBMS, but you will have to let me know thoughts for other projects.

**Comment by BirenRathod** [comment]
@andrewvanbreda If you are going to make changes to iForm module using submodules here -> https://github.com/Indicia-Team/drupal-8-module-iform then I can use that and roll out changes to all sites. That way you don't need to make changes on SPRING/EBMS/UKBMS and it doesn't have to be repetitive work.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
I will email you about this so this thread doesn't get too long.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
In response to the email you just sent me clarifying that you were talking about client_helpers/media.

For the iForm parts of this issue (point 2 & 3) above I will put them in  https://github.com/Indicia-Team/drupal-8-module-iform as suggested by you.
You will then be able to pull the changes into all projects.

For point 1 (adding the add_resource line to prebuilt forms)
For any general forms Indicia forms I will indeed put the changes in https://github.com/Indicia-Team/client_helpers so that you can pull the changes to all projects in the same way.

However going back to my original notes.
Some projects have custom prebuilt forms that only appear in Pantheon and have been taken out of https://github.com/Indicia-Team/client_helpers

So for a precise example, I will need to change the following file
ukbms_sectioned_transects_edit_transect_2.php
by adding the following line to the get_form function
data_entry_helper::add_resource('jquery_form');

Notice this file only appears in brc-ukbms-d10 and not in the indicia-team client_helpers.

I can deal with this for projects I have access to, but if there are similar situations for projects I don't have access to you will need to deal with this.

If you are unsure, you coud send me a list of pages you encountered the Ajax Submit error (or similar) on when we were doing the Drupal 10 migration, and I will instruct you from there.

**Comment by BirenRathod** [comment]
@andrewvanbreda  As long as I'm aware, they all have got prebuilt_forms included. So that specific example is for UKBMS & EBMS or may be poms.

**Comment by BirenRathod** [comment]
@andrewvanbreda on the other note, if you add those files in the client_helpers/prebuilt_forms folder, would that be a problem using this [repo](https://github.com/Indicia-Team/drupal-8-module-iform)? then you don't need to update individually

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Yes this would be a problem for 2 reason I can think of

1. It was agreed quite a while ago in discussions (which included John) to streamline the main Indicia-team repositories and to remove prebuilt forms which are meant for specific projects

2. EBMSUKBMS currently uses some prebuilt forms which have the same name between the projects, but the code is different in the files! (this is not ideal! and something am working to rectify)

**Comment by BirenRathod** [comment]
@andrewvanbreda I know they agreed but still, prebuilt_forms are available on all websites. about specific code related to EBMS/UBMS, you can still make changes. The changes mentioned above could be useful for all websites/projects so keeping them in one repository is fine. 

Anyway, whatever you decide, we go from there. That was just thought I expressed.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
This is all done now.
I have checked and prepared EBMS/UKBMS/UKPoMS/SPRING
The relevant commits have been made to iform/client_helpers Develop.

There is no need to do anything at all, as the sites are already prepared for the background changes made to client_helpers/iform, so next time updates are done there, will be no visible effect to the sites.
