### ISSUE TITLE
Modification to New Zealand setup for app

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#654]
- [x] Guide.  Edit L. boeticus account for guide. Replace "The main foodplant is Bladder Senna (Colutea arborescens)." with "The main foodplants are Fabaceae species, e.g. Bladder Senna (Colutea arborescens)."
- [x] Remove two subspecies. Vanessa gonerilla gonerilla and Vanessa gonerilla ida

**Comment by kazlauskis** [comment]
I've done these now. The new version will go live soon.
