### ISSUE TITLE
Source language changed on Explore online data page  - eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#655]
I realised on the Explore online data page https://butterfly-monitoring.net/elastic/all-records that the source language has changed for some filters, applying even for already translated terms. Now the first and second filters appear in German when they should be in English.

![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/1951720e-0fca-4c22-8d69-ac30064e8702)

I tried to check this on the Configuration - Regional Language- User interface translation and the source language cannot be changed there, so I don't know how to correct it. Any idea @JimBacon ? Thanks in advance!

**Comment by JimBacon** [comment]
If you edit the page iteself and look at the Form Structure section I can see the German has been written in here. I don't know why.

![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/2545390/5f49aef6-d6b9-4f53-96b5-3e67a5f9ae44)

You can change this back to English.

**Comment by CrisSevilleja** [comment]
thank you @JimBacon for the explanation. I will tell my German translators not to change those parts. 
Now it is back to English.
