### ISSUE TITLE
Add moth species

### ISSUE THREAD

**Issue by Joao-Nunes-Moths** [BiologicalRecordsCentre/ABLE#656]
Hello,

Can we add this missing species to eBMS:

Agonopterix olusatri Corley & Buchner, 2019

It would be also useful to add Cryphia algae/pallida. It is a common pair in Iberian Peninsula which only can be safely identified after dissection.

Thank you.

**Comment by kazlauskis** [comment]
@Joao-Nunes-Moths Thanks for creating the issue here. 

I will leave it to @DavidRoy @CrisSevilleja to prioritise. Species dictionary changes would need to be done in the warehouse first.

**Comment by DavidRoy** [comment]
@andrewvanbreda could you add this moth species and aggregate to the eBMS moth list please

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy,

Have done that now.

Note that the "Accepted name unique identifier (external key)" and "Taxon name unique identifier (search code)" fields are empty on the new entries.

Also a field called "Name form" is also empty 
(which is described as "For internal use by scripts which sync names from other databases")
I notice other entries seem to have this filled in as "W" which I can add to the new entries if you want me to.

I guess close if you are happy

**Comment by DavidRoy** [comment]
Thanks @andrewvanbreda. Let's leave open until @kazlauskis has updated the app with the new name

@Joao-Nunes-Moths do you tend to use the app or website to enter your moth records? Could you test via the website as the change should be immediate

**Comment by Joao-Nunes-Moths** [comment]
Ideally, both the app and website, but for now the latter is OK. The new name is already available in the website. Thank you!

**Comment by kazlauskis** [comment]
It's done now and will be available in v1.24.3 this week.

**Comment by Joao-Nunes-Moths** [comment]
Hi @andrewvanbreda,

Can you also add this species?

TORTRICIDAE
Pseudococcyx friedmariana Larsen, 2020

Thank you.

**Comment by andrewvanbreda** [comment]
Hi @Joao-Nunes-Moths 
I have added this to the database (Warehouse), it may take a little time to appear on the website.
I think @kazlauskis would need to add it to the app.

If anyone wants to add any extra information to the new entry, it is here,
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/629215

**Comment by kazlauskis** [comment]
I've pulled this into the app now, it will be ready in the next release later this month.

**Comment by Joao-Nunes-Moths** [comment]
Hi @andrewvanbreda,

Can you also add this species?

Oecophoridae
Pleurota andalusica Back, 1973 

Thank you.

**Comment by andrewvanbreda** [comment]
Hi @Joao-Nunes-Moths 
Have added this now
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/636757

**Comment by Joao-Nunes-Moths** [comment]
Hi @andrewvanbreda,

Can you also add this species?

Erebidae
Eublemma baccatrix Hacker, 2019

Thank you.

**Comment by andrewvanbreda** [comment]
Hi @Joao-Nunes-Moths,
This has been added.

https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/636913

**Comment by Joao-Nunes-Moths** [comment]
Hi @andrewvanbreda ,

Can you also add this species?

Tortricidae
Eucosma subvittana (Staudinger 1892)

Thank you

**Comment by andrewvanbreda** [comment]
Hi @Joao-Nunes-Moths ,

I have added the species to the database here,
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/637959

**Comment by Joao-Nunes-Moths** [comment]
Hi @andrewvanbreda  ,

Can you also add this species?

Gelechiidae
Metzneria neli Huemer, 2021

Thank you

**Comment by andrewvanbreda** [comment]
Hi @Joao-Nunes-Moths 
Yes, I will just finish off my current task, then I will do that.
I will let you know once done.

**Comment by andrewvanbreda** [comment]
Hi @Joao-Nunes-Moths,
I have added to the database here,
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/644790

**Comment by Joao-Nunes-Moths** [comment]
Hi @andrewvanbreda,

Sorry to keep asking you for adding species...

Now is Apatema proteroclina (Meyrick, 1938)

Thank you.

**Comment by andrewvanbreda** [comment]
Hi @Joao-Nunes-Moths,
No worries, it is fine. I have done that now.
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/644944

**Comment by Joao-Nunes-Moths** [comment]
Hi @andrewvanbreda,

Can you add Merulempista azrouella (Lucas, 1933)?

Thank you.

**Comment by andrewvanbreda** [comment]
Hi @Joao-Nunes-Moths,
That has been added now.

**Comment by Joao-Nunes-Moths** [comment]
Thank you @andrewvanbreda . All of these species are strictly nocturnal.
