### ISSUE TITLE
Issue: Moth trap locations have disappeared from the App

### ISSUE THREAD

**Issue by Helder-Cardos** [BiologicalRecordsCentre/ABLE#657]
### Describe the issue

The stored locations for moth traps on the App have disappeared, showing the message "You do not have any moth traps yet".

I have checked my own app, after a user reported that he could not see the moth trap location on the app that he created on the website.

### App Version

1.24.1(309)

**Comment by kazlauskis** [comment]
@Helder-Cardos this was fixed now. Thanks for reporting it!

**Comment by Helder-Cardos** [comment]
Thank you!
