### ISSUE TITLE
Add Projects functionality

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#662]
![Screenshot 2024-03-13 at 14 42 44](https://github.com/BiologicalRecordsCentre/ABLE/assets/7383162/c7dcb249-2d3c-4423-af40-fbbb70e425ea)

**Comment by kazlauskis** [comment]
The way we have implemented this:

https://github.com/BiologicalRecordsCentre/ABLE/assets/7383162/99090338-725d-4bd7-95cb-a6668e26a97b

**Comment by CrisSevilleja** [comment]
Hi @kazlauskis really nice functionality. I am sure many users will like this. 
I think the video is pretty clear on searching and joining projects. Just one thing that would be useful is a search button on All projects page, in case many different projects are registered. For the rest, I think it is pretty good.

**Comment by kazlauskis** [comment]
This functionality is now done and will come out in v1.25.0 shortly.
