### ISSUE TITLE
Add fixed sites functionality

### ISSUE THREAD

**Issue by kazlauskis** [BiologicalRecordsCentre/ABLE#663]
![Screenshot 2024-03-13 at 14 44 18](https://github.com/BiologicalRecordsCentre/ABLE/assets/7383162/18feba63-85fa-4308-9666-22a853d24ea1)

**Comment by chrisvanswaay** [comment]
Is the idea that you can use this to recount 15-minute counts? Either from yourself, or from others who have made their counts open? Because that would be a great feature.

**Comment by larspett** [comment]
Is this the same feature that we have been requesting before? I believe there should be an old issue about that since that is what has been keeping sebms from using the feature more widely.  Ping @DavidRoy

**Comment by DavidRoy** [comment]
@chrisvanswaay - yes, that's the idea. Would appreciate your help with testing
@larspett - potentially meets your previsous issue. Let's see when you test it out. https://github.com/BiologicalRecordsCentre/ABLE/issues/241

This and #662 is being funded by a separate Horizon project

**Comment by chrisvanswaay** [comment]
@DavidRoy Sure, happy to test. This could be a great addition.

**Comment by kazlauskis** [comment]
Yes, people will be able to do repeated 15-minute counts using fixed site locations. However, we need to tie the fixed sites to projects (see #662). So, in this first iteration, users will only be able to select a site that is part of a project that they can set on the website.

As a bonus, we are also implementing a pre-defined species list option for the fixed sites.

**Comment by larspett** [comment]
Same here @Roy, ***@***.***> @Karolis ***@***.***> (but I need the beta then)

**Comment by kazlauskis** [comment]
This is how we have implemented this:
https://github.com/BiologicalRecordsCentre/ABLE/assets/7383162/d957726b-2127-4871-85d0-adecc9c85bf2

**Comment by kazlauskis** [comment]
https://github.com/BiologicalRecordsCentre/ABLE/assets/7383162/a6de41a7-3a91-4577-bfb3-f72c0e3effa4

**Comment by CrisSevilleja** [comment]
Hi @kazlauskis so nice new functionality. Could I use this video to upload it to BCE YouTube channel to explain this new functionality? in that case, I don't need to reproduce it again, but feel free to say no.

**Comment by larspett** [comment]
The video doesn't seem to load here?

**Comment by kazlauskis** [comment]
Are you using Firefox? Try using a Chrome browser.

**Comment by larspett** [comment]
Chrome

22 apr. 2024 kl. 16:47 skrev Karolis Kazlauskis ***@***.***>:

﻿

Are you using Firefox? Try using a Chrome browser.

**Comment by larspett** [comment]
But I was in the github app, thought that would be most likely to work

22 apr. 2024 kl. 16:47 skrev Karolis Kazlauskis ***@***.***>:

﻿

Are you using Firefox? Try using a Chrome browser.

**Comment by larspett** [comment]
Logged into chrome now. Same thing here, inactivated video icon

**Comment by kazlauskis** [comment]
https://github.com/BiologicalRecordsCentre/ABLE/assets/7383162/05c53c51-e1cb-42c3-8eec-c6d24522d45a

**Comment by kazlauskis** [comment]
@larspett try the video above.

**Comment by larspett** [comment]
Hi this one works, thx. BTW are projects available for moth data input  too?

22 apr. 2024 kl. 17:07 skrev Karolis Kazlauskis ***@***.***>:

﻿

@larspett<https://github.com/larspett> try the video above.

**Comment by kazlauskis** [comment]
At the moment, this is implemented only for 15-minute count surveys, which allow recording moths. If you mean the Moth trap survey, then no, this isn't part of it yet.

**Comment by larspett** [comment]
Ok. Would it be a major thing to add it to the moth trap counts? Would it need funding? We might be able to fund that plus a couple of moth trap tweaks.

**Comment by kazlauskis** [comment]
Yes, it would require some extra funding, but now that we have it as part of the app, it wouldn't be very difficult to add the 'projects' to other surveys too. I don't know what implications this would have for the website where users will be setting up the projects.

**Comment by larspett** [comment]
Ok. Could you or someone get a guesstimate? We could most likely commit to funding this.

**Comment by kazlauskis** [comment]
@larspett David is doing the time estimates for the moth projects. I am closing this site's task as done now.

**Comment by jellevanzweden** [comment]
> Is the idea that you can use this to recount 15-minute counts? Either from yourself, or from others who have made their counts open? Because that would be a great feature.

Hi, I'm clearly a bit late with responding to this, but I still wanted to remark something about the prioritisation of sites. Since, it says in the drawing "sites sorted by distance to the user", but I think it would be great if you could also incorporate priority rules and highlight sites with higher priority. For example "high priority for sites that have already been counted this season" or "extra high priority for sites that were counted the day before" or "low priority for sites that were counted last year but increasing priority with time to last count" or ... Incorporating such highlighted sites gives the benefit that you end up with a more balanced dataset and facilitates the statistical modelling done afterwards.
