### ISSUE TITLE
Reporting and totalling of Non Adult species counts

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/ABLE#669]
Also from András Szabadfalvi:
"
#2  it is odd that when totalling the counts other life stages (e.g. eggs, larval webs etc.) are also included >> they should not (i think this oddity must have come from the app's development to accommodate other life stages.
"

There is currently no special processing associated with Life stage on the Walk data entry page, My sites/visit summary, Annual Summary, Year Plot or Section plot.

@DavidRoy Can you confirm:
1) whether the column and row totals on the species data entry page should include non-adult counts, on schemes where life stage is present.
2) whether the species count information on the My sites/visit summary page should include non-adult counts, where life stage is present.
3) whether the values generated by the warehouse summariser module (and displayed in the Annual report and Year Plot [count] pages) should include non-adult counts, where life stage is present.
4) whether the count information on the My Section plot page should include non-adult counts, where life stage is present.

**Comment by DavidRoy** [comment]
@Gary-van-Breda I don't agree with Andras on this. If other stages are recorded, it's for a reason, so reports should include all stage information.  Recording other stages is a rare event in any case

**Comment by Gary-van-Breda** [comment]
OK - in which case we leave as is.
Closing this issue - no action required.
