### ISSUE TITLE
Implement Satellite Map Site Details page

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#67]
- would it be possible to include the Satellite map in the Site Details Page?

When a volunteer draws a transect it would be a good help to have both, Openstreetmap and Satellite Map 
@DavidRoy  @GPowney

**Comment by Gary-van-Breda** [comment]
I have added the Google Hybrid (satellite plus features) layer to the site details page.

**Comment by DavidRoy** [comment]
Looks good to me. @CrisSevilleja please close this issue if you agree

**Comment by CrisSevilleja** [comment]
Yes,  it is okay for me
