### ISSUE TITLE
import Montserrat butterfly list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#672]
- [x]  add taxon attribute for Montserrat
- [x]  add Montserrat as scheme on butterfly-monitoring.net
- [x]  import species list into warehouse
- [x]  make list available in the ButterflyCount app

[Butterfly species list Apr24_MB_V2.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/14969818/Butterfly.species.list.Apr24_MB_V2.xlsx)

@andrewvanbreda are you able to take this on?

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
I would thinks so.
However unlike the Anguilla import, I am having trouble downloading the attached "Butterfly species list Apr24_MB_V2.xlsx" file, it is saying it is 0 bytes and won't open.

**Comment by DavidRoy** [comment]
That's odd. Trying again
[Butterfly species list Apr24_MB_V2.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/14975882/Butterfly.species.list.Apr24_MB_V2.xlsx)

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Yes that second link is fine thanks.
(the first one is still broken so I do not understand either)

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy ,

Note the questions here also cover this issue which is similar
https://github.com/BiologicalRecordsCentre/ABLE/issues/673

I have added attributes here (Anguilla and Montserrat).

https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list_attribute/edit/203
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list_attribute/edit/204

1 (@Gary-van-Breda).
Are either of you able to confirm the official way to add a scheme to EBMS, it is unclear to me after examining the system.

2.
David:
As noted, I have added the above attributes which point at this termlist
https://warehouse1.indicia.org.uk/index.php/termlist/edit/816

The termlist description gives these options
A: Absent
P: Present
P?: Possibly present
M: Regular migrant
I: Irregular vagrant
Ex: Regionally extinct

Am I correct in thinking that we just want to import every species onto the "P" option (For Montserrat too?)

3. The Montserrat list has a distribution column. Is this to be imported?
If so, are you able to provide information on what you want me to do regarding this (i.e should I add an attribute and termlist? Could you give explanation of the terms which are currently acronyms if you want them imported)

4. The Montserrat list has two latin name columns?
What are you wanting done with these? In most cases these are the same, but there are differences e.g. line 2 has "Danaus plexippus ssp. megalippe" as well as "Danaus plexippus megalippe"

5. For the Anguilla list, are you wanting the comment column imported?
If so, I think that would need a new attribute, or the description field could be used.

Thanks

Andy

**Comment by DavidRoy** [comment]
@andrewvanbreda I can add the new scheme to the eBMS website
In answer to your other questions.
- use the species name column 'Binomial (conctenated from genus and species columns)'
- please use 'P' for taxon attribute
- for the species list, can you match to taxon list 251 (eBMS butterflies). If the name already exists, please retain but set the taxon attribute = 'P' for montserrat
- ignore the distribution and comment column(s)

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy @kazlauskis 
Montserrat import into Warehouse done (Anguilla done yesterday).
The following files were used for import (common name 2 and 3 added manually afterwards as wasn't sure of process for importing those)

[Genus import.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/15030195/Genus.import.csv)

[Butterfly list to Import for MS.CSV](https://github.com/BiologicalRecordsCentre/ABLE/files/15030196/Butterfly.list.to.Import.for.MS.CSV)

The following species were existing ones (some from the Anguilla import), "P" was added to the Montserrat (MS) presence attribute.

Vanessa cardui 
Dryas iulia
Heliconius charitonia
Hypolimnas misippus
Leptotes cassius
Hemiargus hanno
Eurema elathea
Eurema lisa
Phoebis sennae
Pieris brassicae (also had Large Cabbage Cutworm and Large Cabbage White common names added from spreadsheet)
Polygonus leo
Urbanus proteus
Pyrgus oileus
Ephyriades arcas

**Comment by kazlauskis** [comment]
I've added this to the app now. It will be available in v1.26.0.
