### ISSUE TITLE
Import Anguilla species list

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#673]
- [x]  add taxon attribute for Anguilla
- [x]  add Anguilla as scheme on butterfly-monitoring.net
- [x]  import species list into warehouse
- [x]  make list available in the ButterflyCount app

[butterflies of anguilla.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/14969822/butterflies.of.anguilla.xlsx)

@andrewvanbreda are you able to take this on?

**Comment by andrewvanbreda** [comment]
@DavidRoy 
Yes I can do this, and will consult with Karolis/Gary as required.

**Comment by kazlauskis** [comment]
@andrewvanbreda, I am trying to wrap up the current ButterflyCount update I am working on, and it would be great if I could include the new species, as I don't know when I'll be working on the next release. Do you know when the species list for Anguilla and Montserrat will be ready?

**Comment by andrewvanbreda** [comment]
@kazlauskis 
Next on my list. I hope will not be too difficult.
I am hoping at least one of them will be done today (assuming nothing unexpected).

**Comment by andrewvanbreda** [comment]
@kazlauskis 
I have done the Anguilla import.
Monteserrat not done yet, but I would think I can do tomorrow if similar difficulty.

In case of problems import files attached below (noting the Common Name 2 & 3 columns were done as manual edits as was unsure how to import).

[Genus import 1.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/15014780/Genus.import.1.csv)
[Genus import 2.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/15014781/Genus.import.2.csv)


[butterflies_of_anguilla 1.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/15014761/butterflies_of_anguilla.1.csv)
[butterflies_of_anguilla 2.csv](https://github.com/BiologicalRecordsCentre/ABLE/files/15014762/butterflies_of_anguilla.2.csv)

The following already existed and had "P" (present) added to the Anguilla attribute
Danaus plexippus
Hypolimnas misippus (added common names "False Plain Tiger" and "Common Diadem" which did not exist)
Vanessa cardui

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy
As noted yesterday for Montserrat, I will assume you are adding the scheme as I don't know how.

**Comment by kazlauskis** [comment]
I've added this to the app now. It will be available in v1.26.0.
