### ISSUE TITLE
Regional coordinators role not working in some pages

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#675]
Regional coordinators (from Spain who are using this role) reported they cannot see the pages under Region admin to My region sites https://butterfly-monitoring.net/my-region-sites & My region walkshttps://butterfly-monitoring.net/my-region-walks.

They get an error: _The website encountered an unexpected error. Try again later._
Thye have this issue since several weeks ago. 

I can access to those pages without issue, but unmasqueraded as them I cannot.

**Comment by DavidRoy** [comment]
@Gary-van-Breda can you look into this please

**Comment by Gary-van-Breda** [comment]
The error is caused by the language drop down, which in turn is getting its language list from the translations of the pages - in these cases there is only English and Hungarian translations, not Spanish. I will put a translation request in for all other languages.

**Comment by Gary-van-Breda** [comment]
I have saved Spanish translations of the two regional pages, and masquerading in as Spanish regional Coordinators now shows the page.
If anyone else has the same problem with a different language, it should be fixed when their translations come back.
@CrisSevilleja Are you happy with this?

**Comment by CrisSevilleja** [comment]
yes, @Gary-van-Breda  thank you, I didn't realize the translated page was missing. Now it is working for Spanish regional coordinators.
