### ISSUE TITLE
Add new language to ButterflyCount app: Galician

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#676]
Hello @kazlauskis 
A reminder for including the Galician language in the new version fo the app. The translators already translated everything on Transifex and the language is ready to be implemented. 

Let me know when you do the new release. Thanks!

**Comment by CrisSevilleja** [comment]
Also, update the Spanish language as some terms were not translated correctly. 
I think you mentioned you update all languages in the new app versions, but just in case. Cheers

**Comment by kazlauskis** [comment]
I've done this now, and it will be available in the next app version.
