### ISSUE TITLE
eBMS butterfly taxon list updates (mainly for DE)

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#678]
- [x] Add additional taxa (complexes) and assign to taxon_attribute = 'P' for country = DE
Pontia daplidice/edusa
Aricia agestis/Polyommatus icarus [note - genus aggregate]
Nymphalis polychloros/urticae [note - species aggregate]
Pieris brassicea/Gonepteryx rhamni [note - genus aggregate]

- [x] Assign complex to countries
423519 Pieris napi/rapae. Set taxon_attribute = 'P' for all countries in Europe

379001 Thymelicus lineola/sylvestris. Set taxon_attribute = 'P' for all countries in Europe

- [x] Assign unknown taxa to all countries
416934 Unidentified Blue
416938 Unidentified Browns, Graylings and Ringlets
416935 Unidentified Copper
417367 Unidentified Fritillary
416936 Unidentified Hairstreak

- [x] Add synonyms for each 'unidentified' as 'unknown'

- [x] Add all Genus as 'P' for all Europe countries
Defined as Rank = Genus and external key like 'eBMS'

- [x] Add all Families as 'P' for all countries

**Comment by DavidRoy** [comment]
Linked issue. @johnvanbreda - can you tackle both together
https://github.com/BiologicalRecordsCentre/ABLE/issues/665

**Comment by CrisSevilleja** [comment]
thanks, @DavidRoy for creating this issue, the aggregate names need an update. Should I ask the coordinators which aggregates are necessary for their countries? then we can update this directly for the countries using more eBMS.

**Comment by DavidRoy** [comment]
@CrisSevilleja - yes please

**Comment by johnvanbreda** [comment]
@DavidRoy 

> Add synonyms for each 'unidentified' as 'unknown'

Can I confirm - does this mean that I should add an additional common name 'Unknown Copper' to 'Unidentified Copper' for example, and the same for the other unidentified taxa?

**Comment by johnvanbreda** [comment]
One more question @DavidRoy:
> Add all Genus as 'P' for all Europe countries
Defined as Rank = Genus and external key like 'eBMS'

What about the genera with different or missing keys, e.g. https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/629323?

**Comment by DavidRoy** [comment]
@johnvanbreda yes to synonyms for 'Unidentified....'
The genera without an external key are non-European so can be left off the action for this issue

**Comment by johnvanbreda** [comment]
Thanks David - all done.
