### ISSUE TITLE
ButterflyCount app error in submiting surveys, not showing transects correct and bad connection with the website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#679]
### Describe the issue

Last weekend several users (at least 5) reported issues with the app. This is what she described (Indicia Warehouse User ID
246336):
- it does not load the transects, even updating the latest app version and clicking on update transects. Attached is a screenshot of the error when trying to send them, after a few hours it did send them but they appear as sent in the app but not on the web.

- it doesn't load the sent samples. It doesn't load the map either, it's as if it lost connection with the web user.

- when you try to upload a count it doesn't do it, and the following message appears: "Sorry. Failed to retrieve".

I know that this is happening to two more volunteers in Galicia (Spain), one who wanted to upload counts and another who could not do her transect with the app because it did not appear (and I checked on the web that it was assigned to her).

Cristina: I checked her account and indeed last surveys don't appear from this weekend on the website despite she submitted them. @chrisvanswaay also had issues this weekend submitting and another user in Greece Indicia Warehouse User ID
301776.

### Expected behaviour

submit surveys without error; sent surveys appear on the website and in the sent surveys page of the app and load transects on the app correctly. 

### To Reproduce

1. go to the app
2. start a survey, finishes it
3. submit it to the database

### App Version

v1.26.0 (346)

### Device

MIUI Global 14.0.5, Android

### When did this happen

last weekend

### Screenshots

![image0](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/8d0e4d99-0ff5-44e8-88fd-56cd7d18600e)
![No aparecen censos anteriores enviados](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/22e40e78-6d65-4925-b7cc-376721aaca97)
![No carga mapa](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/811d27d9-9c51-46f5-8331-e231112a9830)
![No sube recuentos](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/fbe05033-212c-4bb9-9601-ab1222c28d26)

### Additional context

I am away this week, please David keep in contact with Chris and Dan who are reporting this issue. I will keep an eye on this but not able to make tests.

**Comment by kazlauskis** [comment]
@CrisSevilleja Is this still the case? 

@johnvanbreda I can see app logs saying that in the ElasticSearch sample index, some sample entries didn't have an `updated_on` timestamp (doc id=25233106, 25233520). That field should always be present, no? Was anything happening to the ES over the weekend?

**Comment by DavidRoy** [comment]
@kazlauskis 
@CrisSevilleja the warehouse had some downtime over the weekend and the ElasticSearch index is behind. Should now be resolved. Can you confirm with the recorder and close if now ok

**Comment by johnvanbreda** [comment]
@kazlauskis those sample docs do have a value in metadata.updated_on - are you not seeing this?

**Comment by CrisSevilleja** [comment]
@DavidRoy @kazlauskis user Indicia Warehouse User ID246336 reported the uploading is working on the app and the surveys appeared as submitted. 

![uploaded working](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/ac6c047a-315b-430c-b787-ef391d94697e)


However, those uploaded surveys are not visible on the website (surveys from 18May) and she cannot see all the transects on the app (27 assigned transects, she is regional coord.) even when the refresh button is clicked. Only these transects are visible:
![transects on the app](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/6430c390-5660-468d-9e9c-da4afdd1bb6b)

**Comment by kazlauskis** [comment]
@johnvanbreda regarding the updated_on, it is present, but for some reason the app's log files show it couldn't find a valid date string attached to this key during the weekend. Maybe that's just a glitch.

**Comment by CrisSevilleja** [comment]
connection with the website is working again and submission is allowed from the app.
