### ISSUE TITLE
In the app, 15min counts, butterfly numbers are multiplied by six when species list copied from previous count

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#680]
@kazlauskis 
This issue only happens when you copy the species list of your previous count. If you see a butterfly species which was already on the list, then sometimes (not always, roughly in 50% of the cases) when you enter this one butterfly, then within a second it changes its number to 6 (six). Always six, never five or seven. See the screenshot below, I made when I had to start to remove five of the six butterflies. They all get exactly the same location, as you can see. Interestingly this only happens with the first, sometimes also the second or third species, so after a few minutes you can use it as always.
The issue occurred for the first time that I noticed last week already, but as I had often poor internet connection I didn't report it earlier and hoped for a new version to make it go away. But today it was still there when I tested as requested by @CrisSevilleja .

Of course this is not just frustrating, but also leads to mistakes (as you don't always notice the number changing to 6, certainly when there are many butterflies around, and this does not happen every time).

Frustrating.

app. v1.26.0 (346) on android 14 on pixel 8.

![Clipboard01](https://github.com/BiologicalRecordsCentre/ABLE/assets/25886005/1e7b5c80-9fcc-49a8-b83c-f3c23667a339)

**Comment by kazlauskis** [comment]
@chrisvanswaay, sorry this is happening. We have upgraded the interface components, and it seems the tapping button has a bug that we'll fix asap.

**Comment by kazlauskis** [comment]
That's done now, it will be fixed in the next app version v1.26.1.

**Comment by chrisvanswaay** [comment]
Thanks


--

Chris van Swaay
De Vlinderstichting
Mennonietenweg 10
Postbus 506
6700 AM  Wageningen

[t] algemeen  (+31) 0317 467346 / direct (+31) 0317 467342

[e] ***@***.******@***.***>
[i] www.vlinderstichting.nl<http://www.vlinderstichting.nl/>
[twitter] www.twitter.com/vlinderNL<http://www.twitter.com/vlinderNL>
[facebook] www.facebook.com/Vlinderstichting<http://www.facebook.com/Vlinderstichting>
[instagram] www.instagram.com/vlinderstichting<http://www.instagram.com/vlinderstichting>
[linkedin] www.linkedin.com/company/vlinderstichting<http://www.linkedin.com/company/vlinderstichting>


________________________________
