### ISSUE TITLE
Not working "View sample detail" button on My samples page eBMS

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#688]
The small button of ¨View sample detail¨ on My samples page https://butterfly-monitoring.net/mydata/samples is not working and shows the message " The website encountered an unexpected error. Try again later." 
![view sample details](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/66ae57a6-5b0f-429f-8fac-ce865eba0cdb)

The user who reported is ID user 245371 with all the recent 15min counts surveys, she is not able to enter the sample page and see her pictures taken on the survey (survey pictures only appear on the page View sample detail and not on Edit sample detail). Some survey IDs: 25943327, 25942890 15min count of 30/05/2024 and 25811305 15min count of 20/05/2024. She has this issue since while ago (middle of May or so).

 I don't have problems using this button in my 15min count samples but I saw another user, Chris van Swaay with the same issue for his 15min counts of June. There was a similar issue with the button "Edit sample detail" #667 but it is working well in this case. 

I assign @andrewvanbreda sorry if you don't have to deal with this.

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
This problem doesn't appear to be widespread.
It is something about the particular account(s) causing the problem, I can see the error in the log but it is not clear what is happening.
It isn't to do with the user role anyway, as have tested that.
I will let you know once I have investigated.

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
I have fixed this for this page.
It is a problem with the way the translations are working.
I have seen this issue before, please leave this issue open and I will close it when I am happy with the situation.
The problem occurs on pages where there is only an English version.
What I have done is create a version of the page for all the languages (even if they are still in English).

I need to check why if this issue has been present before, but the previous action did not fix it for this case.
I suspect that attempts were made to fix it on the whole site, and this page was missed.

**Comment by CrisSevilleja** [comment]
Hi @andrewvanbreda thanks for resolving this. Again the translation... I thought this page was present for all languages... I will try to keep this idea in case happens again on other pages.

**Comment by andrewvanbreda** [comment]
@CrisSevilleja 
To be honest, I think it probably shouldn't need a version for all languages in theory.

I would think it should just default to the English if it can't find a language specific version of the page.
Unfortunately I think the module handling the translation has an oddity/bug/error in it.

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
Am going to close this now as the original issue is fixed.
I will gradually add the different language pages to the site over time, but it is too much to do at once (and too risky in case of issues).
I think completing these will make some of the other Language problems currently on the site a bit better.

There are already two issues raised relating to problems with language on the site
https://github.com/BiologicalRecordsCentre/ABLE/issues/597
https://github.com/BiologicalRecordsCentre/ABLE/issues/472

At the time of writing the following pages do not have a list of translated pages on the Translate tab, but I will gradually add these over time.
Edit app timed count
Painted Lady seasonal distribution
Edit a sample
My regional walks
My regional sites
Edit an App record
My 15-minute counts
Enter a list of moth records from a trap
Moth trap details
All moth traps
Enter a list of moth records
Edit a record
Global Site/Visit Summary
My timed counts samples with GIS download
Verification downloads
Record details
Survey 562 progress
Species details
Mapping
Timed Count Data Entry
Explore my records
My Timed Counts
All Timed Counts
Burkmar ES test
Walk Data Entry (OLD)
Filters admin
Add or edit permissions filter
Accept invitation to join a project
Create or edit a project site
Manage project sites
Create or edit a project
Invite users to join a project
Projects
Review project membership
Leave a project
Moth trap details old
