### ISSUE TITLE
"Unable to complete request" for displaying Scheme sites

### ISSUE THREAD

**Issue by xaviermestdagh** [BiologicalRecordsCentre/ABLE#689]
I have this issue when trying to display scheme sites. On Firefox, I tried to log off log out. 

![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/24294138/8d50f9fb-886c-4ead-a374-96e216c46636)

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja
Unfortunately the Warehouse is down at the moment, the system admin team know about it.

**Comment by CrisSevilleja** [comment]
Thanks @andrewvanbreda do you know if the warehouse will comeback soon? just to notify users

**Comment by andrewvanbreda** [comment]
@CrisSevilleja 
Afraid I know nothing about timeframes at the moment unfortunately

**Comment by CrisSevilleja** [comment]
ok thank you

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
I have put site into maintenance mode to avoid user confusion.

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
Seems to be running again now
