### ISSUE TITLE
Error when inserting new Moth Traps

### ISSUE THREAD

**Issue by Joao-Nunes-Moths** [BiologicalRecordsCentre/ABLE#692]
There is a problem when trying to insert a new sampling spot of moth trapping. Is this just temporary?

![Sem título](https://github.com/BiologicalRecordsCentre/ABLE/assets/120634514/53cdc21b-a3ec-49a7-aa17-a34b956f63fb)

**Comment by larspett** [comment]
We have experienced this for at least 2 weeks in Sweden, it appears unpredictably but frustratingly often

**Comment by Helder-Cardos** [comment]
Also, in some users it stays "freezed" on this screen:

![448248417_10224565336542787_2203657739304817381_n](https://github.com/BiologicalRecordsCentre/ABLE/assets/120488162/2a1c3464-8153-464b-bc7b-23f9c93eade5)

**Comment by kazlauskis** [comment]
Which app version is this?

**Comment by Helder-Cardos** [comment]
![Screenshot_20240619_094009_ButterflyCount](https://github.com/BiologicalRecordsCentre/ABLE/assets/120488162/1dae9686-9ca9-4a83-811b-d78e318c2d5d)

**Comment by larspett** [comment]
Does everyone experiencing this run the same version as Helder on Androids? I have 1.26.0 (344) on an iPhone and have just had 1-2 such errors

**Comment by larspett** [comment]
My colleague Harriet and her friends have it all the time and they have the same version as Helder

**Comment by kazlauskis** [comment]
@larspett I am looking into this now.

**Comment by kazlauskis** [comment]
I fixed this in v1.26.5 now. For some reason, sometimes the new trap doesn't appear in the list right away after saving it, so you might need to navigate to the previous page and back to the moth trap list page for it to appear - that's something I will look into later.
