### ISSUE TITLE
Issue: Attach coordinates of the site shape (GPS trail or polygon) to named locations

### ISSUE THREAD

**Issue by maudbv** [BiologicalRecordsCentre/ABLE#694]
### Describe the issue

Names locations can be added to a project, and there seems to be a GPS point associated to them, but associating a polygon or GPS track is not possible. One can only create a polygon or track for a single survey, and has to redraw it, or reslect it from the list of "previous" tracks at each new survey of the location. 

### Expected behaviour

It would be better if a polygon or GPS trail could be assigned to a given location the first time it is created (and possibly could be edited later on), instead of a single GPS point.

Basically, this means permanently attaching one of the "previous" trails or polygons to the "project locations". Is that possible?

This means that instead of having one GPS point associated to location, it would be a geospatial object (polygon or trail). This would allow users to see the saved outline of the site when they return to it for repeated surveys, to remember what area they surveyed previously. It would also allow other users to see where past surveys have already been done.  Finally, it would avoid having to re-trace the polygon again. I think the GPS track associated to single surveys in the location could still be kept as additional data to confirm that the survey did indeed take place within the expected location.

### App Version

1.26.0 (344)

### Screenshots

![IMG_1554](https://github.com/BiologicalRecordsCentre/ABLE/assets/6454302/9b4ad648-b210-4523-a9e3-c55997bcdc8b)

### Additional context

We have discussed this already by email also with David Roy. 
It would be great if this could be done! 
see also  issue #695 

Note: perhaps this is already done? My app version is a bit outdated. However, I tried it Monday on the latest version on my colleague's phone and it was still the same, so probably it is still a valid issue.

**Comment by kazlauskis** [comment]
@maudbv The Lat/Long point shown in the example is the first point of the polygon (or maybe the centroid). Saved sites do have geometries saved to them, so it works as expected. Once the website allows you to edit those, you will be able to see the polygon and line shapes.

**Comment by maudbv** [comment]
@kazlauskis that's great! thanks. So I guess now only issue #695 to figure out?

**Comment by maudbv** [comment]
@kazlauskis one question: at what point  and how do we define the geometry of the site? Is it the current geometry (GPS point, polygon or GPS trail) of the survey at the moment we click on "Add" ?

**Comment by kazlauskis** [comment]
Yes, that's right. The geometry is captured the moment you press "Add" new site.
