### ISSUE TITLE
App suggestion: to pause the time of 15min count with a phone button

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#697]
@kazlauskis  A suggestion from an user for improving the app while counting butterflies with 15min counts:

One of the difficulties I find with its use is that at times a butterfly may be observed whose identity may not be immediately known. At this point, I pause the timer so that the activity of trying to identify the specimen does not eat into the timed transect walk. Frequently, when one takes one’s eyes off the butterfly to pause the timer, the butterfly is lost. To combat this issue, if it was possible to press one of the three buttons on my iPhone to pause the timer, I could do so without losing focus on the butterfly.

Do you think it could be possible?

**Comment by kazlauskis** [comment]
Thanks for flagging it here. Unfortunately, this isn't something we could do without much effort, so I am closing it.
