### ISSUE TITLE
Issue: Unable to upload new moth traps

### ISSUE THREAD

**Issue by HarrietArnberg** [BiologicalRecordsCentre/ABLE#699]
### Describe the issue

Several users have reported problems with uploading new trap locations through the app.

### App Version

v1.26.4(351)

### Screenshots

![448604407_797809785430941_5127647552637110203_n](https://github.com/BiologicalRecordsCentre/ABLE/assets/54715850/c880669a-f666-401c-ad71-8a5f2446f286)
![448345764_3746011742345705_6268116882865371808_n](https://github.com/BiologicalRecordsCentre/ABLE/assets/54715850/99dd2da0-db82-4c52-8b14-398300589ae1)
![447891179_975208417432053_5126204153094629929_n](https://github.com/BiologicalRecordsCentre/ABLE/assets/54715850/50f781c3-3d48-4de9-b406-62bd4d6864a1)

**Comment by kazlauskis** [comment]
Those users should update their apps. This was fixed in the previous app version v1.26.5.
