### ISSUE TITLE
Summary map to centered to show all of Europe

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#70]
The map on: https://butterfly-monitoring.net/mydata cuts off Southern Europe.  This is important to fix as we are now getting transects setup in Portugal and Cyprus which would be good to see.

Could the map be zoomed/centered to this default view:
![e](https://user-images.githubusercontent.com/2699478/57838933-8d9e5900-77bd-11e9-883f-fb0655ee5867.png)

**Comment by Gary-van-Breda** [comment]
Done.

**Comment by DavidRoy** [comment]
Thanks for the quick response on this
