### ISSUE TITLE
Enter new species on Walk Data Entry not working

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#701]
Hello, some users reported and I checked on my account. Website users cannot enter new species on the species list when registering a transect walk, 2nd page https://butterfly-monitoring.net/walk-data-entry?sample_id=25243634

Basically, all the upper buttons are not working, nothing happens when clicking on "Species known at this site" or "taxonomic sort order". The most important, the search bar for adding new species is not working not completing the search species. In the screenshot below, I wrote Aricia to find the species and the list of species is not loaded.

![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/c4f57fb1-621b-4447-9a2f-03002d1b5245)

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja,

OK I will check in a minute

**Comment by DavidRoy** [comment]
links to this issue? https://github.com/BiologicalRecordsCentre/UKBMS-online/issues/356#issuecomment-2188447606
problem caused by latest Drupal updates. @andrewvanbreda can you liaise with @Gary-van-Breda and @BirenRathod to resolve

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
Yes this is the same conclusion I have just come to.
I have put EBMS into maintenance mode for now, I will do same for UKBMS after I check it.
@johnvanbreda @BirenRathod
I am seeing the Drupal Table error on the affected page.

**Comment by andrewvanbreda** [comment]
Have mailed John/Biren in case they miss Github notification

**Comment by Gary-van-Breda-EdiUni** [comment]
The same mitigating action should be taken until the fix is available (which I am working on) - switch off the sticky header functionality by moving the species selection autocomplete to under the species grids.
I have done this on both EBMS and UKBMS.
@andrewvanbreda UKBMS should be left operational, and EBMS can be taken out of maintenance mode.

**Comment by andrewvanbreda** [comment]
Taken out of maintenance mode, as workaround is working.
UKBMS was not put into maintenance mode as it seemed OK when I checked it

**Comment by Gary-van-Breda-EdiUni** [comment]
Just to re-iterate, this is due to a change in Drupal 10.3.0 which has removed the TableHeader Javascript, which the Walk DE page used to keep the autocomplete visible at the top as the page was scrolled.

**Comment by BirenRathod** [comment]
@andrewvanbreda & @Gary-van-Breda-EdiUni The fixed has already been applied on the butterfly-monitoring.net website.

**Comment by BirenRathod** [comment]
@CrisSevilleja Can you check now? it should be fine working now.

**Comment by BirenRathod** [comment]
@andrewvanbreda & @Gary-van-Breda-EdiUni As part of Bootstrap & Drupal 10.3 update, the dependencies of jQuery removed , so sites need to enable the jQuery autocomplete, draggable, droppable & resizable modules. 
Also, John has amended the code, so the Tableheader javascript error should not occur.

**Comment by andrewvanbreda** [comment]
@BirenRathod
Great thanks.

@CrisSevilleja
Close once you are happy this is working.

**Comment by CrisSevilleja** [comment]
The search bar is working again and adding species is possible. Thank you for restoring this so fast. 

The only thing is the search bar is now at the bottom, not a big thing but we corrected that before. Users prefer placing the search bar below the other buttons in the upper part, under "Species sort order"
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25052478/e3c86392-79c9-45b8-b360-756accc0067e)

**Comment by Gary-van-Breda** [comment]
Reopening until proper fix deployed with search bar at top of page: this is in prep and should be done today or tomorrow.

**Comment by Gary-van-Breda** [comment]
Proper fix now deployed and search bar moved to top of grids.
