### ISSUE TITLE
'Unidentifieds' for South Africa list

### ISSUE THREAD

**Issue by stevewoodhall** [BiologicalRecordsCentre/ABLE#705]
@DavidRoy this will work for South Africa and for Botswana, and probably Zimbabwe too. Further north there would have to be more 'unknown' categories like 'Unidentified Forester', but we'll cross that bridge when we come to it.
Can we please have these added to the local lists for SA and Botswana? 

Unidentified Blue
Unidentified Browns and Ringlets
Unidentified Copper, Opal or Russet
Unidentified Hairstreak
Unidentified Heliconian
Unidentified Charaxinae
Unidentified White, Yellow or Tip
Unidentified Buff
Unidentified Rocksitter or Zulu
Unidentified Flat Skipper
Unidentified Swift
Unidentified Sandman
Unidentified Ranger
Unidentified Skipper

Thanks

**Comment by stevewoodhall** [comment]
The rationale is that users will be encouraged to identify butterflies to genus level if they can't identify to species or subspecies level. However, all the groups I've asked to be added as 'Unidentified' have more than one possible genus. My point is that it's better to have these 'complexes' than just having 'Unidentifiable Butterfly'.

**Comment by DavidRoy** [comment]
@stevewoodhall apologies for overlooking this. Can you confirm the link to Genera for these common name aggregates. We'll then prioritise the update

**Comment by stevewoodhall** [comment]
@DavidRoy You asked me to link these 'unidentifieds' to genera. Some of these categories cover multiple genera; I thought we would do it at subfamily level. Going to genus level makes it very complicated, but here goes. I've fine tuned them.

Lycaenidae: Polyommatinae:

Unidentified Blue:
Azanus, Eicochrysops, Harpendyreus, Tarucus, ZizIna, Zizula, Zizeeria, Cacyreus, Leptotes, Euchrysops, Lepidochrysops, Orachrysops.

Unidentified 'Pie':
Zintha, Tarucus

Unidentified tiny Lycaenid:
Brephidium, Oraidium, Freyeria

Unidentified Hairstreak
Hypolycaena, Hemiolaus (yes these are now in Polyommatinae!)

What to do with monotypic genera like Pseudonacaduba, Uranothauma, Lampides? The untrained will simply see them as 'blues'.

Lycaenidae: 

Unidentified Copper, Opal or Russet - these cover two subfamilies!
Lafron (Lycaeninae), Aloeides, Chrysoritis, Trimenia, Phasis, Axiocerses, Chloroselas, Crudaria (Aphnaeinae)

I left out some easily identified monotypics like Aphnaeus, Tylopaedia and Argyraspodes.

Also Lycaenidae: Aphnaeinae:

Unidentified Silverline:
Cigaritis

Lycaenidae: Poritiinae:

Unidentified 'Buff/Zulu':
Deloneura, Baliochila, Cnodontes, Teriomima, Alaena, Pentila (some of these different genera are very easy to confuse when they are a few meters away)

Unidentified 'Rocksitter':
Durbania, Durbaniella, Durbaniopsis

Nymphalidae: Satyrinae:

Unidentified Browns and Ringlets
Physcaeneura, Bicyclus, Brakefieldia, Cassionympha, Coenyra, Coenyropsis, Melampias, Neita, Paternympha, Pseudonympha, Stygionympha, Ypthima

Unidentified Widows:
Dingana, Dira, Tarsocera, Torynesis

Nymphalidae: Heliconiinae:

Unidentified Heliconian
Acraea, Bematistes, Rubraea, Stephenia, Telchinia, Tildia

Unidentified 'Leopard'
Phalanta, Lachnoptera

The monotypic Pardopsis should be unmistakable.

Nymphalidae: Charaxinae:

Unidentified 'Charaxes':
Charaxes, Eriboea, Euxanthe, Polyura

Nymphalidae: Biblidinae:

Unidentified Tree Nymph:
Sevenia

Pieridae: Pierinae:

Unidentified White:
Belenois, Dixeia, Pseudanaphaeis, Appias, Pieris, Pontia

Unidentified Dotted Border:
Mylothris

Unidentified 'Tip':
Colotis, Teracolus

Pieridae: Coliadinae:

Unidentified Yellow:
Eurema/Terias, Catopsilia, Colias

Hesperiidae: Coeliadinae:

Unidentified 'Policeman':
Coeliades

Hesperiidae: Pyrginae (now includes Tagiadinae):

Unidentified 'Flat' Skipper:
Alenia, Apallaga, Eretis, Kobelana, Sarangesa, Eagris

Unidentified Sandman:
Agyllia, Ernsta, Spialia

Hesperiidae: Hesperiinae:

Unidentified 'Swift':
Borbo, Gegenes, Parnara, Pelopidas

Unidentified Ranger:
Kedestes, Dotta, Trida

Unidentified Hopper:
Fresna, Platylesches

**Comment by CrisSevilleja** [comment]
Wouw nice classification of the unidentifieds. If that list is applied, I suggest placing this exact list somewhere for the recorders to understand which genus is under each unidentified term.

**Comment by stevewoodhall** [comment]
> Wouw nice classification of the unidentifieds. If that list is applied, I suggest placing this exact list somewhere for the recorders to understand which genus is under each unidentified term.

Busy with that now. The Afrotropical Butterflies database that I sent to David earlier this year is outdated so I'll add the relevant columns to the South Africa list.

**Comment by stevewoodhall** [comment]
@DavidRoy @CrisSevilleja 
[AFROTROPICAL BUTTERFLIES - JULY 2024 as revised for genera common names.xlsx](https://github.com/user-attachments/files/16836471/AFROTROPICAL.BUTTERFLIES.-.JULY.2024.as.revised.for.genera.common.names.xlsx)
Looking at it in this format I modified what I put above. Look on the SOUTH AFRICA species tab Col U, Don't use the common names in Col V; not all of them are 'official' yet. For now, the 'official' South African common names are as used in the second edition of my Field Guide.

**Comment by DavidRoy** [comment]
New taxon added to eBMS list. 
@kazlauskis can you update the list in the app when you next release an app update
