### ISSUE TITLE
Possibility to add environmental variables of moth sample on the website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#710]
The weather data and time are really well captured on the app when recording a moth site sample, filling directly from other resources and with the ability to edit them https://github.com/BiologicalRecordsCentre/ABLE/issues/499 However, when entering a moth site sample through the website, there are no options to add environmental variables (wind, cloud%, moon phase, temperature) either the time of the sample https://butterfly-monitoring.net/my-moth-site-samples

@DavidRoy could it be possible to add these options, env. variables, time and comment variables on the moth site sample? thank you in advance. 

These are the only options available at the moment on the website, location, date and recorder
![Captura de pantalla 2024-07-15 151444](https://github.com/user-attachments/assets/f545dae0-7a56-4a3e-92ae-09e32851ed6e)

**Comment by JimBacon** [comment]
I've added another section to the form with the extra variables. Close the issue if you are happy @CrisSevilleja 

![image](https://github.com/user-attachments/assets/17418344-85af-4719-a4a7-ec889574e77f)

**Comment by CrisSevilleja** [comment]
thanks!
