### ISSUE TITLE
Occurrences missing in Indicia

### ISSUE THREAD

**Issue by mennovenema** [BiologicalRecordsCentre/ABLE#713]
### Describe the issue

Sometimes occurrences are missing in Indicia. For example: sample ID 26722976, the app and the website show 5 records for Pararge aegeria but Indicia only gives 4. 
![website_European Butterfly Monitoring](https://github.com/user-attachments/assets/4adf3ec8-76ad-4bae-bda7-39eca9fdf941)
![indicia](https://github.com/user-attachments/assets/20ec6702-2e37-4519-82f8-6bf30432d080)

### App Version

1.26.5

**Comment by mennovenema** [comment]
Just discovered that there is a default limit of 10 records in the point samples. Used "size": "10000" in my request and it works! So never forget to set this value.

**Comment by DavidRoy** [comment]
Thanks. Is this resolved and we can close the issue?

**Comment by mennovenema** [comment]
Yes, problem solved.
