### ISSUE TITLE
Performance - reports_for_prebuilt_forms/UKBMS/ukbms_visits_and_sites_summary.xml

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/ABLE#72]
See #57

**Comment by johnvanbreda** [comment]
In the examples I found on the warehouse logs, this one has a fairly complex date filter on the parent sample table:
```sql
AND (((trim('')='' OR ''='Click here') AND p.date_end >= CAST(extract(YEAR from NOW())||'-01-01' as date))
  OR (trim('')<>'' AND ''<>'Click here' AND p.date_start >= CAST(COALESCE('','1500-01-01') as date)))
AND (((trim('')='' OR ''='Click here') AND p.date_start <= CAST(extract(YEAR from NOW())||'-12-31' as date))
  OR (trim('')<>'' AND ''<>'Click here' AND p.date_start <= CAST(COALESCE('','1500-01-01') as date)))
```
This seems to just check that the parent sample is for the current year. As UKBMS doesn't use vague dates I think, can we simplify the above to the following?
```sql
AND p.date_start>='2019-01-01'
```

Note, precalculating the year and passing it in as a parameter seems to be the thing that speeds this report up most significantly, it's no trying to use EXTRACT(YEAR FROM ...) to calculate the date parameter. If that's not easily done in the code you can create a parameter which has a preprocess attribute, e.g:
```xml
<param name="year" preprocess="select extract(year from now())" default="2019" />
```
Now you can set the filter as 
```sql
AND p.date_start>='#year#-01-01'
```
Note that the default doesn't matter as it will be replaced - it just ensures the parameter is applied. So, we can use '#year#-01-01' as the default for the date_from parameter then simplify the filter as above. For date_to, we can use the <where> element so it is only applied as needed (no need to filter the end of the current year?).

Although not significant in my tests, tidying up the location_type_id and created_by_id filtering may make a small difference.

I've added a proposed report to the brc_reports module but not tested it in any earnest other than to ensure it loads. Gary, can you compare the output with the current report sometime please?

**Comment by DavidRoy** [comment]
Thanks.  Just to confirm, UKBMS does not use vague-dates

**Comment by Gary-van-Breda** [comment]
I've compared the contents Live vs the new report from John: they match OK.
The new report was OK for ABLE/EBMS, and I have changed the form to point to it; I have had to do a slight tweak to allow its use on UKBMS (due to the choice of Transect/WCBS*); I''l ask for that to be deployed when I complete #71

**Comment by Gary-van-Breda** [comment]
Report has been deployed into ABLE.
I have tried to use on UKBMS, but I am getting wildly different values: for speckled wood, original was 6991, new is 83627(!) - I'm pretty certain it is not working out the date range correctly: I'll revisit

**Comment by Gary-van-Breda** [comment]
Now sorted - was to do with the use of the date_to and from parameters and their default values: I have removed them from the call and now returns the correct values.
Is noticably faster.

**Comment by DavidRoy** [comment]
Thanks
