### ISSUE TITLE
Mismatch between names

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#721]
@JimBacon @DavidRoy @CrisSevilleja 
This has been an issue before, and I thought it was solved, but can't find it anymore, so start a new one.
There was/is a mismatch between names in the database. The record below (and there are many) shows the butterfly was entered by the Dutch name (=icarusblauwtje), which is Polyommatus icarus or Common Blue, but was changed to klöverblåvinge which was then linked to the scientific name Glaucopsyche alexis. 
Of course this one stands out, as this species doesn't occur in NL, but now we have loads of records of this species in the Dutch data, and I don't want to change them one by one. But more important: if this would happen between common species (a Pieris napi is change to Pieris rapae) no one would notice, but our data would be wrong.

So could you please check where this goes wrong and correct. I think this is actually quite important and should have a high priority.

![image](https://github.com/user-attachments/assets/081f9d79-434e-42e6-9e4c-cd4b0b574293)

**Comment by chrisvanswaay** [comment]
btw: I think klöverblåvinge is Swedish...

**Comment by larspett** [comment]
This is definitely a problem. We see many species (moths) that have been imported correctly with their Swedish common names matched with scientific names but that are now shown in German on the webpage.

**Comment by chrisvanswaay** [comment]
@DavidRoy Hope someone can check this, like I said it's and old issue which I thought was solved, but somehow now comes back. All P icarus entered by their Dutch name are transfered to a species not occurring in NL.

**Comment by chrisvanswaay** [comment]
@DavidRoy  I bring this up again, as we still have >300 wrong records in both the eBMS as in our database (via the api, though I have not approved them, so they are not used). Still >300 missing records of P icarus which distort our data.

**Comment by DavidRoy** [comment]
@JimBacon can you pick up the original issue raised by Chris.

**Comment by JimBacon** [comment]
The original issue was https://github.com/BiologicalRecordsCentre/ABLE/issues/574. It indicates that the source of the problem should have gone away but that records which were stored incorrectly are still in need of fixing. I will look at this now.

The common name appearing in an unexpected language is unrelated to the mishandling of icarusblauwtje records . I would guess it is a result of displaying a field in the database called 'default_common_name'. It only holds one value, the first common name added to the taxon list, and is not at all useful in a multilingual website.

**Comment by JimBacon** [comment]
Closed as duplicate ot #574
