### ISSUE TITLE
Annoying pop-up message when doing verification

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#725]
Hello, 

Recently I found that there is a pop-up message when accepting a verification as "considered correct" that appears all the time and it si quite annoying. You have to click on OK everything you accept a record. Verification page: https://butterfly-monitoring.net/verification

It mentions an error, although everything works well and the system takes time to save everything. Not sure why that message appears.
Maybe to place a tick box to no-show against the same message? 
![Captura de pantalla 2024-09-18 154152](https://github.com/user-attachments/assets/f316caa7-4ec3-480b-83d4-6dd7c0c6402a)

**Comment by CrisSevilleja** [comment]
this message continues appearing:
"An error occurred whilst updating the reporting index. It may not reflect your changes temporarily but will be updated automatically later."

**Comment by johnvanbreda** [comment]
This error should now be fixed.
