### ISSUE TITLE
Include Verification category on downloads from eBMS website

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#726]
We need to include the verification status on the download documents from the coordinators' download page https://butterfly-monitoring.net/downloads.
I think it should be applied to all survey documents (transects, 15mincounts and moth traps) on the occurrences files. Not sure if this information is useful for volunteers to include in the rest of the download documents (My annual report and My downloads pages).

Verification status described by @johnvanbreda were:
C - not accepted or rejected
V - verified (accepted)
R - rejected (not accepted)

However, I think the pending status should be included for the records not reviewed by verifiers

**Comment by DavidRoy** [comment]
@johnvanbreda can you extend the downloads to include the record_status field

**Comment by johnvanbreda** [comment]
Done. I've added record status and record substatus so you get all the available info. Shall I also update My Downloads with the same additional fields (https://butterfly-monitoring.net/index.php/mydata/downloads)?

**Comment by DavidRoy** [comment]
Thanks @johnvanbreda. yes, please extend to the My Downloads reports

**Comment by johnvanbreda** [comment]
That's done.

**Comment by DavidRoy** [comment]
Thanks John. @CrisSevilleja can you check this provides what's needed. Reopen the issue if anything extra needed
