### ISSUE TITLE
single species counts: for what species?

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#729]
For single species counts it is possible to see in the downloads what was the target species, as they are recorded without a NA for count, but we can't seem to see this in the api (only that a count was made, but not for which species). Is this right, and if yes, could this be added to the api?

**Comment by chrisvanswaay** [comment]
@johnvanbreda @DavidRoy

**Comment by chrisvanswaay** [comment]
I have the feeling this would not be much word (just add a field which is collected anyway to the api output) but would make a difference for us...

**Comment by DavidRoy** [comment]
@johnvanbreda can you pick this issue up please. For the 'single-species' survey a target species is selected.
@kazlauskis how do you handle this survey when there is a zero count? Do you submit a species occurrence with present = false. Or is the target species captured in a sample attribute?

**Comment by chrisvanswaay** [comment]
Thanks @DavidRoy . I think this is dealt with correctly in the app, as you can see the zero-counts in the overview:
![image](https://github.com/user-attachments/assets/fefb6919-7181-499a-bc99-36944d575496)

I assume the ones with a line through the name (and not a 1 in the column count) are zero counts.
I can also see the samples in the download, also with no count if nothing was seen:
![image](https://github.com/user-attachments/assets/648ee7d4-8dc1-4d01-aad9-39ab80e19a8f)

The problem is in the api, where this information is not shared (or we don't know where it is).

**Comment by johnvanbreda** [comment]
I've just tried testing your API access using the endpoint es-netherlands-reports. My request looks like this:
```json
{
  "size": 10,
  "sort": {
    "id": "asc"
  },
  "query": {
    "bool": {
      "must": [
        {"range": {
          "id": {
            "gt": 36922049
          }
        }}

      ]
    }
  }
}
```

Using that request payload, I can see record 36922050 and 36922051 in the response. Both have the usual taxon data and occurrence.zero_abundance is set to true so they look OK to me. What does your request look like?

**Comment by chrisvanswaay** [comment]
Thanks, I'll check with our it people. It might be something at our side, they told me they couldn't distinguish. I'll come back to you.

**Comment by chrisvanswaay** [comment]
We have adapted our script and now this data comes in. Thanks for all help.
