### ISSUE TITLE
Performance - reports_for_prebuilt_forms/UKBMS/ukbms_filterable_explore_list.xml

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/ABLE#73]
See #57 

This issue also covers the matching mapping and mapping_lores reports since they all run at the same time. 

Investigation of this report indicates 2 things. 

First, it is using the old cache_occurrences view. To make the conversion to the new style easy can we copy over the standard filterable_explore_list.xml files for the 3 reports from library/occurrences, then add a join to samples (parent_sample_id is in cache_occurrences_functional so you don't need to join to the child samples table), then to locations to check sensitivity? 

Second, when I inspect the network tab on http://www.ukbms.org/mydata/explore-map I can see the mapping_lores report runs 15 times. Only the first time returns any data, the following 14 requests are paging 2000 records at a time up to offset 28000. The first request is returning a false count of over 28000 resulting in the extra requests which are not required. I'm not sure why but hopefully the first fix should sort this out.

@Gary-van-Breda are you OK making new versions of these reports based on the ones in library/occurrences with the addition of the sensitive location check, or would you like me to do that?

**Comment by Gary-van-Breda** [comment]
New version committed to indicia-reports: will ask to be deployed when #72 and #71 are completed.

**Comment by Gary-van-Breda** [comment]
Reports have been deployed to live warehouse.
Both UKBMS and ABLE mapping page switched to using the 3 new report versions.
UKBMS still suffers the problem from the second point. ABLE does not have enough data to say if it has the same problem

**Comment by Gary-van-Breda** [comment]
I suggest that the UKBMS issue is transferred to the UKBMS github project, rather than in this ABLE one.

**Comment by DavidRoy** [comment]
Thanks.  Will switch to ElasticSearch mapping in due course so no need to raise a further issue on UKBMS
