### ISSUE TITLE
Issue: App not submitting sample.input_form for moth trap records

### ISSUE THREAD

**Issue by JimBacon** [BiologicalRecordsCentre/ABLE#730]
### Describe the issue

When trying to edit moth trap records submitted by the app an error arises

`The occurrence attribute 912 requested for the grid is not linked with the survey. `

### Expected behaviour

The record should be opened in the moth trap recording form at https://butterfly-monitoring.net/enter-moth-trap-records

### To Reproduce

1. Submit a moth trap record from the app.
2. Go to the website and visit My Data > My Samples.
3. Find the record you submitted and click the "View Sample Details" button at the end of the row.
4. Click the "Edit This Sample" button.

### App Version

all

### Device

all

### When did this happen

forever

### Additional context

This happens because the website has tried to open the record in the wrong recording form. It is expected that the name of the recording form will be stored in the sample.input_form field and the app is not filling this in. The value should be set to `enter-moth-trap-records`

**Comment by kazlauskis** [comment]
Thanks, I've fixed it now. It will come out in the following app version v1.26.6.
