### ISSUE TITLE
system down

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#732]
This afternoon I could not upload counts from the app, and I hoped it was just a short glitch, but this evening it is still not possible. Also the website www.butterfly-monitoring.net only gets you to the first page, logging in doesn´t work and looking at your records also is not working. 
Not sure for whom this is, so only tag @DavidRoy as he will probably know.

**Comment by kazlauskis** [comment]
The database is under maintenance this weekend. It should be back online tomorrow.

**Comment by chrisvanswaay** [comment]
OK, thanks. Still not working though.

**Comment by CrisSevilleja** [comment]
I will post on BCE Facebook that the website is under maintenance. 
Please also post this message on the website, @johnvanbreda  or @JimBacon . I don't know how to do this. At the moment I can enter my account, but I can't see anything else. Volunteers have reported that they cannot submit records from the app. 

As I have mentioned before, please let me know when the maintenance is going to happen, especially if it is going to take some time.

**Comment by JimBacon** [comment]
The website and app should be running normally again.

**Comment by JimBacon** [comment]
There was routine maintenance between 5pm Friday and Sunday which we failed to let you know about. There was then a problem with the servers not starting up correctly which we were unaware of until this morning.

I will check why you didn't get a notification of the maintenance.

**Comment by JimBacon** [comment]
@CrisSevilleja when there is a problem which causes the site to stop working properly you can replace the normal content with a simple message. 

1. Go to the admin menu [Configuration > Development > Maintenance Mode](https://butterfly-monitoring.net/index.php/admin/config/development/maintenance)
2. Check the box 'Put site into maintenance mode'
3. Add a message to display in the text box
4. Click the Save Configuration button

You may need to clear caches to make the change visible.

1. Go to the admin menu [Configuration > Development > Performance](https://butterfly-monitoring.net/index.php/admin/config/development/performance)
2. Click the Clear All Caches button

**Comment by CrisSevilleja** [comment]
thank you so much @JimBacon now the website is running properly and people are aware of the issues this weekend. 
Thank you also for including me on the email list.
