### ISSUE TITLE
Verification - include new filters

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#735]
Add new filters to facilitate the verification process: Country/Nuts regions, Method, and Taxon group. 

These last two are possible to select on the table settings, but it is not intuitive to verifiers they can change the table settings. If the new filters are above the table will be clearer. 

![Captura de pantalla 2024-11-13 110107](https://github.com/user-attachments/assets/0c158769-14fa-4545-acb0-9703e93844dd)

**Comment by johnvanbreda** [comment]
@DavidRoy we could fulfil this requirement by adding the standard create a filter tool to the page, configured to allow NUTS region filtering. Or we could add drop-downs to the page directly as suggested here.

**Comment by johnvanbreda** [comment]
@DavidRoy please confirm which option you'd like. The drop downs will be more efficient if filtering by NUTS regions is something that many verifiers will want to do often. The Create a Filter option will give a wider range of filtering options, but won't be quite so quick as a way of filtering the NUTs region.

**Comment by DavidRoy** [comment]
@johnvanbreda Please add the standard filter tool.
@CrisSevilleja can you then create some guidance for verifiers on this?  I will send you a document that could be adapted

**Comment by johnvanbreda** [comment]
I've added the filter tool.

**Comment by CrisSevilleja** [comment]
Great, thank you. Now I can apply the verification to regional coordinators, I will start with Spain. Indeed, @DavidRoy I was planning to explain to them how to do the verification in their region. I will prepare the document and even an explanatory video on how to use the verification system and the new filters.
