### ISSUE TITLE
Country boundary geometries invalid

### ISSUE THREAD

**Issue by Gary-van-Breda** [BiologicalRecordsCentre/ABLE#75]
All the country boundaries are defined as POLYGONS (? imported via a shape file), each defined as a list of LinearRings: for example France also contains several islands as well as the mainland, each represented as separate LinearRings within a single POLYGON.

This is wrong. The first LinearRing in a POLYGON is the external boundary, and subsequent LinearRings are holes in the initial POLYGON. Multiple mainland/islands etc should be represented in a MULTIPOLYGON geometry type, with a list of POLYGONS, each with a single LinearRing (assuming no "holes"!) representing the distinct areas of the country.

This makes the use of ST_INTERSECTS and other postgis functions fail to work.

**Comment by johnvanbreda** [comment]
@BirenRathod I think you uploaded the countries on warehouse2 a couple of years ago. Do you know where the SHP file came from and if a correct version can be obtained?

**Comment by Gary-van-Breda** [comment]
There is also the possibility that the import function in the warehouse mis-interpreted the shapefile (there is no MULTIPOLYGON code in it). Perhaps it would be best if we can see the original shapefile first, before jumping to conclusions that it is the source of the problems - and I speak as the one who coded the SHP import in the first place!

**Comment by johnvanbreda** [comment]
Possibly, thought the handful of countries imported on warehouse1 do seem to have valid MULTIPOLYGONs in them, so that might imply that the code worked.

**Comment by Gary-van-Breda** [comment]
But there is nowhere in the import code that generates MULTIPOLYGONS: if they have been saved from the e.g. the warehouse front end, that may "fix" it.

**Comment by johnvanbreda** [comment]
Isn't it most likely that the SHP file contained the badly formatted POLYGONs containing LinearRings? Therefore the code itself had nothing to do with this - they were just copied as they are from the SHP file. Also if I load one of the countries using the warehouse 2 user interface, then inspect the page using developer tools, I can see the boundary geom is still the incorrect version with POLYGONs and LinearRings. So I very much doubt that saving it will fix it.
I would imagine it would be possible to convert the polygons to multipolygons by converting to text then doing some judicious search and replace. Using ST_Multi won't work as it just wraps the polygon in a MULTIPOLYGON, keeping the same scenario with LinearRings. You need to convert the LinearRings to Polygons. I'll have a crack at this....

**Comment by johnvanbreda** [comment]
I've come up with the following:
```sql
update locations set boundary_geom=st_geomfromtext(replace(replace(regexp_replace(st_astext(boundary_geom), '\)$', '))'), 'POLYGON(', 'MULTIPOLYGON(('), '),(', ')),(('), 900913)
where location_type_id=213
```

I've applied this to Antigua and Barbuda (ID 15) as a test. Can you check its OK please? 

NOTE: DON'T APPLY THIS TO ID 15 AGAIN!

**Comment by Gary-van-Breda** [comment]
Looks good to me.
Can you apply it to France in ABLE? - I know this is not currently used - I need to check the boundary test in the Site edit form as I think I had to alter it to get around this: I want to check it still works.

**Comment by johnvanbreda** [comment]
France done on warehouse2 (location ID 85). 
Note to self - use the following query as it is safe to run twice on the same locations:
```sql
update locations set boundary_geom=st_geomfromtext(replace(replace(regexp_replace(st_astext(boundary_geom), '\)$', '))'), 'POLYGON(', 'MULTIPOLYGON(('), '),(', ')),(('), 900913)
where location_type_id=213 and st_geometrytype(boundary_geom)='ST_Polygon'
```

**Comment by Gary-van-Breda** [comment]
Looks good: can we apply it to all the countries?
Thanks

**Comment by johnvanbreda** [comment]
Done

**Comment by Gary-van-Breda** [comment]
Thanks:
Looks good, closing.
