### ISSUE TITLE
Error on saving transect during setup

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#76]
Reported from portugal.  Before we could save the transect the following error occurred

![pic](https://user-images.githubusercontent.com/2699478/58806961-20892100-860f-11e9-9bd8-819fe0139ee1.png)

@Gary-van-Breda can you investigate asap

**Comment by Gary-van-Breda** [comment]
This resulted from the temporary change to the warehouse configuration today: when it was swapped to warehouse1/ID118 all the required attributes etc were not set up on pointed to survey, including some which are pre-requistes for the various forms.
Now this has been reverted to warehouse2, this should now be sorted.

**Comment by DavidRoy** [comment]
Thanks.  Confirmed that now working.
