### ISSUE TITLE
update mapping page, using ES

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#77]
Improve mapping on https://butterfly-monitoring.net/explore-map

Implement a version of the Explore Indicia form to use Elastic Search.  Maybe dependent on moving to Warehouse 1 #47

**Comment by johnvanbreda** [comment]
@DavidRoy a question on this - how much of the "Create a filter" functionality needs to be migrated across? This is the main area we don't currently have in the new Elasticsearch code.

**Comment by DavidRoy** [comment]
Not required for the first version for eBMS, although can you provide a time estimate for adding this in.

**Comment by johnvanbreda** [comment]
New Elasticsearch based Explore functionality ready for testing on iRecord at https://www.brc.ac.uk/irecord/elastic/explore/all. This can be moved to ABLE if the latest iform code is deployed.

**Comment by DavidRoy** [comment]
This looks excellent.  It can be deployed to ABLE but with the following modifications:
1. Remove filter option until there is the interface to create a filter
2. Replace Vice County selector with a Country selector.  Or even better, a hierarchical selector of Country->NUTS
3. Remove Vice county from the data grid
4. Remove Determiner from the data grid
5. Map ref should be lat,lon

**Comment by johnvanbreda** [comment]
@DavidRoy All complete now, please close if happy.

Whilst working on this I came across a leaflet plugin https://github.com/aparshin/leaflet-boundary-canvas which could be used to isolate the selected region, tidying up the map.

**Comment by DavidRoy** [comment]
Thanks, closing as mapping page now switched over to the new version

**Comment by DavidRoy** [comment]
Reopening to improve format of page, as applied to #85 

1. Replace 'lat, lon' with 'lat/lon' (i.e. always lat,lon and not specific grid system such as OSGB).
2. Add Count column
3. Ideally each row is only 1 line deep, e.g. 
- Padding in columns tidied
- Col widths calculation improved (since it has to be manually done to allow the grid scroll bar to work).
- rename 'Record ID' to 'ID'

**Comment by johnvanbreda** [comment]
@DavidRoy all done.

**Comment by DavidRoy** [comment]
Thanks
