### ISSUE TITLE
delete test transects

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#78]
Delete from live:
EB_Parque da Paz
EBIO Parque da Paz

Including any associated data

**Comment by xaviermestdagh** [comment]
I have two test transects to delete as well:
2x "Eisekaul_Esch"
So, the delete option was intentionnally removed?

**Comment by Gary-van-Breda** [comment]
When the form was re-coded for ABLE, this site deletion was not fully implemented, as it needed a lot of re-work. It was all commented out. I will look at this again.

**Comment by Gary-van-Breda** [comment]
Delete site functionality reinstated.
Code deployed to Dev and Test: there is some ElasticSearch code from John waiting for deployment into Live before I push onto Live.

The 4 transects above have been removed using the Test Drupal site, which is linked to the live warehouse.

**Comment by Gary-van-Breda** [comment]
The Site delete functionality has now been deployed to Live, and the four sites mentioned above have been deleted.

**Comment by DavidRoy** [comment]
I've tried out, when logged in as admin.  The Delete button is on the form but nothing happens when selected for the following two sites:
https://butterfly-monitoring.net/ebms-site-details?id=216744
https://butterfly-monitoring.net/ebms-site-details?id=220746

I am using Chrome

**Comment by Gary-van-Breda** [comment]
I think I tripped up over a change put in for Johns elasticsearch stuff. I've reset the Openlayers to the minimised version, and cleared the caches. It seems to be working for me now.
I have only checked that the prompt appears when attempting to delete the 2 sites above - I have not actually done the delete - I thought you could do that to confirm it is working ok.
See media submodule issue 21.

**Comment by DavidRoy** [comment]
Does not work for me, logged in as admin and using Chrome

**Comment by Gary-van-Breda** [comment]
I suspect there is a caching issue on your browser - I've set Drupal to aggregate the Javascript, which should force it to serve you the new code, but if that doesn't work, can you make sure your browser cache is cleared?

**Comment by DavidRoy** [comment]
That's done the trick, thanks

**Comment by CrisSevilleja** [comment]
I reopen this issue to delete one test transect in Portugal. 

Please delete the transect in live:  EBIO Lamas de Olo     41.36703N 7.79226W

**Comment by Gary-van-Breda** [comment]
@CrisSevilleja : If you go in to Edit the transect (e.g. via the All sites page), you should see a "Delete" button at the bottom, next to the "Save" button. You should be able to use this to delete the currently displayed transect.
If this doesn't work, let me know, and I'll have a look at why.
