### ISSUE TITLE
Wrong visualization in Reporting -  Site/Visit Summary

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#79]
A coordinator reported that in the Site/Visit Summary https://butterfly-monitoring.net/visit-summary the volunteers could see all species saw in all sites and visits of eBMS. They could see species that even don't occur in their countries. 

In this page, it would be great to add buttons to select the recorder (your records or see all the volunteers) and the country for the scheme coordinator and for us as eBMS coordinators. 

Buttons like in Annual Report https://butterfly-monitoring.net/annual-report
@johnvanbreda  @DavidRoy

**Comment by Gary-van-Breda** [comment]
This will be dealt with under #115

**Comment by Gary-van-Breda** [comment]
Done slightly differently than the Annual report, using standard reporting parameters on new report (see #115)
Can now choose to see your own data, or data for your entire scheme, and either this year or last.
All users can see the data for their scheme.
The ability to see the data for the entire eBMS project has been moved to a different page, which I will make not available for normal data recorders and scheme coordinators.

**Comment by Gary-van-Breda** [comment]
"Global" Site/Visit summary now only available to supermanagers.
