### ISSUE TITLE
Problem with new registrations

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#81]
@Gary-van-Breda I've had reports of users in Portugal receiving a message saying that their email is reserved and cannot be used, even when not currently with an account.  Will email details of emails/users affected.

Please can you look into this urgently as it affects new users

The issue started last week so I wonder if it relates to any work that @kazlauskis is doing in relation to the eBMS mobile app

**Comment by kazlauskis** [comment]
I doubt the Indicia API module somehow affects the website user signup process. It only enables the app signup, but doesn't touch how the users on the website manage accounts.

**Comment by Gary-van-Breda** [comment]
There is a user_restrictions module which allows configuration of restrictions on the email addresses that can be used.
I don't know when it was activated or when it was configured: @BirenRathod do you know? but the regular expressions are wrong and will catch any email address ending in com, network or club.

**Comment by BirenRathod** [comment]
@Gary-van-Breda 
Yes, it has been configured on website on our server. If you find any regular expression wrong, you can implement it.

**Comment by DavidRoy** [comment]
@Gary-van-Breda please update the regular expression as required

**Comment by Gary-van-Breda** [comment]
I've corrected the regexes, but @BirenRathod or @DavidRoy can you confirm what rules we should be implementing? The .com one seems a bit extreme (banning any email with 2 dots in that ends in com)

**Comment by DavidRoy** [comment]
The problem being address was email addresses with double dot addresses after the @, e.g. @root.milltrill.com as an example

**Comment by BirenRathod** [comment]
@Gary-van-Breda 

that two dots that ends in com is exception. I think it needs bit more specific then just two dots. 

Normally I create from the pattern found from spam users. So I suggest keep an eye for spam users and create rule.

**Comment by Gary-van-Breda** [comment]
OK, thats what I thought: I have changed the regex on this to look for 2 dots after the @, and ending in .com.
@DavidRoy : do you want to try again?

**Comment by DavidRoy** [comment]
Thanks.  I'll ask the users to try again, hopefully closing this issue once resolved.

**Comment by DavidRoy** [comment]
Thanks, now resolved
