### ISSUE TITLE
New tabs in the menu

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#82]
New tabs are necessary to include in the Menu of eBMS. Please follow the diagram of the word file. 
[MENU EBMS - July.docx](https://github.com/BiologicalRecordsCentre/ABLE/files/3353751/MENU.EBMS.-.July.docx)

@DavidRoy

**Comment by DavidRoy** [comment]
@Gary-van-Breda I'll make the menu changes, but can you confirm where to update.  Live, Test or Dev so as to integrate with your work on 'micro-sites' #2

**Comment by Gary-van-Breda** [comment]
@DavidRoy : Do all these updates on Live.

**Comment by CrisSevilleja** [comment]
@DavidRoy it is already updated
