### ISSUE TITLE
Temperature drop-down missing from walk entry page

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#83]
Since warehouse migration, the temperature dropdown list is missing.  Therefore transect walks cannot be entered.

@Gary-van-Breda or @johnvanbreda can you fix as a matter of urgency.

https://butterfly-monitoring.net/ebms-input-data?location_type_id=777&date=02/07/2019
![ebms](https://user-images.githubusercontent.com/2699478/60597374-bc3eb600-9da2-11e9-9bec-811a5c44a6c4.png)

**Comment by johnvanbreda** [comment]
Fixed by making the appropriate termlist warehouse owned (rather than UKBMS owned).
