### ISSUE TITLE
Implement an explore-my records report 

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#84]
An explore-my records report is needed for viewing data submitted via the ABLE app.

For the time being, can you add the existing iForm version to the eBMS website as:
www.butterfly-monitoring.net/mydata/my-records

Will switch to an ES version once that is available but I'll raise a separate issue for that

**Comment by johnvanbreda** [comment]
Done - the above link should now work. Will need adding to the menu when tested.

**Comment by DavidRoy** [comment]
Thanks!
