### ISSUE TITLE
ES explore-my records report

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#85]
Follows on from #84 

An ElasticSearch version of the Explore-my records report.  Modelled on the existing iForm report, but with an additional tab of 'Samples'

**Comment by johnvanbreda** [comment]
See https://www.brc.ac.uk/irecord/elastic/explore/my for a demo. I can add the Samples tab once deployed on ABLE (which requires the latest iform code first).

**Comment by DavidRoy** [comment]
Good to deploy.  Need to have an option to download records in .csv

**Comment by johnvanbreda** [comment]
Download added (using new ES Download tool).

@Gary-van-Breda I can't deploy this until the iform client helper and media folders are updated to the latest master branches, but I don't have Pantheon access for ABLE and I wouldn't want to update it anyway in case it breaks your code. Can you please let me know when the code is upgraded next.

**Comment by johnvanbreda** [comment]
Code now brought up to date.

**Comment by DavidRoy** [comment]
Thanks.  Can you now deploy the report on the eBMS website www.butterfly-monitoring.net/elastic/my-records

**Comment by johnvanbreda** [comment]
Agreed - was just making a note of progress for my benefit. I've started setting up the page, but have hit a stumbling block in that the ES migration relies on UKSI to get species details, so doesn't work for non-UKSI species properly. So I'll need to fix that first, which probably means implementing #108 before this.

**Comment by johnvanbreda** [comment]
Also just noting the following progress so I don't forget where I'm up to:
1) I've updated the migration of data into ES so that it will recognise taxonomy in list 251, by updating the taxa.yml and taxon-paths.yml files.
2) I've fixed an issue in the ES migration so that it correctly picks up the name as recorded rather than just the accepted name in taxon.taxon_name.

So, when #108 is implemented we should start finding the ABLE data appears in Elasticsearch and on the prototype my data page.

**Comment by DavidRoy** [comment]
Still required for https://butterfly-monitoring.net/elastic/my-records:
1. remove columns: - Vice County, Determiner
2. view details link does not open a record details page
3. add record edit link
4. report formatting - date overlaps recorder name currently
5. add samples tab
6. link to download file not working

**Comment by johnvanbreda** [comment]
@DavidRoy I've done all the above - please can you check it's OK.

**Comment by DavidRoy** [comment]
Thanks.  
If selecting a row from the occurrences tab, then selecting 'Distribution of species in selected row (grid map)' from the map options, an error message appears.
'Elasticsearch query failed'

Some further changes to simplify.
1. Remove 'Status' dropdown filter list.  Potentially re-instate when verification system operational
2. Relabel 'Region' drop-down list as 'First level NUTS regions of the EU'.  With hyperlink to https://en.wikipedia.org/wiki/First-level_NUTS_of_the_European_Union
3. Make Region drop-down box the same height as the search box
4. For default column view from the data grid, occurrences tab:
- remove species group [we currently only have butterflies]
- have edit/view icons on the same line so that the table rows are less deep
5. I will raise a separate issue for the Samples tab of the report 
6. I will raise a separate issue to simply the download file format

**Comment by johnvanbreda** [comment]
@DavidRoy All done - please close if OK. Note that the action icons are only arranged vertically because that's the way the HTML flows the page - and there are often 2 rows anyway. If you remove a few columns you should see them revert to a single row.

**Comment by DavidRoy** [comment]
@johnvanbreda Thanks for these updates.  A couple of residual issues:
- If i remove the 'Location' field using the Column configuration tool, the formating on the Species and Samples tab breaks as all the fields on these pages become unticked.
- when masquerading as a user (https://butterfly-monitoring.net/user/1281 or https://butterfly-monitoring.net/users/chrisvanswaay) I know has entered app data, the page gives an error message of 'Elasticsearch query failed).  Is there a permissions issue?

Noted here but probably best covered by separate issues
- if going to record details view (e.g. https://butterfly-monitoring.net/mydata/details/record?occurrence_id=11037115), then clicking on the 'explore records of [this species]' link, the page does display the map extent to match the data in the data grid.  Also, should this be an ES explore report?
- the map on the species details page does not zoom to extend of the data.  Should also be an ES explore report?

**Comment by johnvanbreda** [comment]
* Fixed bug where the column changes were affecting all the grids on other tabs.
* Fixed permissions for all users to be able to use the Elasticsearch reporting.

Agreed - can those points be added as separate issues please?

**Comment by DavidRoy** [comment]
Thanks.  Closing this issue and will raise separate ones. 
@johnvanbreda I removed a couple of columns to improve the default view

**Comment by DavidRoy** [comment]
Reopening as vital field is missing: Quantity

This is labelled Abundance count on record details page (e.g. https://butterfly-monitoring.net/mydata/details/record?occurrence_id=11037115).  Warehouse occurrence_attribute ID 780

**Comment by johnvanbreda** [comment]
Updated the list of columns to reflect those available in ES. Due to the way Darwin Core works, there is a Count column (individual count = integer, null if abundance is a code or non-numeric), and a Quantity column (organism quantity = text, same as Count but also contains codes and non-numerics).

**Comment by DavidRoy** [comment]
Please add in the Count column in the list of default columns.

Also replace 'lat, lon' with 'lat/lon' (i.e. always lat,lon and not specific grid system such as OSGB).  

Also, ideally the default data grid is only 1 row deep for standard screen sizes. 
Options are: the lat, lon values be restricted to display at 2 decimal places to take up less space.  Or the year within data is shortened to two numbers (19 rather than 2019)? Or less white space between columns?

**Comment by johnvanbreda** [comment]
* Count added
* Padding in columns tidied
* Col widths calculation improved (since it has to be manually done to allow the grid scroll bar to work).

Now fits data in a single row, though the I had to change "Record ID" to "ID" in the title row to stop it flowing onto 2 rows.

**Comment by DavidRoy** [comment]
That works well, thanks

**Comment by DavidRoy** [comment]
The page is not accessible when masquerading as user:
https://butterfly-monitoring.net/user/1301

Also, not appearing as a menu item in the My Data menu

**Comment by DavidRoy** [comment]
Closing as have updated the permissions

**Comment by johnvanbreda** [comment]
Are you OK to add it to the menus as you see fit as well?

**Comment by DavidRoy** [comment]
yes, all sorted
