### ISSUE TITLE
T&Cs integrated into registration

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#86]
Using text at: https://butterfly-monitoring.net/terms-and-conditions

Users to agree to these terms when signing up

**Comment by Gary-van-Breda** [comment]
Terms of use module set up to use the node above.
There are 2 options:
1) the whole text is included in the user registration form above the checkbox
2) a link is provided to the page above.

I have gone for (2) - if you'd prefer (1), you can change it in Admin->Configuration->People->Terms of Use, and change the "label for the checkbox" to not include "@link": if you'd prefer me to do it, just let me know what text to use as the checkbox lable.

**Comment by DavidRoy** [comment]
That's good, thanks.
