### ISSUE TITLE
add occurrence edit form to eBMS website

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#87]
Further to #84 

Require a form to edit occurrences submitted by the ABLE mobile app.  There is a link from the record details page for app records, e.g. edit button on:
e.g. https://butterfly-monitoring.net/mydata/details/record?occurrence_id=10757818 

but this links to a page that doesn't exist:
https://butterfly-monitoring.net/enter-app-record?occurrence_id=10757818

require a iForm = https://butterfly-monitoring.net/enter-app-record

relates to issue #88

**Comment by johnvanbreda** [comment]
Done, using a fairly generic layout. Are any tweaks needed?

**Comment by DavidRoy** [comment]
Please remove the following fields from the edit form:
Source
Location info
Method info
Data Source
Data Source Version
Application Version

**Comment by johnvanbreda** [comment]
Done
