### ISSUE TITLE
add sample edit form

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#88]
As well as form to edit individual records #87, a form to view/edit the whole sample is required.  As a form with two tabs - sample details and species list

**Comment by johnvanbreda** [comment]
You can use the same form with a sample_id parameter, e.g. https://butterfly-monitoring.net/enter-app-record?sample_id=6134714. Is that OK?

**Comment by DavidRoy** [comment]
Some minor modifications:
1. Enable edit option for species names. Currently just delete option is provided
2. Remove the following fields from page:
Data Source
Data Source Version
Application version

**Comment by johnvanbreda** [comment]
Done
