### ISSUE TITLE
Site details - habitat list drop-downs not populating

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#89]
https://butterfly-monitoring.net/ebms-site-details

The drop-down lists are not showing the term lists.  Presumably needs configuring after migration to warehouse 1.

@johnvanbreda @Gary-van-Breda marked as urgent as affects new sites being setup

![ebms](https://user-images.githubusercontent.com/2699478/60968466-0f6db700-a315-11e9-8bba-478678afc3ae.png)

**Comment by johnvanbreda** [comment]
I think the migration set the date stamps on the termlist term entries to the original values (in 2016) so they weren't picked up as new records and put in the cache properly. I've changed the updated on values to now, so the next run of the scheduled tasks should pick them up. Let me know if they don't appear within an hour.

**Comment by johnvanbreda** [comment]
Closing as they've come through now...
