### ISSUE TITLE
Site details - site code not setup as expected 

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#90]
When setting up a new site, the Internal ABLE site code is not populating properly.  It currently shows [INDEX] as the code.

Also, relabel the field as 'Internal eBMS site code' rather than '...ABLE site code'

![ebms](https://user-images.githubusercontent.com/2699478/60968423-ee0ccb00-a314-11e9-9d1a-7f11d5bbaca7.png)

**Comment by Gary-van-Breda** [comment]
The [INDEX] is converted to a number when the site is saved: this was a fix applied a while back to EBMS to prevent duplicate codes.
I've done the change for the label: I'll chase it through to Live with the Scheme changes

**Comment by Gary-van-Breda** [comment]
Label change code now on Live.
Unless you'd like something specific done, I was going to leave the "[INDEX]" functionality alone.

**Comment by DavidRoy** [comment]
Thanks, now closing
