### ISSUE TITLE
App: Data source missing from warehouse submission?

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#91]
e.g. https://butterfly-monitoring.net/enter-app-record?occurrence_id=10757818

The data source field is empty.

![eg](https://user-images.githubusercontent.com/2699478/61029806-cae52880-a3b3-11e9-9918-d4ab0cd34226.png)

**Comment by johnvanbreda** [comment]
@DavidRoy @kazlauskis this wasn't a data problem in the app, but a result of the termlist used being private to iRecord so you couldn't see the terms. I've made it public so this is fixed.

This is superseded by #88 anyway.
