### ISSUE TITLE
my-records page giving errors

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/ABLE#94]
https://butterfly-monitoring.net/mydata/my-records

when masquerading as https://butterfly-monitoring.net/users/david-roy

@johnvanbreda can you get back up asap as we are testing the app, ready for release soon

**Comment by DavidRoy** [comment]
page now back?  I'll take a screen-shot of the error next time

**Comment by DavidRoy** [comment]
Had the same issue again, but then went away of a refresh.  I suspect to do with masquerading etc, but worth keeping an eye.  Will re-open the issue if this persists.

![err](https://user-images.githubusercontent.com/2699478/61111594-d9017a80-a481-11e9-8652-6f84089ecc0a.png)

**Comment by johnvanbreda** [comment]
Re-opening, because my judgement of the above is that it will occur intermittently, as the expired cache files are deleted on an intermittent basis.

**Comment by johnvanbreda** [comment]
It's hard for me to be sure without file access, but I think this is a result of the Indicia configuration pointing to http rather than https for the warehouse connection. I've changed to https on the live server so I believe this issue will be fixed but please re-open if necessary.
