### ISSUE TITLE
Add new species to the butterfly list: Iphiclides feisthamelii

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#98]
Iphiclides feisthamelii is a new species for the Iberian Peninsula. Before it was Iphiclides podalirius 
@DavidRoy @johnvanbreda

**Comment by DavidRoy** [comment]
We use the European checklist as the basis of our list: https://zookeys.pensoft.net/article/28712/list/5/

This lists both Iphiclides podalirius and Iphiclides feisthamelii as both present in Europe - as different species.  See this image from the checklist spreadsheet

![ipth](https://user-images.githubusercontent.com/2699478/61210083-4e27b680-a6f3-11e9-832f-59709eee55c9.png)

@johnvanbreda - but I am confused why both species don't appear in the warehouse1 view of the checklist, e.g. http://warehouse1.indicia.org.uk/index.php/taxon_list/edit/254 only returns Iphiclides podalirius.  However, the list you exported for Karolis includes both species

**Comment by johnvanbreda** [comment]
@DavidRoy there are 2 lists in play here. List 251 (ABLE Butterflies) is the list I imported from the data you gave me and is the list that I gave to Karolis. List 254 is the result of the data migration from warehouse2, where we were using an older European butterflies list which I think Biren added to that warehouse a couple of years ago. 
List 251 does have both species.

**Comment by DavidRoy** [comment]
ok, I think I understand in that case.  The eBMS transect input system still uses list 254?  

As a temporary action, I've manually added I. feisthamelii to list 254 so it is available for transect recording.

The action is to switch to using list 251 as that is now the preferred list.  I will add a new issue for this.

**Comment by johnvanbreda** [comment]
That's correct. Presumably this can be closed?

**Comment by DavidRoy** [comment]
Closing, having now confirmed that I. feisthamelii is available for transect input
