### ISSUE TITLE
Website translations to Swedish refused

### ISSUE THREAD

**Issue by larspett** [BiologicalRecordsCentre/ABLE#99]
I tried to enter translations for the missing 5 website strings but they bounce. Do I just lack access or is sth else causing this?

**Comment by Gary-van-Breda** [comment]
Two things:
1) Swedish is not currently enabled as a language
2) Lars is only a data recorder: he needs to be at least a scheme co-ordinator or project editor.

@DavidRoy : are we OK to change these 2 items?

**Comment by DavidRoy** [comment]
1. I've enabled Swedish as a language.
2. I would like to move to using Transifex to handle the website translations but this is not setup yet.  @larspett in the meantime, can you send us required translations as a word document and we'll add them manually to the website

**Comment by DavidRoy** [comment]
@Gary-van-Breda p.s. I think this issue relates to translations for the eBMS mobile app that is using Transifex to handle translations.

**Comment by larspett** [comment]
String 1: issue: The sentence is not complete, either maybe something like "to ... schemes" or "to a ... scheme"
String 1, translated: En plats för att marknadsföra projekt med kopplingar till fjärilsövervakningen
String 2, issue: "schem" should be "scheme" in the untranslated string
String 2: translated: Ett system för att etablera fjärilsövervakningslokaler i områden som för närvarande saknar ett nationellt fjärilsövervakningsprogram
String 3, translated: Den här sidan är under uppbyggnad, men mer information om vart och ett av dessa element kommer snart .....
String 4, translated: - En samling av nationella dataset för fjärilsövervakning i Europa - eBMS-partnerskapet
String 5, translated: Välkommen till startsidan för European Butterfly Monitoring Scheme (eBMS). Inom ramen för Butterfly Conservation Europe är denna webbplats mål att främja fjärilsövervakning över hela Europa och den omfattar:

PS Some of the translations are likely in need of tweaking since the exact phrasing depends on the context

**Comment by kazlauskis** [comment]
To clarify this, @larspett is talking about the `website`resource that is currently next to the `app` resource under eBMS project in transifex. This `website`resource is not for translations yet as it has been a test file previously uploaded by @DavidRoy and is not yet complete, therefore locked. Once @Gary-van-Breda uploads some website terms to translate, David can unlock it for translations.

**Comment by larspett** [comment]
Is there any way of submitting website translation strings?  Right now there are so few strings translated (at least in Swedish) that it might even be better to keep everything in English until the translation has been brought more up to date. Ping @DavidRoy @kazlauskis

**Comment by DavidRoy** [comment]
We have nearly linked Transifex to Drupal to enable wider translation.  Within the next month we will request translations for the website

**Comment by larspett** [comment]
excellent
